/* Port-r04-301 */
/************************************************************************************************/
/*                                                                                              */
/*     PORT Driver                                                                              */
/*                                                                                              */
/*      Copyright : DENSO CORPORATION                                                           */
/*                                                                                              */
/************************************************************************************************/

/*==============================================================================================*/
/* include files                                                                                */
/*==============================================================================================*/
#include "Port.h"
#include "Port_ModeCfg.h"
/*==============================================================================================*/
/*  Global Data                                                                                 */
/*==============================================================================================*/

#if ( MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2A )
/* P2_11 */
#define	CSTPORT_MODE_SETTING_0 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_0, \
	PORT_U2A_MODE_CFG_MODE_0, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_0, \
	PORT_U2A_MODE_CFG_IP_CTRL_0, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_0, \
	PORT_U2A_MODE_CFG_CTRL_EXP_0, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_0, \
	PORT_U2A_MODE_CFG_PULL_UP_0, \
	PORT_U2A_MODE_CFG_PULL_DOWN_0, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_0, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_0, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_0, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_0, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_0, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_0,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_0,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_0,\
	PORT_U2A_MODE_CFG_PORT_0,\
	PORT_U2A_MODE_CFG_PORT_NOT_0,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_0, \
	PORT_U2A_MODE_CFG_LVDS_USE_0 \
}
#define	CSTPORT_NOISEFILTER_SETTING_0 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_0, \
	PORT_U2A_MODE_CFG_FLT_CTRL_0, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_0 \
}
#define	CSTPORT_SAFESTATE_SETTING_0 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_0, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_0, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_0 \
}
/* P2_12 */
#define	CSTPORT_MODE_SETTING_1 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_1, \
	PORT_U2A_MODE_CFG_MODE_1, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_1, \
	PORT_U2A_MODE_CFG_IP_CTRL_1, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_1, \
	PORT_U2A_MODE_CFG_CTRL_EXP_1, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_1, \
	PORT_U2A_MODE_CFG_PULL_UP_1, \
	PORT_U2A_MODE_CFG_PULL_DOWN_1, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_1, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_1, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_1, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_1, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_1, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_1,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_1,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_1,\
	PORT_U2A_MODE_CFG_PORT_1,\
	PORT_U2A_MODE_CFG_PORT_NOT_1,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_1, \
	PORT_U2A_MODE_CFG_LVDS_USE_1 \
}
#define	CSTPORT_NOISEFILTER_SETTING_1 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_1, \
	PORT_U2A_MODE_CFG_FLT_CTRL_1, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_1 \
}
#define	CSTPORT_SAFESTATE_SETTING_1 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_1, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_1, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_1 \
}
/* P2_13 */
#define	CSTPORT_MODE_SETTING_2 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_2, \
	PORT_U2A_MODE_CFG_MODE_2, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_2, \
	PORT_U2A_MODE_CFG_IP_CTRL_2, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_2, \
	PORT_U2A_MODE_CFG_CTRL_EXP_2, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_2, \
	PORT_U2A_MODE_CFG_PULL_UP_2, \
	PORT_U2A_MODE_CFG_PULL_DOWN_2, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_2, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_2, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_2, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_2, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_2, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_2,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_2,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_2,\
	PORT_U2A_MODE_CFG_PORT_2,\
	PORT_U2A_MODE_CFG_PORT_NOT_2,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_2, \
	PORT_U2A_MODE_CFG_LVDS_USE_2 \
}
#define	CSTPORT_NOISEFILTER_SETTING_2 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_2, \
	PORT_U2A_MODE_CFG_FLT_CTRL_2, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_2 \
}
#define	CSTPORT_SAFESTATE_SETTING_2 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_2, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_2, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_2 \
}
/* P2_14 */
#define	CSTPORT_MODE_SETTING_3 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_3, \
	PORT_U2A_MODE_CFG_MODE_3, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_3, \
	PORT_U2A_MODE_CFG_IP_CTRL_3, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_3, \
	PORT_U2A_MODE_CFG_CTRL_EXP_3, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_3, \
	PORT_U2A_MODE_CFG_PULL_UP_3, \
	PORT_U2A_MODE_CFG_PULL_DOWN_3, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_3, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_3, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_3, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_3, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_3, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_3,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_3,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_3,\
	PORT_U2A_MODE_CFG_PORT_3,\
	PORT_U2A_MODE_CFG_PORT_NOT_3,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_3, \
	PORT_U2A_MODE_CFG_LVDS_USE_3 \
}
#define	CSTPORT_NOISEFILTER_SETTING_3 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_3, \
	PORT_U2A_MODE_CFG_FLT_CTRL_3, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_3 \
}
#define	CSTPORT_SAFESTATE_SETTING_3 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_3, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_3, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_3 \
}
/* P4_5 */
#define	CSTPORT_MODE_SETTING_4 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_4, \
	PORT_U2A_MODE_CFG_MODE_4, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_4, \
	PORT_U2A_MODE_CFG_IP_CTRL_4, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_4, \
	PORT_U2A_MODE_CFG_CTRL_EXP_4, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_4, \
	PORT_U2A_MODE_CFG_PULL_UP_4, \
	PORT_U2A_MODE_CFG_PULL_DOWN_4, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_4, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_4, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_4, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_4, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_4, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_4,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_4,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_4,\
	PORT_U2A_MODE_CFG_PORT_4,\
	PORT_U2A_MODE_CFG_PORT_NOT_4,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_4, \
	PORT_U2A_MODE_CFG_LVDS_USE_4 \
}
#define	CSTPORT_NOISEFILTER_SETTING_4 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_4, \
	PORT_U2A_MODE_CFG_FLT_CTRL_4, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_4 \
}
#define	CSTPORT_SAFESTATE_SETTING_4 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_4, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_4, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_4 \
}
/* P4_6 */
#define	CSTPORT_MODE_SETTING_5 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_5, \
	PORT_U2A_MODE_CFG_MODE_5, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_5, \
	PORT_U2A_MODE_CFG_IP_CTRL_5, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_5, \
	PORT_U2A_MODE_CFG_CTRL_EXP_5, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_5, \
	PORT_U2A_MODE_CFG_PULL_UP_5, \
	PORT_U2A_MODE_CFG_PULL_DOWN_5, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_5, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_5, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_5, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_5, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_5, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_5,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_5,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_5,\
	PORT_U2A_MODE_CFG_PORT_5,\
	PORT_U2A_MODE_CFG_PORT_NOT_5,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_5, \
	PORT_U2A_MODE_CFG_LVDS_USE_5 \
}
#define	CSTPORT_NOISEFILTER_SETTING_5 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_5, \
	PORT_U2A_MODE_CFG_FLT_CTRL_5, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_5 \
}
#define	CSTPORT_SAFESTATE_SETTING_5 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_5, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_5, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_5 \
}
/* P4_7 */
#define	CSTPORT_MODE_SETTING_6 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_6, \
	PORT_U2A_MODE_CFG_MODE_6, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_6, \
	PORT_U2A_MODE_CFG_IP_CTRL_6, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_6, \
	PORT_U2A_MODE_CFG_CTRL_EXP_6, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_6, \
	PORT_U2A_MODE_CFG_PULL_UP_6, \
	PORT_U2A_MODE_CFG_PULL_DOWN_6, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_6, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_6, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_6, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_6, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_6, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_6,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_6,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_6,\
	PORT_U2A_MODE_CFG_PORT_6,\
	PORT_U2A_MODE_CFG_PORT_NOT_6,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_6, \
	PORT_U2A_MODE_CFG_LVDS_USE_6 \
}
#define	CSTPORT_NOISEFILTER_SETTING_6 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_6, \
	PORT_U2A_MODE_CFG_FLT_CTRL_6, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_6 \
}
#define	CSTPORT_SAFESTATE_SETTING_6 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_6, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_6, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_6 \
}
/* P4_10 */
#define	CSTPORT_MODE_SETTING_7 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_7, \
	PORT_U2A_MODE_CFG_MODE_7, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_7, \
	PORT_U2A_MODE_CFG_IP_CTRL_7, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_7, \
	PORT_U2A_MODE_CFG_CTRL_EXP_7, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_7, \
	PORT_U2A_MODE_CFG_PULL_UP_7, \
	PORT_U2A_MODE_CFG_PULL_DOWN_7, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_7, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_7, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_7, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_7, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_7, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_7,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_7,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_7,\
	PORT_U2A_MODE_CFG_PORT_7,\
	PORT_U2A_MODE_CFG_PORT_NOT_7,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_7, \
	PORT_U2A_MODE_CFG_LVDS_USE_7 \
}
#define	CSTPORT_NOISEFILTER_SETTING_7 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_7, \
	PORT_U2A_MODE_CFG_FLT_CTRL_7, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_7 \
}
#define	CSTPORT_SAFESTATE_SETTING_7 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_7, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_7, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_7 \
}
/* P6_6 */
#define	CSTPORT_MODE_SETTING_8 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_8, \
	PORT_U2A_MODE_CFG_MODE_8, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_8, \
	PORT_U2A_MODE_CFG_IP_CTRL_8, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_8, \
	PORT_U2A_MODE_CFG_CTRL_EXP_8, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_8, \
	PORT_U2A_MODE_CFG_PULL_UP_8, \
	PORT_U2A_MODE_CFG_PULL_DOWN_8, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_8, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_8, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_8, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_8, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_8, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_8,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_8,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_8,\
	PORT_U2A_MODE_CFG_PORT_8,\
	PORT_U2A_MODE_CFG_PORT_NOT_8,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_8, \
	PORT_U2A_MODE_CFG_LVDS_USE_8 \
}
#define	CSTPORT_NOISEFILTER_SETTING_8 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_8, \
	PORT_U2A_MODE_CFG_FLT_CTRL_8, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_8 \
}
#define	CSTPORT_SAFESTATE_SETTING_8 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_8, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_8, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_8 \
}
/* P20_1 */
#define	CSTPORT_MODE_SETTING_9 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_9, \
	PORT_U2A_MODE_CFG_MODE_9, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_9, \
	PORT_U2A_MODE_CFG_IP_CTRL_9, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_9, \
	PORT_U2A_MODE_CFG_CTRL_EXP_9, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_9, \
	PORT_U2A_MODE_CFG_PULL_UP_9, \
	PORT_U2A_MODE_CFG_PULL_DOWN_9, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_9, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_9, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_9, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_9, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_9, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_9,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_9,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_9,\
	PORT_U2A_MODE_CFG_PORT_9,\
	PORT_U2A_MODE_CFG_PORT_NOT_9,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_9, \
	PORT_U2A_MODE_CFG_LVDS_USE_9 \
}
#define	CSTPORT_NOISEFILTER_SETTING_9 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_9, \
	PORT_U2A_MODE_CFG_FLT_CTRL_9, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_9 \
}
#define	CSTPORT_SAFESTATE_SETTING_9 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_9, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_9, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_9 \
}
/* P20_2 */
#define	CSTPORT_MODE_SETTING_10 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_10, \
	PORT_U2A_MODE_CFG_MODE_10, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_10, \
	PORT_U2A_MODE_CFG_IP_CTRL_10, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_10, \
	PORT_U2A_MODE_CFG_CTRL_EXP_10, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_10, \
	PORT_U2A_MODE_CFG_PULL_UP_10, \
	PORT_U2A_MODE_CFG_PULL_DOWN_10, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_10, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_10, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_10, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_10, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_10, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_10,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_10,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_10,\
	PORT_U2A_MODE_CFG_PORT_10,\
	PORT_U2A_MODE_CFG_PORT_NOT_10,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_10, \
	PORT_U2A_MODE_CFG_LVDS_USE_10 \
}
#define	CSTPORT_NOISEFILTER_SETTING_10 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_10, \
	PORT_U2A_MODE_CFG_FLT_CTRL_10, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_10 \
}
#define	CSTPORT_SAFESTATE_SETTING_10 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_10, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_10, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_10 \
}
/* P21_0 */
#define	CSTPORT_MODE_SETTING_11 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_11, \
	PORT_U2A_MODE_CFG_MODE_11, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_11, \
	PORT_U2A_MODE_CFG_IP_CTRL_11, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_11, \
	PORT_U2A_MODE_CFG_CTRL_EXP_11, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_11, \
	PORT_U2A_MODE_CFG_PULL_UP_11, \
	PORT_U2A_MODE_CFG_PULL_DOWN_11, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_11, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_11, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_11, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_11, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_11, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_11,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_11,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_11,\
	PORT_U2A_MODE_CFG_PORT_11,\
	PORT_U2A_MODE_CFG_PORT_NOT_11,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_11, \
	PORT_U2A_MODE_CFG_LVDS_USE_11 \
}
#define	CSTPORT_NOISEFILTER_SETTING_11 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_11, \
	PORT_U2A_MODE_CFG_FLT_CTRL_11, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_11 \
}
#define	CSTPORT_SAFESTATE_SETTING_11 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_11, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_11, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_11 \
}
/* P21_1 */
#define	CSTPORT_MODE_SETTING_12 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_12, \
	PORT_U2A_MODE_CFG_MODE_12, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_12, \
	PORT_U2A_MODE_CFG_IP_CTRL_12, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_12, \
	PORT_U2A_MODE_CFG_CTRL_EXP_12, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_12, \
	PORT_U2A_MODE_CFG_PULL_UP_12, \
	PORT_U2A_MODE_CFG_PULL_DOWN_12, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_12, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_12, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_12, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_12, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_12, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_12,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_12,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_12,\
	PORT_U2A_MODE_CFG_PORT_12,\
	PORT_U2A_MODE_CFG_PORT_NOT_12,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_12, \
	PORT_U2A_MODE_CFG_LVDS_USE_12 \
}
#define	CSTPORT_NOISEFILTER_SETTING_12 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_12, \
	PORT_U2A_MODE_CFG_FLT_CTRL_12, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_12 \
}
#define	CSTPORT_SAFESTATE_SETTING_12 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_12, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_12, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_12 \
}
/* P21_2 */
#define	CSTPORT_MODE_SETTING_13 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_13, \
	PORT_U2A_MODE_CFG_MODE_13, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_13, \
	PORT_U2A_MODE_CFG_IP_CTRL_13, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_13, \
	PORT_U2A_MODE_CFG_CTRL_EXP_13, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_13, \
	PORT_U2A_MODE_CFG_PULL_UP_13, \
	PORT_U2A_MODE_CFG_PULL_DOWN_13, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_13, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_13, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_13, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_13, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_13, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_13,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_13,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_13,\
	PORT_U2A_MODE_CFG_PORT_13,\
	PORT_U2A_MODE_CFG_PORT_NOT_13,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_13, \
	PORT_U2A_MODE_CFG_LVDS_USE_13 \
}
#define	CSTPORT_NOISEFILTER_SETTING_13 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_13, \
	PORT_U2A_MODE_CFG_FLT_CTRL_13, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_13 \
}
#define	CSTPORT_SAFESTATE_SETTING_13 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_13, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_13, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_13 \
}
/* P24_4 */
#define	CSTPORT_MODE_SETTING_14 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_14, \
	PORT_U2A_MODE_CFG_MODE_14, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_14, \
	PORT_U2A_MODE_CFG_IP_CTRL_14, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_14, \
	PORT_U2A_MODE_CFG_CTRL_EXP_14, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_14, \
	PORT_U2A_MODE_CFG_PULL_UP_14, \
	PORT_U2A_MODE_CFG_PULL_DOWN_14, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_14, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_14, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_14, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_14, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_14, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_14,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_14,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_14,\
	PORT_U2A_MODE_CFG_PORT_14,\
	PORT_U2A_MODE_CFG_PORT_NOT_14,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_14, \
	PORT_U2A_MODE_CFG_LVDS_USE_14 \
}
#define	CSTPORT_NOISEFILTER_SETTING_14 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_14, \
	PORT_U2A_MODE_CFG_FLT_CTRL_14, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_14 \
}
#define	CSTPORT_SAFESTATE_SETTING_14 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_14, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_14, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_14 \
}
/* P24_5 */
#define	CSTPORT_MODE_SETTING_15 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_15, \
	PORT_U2A_MODE_CFG_MODE_15, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_15, \
	PORT_U2A_MODE_CFG_IP_CTRL_15, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_15, \
	PORT_U2A_MODE_CFG_CTRL_EXP_15, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_15, \
	PORT_U2A_MODE_CFG_PULL_UP_15, \
	PORT_U2A_MODE_CFG_PULL_DOWN_15, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_15, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_15, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_15, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_15, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_15, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_15,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_15,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_15,\
	PORT_U2A_MODE_CFG_PORT_15,\
	PORT_U2A_MODE_CFG_PORT_NOT_15,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_15, \
	PORT_U2A_MODE_CFG_LVDS_USE_15 \
}
#define	CSTPORT_NOISEFILTER_SETTING_15 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_15, \
	PORT_U2A_MODE_CFG_FLT_CTRL_15, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_15 \
}
#define	CSTPORT_SAFESTATE_SETTING_15 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_15, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_15, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_15 \
}
/* P24_6 */
#define	CSTPORT_MODE_SETTING_16 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_16, \
	PORT_U2A_MODE_CFG_MODE_16, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_16, \
	PORT_U2A_MODE_CFG_IP_CTRL_16, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_16, \
	PORT_U2A_MODE_CFG_CTRL_EXP_16, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_16, \
	PORT_U2A_MODE_CFG_PULL_UP_16, \
	PORT_U2A_MODE_CFG_PULL_DOWN_16, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_16, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_16, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_16, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_16, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_16, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_16,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_16,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_16,\
	PORT_U2A_MODE_CFG_PORT_16,\
	PORT_U2A_MODE_CFG_PORT_NOT_16,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_16, \
	PORT_U2A_MODE_CFG_LVDS_USE_16 \
}
#define	CSTPORT_NOISEFILTER_SETTING_16 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_16, \
	PORT_U2A_MODE_CFG_FLT_CTRL_16, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_16 \
}
#define	CSTPORT_SAFESTATE_SETTING_16 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_16, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_16, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_16 \
}
/* P24_10 */
#define	CSTPORT_MODE_SETTING_17 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_17, \
	PORT_U2A_MODE_CFG_MODE_17, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_17, \
	PORT_U2A_MODE_CFG_IP_CTRL_17, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_17, \
	PORT_U2A_MODE_CFG_CTRL_EXP_17, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_17, \
	PORT_U2A_MODE_CFG_PULL_UP_17, \
	PORT_U2A_MODE_CFG_PULL_DOWN_17, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_17, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_17, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_17, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_17, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_17, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_17,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_17,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_17,\
	PORT_U2A_MODE_CFG_PORT_17,\
	PORT_U2A_MODE_CFG_PORT_NOT_17,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_17, \
	PORT_U2A_MODE_CFG_LVDS_USE_17 \
}
#define	CSTPORT_NOISEFILTER_SETTING_17 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_17, \
	PORT_U2A_MODE_CFG_FLT_CTRL_17, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_17 \
}
#define	CSTPORT_SAFESTATE_SETTING_17 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_17, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_17, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_17 \
}
/* P24_12 */
#define	CSTPORT_MODE_SETTING_18 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_18, \
	PORT_U2A_MODE_CFG_MODE_18, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_18, \
	PORT_U2A_MODE_CFG_IP_CTRL_18, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_18, \
	PORT_U2A_MODE_CFG_CTRL_EXP_18, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_18, \
	PORT_U2A_MODE_CFG_PULL_UP_18, \
	PORT_U2A_MODE_CFG_PULL_DOWN_18, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_18, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_18, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_18, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_18, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_18, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_18,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_18,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_18,\
	PORT_U2A_MODE_CFG_PORT_18,\
	PORT_U2A_MODE_CFG_PORT_NOT_18,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_18, \
	PORT_U2A_MODE_CFG_LVDS_USE_18 \
}
#define	CSTPORT_NOISEFILTER_SETTING_18 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_18, \
	PORT_U2A_MODE_CFG_FLT_CTRL_18, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_18 \
}
#define	CSTPORT_SAFESTATE_SETTING_18 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_18, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_18, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_18 \
}
/* P24_13 */
#define	CSTPORT_MODE_SETTING_19 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_19, \
	PORT_U2A_MODE_CFG_MODE_19, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_19, \
	PORT_U2A_MODE_CFG_IP_CTRL_19, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_19, \
	PORT_U2A_MODE_CFG_CTRL_EXP_19, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_19, \
	PORT_U2A_MODE_CFG_PULL_UP_19, \
	PORT_U2A_MODE_CFG_PULL_DOWN_19, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_19, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_19, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_19, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_19, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_19, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_19,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_19,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_19,\
	PORT_U2A_MODE_CFG_PORT_19,\
	PORT_U2A_MODE_CFG_PORT_NOT_19,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_19, \
	PORT_U2A_MODE_CFG_LVDS_USE_19 \
}
#define	CSTPORT_NOISEFILTER_SETTING_19 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_19, \
	PORT_U2A_MODE_CFG_FLT_CTRL_19, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_19 \
}
#define	CSTPORT_SAFESTATE_SETTING_19 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_19, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_19, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_19 \
}
/* P2_10 */
#define	CSTPORT_MODE_SETTING_20 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_20, \
	PORT_U2A_MODE_CFG_MODE_20, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_20, \
	PORT_U2A_MODE_CFG_IP_CTRL_20, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_20, \
	PORT_U2A_MODE_CFG_CTRL_EXP_20, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_20, \
	PORT_U2A_MODE_CFG_PULL_UP_20, \
	PORT_U2A_MODE_CFG_PULL_DOWN_20, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_20, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_20, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_20, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_20, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_20, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_20,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_20,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_20,\
	PORT_U2A_MODE_CFG_PORT_20,\
	PORT_U2A_MODE_CFG_PORT_NOT_20,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_20, \
	PORT_U2A_MODE_CFG_LVDS_USE_20 \
}
#define	CSTPORT_NOISEFILTER_SETTING_20 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_20, \
	PORT_U2A_MODE_CFG_FLT_CTRL_20, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_20 \
}
#define	CSTPORT_SAFESTATE_SETTING_20 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_20, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_20, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_20 \
}
/* P8_0 */
#define	CSTPORT_MODE_SETTING_21 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_21, \
	PORT_U2A_MODE_CFG_MODE_21, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_21, \
	PORT_U2A_MODE_CFG_IP_CTRL_21, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_21, \
	PORT_U2A_MODE_CFG_CTRL_EXP_21, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_21, \
	PORT_U2A_MODE_CFG_PULL_UP_21, \
	PORT_U2A_MODE_CFG_PULL_DOWN_21, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_21, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_21, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_21, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_21, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_21, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_21,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_21,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_21,\
	PORT_U2A_MODE_CFG_PORT_21,\
	PORT_U2A_MODE_CFG_PORT_NOT_21,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_21, \
	PORT_U2A_MODE_CFG_LVDS_USE_21 \
}
#define	CSTPORT_NOISEFILTER_SETTING_21 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_21, \
	PORT_U2A_MODE_CFG_FLT_CTRL_21, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_21 \
}
#define	CSTPORT_SAFESTATE_SETTING_21 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_21, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_21, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_21 \
}
/* P8_2 */
#define	CSTPORT_MODE_SETTING_22 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_22, \
	PORT_U2A_MODE_CFG_MODE_22, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_22, \
	PORT_U2A_MODE_CFG_IP_CTRL_22, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_22, \
	PORT_U2A_MODE_CFG_CTRL_EXP_22, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_22, \
	PORT_U2A_MODE_CFG_PULL_UP_22, \
	PORT_U2A_MODE_CFG_PULL_DOWN_22, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_22, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_22, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_22, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_22, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_22, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_22,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_22,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_22,\
	PORT_U2A_MODE_CFG_PORT_22,\
	PORT_U2A_MODE_CFG_PORT_NOT_22,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_22, \
	PORT_U2A_MODE_CFG_LVDS_USE_22 \
}
#define	CSTPORT_NOISEFILTER_SETTING_22 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_22, \
	PORT_U2A_MODE_CFG_FLT_CTRL_22, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_22 \
}
#define	CSTPORT_SAFESTATE_SETTING_22 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_22, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_22, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_22 \
}
/* AP5_1 */
#define	CSTPORT_MODE_SETTING_23 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_23, \
	PORT_U2A_MODE_CFG_MODE_23, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_23, \
	PORT_U2A_MODE_CFG_IP_CTRL_23, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_23, \
	PORT_U2A_MODE_CFG_CTRL_EXP_23, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_23, \
	PORT_U2A_MODE_CFG_PULL_UP_23, \
	PORT_U2A_MODE_CFG_PULL_DOWN_23, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_23, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_23, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_23, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_23, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_23, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_23,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_23,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_23,\
	PORT_U2A_MODE_CFG_PORT_23,\
	PORT_U2A_MODE_CFG_PORT_NOT_23,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_23, \
	PORT_U2A_MODE_CFG_LVDS_USE_23 \
}
#define	CSTPORT_NOISEFILTER_SETTING_23 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_23, \
	PORT_U2A_MODE_CFG_FLT_CTRL_23, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_23 \
}
#define	CSTPORT_SAFESTATE_SETTING_23 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_23, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_23, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_23 \
}
/* P10_0 */
#define	CSTPORT_MODE_SETTING_24 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_24, \
	PORT_U2A_MODE_CFG_MODE_24, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_24, \
	PORT_U2A_MODE_CFG_IP_CTRL_24, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_24, \
	PORT_U2A_MODE_CFG_CTRL_EXP_24, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_24, \
	PORT_U2A_MODE_CFG_PULL_UP_24, \
	PORT_U2A_MODE_CFG_PULL_DOWN_24, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_24, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_24, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_24, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_24, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_24, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_24,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_24,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_24,\
	PORT_U2A_MODE_CFG_PORT_24,\
	PORT_U2A_MODE_CFG_PORT_NOT_24,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_24, \
	PORT_U2A_MODE_CFG_LVDS_USE_24 \
}
#define	CSTPORT_NOISEFILTER_SETTING_24 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_24, \
	PORT_U2A_MODE_CFG_FLT_CTRL_24, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_24 \
}
#define	CSTPORT_SAFESTATE_SETTING_24 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_24, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_24, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_24 \
}
/* P10_1 */
#define	CSTPORT_MODE_SETTING_25 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_25, \
	PORT_U2A_MODE_CFG_MODE_25, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_25, \
	PORT_U2A_MODE_CFG_IP_CTRL_25, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_25, \
	PORT_U2A_MODE_CFG_CTRL_EXP_25, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_25, \
	PORT_U2A_MODE_CFG_PULL_UP_25, \
	PORT_U2A_MODE_CFG_PULL_DOWN_25, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_25, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_25, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_25, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_25, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_25, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_25,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_25,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_25,\
	PORT_U2A_MODE_CFG_PORT_25,\
	PORT_U2A_MODE_CFG_PORT_NOT_25,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_25, \
	PORT_U2A_MODE_CFG_LVDS_USE_25 \
}
#define	CSTPORT_NOISEFILTER_SETTING_25 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_25, \
	PORT_U2A_MODE_CFG_FLT_CTRL_25, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_25 \
}
#define	CSTPORT_SAFESTATE_SETTING_25 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_25, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_25, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_25 \
}
/* P22_3 */
#define	CSTPORT_MODE_SETTING_26 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_26, \
	PORT_U2A_MODE_CFG_MODE_26, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_26, \
	PORT_U2A_MODE_CFG_IP_CTRL_26, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_26, \
	PORT_U2A_MODE_CFG_CTRL_EXP_26, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_26, \
	PORT_U2A_MODE_CFG_PULL_UP_26, \
	PORT_U2A_MODE_CFG_PULL_DOWN_26, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_26, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_26, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_26, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_26, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_26, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_26,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_26,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_26,\
	PORT_U2A_MODE_CFG_PORT_26,\
	PORT_U2A_MODE_CFG_PORT_NOT_26,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_26, \
	PORT_U2A_MODE_CFG_LVDS_USE_26 \
}
#define	CSTPORT_NOISEFILTER_SETTING_26 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_26, \
	PORT_U2A_MODE_CFG_FLT_CTRL_26, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_26 \
}
#define	CSTPORT_SAFESTATE_SETTING_26 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_26, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_26, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_26 \
}
/* P22_4 */
#define	CSTPORT_MODE_SETTING_27 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_27, \
	PORT_U2A_MODE_CFG_MODE_27, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_27, \
	PORT_U2A_MODE_CFG_IP_CTRL_27, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_27, \
	PORT_U2A_MODE_CFG_CTRL_EXP_27, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_27, \
	PORT_U2A_MODE_CFG_PULL_UP_27, \
	PORT_U2A_MODE_CFG_PULL_DOWN_27, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_27, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_27, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_27, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_27, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_27, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_27,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_27,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_27,\
	PORT_U2A_MODE_CFG_PORT_27,\
	PORT_U2A_MODE_CFG_PORT_NOT_27,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_27, \
	PORT_U2A_MODE_CFG_LVDS_USE_27 \
}
#define	CSTPORT_NOISEFILTER_SETTING_27 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_27, \
	PORT_U2A_MODE_CFG_FLT_CTRL_27, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_27 \
}
#define	CSTPORT_SAFESTATE_SETTING_27 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_27, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_27, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_27 \
}
/* P10_0 */
#define	CSTPORT_MODE_SETTING_28 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_28, \
	PORT_U2A_MODE_CFG_MODE_28, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_28, \
	PORT_U2A_MODE_CFG_IP_CTRL_28, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_28, \
	PORT_U2A_MODE_CFG_CTRL_EXP_28, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_28, \
	PORT_U2A_MODE_CFG_PULL_UP_28, \
	PORT_U2A_MODE_CFG_PULL_DOWN_28, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_28, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_28, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_28, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_28, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_28, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_28,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_28,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_28,\
	PORT_U2A_MODE_CFG_PORT_28,\
	PORT_U2A_MODE_CFG_PORT_NOT_28,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_28, \
	PORT_U2A_MODE_CFG_LVDS_USE_28 \
}
#define	CSTPORT_NOISEFILTER_SETTING_28 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_28, \
	PORT_U2A_MODE_CFG_FLT_CTRL_28, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_28 \
}
#define	CSTPORT_SAFESTATE_SETTING_28 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_28, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_28, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_28 \
}
/* P10_1 */
#define	CSTPORT_MODE_SETTING_29 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_29, \
	PORT_U2A_MODE_CFG_MODE_29, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_29, \
	PORT_U2A_MODE_CFG_IP_CTRL_29, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_29, \
	PORT_U2A_MODE_CFG_CTRL_EXP_29, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_29, \
	PORT_U2A_MODE_CFG_PULL_UP_29, \
	PORT_U2A_MODE_CFG_PULL_DOWN_29, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_29, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_29, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_29, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_29, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_29, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_29,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_29,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_29,\
	PORT_U2A_MODE_CFG_PORT_29,\
	PORT_U2A_MODE_CFG_PORT_NOT_29,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_29, \
	PORT_U2A_MODE_CFG_LVDS_USE_29 \
}
#define	CSTPORT_NOISEFILTER_SETTING_29 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_29, \
	PORT_U2A_MODE_CFG_FLT_CTRL_29, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_29 \
}
#define	CSTPORT_SAFESTATE_SETTING_29 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_29, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_29, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_29 \
}
/* P22_3 */
#define	CSTPORT_MODE_SETTING_30 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_30, \
	PORT_U2A_MODE_CFG_MODE_30, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_30, \
	PORT_U2A_MODE_CFG_IP_CTRL_30, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_30, \
	PORT_U2A_MODE_CFG_CTRL_EXP_30, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_30, \
	PORT_U2A_MODE_CFG_PULL_UP_30, \
	PORT_U2A_MODE_CFG_PULL_DOWN_30, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_30, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_30, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_30, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_30, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_30, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_30,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_30,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_30,\
	PORT_U2A_MODE_CFG_PORT_30,\
	PORT_U2A_MODE_CFG_PORT_NOT_30,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_30, \
	PORT_U2A_MODE_CFG_LVDS_USE_30 \
}
#define	CSTPORT_NOISEFILTER_SETTING_30 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_30, \
	PORT_U2A_MODE_CFG_FLT_CTRL_30, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_30 \
}
#define	CSTPORT_SAFESTATE_SETTING_30 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_30, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_30, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_30 \
}
/* P22_4 */
#define	CSTPORT_MODE_SETTING_31 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_31, \
	PORT_U2A_MODE_CFG_MODE_31, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_31, \
	PORT_U2A_MODE_CFG_IP_CTRL_31, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_31, \
	PORT_U2A_MODE_CFG_CTRL_EXP_31, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_31, \
	PORT_U2A_MODE_CFG_PULL_UP_31, \
	PORT_U2A_MODE_CFG_PULL_DOWN_31, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_31, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_31, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_31, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_31, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_31, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_31,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_31,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_31,\
	PORT_U2A_MODE_CFG_PORT_31,\
	PORT_U2A_MODE_CFG_PORT_NOT_31,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_31, \
	PORT_U2A_MODE_CFG_LVDS_USE_31 \
}
#define	CSTPORT_NOISEFILTER_SETTING_31 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_31, \
	PORT_U2A_MODE_CFG_FLT_CTRL_31, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_31 \
}
#define	CSTPORT_SAFESTATE_SETTING_31 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_31, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_31, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_31 \
}
/* P2_10 */
#define	CSTPORT_MODE_SETTING_32 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_32, \
	PORT_U2A_MODE_CFG_MODE_32, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_32, \
	PORT_U2A_MODE_CFG_IP_CTRL_32, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_32, \
	PORT_U2A_MODE_CFG_CTRL_EXP_32, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_32, \
	PORT_U2A_MODE_CFG_PULL_UP_32, \
	PORT_U2A_MODE_CFG_PULL_DOWN_32, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_32, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_32, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_32, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_32, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_32, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_32,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_32,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_32,\
	PORT_U2A_MODE_CFG_PORT_32,\
	PORT_U2A_MODE_CFG_PORT_NOT_32,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_32, \
	PORT_U2A_MODE_CFG_LVDS_USE_32 \
}
#define	CSTPORT_NOISEFILTER_SETTING_32 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_32, \
	PORT_U2A_MODE_CFG_FLT_CTRL_32, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_32 \
}
#define	CSTPORT_SAFESTATE_SETTING_32 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_32, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_32, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_32 \
}
/* P2_11 */
#define	CSTPORT_MODE_SETTING_33 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_33, \
	PORT_U2A_MODE_CFG_MODE_33, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_33, \
	PORT_U2A_MODE_CFG_IP_CTRL_33, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_33, \
	PORT_U2A_MODE_CFG_CTRL_EXP_33, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_33, \
	PORT_U2A_MODE_CFG_PULL_UP_33, \
	PORT_U2A_MODE_CFG_PULL_DOWN_33, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_33, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_33, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_33, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_33, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_33, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_33,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_33,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_33,\
	PORT_U2A_MODE_CFG_PORT_33,\
	PORT_U2A_MODE_CFG_PORT_NOT_33,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_33, \
	PORT_U2A_MODE_CFG_LVDS_USE_33 \
}
#define	CSTPORT_NOISEFILTER_SETTING_33 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_33, \
	PORT_U2A_MODE_CFG_FLT_CTRL_33, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_33 \
}
#define	CSTPORT_SAFESTATE_SETTING_33 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_33, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_33, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_33 \
}
/* P2_12 */
#define	CSTPORT_MODE_SETTING_34 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_34, \
	PORT_U2A_MODE_CFG_MODE_34, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_34, \
	PORT_U2A_MODE_CFG_IP_CTRL_34, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_34, \
	PORT_U2A_MODE_CFG_CTRL_EXP_34, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_34, \
	PORT_U2A_MODE_CFG_PULL_UP_34, \
	PORT_U2A_MODE_CFG_PULL_DOWN_34, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_34, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_34, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_34, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_34, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_34, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_34,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_34,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_34,\
	PORT_U2A_MODE_CFG_PORT_34,\
	PORT_U2A_MODE_CFG_PORT_NOT_34,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_34, \
	PORT_U2A_MODE_CFG_LVDS_USE_34 \
}
#define	CSTPORT_NOISEFILTER_SETTING_34 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_34, \
	PORT_U2A_MODE_CFG_FLT_CTRL_34, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_34 \
}
#define	CSTPORT_SAFESTATE_SETTING_34 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_34, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_34, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_34 \
}
/* P2_13 */
#define	CSTPORT_MODE_SETTING_35 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_35, \
	PORT_U2A_MODE_CFG_MODE_35, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_35, \
	PORT_U2A_MODE_CFG_IP_CTRL_35, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_35, \
	PORT_U2A_MODE_CFG_CTRL_EXP_35, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_35, \
	PORT_U2A_MODE_CFG_PULL_UP_35, \
	PORT_U2A_MODE_CFG_PULL_DOWN_35, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_35, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_35, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_35, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_35, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_35, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_35,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_35,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_35,\
	PORT_U2A_MODE_CFG_PORT_35,\
	PORT_U2A_MODE_CFG_PORT_NOT_35,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_35, \
	PORT_U2A_MODE_CFG_LVDS_USE_35 \
}
#define	CSTPORT_NOISEFILTER_SETTING_35 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_35, \
	PORT_U2A_MODE_CFG_FLT_CTRL_35, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_35 \
}
#define	CSTPORT_SAFESTATE_SETTING_35 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_35, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_35, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_35 \
}
/* P2_14 */
#define	CSTPORT_MODE_SETTING_36 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_36, \
	PORT_U2A_MODE_CFG_MODE_36, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_36, \
	PORT_U2A_MODE_CFG_IP_CTRL_36, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_36, \
	PORT_U2A_MODE_CFG_CTRL_EXP_36, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_36, \
	PORT_U2A_MODE_CFG_PULL_UP_36, \
	PORT_U2A_MODE_CFG_PULL_DOWN_36, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_36, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_36, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_36, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_36, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_36, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_36,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_36,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_36,\
	PORT_U2A_MODE_CFG_PORT_36,\
	PORT_U2A_MODE_CFG_PORT_NOT_36,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_36, \
	PORT_U2A_MODE_CFG_LVDS_USE_36 \
}
#define	CSTPORT_NOISEFILTER_SETTING_36 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_36, \
	PORT_U2A_MODE_CFG_FLT_CTRL_36, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_36 \
}
#define	CSTPORT_SAFESTATE_SETTING_36 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_36, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_36, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_36 \
}
/* P4_5 */
#define	CSTPORT_MODE_SETTING_37 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_37, \
	PORT_U2A_MODE_CFG_MODE_37, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_37, \
	PORT_U2A_MODE_CFG_IP_CTRL_37, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_37, \
	PORT_U2A_MODE_CFG_CTRL_EXP_37, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_37, \
	PORT_U2A_MODE_CFG_PULL_UP_37, \
	PORT_U2A_MODE_CFG_PULL_DOWN_37, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_37, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_37, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_37, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_37, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_37, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_37,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_37,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_37,\
	PORT_U2A_MODE_CFG_PORT_37,\
	PORT_U2A_MODE_CFG_PORT_NOT_37,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_37, \
	PORT_U2A_MODE_CFG_LVDS_USE_37 \
}
#define	CSTPORT_NOISEFILTER_SETTING_37 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_37, \
	PORT_U2A_MODE_CFG_FLT_CTRL_37, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_37 \
}
#define	CSTPORT_SAFESTATE_SETTING_37 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_37, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_37, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_37 \
}
/* P4_6 */
#define	CSTPORT_MODE_SETTING_38 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_38, \
	PORT_U2A_MODE_CFG_MODE_38, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_38, \
	PORT_U2A_MODE_CFG_IP_CTRL_38, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_38, \
	PORT_U2A_MODE_CFG_CTRL_EXP_38, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_38, \
	PORT_U2A_MODE_CFG_PULL_UP_38, \
	PORT_U2A_MODE_CFG_PULL_DOWN_38, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_38, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_38, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_38, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_38, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_38, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_38,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_38,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_38,\
	PORT_U2A_MODE_CFG_PORT_38,\
	PORT_U2A_MODE_CFG_PORT_NOT_38,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_38, \
	PORT_U2A_MODE_CFG_LVDS_USE_38 \
}
#define	CSTPORT_NOISEFILTER_SETTING_38 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_38, \
	PORT_U2A_MODE_CFG_FLT_CTRL_38, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_38 \
}
#define	CSTPORT_SAFESTATE_SETTING_38 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_38, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_38, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_38 \
}
/* P4_7 */
#define	CSTPORT_MODE_SETTING_39 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_39, \
	PORT_U2A_MODE_CFG_MODE_39, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_39, \
	PORT_U2A_MODE_CFG_IP_CTRL_39, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_39, \
	PORT_U2A_MODE_CFG_CTRL_EXP_39, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_39, \
	PORT_U2A_MODE_CFG_PULL_UP_39, \
	PORT_U2A_MODE_CFG_PULL_DOWN_39, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_39, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_39, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_39, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_39, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_39, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_39,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_39,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_39,\
	PORT_U2A_MODE_CFG_PORT_39,\
	PORT_U2A_MODE_CFG_PORT_NOT_39,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_39, \
	PORT_U2A_MODE_CFG_LVDS_USE_39 \
}
#define	CSTPORT_NOISEFILTER_SETTING_39 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_39, \
	PORT_U2A_MODE_CFG_FLT_CTRL_39, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_39 \
}
#define	CSTPORT_SAFESTATE_SETTING_39 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_39, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_39, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_39 \
}
/* P4_10 */
#define	CSTPORT_MODE_SETTING_40 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_40, \
	PORT_U2A_MODE_CFG_MODE_40, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_40, \
	PORT_U2A_MODE_CFG_IP_CTRL_40, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_40, \
	PORT_U2A_MODE_CFG_CTRL_EXP_40, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_40, \
	PORT_U2A_MODE_CFG_PULL_UP_40, \
	PORT_U2A_MODE_CFG_PULL_DOWN_40, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_40, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_40, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_40, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_40, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_40, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_40,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_40,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_40,\
	PORT_U2A_MODE_CFG_PORT_40,\
	PORT_U2A_MODE_CFG_PORT_NOT_40,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_40, \
	PORT_U2A_MODE_CFG_LVDS_USE_40 \
}
#define	CSTPORT_NOISEFILTER_SETTING_40 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_40, \
	PORT_U2A_MODE_CFG_FLT_CTRL_40, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_40 \
}
#define	CSTPORT_SAFESTATE_SETTING_40 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_40, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_40, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_40 \
}
/* P20_1 */
#define	CSTPORT_MODE_SETTING_41 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_41, \
	PORT_U2A_MODE_CFG_MODE_41, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_41, \
	PORT_U2A_MODE_CFG_IP_CTRL_41, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_41, \
	PORT_U2A_MODE_CFG_CTRL_EXP_41, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_41, \
	PORT_U2A_MODE_CFG_PULL_UP_41, \
	PORT_U2A_MODE_CFG_PULL_DOWN_41, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_41, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_41, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_41, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_41, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_41, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_41,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_41,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_41,\
	PORT_U2A_MODE_CFG_PORT_41,\
	PORT_U2A_MODE_CFG_PORT_NOT_41,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_41, \
	PORT_U2A_MODE_CFG_LVDS_USE_41 \
}
#define	CSTPORT_NOISEFILTER_SETTING_41 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_41, \
	PORT_U2A_MODE_CFG_FLT_CTRL_41, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_41 \
}
#define	CSTPORT_SAFESTATE_SETTING_41 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_41, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_41, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_41 \
}
/* P20_2 */
#define	CSTPORT_MODE_SETTING_42 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_42, \
	PORT_U2A_MODE_CFG_MODE_42, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_42, \
	PORT_U2A_MODE_CFG_IP_CTRL_42, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_42, \
	PORT_U2A_MODE_CFG_CTRL_EXP_42, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_42, \
	PORT_U2A_MODE_CFG_PULL_UP_42, \
	PORT_U2A_MODE_CFG_PULL_DOWN_42, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_42, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_42, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_42, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_42, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_42, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_42,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_42,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_42,\
	PORT_U2A_MODE_CFG_PORT_42,\
	PORT_U2A_MODE_CFG_PORT_NOT_42,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_42, \
	PORT_U2A_MODE_CFG_LVDS_USE_42 \
}
#define	CSTPORT_NOISEFILTER_SETTING_42 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_42, \
	PORT_U2A_MODE_CFG_FLT_CTRL_42, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_42 \
}
#define	CSTPORT_SAFESTATE_SETTING_42 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_42, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_42, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_42 \
}
/* P21_0 */
#define	CSTPORT_MODE_SETTING_43 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_43, \
	PORT_U2A_MODE_CFG_MODE_43, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_43, \
	PORT_U2A_MODE_CFG_IP_CTRL_43, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_43, \
	PORT_U2A_MODE_CFG_CTRL_EXP_43, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_43, \
	PORT_U2A_MODE_CFG_PULL_UP_43, \
	PORT_U2A_MODE_CFG_PULL_DOWN_43, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_43, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_43, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_43, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_43, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_43, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_43,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_43,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_43,\
	PORT_U2A_MODE_CFG_PORT_43,\
	PORT_U2A_MODE_CFG_PORT_NOT_43,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_43, \
	PORT_U2A_MODE_CFG_LVDS_USE_43 \
}
#define	CSTPORT_NOISEFILTER_SETTING_43 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_43, \
	PORT_U2A_MODE_CFG_FLT_CTRL_43, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_43 \
}
#define	CSTPORT_SAFESTATE_SETTING_43 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_43, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_43, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_43 \
}
/* P21_1 */
#define	CSTPORT_MODE_SETTING_44 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_44, \
	PORT_U2A_MODE_CFG_MODE_44, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_44, \
	PORT_U2A_MODE_CFG_IP_CTRL_44, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_44, \
	PORT_U2A_MODE_CFG_CTRL_EXP_44, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_44, \
	PORT_U2A_MODE_CFG_PULL_UP_44, \
	PORT_U2A_MODE_CFG_PULL_DOWN_44, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_44, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_44, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_44, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_44, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_44, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_44,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_44,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_44,\
	PORT_U2A_MODE_CFG_PORT_44,\
	PORT_U2A_MODE_CFG_PORT_NOT_44,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_44, \
	PORT_U2A_MODE_CFG_LVDS_USE_44 \
}
#define	CSTPORT_NOISEFILTER_SETTING_44 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_44, \
	PORT_U2A_MODE_CFG_FLT_CTRL_44, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_44 \
}
#define	CSTPORT_SAFESTATE_SETTING_44 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_44, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_44, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_44 \
}
/* P21_2 */
#define	CSTPORT_MODE_SETTING_45 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_45, \
	PORT_U2A_MODE_CFG_MODE_45, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_45, \
	PORT_U2A_MODE_CFG_IP_CTRL_45, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_45, \
	PORT_U2A_MODE_CFG_CTRL_EXP_45, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_45, \
	PORT_U2A_MODE_CFG_PULL_UP_45, \
	PORT_U2A_MODE_CFG_PULL_DOWN_45, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_45, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_45, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_45, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_45, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_45, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_45,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_45,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_45,\
	PORT_U2A_MODE_CFG_PORT_45,\
	PORT_U2A_MODE_CFG_PORT_NOT_45,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_45, \
	PORT_U2A_MODE_CFG_LVDS_USE_45 \
}
#define	CSTPORT_NOISEFILTER_SETTING_45 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_45, \
	PORT_U2A_MODE_CFG_FLT_CTRL_45, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_45 \
}
#define	CSTPORT_SAFESTATE_SETTING_45 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_45, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_45, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_45 \
}
/* P24_10 */
#define	CSTPORT_MODE_SETTING_46 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_46, \
	PORT_U2A_MODE_CFG_MODE_46, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_46, \
	PORT_U2A_MODE_CFG_IP_CTRL_46, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_46, \
	PORT_U2A_MODE_CFG_CTRL_EXP_46, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_46, \
	PORT_U2A_MODE_CFG_PULL_UP_46, \
	PORT_U2A_MODE_CFG_PULL_DOWN_46, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_46, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_46, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_46, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_46, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_46, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_46,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_46,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_46,\
	PORT_U2A_MODE_CFG_PORT_46,\
	PORT_U2A_MODE_CFG_PORT_NOT_46,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_46, \
	PORT_U2A_MODE_CFG_LVDS_USE_46 \
}
#define	CSTPORT_NOISEFILTER_SETTING_46 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_46, \
	PORT_U2A_MODE_CFG_FLT_CTRL_46, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_46 \
}
#define	CSTPORT_SAFESTATE_SETTING_46 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_46, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_46, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_46 \
}
/* P24_12 */
#define	CSTPORT_MODE_SETTING_47 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_47, \
	PORT_U2A_MODE_CFG_MODE_47, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_47, \
	PORT_U2A_MODE_CFG_IP_CTRL_47, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_47, \
	PORT_U2A_MODE_CFG_CTRL_EXP_47, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_47, \
	PORT_U2A_MODE_CFG_PULL_UP_47, \
	PORT_U2A_MODE_CFG_PULL_DOWN_47, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_47, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_47, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_47, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_47, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_47, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_47,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_47,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_47,\
	PORT_U2A_MODE_CFG_PORT_47,\
	PORT_U2A_MODE_CFG_PORT_NOT_47,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_47, \
	PORT_U2A_MODE_CFG_LVDS_USE_47 \
}
#define	CSTPORT_NOISEFILTER_SETTING_47 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_47, \
	PORT_U2A_MODE_CFG_FLT_CTRL_47, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_47 \
}
#define	CSTPORT_SAFESTATE_SETTING_47 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_47, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_47, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_47 \
}
/* P24_13 */
#define	CSTPORT_MODE_SETTING_48 { \
	PORT_U2A_MODE_CFG_MODE_CTRL_48, \
	PORT_U2A_MODE_CFG_MODE_48, \
	PORT_U2A_MODE_CFG_IN_BUF_CTRL_48, \
	PORT_U2A_MODE_CFG_IP_CTRL_48, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_48, \
	PORT_U2A_MODE_CFG_CTRL_EXP_48, \
	PORT_U2A_MODE_CFG_FUNC_CTRL_ADD_EXP_48, \
	PORT_U2A_MODE_CFG_PULL_UP_48, \
	PORT_U2A_MODE_CFG_PULL_DOWN_48, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_48, \
	PORT_U2A_MODE_CFG_IN_BUF_SEL_ADV_48, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_48, \
	PORT_U2A_MODE_CFG_OPEN_DRAIN_CTRL_EXP_48, \
	PORT_U2A_MODE_CFG_DRIVE_STR_CTRL_48, \
	PORT_U2A_MODE_CFG_UNIV_CHAR_CTRL_48,\
	PORT_U2A_MODE_CFG_OUT_VAL_INV_48,\
	PORT_U2A_MODE_CFG_BI_DIRECTION_CTRL_48,\
	PORT_U2A_MODE_CFG_PORT_48,\
	PORT_U2A_MODE_CFG_PORT_NOT_48,\
	PORT_U2A_MODE_CFG_LVDS_VOLTAGE_48, \
	PORT_U2A_MODE_CFG_LVDS_USE_48 \
}
#define	CSTPORT_NOISEFILTER_SETTING_48 { \
	PORT_NOISE_FILTER_FUNC_RLIN30RX, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_ENABLE_48, \
	PORT_U2A_MODE_CFG_FLT_CTRL_48, \
	PORT_U2A_MODE_CFG_DIG_NOISE_ELIM_CTRL_48 \
}
#define	CSTPORT_SAFESTATE_SETTING_48 { \
	PORT_U2A_MODE_CFG_SAFE_STATE_CTRL_48, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_48, \
	PORT_U2A_MODE_CFG_ERR_TRG_SEL_EXP_48 \
}

#define PORT_START_SEC_CONST_UNSPECIFIED
#include "Port_MemMap.h"
CONST(Port_SetPinModeType, PORT_CONST) cstPort_SetPinMode[] = {
	{
		CSTPORT_MODE_SETTING_0,
		CSTPORT_NOISEFILTER_SETTING_0,
		CSTPORT_SAFESTATE_SETTING_0,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_0,
		PORT_U2A_MODE_CFG_MODE_FLAG_0,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_0
	},
	{
		CSTPORT_MODE_SETTING_1,
		CSTPORT_NOISEFILTER_SETTING_1,
		CSTPORT_SAFESTATE_SETTING_1,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_1,
		PORT_U2A_MODE_CFG_MODE_FLAG_1,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_1
	},
	{
		CSTPORT_MODE_SETTING_2,
		CSTPORT_NOISEFILTER_SETTING_2,
		CSTPORT_SAFESTATE_SETTING_2,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_2,
		PORT_U2A_MODE_CFG_MODE_FLAG_2,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_2
	},
	{
		CSTPORT_MODE_SETTING_3,
		CSTPORT_NOISEFILTER_SETTING_3,
		CSTPORT_SAFESTATE_SETTING_3,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_3,
		PORT_U2A_MODE_CFG_MODE_FLAG_3,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_3
	},
	{
		CSTPORT_MODE_SETTING_4,
		CSTPORT_NOISEFILTER_SETTING_4,
		CSTPORT_SAFESTATE_SETTING_4,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_4,
		PORT_U2A_MODE_CFG_MODE_FLAG_4,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_4
	},
	{
		CSTPORT_MODE_SETTING_5,
		CSTPORT_NOISEFILTER_SETTING_5,
		CSTPORT_SAFESTATE_SETTING_5,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_5,
		PORT_U2A_MODE_CFG_MODE_FLAG_5,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_5
	},
	{
		CSTPORT_MODE_SETTING_6,
		CSTPORT_NOISEFILTER_SETTING_6,
		CSTPORT_SAFESTATE_SETTING_6,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_6,
		PORT_U2A_MODE_CFG_MODE_FLAG_6,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_6
	},
	{
		CSTPORT_MODE_SETTING_7,
		CSTPORT_NOISEFILTER_SETTING_7,
		CSTPORT_SAFESTATE_SETTING_7,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_7,
		PORT_U2A_MODE_CFG_MODE_FLAG_7,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_7
	},
	{
		CSTPORT_MODE_SETTING_8,
		CSTPORT_NOISEFILTER_SETTING_8,
		CSTPORT_SAFESTATE_SETTING_8,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_8,
		PORT_U2A_MODE_CFG_MODE_FLAG_8,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_8
	},
	{
		CSTPORT_MODE_SETTING_9,
		CSTPORT_NOISEFILTER_SETTING_9,
		CSTPORT_SAFESTATE_SETTING_9,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_9,
		PORT_U2A_MODE_CFG_MODE_FLAG_9,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_9
	},
	{
		CSTPORT_MODE_SETTING_10,
		CSTPORT_NOISEFILTER_SETTING_10,
		CSTPORT_SAFESTATE_SETTING_10,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_10,
		PORT_U2A_MODE_CFG_MODE_FLAG_10,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_10
	},
	{
		CSTPORT_MODE_SETTING_11,
		CSTPORT_NOISEFILTER_SETTING_11,
		CSTPORT_SAFESTATE_SETTING_11,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_11,
		PORT_U2A_MODE_CFG_MODE_FLAG_11,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_11
	},
	{
		CSTPORT_MODE_SETTING_12,
		CSTPORT_NOISEFILTER_SETTING_12,
		CSTPORT_SAFESTATE_SETTING_12,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_12,
		PORT_U2A_MODE_CFG_MODE_FLAG_12,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_12
	},
	{
		CSTPORT_MODE_SETTING_13,
		CSTPORT_NOISEFILTER_SETTING_13,
		CSTPORT_SAFESTATE_SETTING_13,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_13,
		PORT_U2A_MODE_CFG_MODE_FLAG_13,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_13
	},
	{
		CSTPORT_MODE_SETTING_14,
		CSTPORT_NOISEFILTER_SETTING_14,
		CSTPORT_SAFESTATE_SETTING_14,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_14,
		PORT_U2A_MODE_CFG_MODE_FLAG_14,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_14
	},
	{
		CSTPORT_MODE_SETTING_15,
		CSTPORT_NOISEFILTER_SETTING_15,
		CSTPORT_SAFESTATE_SETTING_15,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_15,
		PORT_U2A_MODE_CFG_MODE_FLAG_15,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_15
	},
	{
		CSTPORT_MODE_SETTING_16,
		CSTPORT_NOISEFILTER_SETTING_16,
		CSTPORT_SAFESTATE_SETTING_16,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_16,
		PORT_U2A_MODE_CFG_MODE_FLAG_16,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_16
	},
	{
		CSTPORT_MODE_SETTING_17,
		CSTPORT_NOISEFILTER_SETTING_17,
		CSTPORT_SAFESTATE_SETTING_17,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_17,
		PORT_U2A_MODE_CFG_MODE_FLAG_17,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_17
	},
	{
		CSTPORT_MODE_SETTING_18,
		CSTPORT_NOISEFILTER_SETTING_18,
		CSTPORT_SAFESTATE_SETTING_18,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_18,
		PORT_U2A_MODE_CFG_MODE_FLAG_18,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_18
	},
	{
		CSTPORT_MODE_SETTING_19,
		CSTPORT_NOISEFILTER_SETTING_19,
		CSTPORT_SAFESTATE_SETTING_19,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_19,
		PORT_U2A_MODE_CFG_MODE_FLAG_19,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_19
	},
	{
		CSTPORT_MODE_SETTING_20,
		CSTPORT_NOISEFILTER_SETTING_20,
		CSTPORT_SAFESTATE_SETTING_20,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_20,
		PORT_U2A_MODE_CFG_MODE_FLAG_20,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_20
	},
	{
		CSTPORT_MODE_SETTING_21,
		CSTPORT_NOISEFILTER_SETTING_21,
		CSTPORT_SAFESTATE_SETTING_21,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_21,
		PORT_U2A_MODE_CFG_MODE_FLAG_21,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_21
	},
	{
		CSTPORT_MODE_SETTING_22,
		CSTPORT_NOISEFILTER_SETTING_22,
		CSTPORT_SAFESTATE_SETTING_22,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_22,
		PORT_U2A_MODE_CFG_MODE_FLAG_22,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_22
	},
	{
		CSTPORT_MODE_SETTING_23,
		CSTPORT_NOISEFILTER_SETTING_23,
		CSTPORT_SAFESTATE_SETTING_23,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_23,
		PORT_U2A_MODE_CFG_MODE_FLAG_23,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_23
	},
	{
		CSTPORT_MODE_SETTING_24,
		CSTPORT_NOISEFILTER_SETTING_24,
		CSTPORT_SAFESTATE_SETTING_24,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_24,
		PORT_U2A_MODE_CFG_MODE_FLAG_24,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_24
	},
	{
		CSTPORT_MODE_SETTING_25,
		CSTPORT_NOISEFILTER_SETTING_25,
		CSTPORT_SAFESTATE_SETTING_25,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_25,
		PORT_U2A_MODE_CFG_MODE_FLAG_25,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_25
	},
	{
		CSTPORT_MODE_SETTING_26,
		CSTPORT_NOISEFILTER_SETTING_26,
		CSTPORT_SAFESTATE_SETTING_26,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_26,
		PORT_U2A_MODE_CFG_MODE_FLAG_26,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_26
	},
	{
		CSTPORT_MODE_SETTING_27,
		CSTPORT_NOISEFILTER_SETTING_27,
		CSTPORT_SAFESTATE_SETTING_27,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_27,
		PORT_U2A_MODE_CFG_MODE_FLAG_27,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_27
	},
	{
		CSTPORT_MODE_SETTING_28,
		CSTPORT_NOISEFILTER_SETTING_28,
		CSTPORT_SAFESTATE_SETTING_28,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_28,
		PORT_U2A_MODE_CFG_MODE_FLAG_28,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_28
	},
	{
		CSTPORT_MODE_SETTING_29,
		CSTPORT_NOISEFILTER_SETTING_29,
		CSTPORT_SAFESTATE_SETTING_29,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_29,
		PORT_U2A_MODE_CFG_MODE_FLAG_29,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_29
	},
	{
		CSTPORT_MODE_SETTING_30,
		CSTPORT_NOISEFILTER_SETTING_30,
		CSTPORT_SAFESTATE_SETTING_30,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_30,
		PORT_U2A_MODE_CFG_MODE_FLAG_30,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_30
	},
	{
		CSTPORT_MODE_SETTING_31,
		CSTPORT_NOISEFILTER_SETTING_31,
		CSTPORT_SAFESTATE_SETTING_31,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_31,
		PORT_U2A_MODE_CFG_MODE_FLAG_31,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_31
	},
	{
		CSTPORT_MODE_SETTING_32,
		CSTPORT_NOISEFILTER_SETTING_32,
		CSTPORT_SAFESTATE_SETTING_32,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_32,
		PORT_U2A_MODE_CFG_MODE_FLAG_32,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_32
	},
	{
		CSTPORT_MODE_SETTING_33,
		CSTPORT_NOISEFILTER_SETTING_33,
		CSTPORT_SAFESTATE_SETTING_33,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_33,
		PORT_U2A_MODE_CFG_MODE_FLAG_33,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_33
	},
	{
		CSTPORT_MODE_SETTING_34,
		CSTPORT_NOISEFILTER_SETTING_34,
		CSTPORT_SAFESTATE_SETTING_34,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_34,
		PORT_U2A_MODE_CFG_MODE_FLAG_34,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_34
	},
	{
		CSTPORT_MODE_SETTING_35,
		CSTPORT_NOISEFILTER_SETTING_35,
		CSTPORT_SAFESTATE_SETTING_35,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_35,
		PORT_U2A_MODE_CFG_MODE_FLAG_35,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_35
	},
	{
		CSTPORT_MODE_SETTING_36,
		CSTPORT_NOISEFILTER_SETTING_36,
		CSTPORT_SAFESTATE_SETTING_36,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_36,
		PORT_U2A_MODE_CFG_MODE_FLAG_36,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_36
	},
	{
		CSTPORT_MODE_SETTING_37,
		CSTPORT_NOISEFILTER_SETTING_37,
		CSTPORT_SAFESTATE_SETTING_37,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_37,
		PORT_U2A_MODE_CFG_MODE_FLAG_37,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_37
	},
	{
		CSTPORT_MODE_SETTING_38,
		CSTPORT_NOISEFILTER_SETTING_38,
		CSTPORT_SAFESTATE_SETTING_38,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_38,
		PORT_U2A_MODE_CFG_MODE_FLAG_38,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_38
	},
	{
		CSTPORT_MODE_SETTING_39,
		CSTPORT_NOISEFILTER_SETTING_39,
		CSTPORT_SAFESTATE_SETTING_39,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_39,
		PORT_U2A_MODE_CFG_MODE_FLAG_39,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_39
	},
	{
		CSTPORT_MODE_SETTING_40,
		CSTPORT_NOISEFILTER_SETTING_40,
		CSTPORT_SAFESTATE_SETTING_40,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_40,
		PORT_U2A_MODE_CFG_MODE_FLAG_40,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_40
	},
	{
		CSTPORT_MODE_SETTING_41,
		CSTPORT_NOISEFILTER_SETTING_41,
		CSTPORT_SAFESTATE_SETTING_41,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_41,
		PORT_U2A_MODE_CFG_MODE_FLAG_41,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_41
	},
	{
		CSTPORT_MODE_SETTING_42,
		CSTPORT_NOISEFILTER_SETTING_42,
		CSTPORT_SAFESTATE_SETTING_42,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_42,
		PORT_U2A_MODE_CFG_MODE_FLAG_42,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_42
	},
	{
		CSTPORT_MODE_SETTING_43,
		CSTPORT_NOISEFILTER_SETTING_43,
		CSTPORT_SAFESTATE_SETTING_43,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_43,
		PORT_U2A_MODE_CFG_MODE_FLAG_43,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_43
	},
	{
		CSTPORT_MODE_SETTING_44,
		CSTPORT_NOISEFILTER_SETTING_44,
		CSTPORT_SAFESTATE_SETTING_44,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_44,
		PORT_U2A_MODE_CFG_MODE_FLAG_44,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_44
	},
	{
		CSTPORT_MODE_SETTING_45,
		CSTPORT_NOISEFILTER_SETTING_45,
		CSTPORT_SAFESTATE_SETTING_45,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_45,
		PORT_U2A_MODE_CFG_MODE_FLAG_45,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_45
	},
	{
		CSTPORT_MODE_SETTING_46,
		CSTPORT_NOISEFILTER_SETTING_46,
		CSTPORT_SAFESTATE_SETTING_46,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_46,
		PORT_U2A_MODE_CFG_MODE_FLAG_46,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_46
	},
	{
		CSTPORT_MODE_SETTING_47,
		CSTPORT_NOISEFILTER_SETTING_47,
		CSTPORT_SAFESTATE_SETTING_47,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_47,
		PORT_U2A_MODE_CFG_MODE_FLAG_47,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_47
	},
	{
		CSTPORT_MODE_SETTING_48,
		CSTPORT_NOISEFILTER_SETTING_48,
		CSTPORT_SAFESTATE_SETTING_48,
		PORT_U2A_MODE_CFG_NOISE_FILTER_FLAG_48,
		PORT_U2A_MODE_CFG_MODE_FLAG_48,
		PORT_U2A_MODE_CFG_SAFE_STATE_FLAG_48
	}
};
#define PORT_STOP_SEC_CONST_UNSPECIFIED
#include "Port_MemMap.h"
#endif /* ( MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2A ) */

/*-- End Of File -------------------------------------------------------------------------------*/
