/**
 * @file
 ***********************************************************************************************
 * @brief File generated from @ref VMS resource configuration step.
 *        Key id table.
 *
 ***********************************************************************************************

 * @copyright                                 Copyright (c) ETAS GmbH 2023, all rights reserved.

 ***********************************************************************************************/

#ifndef ECY_HSM_CSAI_KEYID_H
#define ECY_HSM_CSAI_KEYID_H

/**
 * @addtogroup GROUP_CSAI_KEY_MANAGEMENT
 * @{
 */

/* *INDENT-OFF* */
#ifdef __cplusplus
    extern "C" {
#endif
/* *INDENT-ON* */


/* *** Type declarations **********************************************************************/

/* PRQA S 0779, 0789 ++ */ /* rule_5.2_0779_0789 */
/* PRQA S 0785 ++ */       /* rule_5.5_0785_backwards_compatibility */

/** Define Key IDs, these are an extension of those specified by SHE */
/*  SHE keys can be accessed by CSAI */
typedef enum ecy_hsm_Csai_KeyIdTag
{
    ecy_hsm_CSAI_KEYID_AES_KEY_start = 0x0U,
    ecy_hsm_CSAI_KEYID_AES_KEY_VOLATILE_BASIC_SHE_SECRET_KEY = 0x0U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_BASIC_SHE_MASTER_KEY = 0x1U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_BASIC_SHE_BOOT_KEY = 0x2U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_BASIC_SHE_MAC_KEY = 0x3U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_BASIC_SHE_DFLASH_KEY_BASE_0 = 0x4U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_BASIC_SHE_DFLASH_KEY_INST_1 = 0x5U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_BASIC_SHE_DFLASH_KEY_INST_2 = 0x6U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_BASIC_SHE_DFLASH_KEY_INST_3 = 0x7U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_BASIC_SHE_DFLASH_KEY_INST_4 = 0x8U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_BASIC_SHE_DFLASH_KEY_INST_5 = 0x9U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_BASIC_SHE_DFLASH_KEY_INST_6 = 0xAU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_BASIC_SHE_DFLASH_KEY_INST_7 = 0xBU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_BASIC_SHE_DFLASH_KEY_INST_8 = 0xCU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_BASIC_SHE_DFLASH_KEY_INST_9 = 0xDU,
    ecy_hsm_CSAI_KEYID_AES_KEY_VOLATILE_BASIC_SHE_RAM_KEY = 0xEU,
    ecy_hsm_CSAI_KEYID_AES_KEY_VOLATILE_BASIC_SHE_RESERVED_KEY = 0xFU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_EXT_SHE_DFLASH_KEY_BASE_0 = 0x10U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_EXT_SHE_DFLASH_KEY_INST_1 = 0x11U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_EXT_SHE_DFLASH_KEY_INST_2 = 0x12U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_EXT_SHE_DFLASH_KEY_INST_3 = 0x13U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_EXT_SHE_DFLASH_KEY_INST_4 = 0x14U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_EXT_SHE_DFLASH_KEY_INST_5 = 0x15U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_EXT_SHE_DFLASH_KEY_INST_6 = 0x16U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_EXT_SHE_DFLASH_KEY_INST_7 = 0x17U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_EXT_SHE_DFLASH_KEY_INST_8 = 0x18U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_EXT_SHE_DFLASH_KEY_INST_9 = 0x19U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_BASE_0 = 0x1AU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_1 = 0x1BU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_2 = 0x1CU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_3 = 0x1DU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_4 = 0x1EU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_5 = 0x1FU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_6 = 0x20U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_7 = 0x21U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_8 = 0x22U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_9 = 0x23U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_10 = 0x24U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_11 = 0x25U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_12 = 0x26U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_13 = 0x27U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_14 = 0x28U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_15 = 0x29U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_16 = 0x2AU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_17 = 0x2BU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_18 = 0x2CU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_19 = 0x2DU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_20 = 0x2EU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_21 = 0x2FU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_22 = 0x30U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_23 = 0x31U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_128_INST_24 = 0x32U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_BASE_0 = 0x33U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_1 = 0x34U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_2 = 0x35U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_3 = 0x36U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_4 = 0x37U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_5 = 0x38U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_6 = 0x39U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_7 = 0x3AU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_8 = 0x3BU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_9 = 0x3CU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_10 = 0x3DU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_11 = 0x3EU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_12 = 0x3FU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_13 = 0x40U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_14 = 0x41U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_15 = 0x42U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_16 = 0x43U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_17 = 0x44U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_18 = 0x45U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_19 = 0x46U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_20 = 0x47U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_21 = 0x48U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_22 = 0x49U,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_23 = 0x4AU,
    ecy_hsm_CSAI_KEYID_AES_KEY_DYNAMIC_CFG_AES_KEY_256_INST_24 = 0x4BU,
    ecy_hsm_CSAI_KEYID_AES_KEY_end,

    ecy_hsm_CSAI_KEYID_RSA_KEY_start = 0x100U,
    ecy_hsm_CSAI_KEYID_RSA_KEY_DYNAMIC_RSA_PUBLIC_KEY_3072_BASE_0 = 0x100U,
    ecy_hsm_CSAI_KEYID_RSA_KEY_DYNAMIC_RSA_PUBLIC_KEY_3072_INST_1 = 0x101U,
    ecy_hsm_CSAI_KEYID_RSA_KEY_DYNAMIC_RSA_PUBLIC_KEY_3072_INST_2 = 0x102U,
    ecy_hsm_CSAI_KEYID_RSA_KEY_end,

    ecy_hsm_CSAI_KEYID_ECC_KEY_start = 0x200U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_EDDSA_PUBLIC_KEY_256_BASE_0 = 0x200U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_EDDSA_PUBLIC_KEY_256_INST_1 = 0x201U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_EDDSA_PUBLIC_KEY_256_INST_2 = 0x202U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PUBLIC_KEY_384_BASE_0 = 0x203U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PUBLIC_KEY_384_INST_1 = 0x204U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PUBLIC_KEY_384_INST_2 = 0x205U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PUBLIC_KEY_384_INST_3 = 0x206U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PUBLIC_KEY_384_INST_4 = 0x207U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PUBLIC_KEY_384_INST_5 = 0x208U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PUBLIC_KEY_384_INST_6 = 0x209U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PUBLIC_KEY_384_INST_7 = 0x20AU,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_EDDSA_PRIVATE_KEY_256_BASE_0 = 0x20BU,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_EDDSA_PRIVATE_KEY_256_INST_1 = 0x20CU,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_EDDSA_PRIVATE_KEY_256_INST_2 = 0x20DU,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PRIVATE_KEY_384_BASE_0 = 0x20EU,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PRIVATE_KEY_384_INST_1 = 0x20FU,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PRIVATE_KEY_384_INST_2 = 0x210U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PRIVATE_KEY_384_INST_3 = 0x211U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PRIVATE_KEY_384_INST_4 = 0x212U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PRIVATE_KEY_384_INST_5 = 0x213U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PRIVATE_KEY_384_INST_6 = 0x214U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_PRIVATE_KEY_384_INST_7 = 0x215U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_EDDSA_KEY_PAIR_256_BASE_0 = 0x216U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_EDDSA_KEY_PAIR_256_INST_1 = 0x217U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_EDDSA_KEY_PAIR_256_INST_2 = 0x218U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_KEY_PAIR_384_BASE_0 = 0x219U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_KEY_PAIR_384_INST_1 = 0x21AU,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_KEY_PAIR_384_INST_2 = 0x21BU,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_KEY_PAIR_384_INST_3 = 0x21CU,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_KEY_PAIR_384_INST_4 = 0x21DU,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_KEY_PAIR_384_INST_5 = 0x21EU,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_KEY_PAIR_384_INST_6 = 0x21FU,
    ecy_hsm_CSAI_KEYID_ECC_KEY_DYNAMIC_ECDSA_KEY_PAIR_384_INST_7 = 0x220U,
    ecy_hsm_CSAI_KEYID_ECC_KEY_end,

    ecy_hsm_CSAI_KEYID_CERT_start = 0x300U,
    ecy_hsm_CSAI_KEYID_CERT_STATIC_CFG_CERT_X509_PFLASH = 0x300U,
    ecy_hsm_CSAI_KEYID_CERT_end,

    ecy_hsm_CSAI_KEYID_OID_start = 0x400U,
    ecy_hsm_CSAI_KEYID_OID_end,

    ecy_hsm_CSAI_KEYID_SECRET_DATA_start = 0x500U,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_MONOTONIC_0_BASE_0 = 0x500U,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_MONOTONIC_0_INST_1 = 0x501U,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_MONOTONIC_0_INST_2 = 0x502U,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_MONOTONIC_0_INST_3 = 0x503U,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_SMALL_0_BASE_0 = 0x504U,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_SMALL_0_INST_1 = 0x505U,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_SMALL_0_INST_2 = 0x506U,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_SMALL_0_INST_3 = 0x507U,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_SMALL_0_INST_4 = 0x508U,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_SMALL_0_INST_5 = 0x509U,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_SMALL_0_INST_6 = 0x50AU,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_SMALL_0_INST_7 = 0x50BU,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_LARGE_0_BASE_0 = 0x50CU,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_LARGE_0_INST_1 = 0x50DU,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_LARGE_0_INST_2 = 0x50EU,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_DYNAMIC_CFG_SECRET_DATA_LARGE_0_INST_3 = 0x50FU,
    ecy_hsm_CSAI_KEYID_SECRET_DATA_end,

    ecy_hsm_CSAI_KEYID_INT_DATA_start = 0x600U,
    ecy_hsm_CSAI_KEYID_INT_DATA_DYNAMIC_CFG_SERIALNUMBER = 0x600U,
    ecy_hsm_CSAI_KEYID_INT_DATA_DYNAMIC_CFG_PASSWORDS = 0x601U,
    ecy_hsm_CSAI_KEYID_INT_DATA_DYNAMIC_CFG_HSM_UPDATE_PASSWORD = 0x602U,
    ecy_hsm_CSAI_KEYID_INT_DATA_STATIC_CFG_INT_DATA_0 = 0x603U,
    ecy_hsm_CSAI_KEYID_INT_DATA_DYNAMIC_CFG_INT_DATA_TRUSTED_BOOT_REF = 0x604U,
    ecy_hsm_CSAI_KEYID_INT_DATA_STATIC_CFG_HSM_SUSPEND_TIME = 0x605U,
    ecy_hsm_CSAI_KEYID_INT_DATA_DYNAMIC_CFG_LIFE_CYCLE_STATE = 0x606U,
    ecy_hsm_CSAI_KEYID_INT_DATA_end,

    ecy_hsm_CSAI_KEYID_SECLOG_DATA_start = 0x700U,
    ecy_hsm_CSAI_KEYID_SECLOG_DATA_end,

    ecy_hsm_CSAI_KEYID_DOWNGRADE_PROTECTION_DATA_start = 0x800U,
    ecy_hsm_CSAI_KEYID_DOWNGRADE_PROTECTION_DATA_end,

    ecy_hsm_CSAI_KEYID_CUSTOMCODE_start = 0x900U,
    ecy_hsm_CSAI_KEYID_CUSTOMCODE_end,

    ecy_hsm_CSAI_KEYID_OTP_CERT_start = 0xA00U,
    ecy_hsm_CSAI_KEYID_OTP_CERT_end,

    ecy_hsm_CSAI_KEYID_OTP_OID_start = 0xB00U,
    ecy_hsm_CSAI_KEYID_OTP_OID_end,

    ecy_hsm_CSAI_KEYID_OTP_UPDATE_KEY_start = 0xC00U,
    ecy_hsm_CSAI_KEYID_OTP_UPDATE_KEY_end,

    ecy_hsm_CSAI_KEYID_SMART_TB_DATA_start = 0xD00U,
    ecy_hsm_CSAI_KEYID_SMART_TB_DATA_end,

    ecy_hsm_CSAI_SHE_KEYID_RESERVED = 0x7FFFFFFFU           /**< Ensure full 32 bits are used for the enum         */

} ecy_hsm_Csai_KeyIdT;

/* PRQA S 0785 -- */
/* PRQA S 0779, 0789 -- */

/* *INDENT-OFF* */
#ifdef __cplusplus
    } /* extern "C" */
#endif
/* *INDENT-ON* */

/**
* @}
*/

#endif /* Multiple inclusion lock  */
