/* 2.0.0 */
/*===================================================================================================================================*/
/*  Copyright DENSO Corporation                                                                                                      */
/*===================================================================================================================================*/
/*  OEM eXtention of CAN : Rx Detection                                                                                              */
/*                                                                                                                                   */
/*  WARNING :                                                                                                                        */
/*  oxcan_rxd_def.h is included in oxcan_lib.h and oxcan.h                                                                           */
/*  DO NOT include this file in any file even though this configuration header is public.                                            */
/*                                                                                                                                   */
/*===================================================================================================================================*/

#ifndef OXCAN_RXD_DEF_H
#define OXCAN_RXD_DEF_H

/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Version                                                                                                                          */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define OXCAN_RXD_DEF_H_MAJOR                    (2U)
#define OXCAN_RXD_DEF_H_MINOR                    (0U)
#define OXCAN_RXD_DEF_H_PATCH                    (0U)

/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Literal Definitions                                                                                                              */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define OXCAN_RXD_NUM_GR                         (1U)
#define OXCAN_RXD_GR_CAN                         (0U)

/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define OXCAN_RXD_NUM_PDU                        (320U)

#define OXCAN_RXD_PDU_CAN_ABG1D50_CH0            (0U)
#define OXCAN_RXD_PDU_CAN_ABG1D51_CH0            (1U)
#define OXCAN_RXD_PDU_CAN_ABG1S01_CH0            (2U)
#define OXCAN_RXD_PDU_CAN_ABG1S04_CH0            (3U)
#define OXCAN_RXD_PDU_CAN_ABG1S09_CH0            (4U)
#define OXCAN_RXD_PDU_CAN_ACN1D50_CH0            (5U)
#define OXCAN_RXD_PDU_CAN_ACN1S03_CH0            (6U)
#define OXCAN_RXD_PDU_CAN_ACN1S04_CH0            (7U)
#define OXCAN_RXD_PDU_CAN_ACN1S05_CH0            (8U)
#define OXCAN_RXD_PDU_CAN_ACN1S07_CH0            (9U)
#define OXCAN_RXD_PDU_CAN_ACN1S15_CH0            (10U)
#define OXCAN_RXD_PDU_CAN_ACN1S16_CH0            (11U)
#define OXCAN_RXD_PDU_CAN_ACN1S22_CH0            (12U)
#define OXCAN_RXD_PDU_CAN_ACN1S25_CH0            (13U)
#define OXCAN_RXD_PDU_CAN_ACN1S29_CH0            (14U)
#define OXCAN_RXD_PDU_CAN_ADC1S06_CH0            (15U)
#define OXCAN_RXD_PDU_CAN_ADC1S13_CH0            (16U)
#define OXCAN_RXD_PDU_CAN_ADC1S14_CH0            (17U)
#define OXCAN_RXD_PDU_CAN_ADC1S15_CH0            (18U)
#define OXCAN_RXD_PDU_CAN_ADC1S17_CH0            (19U)
#define OXCAN_RXD_PDU_CAN_ADC1S19_CH0            (20U)
#define OXCAN_RXD_PDU_CAN_ADC1S23_CH0            (21U)
#define OXCAN_RXD_PDU_CAN_ADC1S30_CH0            (22U)
#define OXCAN_RXD_PDU_CAN_ADC1S33_CH0            (23U)
#define OXCAN_RXD_PDU_CAN_ADU1S02_CH0            (24U)
#define OXCAN_RXD_PDU_CAN_ADU1S03_CH0            (25U)
#define OXCAN_RXD_PDU_CAN_ADU1S05_CH0            (26U)
#define OXCAN_RXD_PDU_CAN_ADU1S06_CH0            (27U)
#define OXCAN_RXD_PDU_CAN_ADU1S07_CH0            (28U)
#define OXCAN_RXD_PDU_CAN_ARS1S01_CH0            (29U)
#define OXCAN_RXD_PDU_CAN_BAT1E41_CH0            (30U)
#define OXCAN_RXD_PDU_CAN_BAT1E45_CH0            (31U)
#define OXCAN_RXD_PDU_CAN_BAT1S01_CH0            (32U)
#define OXCAN_RXD_PDU_CAN_BAT1S08_CH0            (33U)
#define OXCAN_RXD_PDU_CAN_BAT1S12_CH0            (34U)
#define OXCAN_RXD_PDU_CAN_BAT2ED2_CH0            (35U)
#define OXCAN_RXD_PDU_CAN_BCC1S05_CH0            (36U)
#define OXCAN_RXD_PDU_CAN_BCC1S06_CH0            (37U)
#define OXCAN_RXD_PDU_CAN_BDB1D50_CH0            (38U)
#define OXCAN_RXD_PDU_CAN_BDB1F01_CH0            (39U)
#define OXCAN_RXD_PDU_CAN_BDB1F03_CH0            (40U)
#define OXCAN_RXD_PDU_CAN_BDB1S01_CH0            (41U)
#define OXCAN_RXD_PDU_CAN_BDB1S03_CH0            (42U)
#define OXCAN_RXD_PDU_CAN_BDB1S04_CH0            (43U)
#define OXCAN_RXD_PDU_CAN_BDB1S05_CH0            (44U)
#define OXCAN_RXD_PDU_CAN_BDB1S08_CH0            (45U)
#define OXCAN_RXD_PDU_CAN_BDB1S19_CH0            (46U)
#define OXCAN_RXD_PDU_CAN_BDB1S25_CH0            (47U)
#define OXCAN_RXD_PDU_CAN_BDB1S26_CH0            (48U)
#define OXCAN_RXD_PDU_CAN_BDB1S27_CH0            (49U)
#define OXCAN_RXD_PDU_CAN_BDB1S28_CH0            (50U)
#define OXCAN_RXD_PDU_CAN_BDB1S29_CH0            (51U)
#define OXCAN_RXD_PDU_CAN_BDB1S35_CH0            (52U)
#define OXCAN_RXD_PDU_CAN_BDB1S36_CH0            (53U)
#define OXCAN_RXD_PDU_CAN_BDC1D00_CH0            (54U)
#define OXCAN_RXD_PDU_CAN_BDC1D01_CH0            (55U)
#define OXCAN_RXD_PDU_CAN_BDC1S13_CH0            (56U)
#define OXCAN_RXD_PDU_CAN_BDC1S14_CH0            (57U)
#define OXCAN_RXD_PDU_CAN_BDC1S16_CH0            (58U)
#define OXCAN_RXD_PDU_CAN_BDC1S20_CH0            (59U)
#define OXCAN_RXD_PDU_CAN_BDC1S30_CH0            (60U)
#define OXCAN_RXD_PDU_CAN_BDC1S33_CH0            (61U)
#define OXCAN_RXD_PDU_CAN_BDC1S40_CH0            (62U)
#define OXCAN_RXD_PDU_CAN_BDC1S41_CH0            (63U)
#define OXCAN_RXD_PDU_CAN_BDC1S45_CH0            (64U)
#define OXCAN_RXD_PDU_CAN_BDC1S46_CH0            (65U)
#define OXCAN_RXD_PDU_CAN_BDC1S48_CH0            (66U)
#define OXCAN_RXD_PDU_CAN_BDC1S60_CH0            (67U)
#define OXCAN_RXD_PDU_CAN_BDC1S74_CH0            (68U)
#define OXCAN_RXD_PDU_CAN_BDC1S81_CH0            (69U)
#define OXCAN_RXD_PDU_CAN_BDC1S82_CH0            (70U)
#define OXCAN_RXD_PDU_CAN_BDC1S83_CH0            (71U)
#define OXCAN_RXD_PDU_CAN_BDC1S91_CH0            (72U)
#define OXCAN_RXD_PDU_CAN_BDC1S97_CH0            (73U)
#define OXCAN_RXD_PDU_CAN_BDC1S98_CH0            (74U)
#define OXCAN_RXD_PDU_CAN_BDC1S99_CH0            (75U)
#define OXCAN_RXD_PDU_CAN_BDC1SA0_CH0            (76U)
#define OXCAN_RXD_PDU_CAN_BDC1SA1_CH0            (77U)
#define OXCAN_RXD_PDU_CAN_BDC1SC1_CH0            (78U)
#define OXCAN_RXD_PDU_CAN_BDC1SC2_CH0            (79U)
#define OXCAN_RXD_PDU_CAN_BDC1SC3_CH0            (80U)
#define OXCAN_RXD_PDU_CAN_BDC1SC4_CH0            (81U)
#define OXCAN_RXD_PDU_CAN_BDC1SC5_CH0            (82U)
#define OXCAN_RXD_PDU_CAN_BDC1SC6_CH0            (83U)
#define OXCAN_RXD_PDU_CAN_BDC1SC7_CH0            (84U)
#define OXCAN_RXD_PDU_CAN_BDC1SC8_CH0            (85U)
#define OXCAN_RXD_PDU_CAN_BDC1SC9_CH0            (86U)
#define OXCAN_RXD_PDU_CAN_BDC1SD1_CH0            (87U)
#define OXCAN_RXD_PDU_CAN_BDC1SD2_CH0            (88U)
#define OXCAN_RXD_PDU_CAN_BDC1SD3_CH0            (89U)
#define OXCAN_RXD_PDU_CAN_BDC1SD4_CH0            (90U)
#define OXCAN_RXD_PDU_CAN_BDC1SD5_CH0            (91U)
#define OXCAN_RXD_PDU_CAN_BDC1SD6_CH0            (92U)
#define OXCAN_RXD_PDU_CAN_BDC1SD7_CH0            (93U)
#define OXCAN_RXD_PDU_CAN_BDC1SD8_CH0            (94U)
#define OXCAN_RXD_PDU_CAN_BDC1SD9_CH0            (95U)
#define OXCAN_RXD_PDU_CAN_BDC1SE1_CH0            (96U)
#define OXCAN_RXD_PDU_CAN_BDC1SE2_CH0            (97U)
#define OXCAN_RXD_PDU_CAN_BDC1SE3_CH0            (98U)
#define OXCAN_RXD_PDU_CAN_BDC1SE4_CH0            (99U)
#define OXCAN_RXD_PDU_CAN_BDC1SE5_CH0            (100U)
#define OXCAN_RXD_PDU_CAN_BDC1SE6_CH0            (101U)
#define OXCAN_RXD_PDU_CAN_BDC1SE7_CH0            (102U)
#define OXCAN_RXD_PDU_CAN_BDC1SE8_CH0            (103U)
#define OXCAN_RXD_PDU_CAN_BDC1SE9_CH0            (104U)
#define OXCAN_RXD_PDU_CAN_BDC1SF1_CH0            (105U)
#define OXCAN_RXD_PDU_CAN_BDC1SF2_CH0            (106U)
#define OXCAN_RXD_PDU_CAN_BDC1SF3_CH0            (107U)
#define OXCAN_RXD_PDU_CAN_BDC1SF4_CH0            (108U)
#define OXCAN_RXD_PDU_CAN_BDC1SF5_CH0            (109U)
#define OXCAN_RXD_PDU_CAN_BDC1SF6_CH0            (110U)
#define OXCAN_RXD_PDU_CAN_BDC1SG4_CH0            (111U)
#define OXCAN_RXD_PDU_CAN_BDC1SG6_CH0            (112U)
#define OXCAN_RXD_PDU_CAN_BDC1SG7_CH0            (113U)
#define OXCAN_RXD_PDU_CAN_BDC1SG8_CH0            (114U)
#define OXCAN_RXD_PDU_CAN_BDC1SG9_CH0            (115U)
#define OXCAN_RXD_PDU_CAN_BDC1SH3_CH0            (116U)
#define OXCAN_RXD_PDU_CAN_BDC1SH4_CH0            (117U)
#define OXCAN_RXD_PDU_CAN_BDC1SH5_CH0            (118U)
#define OXCAN_RXD_PDU_CAN_BDC1SH6_CH0            (119U)
#define OXCAN_RXD_PDU_CAN_BDC1SH8_CH0            (120U)
#define OXCAN_RXD_PDU_CAN_BDC1SI0_CH0            (121U)
#define OXCAN_RXD_PDU_CAN_BDC1SI1_CH0            (122U)
#define OXCAN_RXD_PDU_CAN_BDC1SI2_CH0            (123U)
#define OXCAN_RXD_PDU_CAN_BDC1SI3_CH0            (124U)
#define OXCAN_RXD_PDU_CAN_BDC1SI4_CH0            (125U)
#define OXCAN_RXD_PDU_CAN_BDC1SI5_CH0            (126U)
#define OXCAN_RXD_PDU_CAN_BDC1SI6_CH0            (127U)
#define OXCAN_RXD_PDU_CAN_BDC1SI7_CH0            (128U)
#define OXCAN_RXD_PDU_CAN_BDC1SI8_CH0            (129U)
#define OXCAN_RXD_PDU_CAN_BDC1SI9_CH0            (130U)
#define OXCAN_RXD_PDU_CAN_BDC1SJ0_CH0            (131U)
#define OXCAN_RXD_PDU_CAN_BDC1SJ1_CH0            (132U)
#define OXCAN_RXD_PDU_CAN_BDC1SJ2_CH0            (133U)
#define OXCAN_RXD_PDU_CAN_BDC1SJ3_CH0            (134U)
#define OXCAN_RXD_PDU_CAN_BDC1SJ4_CH0            (135U)
#define OXCAN_RXD_PDU_CAN_BDC1SJ5_CH0            (136U)
#define OXCAN_RXD_PDU_CAN_BDC1SJ6_CH0            (137U)
#define OXCAN_RXD_PDU_CAN_BDC1SJ7_CH0            (138U)
#define OXCAN_RXD_PDU_CAN_BDC1SJ8_CH0            (139U)
#define OXCAN_RXD_PDU_CAN_BDC1SV1_CH0            (140U)
#define OXCAN_RXD_PDU_CAN_BDC1SV2_CH0            (141U)
#define OXCAN_RXD_PDU_CAN_BDF3S01_CH0            (142U)
#define OXCAN_RXD_PDU_CAN_BDF3S02_CH0            (143U)
#define OXCAN_RXD_PDU_CAN_BDR3S02_CH0            (144U)
#define OXCAN_RXD_PDU_CAN_BSR1S01_CH0            (145U)
#define OXCAN_RXD_PDU_CAN_BSR1S02_CH0            (146U)
#define OXCAN_RXD_PDU_CAN_BSR1S03_CH0            (147U)
#define OXCAN_RXD_PDU_CAN_CDC1S01_CH0            (148U)
#define OXCAN_RXD_PDU_CAN_CMB1S03_CH0            (149U)
#define OXCAN_RXD_PDU_CAN_CMB1S04_CH0            (150U)
#define OXCAN_RXD_PDU_CAN_CSR1G10_CH0            (151U)
#define OXCAN_RXD_PDU_CAN_CSR1S04_CH0            (152U)
#define OXCAN_RXD_PDU_CAN_CSR1S07_CH0            (153U)
#define OXCAN_RXD_PDU_CAN_DCM1S01_CH0            (154U)
#define OXCAN_RXD_PDU_CAN_DCM1S03_CH0            (155U)
#define OXCAN_RXD_PDU_CAN_DCM1S04_CH0            (156U)
#define OXCAN_RXD_PDU_CAN_DCM1S08_CH0            (157U)
#define OXCAN_RXD_PDU_CAN_DDM1S00_CH0            (158U)
#define OXCAN_RXD_PDU_CAN_DDM1S09_CH0            (159U)
#define OXCAN_RXD_PDU_CAN_DDM1S12_CH0            (160U)
#define OXCAN_RXD_PDU_CAN_DDM1S16_CH0            (161U)
#define OXCAN_RXD_PDU_CAN_DDM1S17_CH0            (162U)
#define OXCAN_RXD_PDU_CAN_DDM1S20_CH0            (163U)
#define OXCAN_RXD_PDU_CAN_DDM1S32_CH0            (164U)
#define OXCAN_RXD_PDU_CAN_DDM1S35_CH0            (165U)
#define OXCAN_RXD_PDU_CAN_DDM1SFH_CH0            (166U)
#define OXCAN_RXD_PDU_CAN_DKY1S26_CH0            (167U)
#define OXCAN_RXD_PDU_CAN_DS11S27_CH0            (168U)
#define OXCAN_RXD_PDU_CAN_DS11S37_CH0            (169U)
#define OXCAN_RXD_PDU_CAN_DS11S40_CH0            (170U)
#define OXCAN_RXD_PDU_CAN_DS12F02_CH0            (171U)
#define OXCAN_RXD_PDU_CAN_DS12F03_CH0            (172U)
#define OXCAN_RXD_PDU_CAN_DST1S02_CH0            (173U)
#define OXCAN_RXD_PDU_CAN_EBU1D01_CH0            (174U)
#define OXCAN_RXD_PDU_CAN_ECT1G01_CH0            (175U)
#define OXCAN_RXD_PDU_CAN_ECT1G92_CH0            (176U)
#define OXCAN_RXD_PDU_CAN_ECT1S93_CH0            (177U)
#define OXCAN_RXD_PDU_CAN_EHV1E96_CH0            (178U)
#define OXCAN_RXD_PDU_CAN_EHV1F02_CH0            (179U)
#define OXCAN_RXD_PDU_CAN_EHV1F04_CH0            (180U)
#define OXCAN_RXD_PDU_CAN_EHV1G70_CH0            (181U)
#define OXCAN_RXD_PDU_CAN_EHV1G71_CH0            (182U)
#define OXCAN_RXD_PDU_CAN_EHV1S23_CH0            (183U)
#define OXCAN_RXD_PDU_CAN_EHV1S31_CH0            (184U)
#define OXCAN_RXD_PDU_CAN_EHV1S95_CH0            (185U)
#define OXCAN_RXD_PDU_CAN_EHV1S96_CH0            (186U)
#define OXCAN_RXD_PDU_CAN_EHV1S97_CH0            (187U)
#define OXCAN_RXD_PDU_CAN_EHV1S99_CH0            (188U)
#define OXCAN_RXD_PDU_CAN_EHV1SL2_CH0            (189U)
#define OXCAN_RXD_PDU_CAN_EHV2G02_CH0            (190U)
#define OXCAN_RXD_PDU_CAN_EHV2G20_CH0            (191U)
#define OXCAN_RXD_PDU_CAN_EHV2G70_CH0            (192U)
#define OXCAN_RXD_PDU_CAN_ENG1C01_CH0            (193U)
#define OXCAN_RXD_PDU_CAN_ENG1C02_CH0            (194U)
#define OXCAN_RXD_PDU_CAN_ENG1D51_CH0            (195U)
#define OXCAN_RXD_PDU_CAN_ENG1D52_CH0            (196U)
#define OXCAN_RXD_PDU_CAN_ENG1D53_CH0            (197U)
#define OXCAN_RXD_PDU_CAN_ENG1D55_CH0            (198U)
#define OXCAN_RXD_PDU_CAN_ENG1D56_CH0            (199U)
#define OXCAN_RXD_PDU_CAN_ENG1D59_CH0            (200U)
#define OXCAN_RXD_PDU_CAN_ENG1D60_CH0            (201U)
#define OXCAN_RXD_PDU_CAN_ENG1G03_CH0            (202U)
#define OXCAN_RXD_PDU_CAN_ENG1G90_CH0            (203U)
#define OXCAN_RXD_PDU_CAN_ENG1G92_CH0            (204U)
#define OXCAN_RXD_PDU_CAN_ENG1S51_CH0            (205U)
#define OXCAN_RXD_PDU_CAN_ENG1S60_CH0            (206U)
#define OXCAN_RXD_PDU_CAN_EPS1D50_CH0            (207U)
#define OXCAN_RXD_PDU_CAN_EPS1S11_CH0            (208U)
#define OXCAN_RXD_PDU_CAN_FCM1C01_CH0            (209U)
#define OXCAN_RXD_PDU_CAN_FCM1C03_CH0            (210U)
#define OXCAN_RXD_PDU_CAN_FCM1S10_CH0            (211U)
#define OXCAN_RXD_PDU_CAN_FCM1S12_CH0            (212U)
#define OXCAN_RXD_PDU_CAN_FCM1S39_CH0            (213U)
#define OXCAN_RXD_PDU_CAN_FCM1S41_CH0            (214U)
#define OXCAN_RXD_PDU_CAN_FCM1S49_CH0            (215U)
#define OXCAN_RXD_PDU_CAN_FCM1S51_CH0            (216U)
#define OXCAN_RXD_PDU_CAN_FCM1S52_CH0            (217U)
#define OXCAN_RXD_PDU_CAN_FCM1S66_CH0            (218U)
#define OXCAN_RXD_PDU_CAN_FCM1S70_CH0            (219U)
#define OXCAN_RXD_PDU_CAN_FCM1S79_CH0            (220U)
#define OXCAN_RXD_PDU_CAN_FCM1S88_CH0            (221U)
#define OXCAN_RXD_PDU_CAN_FCM1S90_CH0            (222U)
#define OXCAN_RXD_PDU_CAN_FCM1S95_CH0            (223U)
#define OXCAN_RXD_PDU_CAN_IDT1S07_CH0            (224U)
#define OXCAN_RXD_PDU_CAN_IDT1S08_CH0            (225U)
#define OXCAN_RXD_PDU_CAN_IDT1S15_CH0            (226U)
#define OXCAN_RXD_PDU_CAN_IPA1S05_CH0            (227U)
#define OXCAN_RXD_PDU_CAN_ITS1S01_CH0            (228U)
#define OXCAN_RXD_PDU_CAN_ITS1S04_CH0            (229U)
#define OXCAN_RXD_PDU_CAN_ITS1S08_CH0            (230U)
#define OXCAN_RXD_PDU_CAN_LVN1S01_CH0            (231U)
#define OXCAN_RXD_PDU_CAN_MET1S02_CH0            (232U)
#define OXCAN_RXD_PDU_CAN_MET1S11_CH0            (233U)
#define OXCAN_RXD_PDU_CAN_MET1S38_CH0            (234U)
#define OXCAN_RXD_PDU_CAN_MET1S47_CH0            (235U)
#define OXCAN_RXD_PDU_CAN_MET1S55_CH0            (236U)
#define OXCAN_RXD_PDU_CAN_MGC1F13_CH0            (237U)
#define OXCAN_RXD_PDU_CAN_PCN1S01_CH0            (238U)
#define OXCAN_RXD_PDU_CAN_PDC1G01_CH0            (239U)
#define OXCAN_RXD_PDU_CAN_PDC1G02_CH0            (240U)
#define OXCAN_RXD_PDU_CAN_PLG1G15_CH0            (241U)
#define OXCAN_RXD_PDU_CAN_PLG1G16_CH0            (242U)
#define OXCAN_RXD_PDU_CAN_PLG1S01_CH0            (243U)
#define OXCAN_RXD_PDU_CAN_PLG1S06_CH0            (244U)
#define OXCAN_RXD_PDU_CAN_PLG1S20_CH0            (245U)
#define OXCAN_RXD_PDU_CAN_PLG1S21_CH0            (246U)
#define OXCAN_RXD_PDU_CAN_PMN1G03_CH0            (247U)
#define OXCAN_RXD_PDU_CAN_PST1S01_CH0            (248U)
#define OXCAN_RXD_PDU_CAN_PST1S02_CH0            (249U)
#define OXCAN_RXD_PDU_CAN_RCP1S01_CH0            (250U)
#define OXCAN_RXD_PDU_CAN_RCP1S02_CH0            (251U)
#define OXCAN_RXD_PDU_CAN_RCP1S03_CH0            (252U)
#define OXCAN_RXD_PDU_CAN_RCP1S04_CH0            (253U)
#define OXCAN_RXD_PDU_CAN_RCP1S05_CH0            (254U)
#define OXCAN_RXD_PDU_CAN_RCP1S06_CH0            (255U)
#define OXCAN_RXD_PDU_CAN_RSE1G20_CH0            (256U)
#define OXCAN_RXD_PDU_CAN_RSE1G24_CH0            (257U)
#define OXCAN_RXD_PDU_CAN_RSE1G25_CH0            (258U)
#define OXCAN_RXD_PDU_CAN_RSE1G26_CH0            (259U)
#define OXCAN_RXD_PDU_CAN_RST1S03_CH0            (260U)
#define OXCAN_RXD_PDU_CAN_SCN1S01_CH0            (261U)
#define OXCAN_RXD_PDU_CAN_SCN1S02_CH0            (262U)
#define OXCAN_RXD_PDU_CAN_SCS1D50_CH0            (263U)
#define OXCAN_RXD_PDU_CAN_SCS1S10_CH0            (264U)
#define OXCAN_RXD_PDU_CAN_SCS1S11_CH0            (265U)
#define OXCAN_RXD_PDU_CAN_SCS1S14_CH0            (266U)
#define OXCAN_RXD_PDU_CAN_SOL1S02_CH0            (267U)
#define OXCAN_RXD_PDU_CAN_SOL1S03_CH0            (268U)
#define OXCAN_RXD_PDU_CAN_SOL1S04_CH0            (269U)
#define OXCAN_RXD_PDU_CAN_SOL1S05_CH0            (270U)
#define OXCAN_RXD_PDU_CAN_SOL1S06_CH0            (271U)
#define OXCAN_RXD_PDU_CAN_TPM1S02_CH0            (272U)
#define OXCAN_RXD_PDU_CAN_TPM1S03_CH0            (273U)
#define OXCAN_RXD_PDU_CAN_TPM1S04_CH0            (274U)
#define OXCAN_RXD_PDU_CAN_TPM1S05_CH0            (275U)
#define OXCAN_RXD_PDU_CAN_TPM1S06_CH0            (276U)
#define OXCAN_RXD_PDU_CAN_TPM1S07_CH0            (277U)
#define OXCAN_RXD_PDU_CAN_TPM1S08_CH0            (278U)
#define OXCAN_RXD_PDU_CAN_TPM1S09_CH0            (279U)
#define OXCAN_RXD_PDU_CAN_TPM1S10_CH0            (280U)
#define OXCAN_RXD_PDU_CAN_TPM1S11_CH0            (281U)
#define OXCAN_RXD_PDU_CAN_TPM1S12_CH0            (282U)
#define OXCAN_RXD_PDU_CAN_TRA1S01_CH0            (283U)
#define OXCAN_RXD_PDU_CAN_TRA1S02_CH0            (284U)
#define OXCAN_RXD_PDU_CAN_UCB1S01_CH0            (285U)
#define OXCAN_RXD_PDU_CAN_VGR1D50_CH0            (286U)
#define OXCAN_RXD_PDU_CAN_VSC1D51_CH0            (287U)
#define OXCAN_RXD_PDU_CAN_VSC1F01_CH0            (288U)
#define OXCAN_RXD_PDU_CAN_VSC1G12_CH0            (289U)
#define OXCAN_RXD_PDU_CAN_VSC1G13_CH0            (290U)
#define OXCAN_RXD_PDU_CAN_VSC1G14_CH0            (291U)
#define OXCAN_RXD_PDU_CAN_VSC1G96_CH0            (292U)
#define OXCAN_RXD_PDU_CAN_VUM1S01_CH0            (293U)
#define OXCAN_RXD_PDU_CAN_WIP1S01_CH0            (294U)
#define OXCAN_RXD_PDU_CAN_ZN11S02_CH0            (295U)
#define OXCAN_RXD_PDU_CAN_ZN11S03_CH0            (296U)
#define OXCAN_RXD_PDU_CAN_ZN11S08_CH0            (297U)
#define OXCAN_RXD_PDU_CAN_ZN11S14_CH0            (298U)
#define OXCAN_RXD_PDU_CAN_ZN11S17_CH0            (299U)
#define OXCAN_RXD_PDU_CAN_ZN11S19_CH0            (300U)
#define OXCAN_RXD_PDU_CAN_ZN11S25_CH0            (301U)
#define OXCAN_RXD_PDU_CAN_ZN11S26_CH0            (302U)
#define OXCAN_RXD_PDU_CAN_ZN11S38_CH0            (303U)
#define OXCAN_RXD_PDU_CAN_ZN11S60_CH0            (304U)
#define OXCAN_RXD_PDU_CAN_ZN11S63_CH0            (305U)
#define OXCAN_RXD_PDU_CAN_ZN11S64_CH0            (306U)
#define OXCAN_RXD_PDU_CAN_ZN11S65_CH0            (307U)
#define OXCAN_RXD_PDU_CAN_ZN11S66_CH0            (308U)
#define OXCAN_RXD_PDU_CAN_ZN11S67_CH0            (309U)
#define OXCAN_RXD_PDU_CAN_ZN11SF8_CH0            (310U)
#define OXCAN_RXD_PDU_CAN_ZN11SF9_CH0            (311U)
#define OXCAN_RXD_PDU_CAN_ZN21S05_CH0            (312U)
#define OXCAN_RXD_PDU_CAN_ZN21S13_CH0            (313U)
#define OXCAN_RXD_PDU_CAN_ZN21S28_CH0            (314U)
#define OXCAN_RXD_PDU_CAN_ZN21S52_CH0            (315U)
#define OXCAN_RXD_PDU_CAN_ZN21S72_CH0            (316U)

#define OXCAN_RXD_PDU_CAN_MCDMS01_CH0            (317U)
#define OXCAN_RXD_PDU_CAN_MCDMS02_CH0            (318U)
#define OXCAN_RXD_PDU_CAN_MCDMN01_CH0            (319U)
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Macro Definitions                                                                                                                */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Type Definitions                                                                                                                 */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Variable Externs                                                                                                                 */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Function Prototypes                                                                                                              */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Constant Externs                                                                                                                 */
/*-----------------------------------------------------------------------------------------------------------------------------------*/

#endif      /* OXCAN_RXD_DEF_H */

/*===================================================================================================================================*/
/*                                                                                                                                   */
/*  Change History  :  see and oxcan_rxd_cfg.c                                                                                       */
/*                                                                                                                                   */
/*===================================================================================================================================*/
