#if defined MCALCOMMON_START_SEC_VAR_NO_INIT_GLOBAL_UNSPECIFIED
#pragma ghs section bss=".MCALCOMMON_BSS_VAR_NO_INIT"
#undef MCALCOMMON_START_SEC_VAR_NO_INIT_GLOBAL_UNSPECIFIED
#undef MEMMAP_ERROR
#elif defined MCALCOMMON_STOP_SEC_VAR_NO_INIT_GLOBAL_UNSPECIFIED
#pragma ghs section
#undef MCALCOMMON_STOP_SEC_VAR_NO_INIT_GLOBAL_UNSPECIFIED
#undef MEMMAP_ERROR

#elif defined MCALCOMMON_START_SEC_CODE_GLOBAL
#pragma ghs section text=".MCALCOMMON_TEXT_CODE"
#undef MCALCOMMON_START_SEC_CODE_GLOBAL
#undef MEMMAP_ERROR
#elif defined MCALCOMMON_STOP_SEC_CODE_GLOBAL
#pragma ghs section
#undef MCALCOMMON_STOP_SEC_CODE_GLOBAL
#undef MEMMAP_ERROR

#endif
