/* bsw_com_config_h_v3-0-0                                                  */
/****************************************************************************/
/* Protected                                                                */
/* Copyright DENSO CORPORATION                                              */
/****************************************************************************/

/****************************************************************************/
/* Object Name  | BSW/COM/CONFIG/HEADER                                     */
/*--------------------------------------------------------------------------*/
/* Notes        |                                                           */
/****************************************************************************/

#ifndef     BSW_COM_CONFIG_H
#define     BSW_COM_CONFIG_H

#include <bswm_cs/bsw_bswm_cs.h>
#include "../cfg/Com_Cfg.h"
#include "../../BswM_CS/inc/bsw_bswm_cs_config.h"

/*--------------------------------------------------------------------------*/
/* Macros                                                                   */
/*--------------------------------------------------------------------------*/
#define BSW_COM_HANDLE_NUM               BSW_COM_CFG_HANDLE_NUM
#define BSW_COM_MSGBUF_SIZE              BSW_COM_CFG_MSGBUF_SIZE
#define BSW_COM_TX_MSGBUF_SIZE           BSW_COM_CFG_TX_MSGBUF_SIZE
#define BSW_COM_FAILSAFE_SIZE            BSW_COM_CFG_FAILSAFE_SIZE

#define BSW_COM_RX_MSG_NUM               (BSW_COM_RX_MSG_NUM31)
#define BSW_COM_RX_MSG_NUM31             (BSW_COM_CFG_CH31_RX_NUM + BSW_COM_RX_MSG_NUM30)
#define BSW_COM_RX_MSG_NUM30             (BSW_COM_CFG_CH30_RX_NUM + BSW_COM_RX_MSG_NUM29)
#define BSW_COM_RX_MSG_NUM29             (BSW_COM_CFG_CH29_RX_NUM + BSW_COM_RX_MSG_NUM28)
#define BSW_COM_RX_MSG_NUM28             (BSW_COM_CFG_CH28_RX_NUM + BSW_COM_RX_MSG_NUM27)
#define BSW_COM_RX_MSG_NUM27             (BSW_COM_CFG_CH27_RX_NUM + BSW_COM_RX_MSG_NUM26)
#define BSW_COM_RX_MSG_NUM26             (BSW_COM_CFG_CH26_RX_NUM + BSW_COM_RX_MSG_NUM25)
#define BSW_COM_RX_MSG_NUM25             (BSW_COM_CFG_CH25_RX_NUM + BSW_COM_RX_MSG_NUM24)
#define BSW_COM_RX_MSG_NUM24             (BSW_COM_CFG_CH24_RX_NUM + BSW_COM_RX_MSG_NUM23)
#define BSW_COM_RX_MSG_NUM23             (BSW_COM_CFG_CH23_RX_NUM + BSW_COM_RX_MSG_NUM22)
#define BSW_COM_RX_MSG_NUM22             (BSW_COM_CFG_CH22_RX_NUM + BSW_COM_RX_MSG_NUM21)
#define BSW_COM_RX_MSG_NUM21             (BSW_COM_CFG_CH21_RX_NUM + BSW_COM_RX_MSG_NUM20)
#define BSW_COM_RX_MSG_NUM20             (BSW_COM_CFG_CH20_RX_NUM + BSW_COM_RX_MSG_NUM19)
#define BSW_COM_RX_MSG_NUM19             (BSW_COM_CFG_CH19_RX_NUM + BSW_COM_RX_MSG_NUM18)
#define BSW_COM_RX_MSG_NUM18             (BSW_COM_CFG_CH18_RX_NUM + BSW_COM_RX_MSG_NUM17)
#define BSW_COM_RX_MSG_NUM17             (BSW_COM_CFG_CH17_RX_NUM + BSW_COM_RX_MSG_NUM16)
#define BSW_COM_RX_MSG_NUM16             (BSW_COM_CFG_CH16_RX_NUM + BSW_COM_RX_MSG_NUM15)
#define BSW_COM_RX_MSG_NUM15             (BSW_COM_CFG_CH15_RX_NUM + BSW_COM_RX_MSG_NUM14)
#define BSW_COM_RX_MSG_NUM14             (BSW_COM_CFG_CH14_RX_NUM + BSW_COM_RX_MSG_NUM13)
#define BSW_COM_RX_MSG_NUM13             (BSW_COM_CFG_CH13_RX_NUM + BSW_COM_RX_MSG_NUM12)
#define BSW_COM_RX_MSG_NUM12             (BSW_COM_CFG_CH12_RX_NUM + BSW_COM_RX_MSG_NUM11)
#define BSW_COM_RX_MSG_NUM11             (BSW_COM_CFG_CH11_RX_NUM + BSW_COM_RX_MSG_NUM10)
#define BSW_COM_RX_MSG_NUM10             (BSW_COM_CFG_CH10_RX_NUM + BSW_COM_RX_MSG_NUM09)
#define BSW_COM_RX_MSG_NUM09             (BSW_COM_CFG_CH09_RX_NUM + BSW_COM_RX_MSG_NUM08)
#define BSW_COM_RX_MSG_NUM08             (BSW_COM_CFG_CH08_RX_NUM + BSW_COM_RX_MSG_NUM07)
#define BSW_COM_RX_MSG_NUM07             (BSW_COM_CFG_CH07_RX_NUM + BSW_COM_RX_MSG_NUM06)
#define BSW_COM_RX_MSG_NUM06             (BSW_COM_CFG_CH06_RX_NUM + BSW_COM_RX_MSG_NUM05)
#define BSW_COM_RX_MSG_NUM05             (BSW_COM_CFG_CH05_RX_NUM + BSW_COM_RX_MSG_NUM04)
#define BSW_COM_RX_MSG_NUM04             (BSW_COM_CFG_CH04_RX_NUM + BSW_COM_RX_MSG_NUM03)
#define BSW_COM_RX_MSG_NUM03             (BSW_COM_CFG_CH03_RX_NUM + BSW_COM_RX_MSG_NUM02)
#define BSW_COM_RX_MSG_NUM02             (BSW_COM_CFG_CH02_RX_NUM + BSW_COM_RX_MSG_NUM01)
#define BSW_COM_RX_MSG_NUM01             (BSW_COM_CFG_CH01_RX_NUM + BSW_COM_RX_MSG_NUM00)
#define BSW_COM_RX_MSG_NUM00             (BSW_COM_CFG_CH00_RX_NUM)


#if (BSW_BSWM_CS_MSG_DELIVER == BSW_BSWM_CS_MSGDELIVER_HIGH)
#define BSW_COM_u2MILSEC                 BSW_BSWM_CS_u2MILSEC2TICK_HIGH
#define BSW_COM_u2MILSEC_RUP             BSW_BSWM_CS_u2MS2TICK_RUP_HIGH
#else
#define BSW_COM_u2MILSEC                 BSW_BSWM_CS_u2MILSEC2TICK_MID
#define BSW_COM_u2MILSEC_RUP             BSW_BSWM_CS_u2MS2TICK_RUP_MID
#endif

#define BSW_COM_NETWORK_NUM              BSW_COM_CFG_CHNUM
#define BSW_COM_MSG_NUM                 (BSW_COM_TX_MSG_NUM + BSW_COM_RX_MSG_NUM)

#define BSW_COM_TX_MSG_NUM               (BSW_COM_TX_MSG_NUM31)
#define BSW_COM_TX_MSG_NUM31             (BSW_COM_CFG_CH31_TX_NUM + BSW_COM_TX_MSG_NUM30)
#define BSW_COM_TX_MSG_NUM30             (BSW_COM_CFG_CH30_TX_NUM + BSW_COM_TX_MSG_NUM29)
#define BSW_COM_TX_MSG_NUM29             (BSW_COM_CFG_CH29_TX_NUM + BSW_COM_TX_MSG_NUM28)
#define BSW_COM_TX_MSG_NUM28             (BSW_COM_CFG_CH28_TX_NUM + BSW_COM_TX_MSG_NUM27)
#define BSW_COM_TX_MSG_NUM27             (BSW_COM_CFG_CH27_TX_NUM + BSW_COM_TX_MSG_NUM26)
#define BSW_COM_TX_MSG_NUM26             (BSW_COM_CFG_CH26_TX_NUM + BSW_COM_TX_MSG_NUM25)
#define BSW_COM_TX_MSG_NUM25             (BSW_COM_CFG_CH25_TX_NUM + BSW_COM_TX_MSG_NUM24)
#define BSW_COM_TX_MSG_NUM24             (BSW_COM_CFG_CH24_TX_NUM + BSW_COM_TX_MSG_NUM23)
#define BSW_COM_TX_MSG_NUM23             (BSW_COM_CFG_CH23_TX_NUM + BSW_COM_TX_MSG_NUM22)
#define BSW_COM_TX_MSG_NUM22             (BSW_COM_CFG_CH22_TX_NUM + BSW_COM_TX_MSG_NUM21)
#define BSW_COM_TX_MSG_NUM21             (BSW_COM_CFG_CH21_TX_NUM + BSW_COM_TX_MSG_NUM20)
#define BSW_COM_TX_MSG_NUM20             (BSW_COM_CFG_CH20_TX_NUM + BSW_COM_TX_MSG_NUM19)
#define BSW_COM_TX_MSG_NUM19             (BSW_COM_CFG_CH19_TX_NUM + BSW_COM_TX_MSG_NUM18)
#define BSW_COM_TX_MSG_NUM18             (BSW_COM_CFG_CH18_TX_NUM + BSW_COM_TX_MSG_NUM17)
#define BSW_COM_TX_MSG_NUM17             (BSW_COM_CFG_CH17_TX_NUM + BSW_COM_TX_MSG_NUM16)
#define BSW_COM_TX_MSG_NUM16             (BSW_COM_CFG_CH16_TX_NUM + BSW_COM_TX_MSG_NUM15)
#define BSW_COM_TX_MSG_NUM15             (BSW_COM_CFG_CH15_TX_NUM + BSW_COM_TX_MSG_NUM14)
#define BSW_COM_TX_MSG_NUM14             (BSW_COM_CFG_CH14_TX_NUM + BSW_COM_TX_MSG_NUM13)
#define BSW_COM_TX_MSG_NUM13             (BSW_COM_CFG_CH13_TX_NUM + BSW_COM_TX_MSG_NUM12)
#define BSW_COM_TX_MSG_NUM12             (BSW_COM_CFG_CH12_TX_NUM + BSW_COM_TX_MSG_NUM11)
#define BSW_COM_TX_MSG_NUM11             (BSW_COM_CFG_CH11_TX_NUM + BSW_COM_TX_MSG_NUM10)
#define BSW_COM_TX_MSG_NUM10             (BSW_COM_CFG_CH10_TX_NUM + BSW_COM_TX_MSG_NUM09)
#define BSW_COM_TX_MSG_NUM09             (BSW_COM_CFG_CH09_TX_NUM + BSW_COM_TX_MSG_NUM08)
#define BSW_COM_TX_MSG_NUM08             (BSW_COM_CFG_CH08_TX_NUM + BSW_COM_TX_MSG_NUM07)
#define BSW_COM_TX_MSG_NUM07             (BSW_COM_CFG_CH07_TX_NUM + BSW_COM_TX_MSG_NUM06)
#define BSW_COM_TX_MSG_NUM06             (BSW_COM_CFG_CH06_TX_NUM + BSW_COM_TX_MSG_NUM05)
#define BSW_COM_TX_MSG_NUM05             (BSW_COM_CFG_CH05_TX_NUM + BSW_COM_TX_MSG_NUM04)
#define BSW_COM_TX_MSG_NUM04             (BSW_COM_CFG_CH04_TX_NUM + BSW_COM_TX_MSG_NUM03)
#define BSW_COM_TX_MSG_NUM03             (BSW_COM_CFG_CH03_TX_NUM + BSW_COM_TX_MSG_NUM02)
#define BSW_COM_TX_MSG_NUM02             (BSW_COM_CFG_CH02_TX_NUM + BSW_COM_TX_MSG_NUM01)
#define BSW_COM_TX_MSG_NUM01             (BSW_COM_CFG_CH01_TX_NUM + BSW_COM_TX_MSG_NUM00)
#define BSW_COM_TX_MSG_NUM00             (BSW_COM_CFG_CH00_TX_NUM)

#define BSW_COM_TX_ALVCNTMSG_NUM         BSW_COM_CFG_TX_ALVCNTMSG_NUM
#define BSW_COM_RX_ALVCNTMSG_NUM         BSW_COM_CFG_RX_ALVCNTMSG_NUM
#define BSW_COM_TX_ALVCNT3MSG_NUM        BSW_COM_CFG_TX_ALVCNT3MSG_NUM
#define BSW_COM_RX_ALVCNT3MSG_NUM        BSW_COM_CFG_RX_ALVCNT3MSG_NUM
#define BSW_COM_SENDNTIMES_MSG_NUM       BSW_COM_CFG_SENDNTIMES_MSG_NUM
#define BSW_COM_CHGPERIOD_MSG_NUM        BSW_COM_CFG_CHGPERIOD_MSG_NUM

#define BSW_COM_CH00_TX_NUM              BSW_COM_CFG_CH00_TX_NUM
#define BSW_COM_CH01_TX_NUM              BSW_COM_CFG_CH01_TX_NUM
#define BSW_COM_CH02_TX_NUM              BSW_COM_CFG_CH02_TX_NUM
#define BSW_COM_CH03_TX_NUM              BSW_COM_CFG_CH03_TX_NUM
#define BSW_COM_CH04_TX_NUM              BSW_COM_CFG_CH04_TX_NUM
#define BSW_COM_CH05_TX_NUM              BSW_COM_CFG_CH05_TX_NUM
#define BSW_COM_CH06_TX_NUM              BSW_COM_CFG_CH06_TX_NUM
#define BSW_COM_CH07_TX_NUM              BSW_COM_CFG_CH07_TX_NUM
#define BSW_COM_CH08_TX_NUM              BSW_COM_CFG_CH08_TX_NUM
#define BSW_COM_CH09_TX_NUM              BSW_COM_CFG_CH09_TX_NUM
#define BSW_COM_CH10_TX_NUM              BSW_COM_CFG_CH10_TX_NUM
#define BSW_COM_CH11_TX_NUM              BSW_COM_CFG_CH11_TX_NUM
#define BSW_COM_CH12_TX_NUM              BSW_COM_CFG_CH12_TX_NUM
#define BSW_COM_CH13_TX_NUM              BSW_COM_CFG_CH13_TX_NUM
#define BSW_COM_CH14_TX_NUM              BSW_COM_CFG_CH14_TX_NUM
#define BSW_COM_CH15_TX_NUM              BSW_COM_CFG_CH15_TX_NUM
#define BSW_COM_CH16_TX_NUM              BSW_COM_CFG_CH16_TX_NUM
#define BSW_COM_CH17_TX_NUM              BSW_COM_CFG_CH17_TX_NUM
#define BSW_COM_CH18_TX_NUM              BSW_COM_CFG_CH18_TX_NUM
#define BSW_COM_CH19_TX_NUM              BSW_COM_CFG_CH19_TX_NUM
#define BSW_COM_CH20_TX_NUM              BSW_COM_CFG_CH20_TX_NUM
#define BSW_COM_CH21_TX_NUM              BSW_COM_CFG_CH21_TX_NUM
#define BSW_COM_CH22_TX_NUM              BSW_COM_CFG_CH22_TX_NUM
#define BSW_COM_CH23_TX_NUM              BSW_COM_CFG_CH23_TX_NUM
#define BSW_COM_CH24_TX_NUM              BSW_COM_CFG_CH24_TX_NUM
#define BSW_COM_CH25_TX_NUM              BSW_COM_CFG_CH25_TX_NUM
#define BSW_COM_CH26_TX_NUM              BSW_COM_CFG_CH26_TX_NUM
#define BSW_COM_CH27_TX_NUM              BSW_COM_CFG_CH27_TX_NUM
#define BSW_COM_CH28_TX_NUM              BSW_COM_CFG_CH28_TX_NUM
#define BSW_COM_CH29_TX_NUM              BSW_COM_CFG_CH29_TX_NUM
#define BSW_COM_CH30_TX_NUM              BSW_COM_CFG_CH30_TX_NUM
#define BSW_COM_CH31_TX_NUM              BSW_COM_CFG_CH31_TX_NUM

#define BSW_COM_CH00_RX_NUM              BSW_COM_CFG_CH00_RX_NUM
#define BSW_COM_CH01_RX_NUM              BSW_COM_CFG_CH01_RX_NUM
#define BSW_COM_CH02_RX_NUM              BSW_COM_CFG_CH02_RX_NUM
#define BSW_COM_CH03_RX_NUM              BSW_COM_CFG_CH03_RX_NUM
#define BSW_COM_CH04_RX_NUM              BSW_COM_CFG_CH04_RX_NUM
#define BSW_COM_CH05_RX_NUM              BSW_COM_CFG_CH05_RX_NUM
#define BSW_COM_CH06_RX_NUM              BSW_COM_CFG_CH06_RX_NUM
#define BSW_COM_CH07_RX_NUM              BSW_COM_CFG_CH07_RX_NUM
#define BSW_COM_CH08_RX_NUM              BSW_COM_CFG_CH08_RX_NUM
#define BSW_COM_CH09_RX_NUM              BSW_COM_CFG_CH09_RX_NUM
#define BSW_COM_CH10_RX_NUM              BSW_COM_CFG_CH10_RX_NUM
#define BSW_COM_CH11_RX_NUM              BSW_COM_CFG_CH11_RX_NUM
#define BSW_COM_CH12_RX_NUM              BSW_COM_CFG_CH12_RX_NUM
#define BSW_COM_CH13_RX_NUM              BSW_COM_CFG_CH13_RX_NUM
#define BSW_COM_CH14_RX_NUM              BSW_COM_CFG_CH14_RX_NUM
#define BSW_COM_CH15_RX_NUM              BSW_COM_CFG_CH15_RX_NUM
#define BSW_COM_CH16_RX_NUM              BSW_COM_CFG_CH16_RX_NUM
#define BSW_COM_CH17_RX_NUM              BSW_COM_CFG_CH17_RX_NUM
#define BSW_COM_CH18_RX_NUM              BSW_COM_CFG_CH18_RX_NUM
#define BSW_COM_CH19_RX_NUM              BSW_COM_CFG_CH19_RX_NUM
#define BSW_COM_CH20_RX_NUM              BSW_COM_CFG_CH20_RX_NUM
#define BSW_COM_CH21_RX_NUM              BSW_COM_CFG_CH21_RX_NUM
#define BSW_COM_CH22_RX_NUM              BSW_COM_CFG_CH22_RX_NUM
#define BSW_COM_CH23_RX_NUM              BSW_COM_CFG_CH23_RX_NUM
#define BSW_COM_CH24_RX_NUM              BSW_COM_CFG_CH24_RX_NUM
#define BSW_COM_CH25_RX_NUM              BSW_COM_CFG_CH25_RX_NUM
#define BSW_COM_CH26_RX_NUM              BSW_COM_CFG_CH26_RX_NUM
#define BSW_COM_CH27_RX_NUM              BSW_COM_CFG_CH27_RX_NUM
#define BSW_COM_CH28_RX_NUM              BSW_COM_CFG_CH28_RX_NUM
#define BSW_COM_CH29_RX_NUM              BSW_COM_CFG_CH29_RX_NUM
#define BSW_COM_CH30_RX_NUM              BSW_COM_CFG_CH30_RX_NUM
#define BSW_COM_CH31_RX_NUM              BSW_COM_CFG_CH31_RX_NUM

#define BSW_COM_EVMSG_DELAY_TIME         BSW_COM_CFG_EVMSG_DELAY_TIME

#define BSW_COM_TX_TIMEOUT_USE           BSW_COM_CFG_TX_TIMEOUT_USE
#define BSW_COM_TX_DLYRTRGPRD_USE        BSW_COM_CFG_TX_DLYRTRGPRD_USE
#define BSW_COM_TX_DLYBYMSG_USE          BSW_COM_CFG_TX_DLYBYMSG_USE
#define BSW_COM_TX_DLYSW_USE             BSW_COM_CFG_TX_DLYSW_USE
#define BSW_COM_TX_CHGPERIOD_USE         BSW_BSWM_CS_TXCTRL_CYCCHG_USE

#define BSW_COM_CH00_TIMER_RETRIGGER     BSW_COM_CFG_CH00_TIM_RETRIGGER
#define BSW_COM_CH01_TIMER_RETRIGGER     BSW_COM_CFG_CH01_TIM_RETRIGGER
#define BSW_COM_CH02_TIMER_RETRIGGER     BSW_COM_CFG_CH02_TIM_RETRIGGER
#define BSW_COM_CH03_TIMER_RETRIGGER     BSW_COM_CFG_CH03_TIM_RETRIGGER
#define BSW_COM_CH04_TIMER_RETRIGGER     BSW_COM_CFG_CH04_TIM_RETRIGGER
#define BSW_COM_CH05_TIMER_RETRIGGER     BSW_COM_CFG_CH05_TIM_RETRIGGER
#define BSW_COM_CH06_TIMER_RETRIGGER     BSW_COM_CFG_CH06_TIM_RETRIGGER
#define BSW_COM_CH07_TIMER_RETRIGGER     BSW_COM_CFG_CH07_TIM_RETRIGGER
#define BSW_COM_CH08_TIMER_RETRIGGER     BSW_COM_CFG_CH08_TIM_RETRIGGER
#define BSW_COM_CH09_TIMER_RETRIGGER     BSW_COM_CFG_CH09_TIM_RETRIGGER
#define BSW_COM_CH10_TIMER_RETRIGGER     BSW_COM_CFG_CH10_TIM_RETRIGGER
#define BSW_COM_CH11_TIMER_RETRIGGER     BSW_COM_CFG_CH11_TIM_RETRIGGER
#define BSW_COM_CH12_TIMER_RETRIGGER     BSW_COM_CFG_CH12_TIM_RETRIGGER
#define BSW_COM_CH13_TIMER_RETRIGGER     BSW_COM_CFG_CH13_TIM_RETRIGGER
#define BSW_COM_CH14_TIMER_RETRIGGER     BSW_COM_CFG_CH14_TIM_RETRIGGER
#define BSW_COM_CH15_TIMER_RETRIGGER     BSW_COM_CFG_CH15_TIM_RETRIGGER
#define BSW_COM_CH16_TIMER_RETRIGGER     BSW_COM_CFG_CH16_TIM_RETRIGGER
#define BSW_COM_CH17_TIMER_RETRIGGER     BSW_COM_CFG_CH17_TIM_RETRIGGER
#define BSW_COM_CH18_TIMER_RETRIGGER     BSW_COM_CFG_CH18_TIM_RETRIGGER
#define BSW_COM_CH19_TIMER_RETRIGGER     BSW_COM_CFG_CH19_TIM_RETRIGGER
#define BSW_COM_CH20_TIMER_RETRIGGER     BSW_COM_CFG_CH20_TIM_RETRIGGER
#define BSW_COM_CH21_TIMER_RETRIGGER     BSW_COM_CFG_CH21_TIM_RETRIGGER
#define BSW_COM_CH22_TIMER_RETRIGGER     BSW_COM_CFG_CH22_TIM_RETRIGGER
#define BSW_COM_CH23_TIMER_RETRIGGER     BSW_COM_CFG_CH23_TIM_RETRIGGER
#define BSW_COM_CH24_TIMER_RETRIGGER     BSW_COM_CFG_CH24_TIM_RETRIGGER
#define BSW_COM_CH25_TIMER_RETRIGGER     BSW_COM_CFG_CH25_TIM_RETRIGGER
#define BSW_COM_CH26_TIMER_RETRIGGER     BSW_COM_CFG_CH26_TIM_RETRIGGER
#define BSW_COM_CH27_TIMER_RETRIGGER     BSW_COM_CFG_CH27_TIM_RETRIGGER
#define BSW_COM_CH28_TIMER_RETRIGGER     BSW_COM_CFG_CH28_TIM_RETRIGGER
#define BSW_COM_CH29_TIMER_RETRIGGER     BSW_COM_CFG_CH29_TIM_RETRIGGER
#define BSW_COM_CH30_TIMER_RETRIGGER     BSW_COM_CFG_CH30_TIM_RETRIGGER
#define BSW_COM_CH31_TIMER_RETRIGGER     BSW_COM_CFG_CH31_TIM_RETRIGGER

#define BSW_COM_CH00_TX_DLYMODE          BSW_COM_CFG_CH00_TX_DLYMODE
#define BSW_COM_CH01_TX_DLYMODE          BSW_COM_CFG_CH01_TX_DLYMODE
#define BSW_COM_CH02_TX_DLYMODE          BSW_COM_CFG_CH02_TX_DLYMODE
#define BSW_COM_CH03_TX_DLYMODE          BSW_COM_CFG_CH03_TX_DLYMODE
#define BSW_COM_CH04_TX_DLYMODE          BSW_COM_CFG_CH04_TX_DLYMODE
#define BSW_COM_CH05_TX_DLYMODE          BSW_COM_CFG_CH05_TX_DLYMODE
#define BSW_COM_CH06_TX_DLYMODE          BSW_COM_CFG_CH06_TX_DLYMODE
#define BSW_COM_CH07_TX_DLYMODE          BSW_COM_CFG_CH07_TX_DLYMODE
#define BSW_COM_CH08_TX_DLYMODE          BSW_COM_CFG_CH08_TX_DLYMODE
#define BSW_COM_CH09_TX_DLYMODE          BSW_COM_CFG_CH09_TX_DLYMODE
#define BSW_COM_CH10_TX_DLYMODE          BSW_COM_CFG_CH10_TX_DLYMODE
#define BSW_COM_CH11_TX_DLYMODE          BSW_COM_CFG_CH11_TX_DLYMODE
#define BSW_COM_CH12_TX_DLYMODE          BSW_COM_CFG_CH12_TX_DLYMODE
#define BSW_COM_CH13_TX_DLYMODE          BSW_COM_CFG_CH13_TX_DLYMODE
#define BSW_COM_CH14_TX_DLYMODE          BSW_COM_CFG_CH14_TX_DLYMODE
#define BSW_COM_CH15_TX_DLYMODE          BSW_COM_CFG_CH15_TX_DLYMODE
#define BSW_COM_CH16_TX_DLYMODE          BSW_COM_CFG_CH16_TX_DLYMODE
#define BSW_COM_CH17_TX_DLYMODE          BSW_COM_CFG_CH17_TX_DLYMODE
#define BSW_COM_CH18_TX_DLYMODE          BSW_COM_CFG_CH18_TX_DLYMODE
#define BSW_COM_CH19_TX_DLYMODE          BSW_COM_CFG_CH19_TX_DLYMODE
#define BSW_COM_CH20_TX_DLYMODE          BSW_COM_CFG_CH20_TX_DLYMODE
#define BSW_COM_CH21_TX_DLYMODE          BSW_COM_CFG_CH21_TX_DLYMODE
#define BSW_COM_CH22_TX_DLYMODE          BSW_COM_CFG_CH22_TX_DLYMODE
#define BSW_COM_CH23_TX_DLYMODE          BSW_COM_CFG_CH23_TX_DLYMODE
#define BSW_COM_CH24_TX_DLYMODE          BSW_COM_CFG_CH24_TX_DLYMODE
#define BSW_COM_CH25_TX_DLYMODE          BSW_COM_CFG_CH25_TX_DLYMODE
#define BSW_COM_CH26_TX_DLYMODE          BSW_COM_CFG_CH26_TX_DLYMODE
#define BSW_COM_CH27_TX_DLYMODE          BSW_COM_CFG_CH27_TX_DLYMODE
#define BSW_COM_CH28_TX_DLYMODE          BSW_COM_CFG_CH28_TX_DLYMODE
#define BSW_COM_CH29_TX_DLYMODE          BSW_COM_CFG_CH29_TX_DLYMODE
#define BSW_COM_CH30_TX_DLYMODE          BSW_COM_CFG_CH30_TX_DLYMODE
#define BSW_COM_CH31_TX_DLYMODE          BSW_COM_CFG_CH31_TX_DLYMODE

#define BSW_COM_CH00_TX_EVTRTRGMODE      BSW_COM_CFG_CH00_EVTTXRTRGMODE
#define BSW_COM_CH01_TX_EVTRTRGMODE      BSW_COM_CFG_CH01_EVTTXRTRGMODE
#define BSW_COM_CH02_TX_EVTRTRGMODE      BSW_COM_CFG_CH02_EVTTXRTRGMODE
#define BSW_COM_CH03_TX_EVTRTRGMODE      BSW_COM_CFG_CH03_EVTTXRTRGMODE
#define BSW_COM_CH04_TX_EVTRTRGMODE      BSW_COM_CFG_CH04_EVTTXRTRGMODE
#define BSW_COM_CH05_TX_EVTRTRGMODE      BSW_COM_CFG_CH05_EVTTXRTRGMODE
#define BSW_COM_CH06_TX_EVTRTRGMODE      BSW_COM_CFG_CH06_EVTTXRTRGMODE
#define BSW_COM_CH07_TX_EVTRTRGMODE      BSW_COM_CFG_CH07_EVTTXRTRGMODE
#define BSW_COM_CH08_TX_EVTRTRGMODE      BSW_COM_CFG_CH08_EVTTXRTRGMODE
#define BSW_COM_CH09_TX_EVTRTRGMODE      BSW_COM_CFG_CH09_EVTTXRTRGMODE
#define BSW_COM_CH10_TX_EVTRTRGMODE      BSW_COM_CFG_CH10_EVTTXRTRGMODE
#define BSW_COM_CH11_TX_EVTRTRGMODE      BSW_COM_CFG_CH11_EVTTXRTRGMODE
#define BSW_COM_CH12_TX_EVTRTRGMODE      BSW_COM_CFG_CH12_EVTTXRTRGMODE
#define BSW_COM_CH13_TX_EVTRTRGMODE      BSW_COM_CFG_CH13_EVTTXRTRGMODE
#define BSW_COM_CH14_TX_EVTRTRGMODE      BSW_COM_CFG_CH14_EVTTXRTRGMODE
#define BSW_COM_CH15_TX_EVTRTRGMODE      BSW_COM_CFG_CH15_EVTTXRTRGMODE
#define BSW_COM_CH16_TX_EVTRTRGMODE      BSW_COM_CFG_CH16_EVTTXRTRGMODE
#define BSW_COM_CH17_TX_EVTRTRGMODE      BSW_COM_CFG_CH17_EVTTXRTRGMODE
#define BSW_COM_CH18_TX_EVTRTRGMODE      BSW_COM_CFG_CH18_EVTTXRTRGMODE
#define BSW_COM_CH19_TX_EVTRTRGMODE      BSW_COM_CFG_CH19_EVTTXRTRGMODE
#define BSW_COM_CH20_TX_EVTRTRGMODE      BSW_COM_CFG_CH20_EVTTXRTRGMODE
#define BSW_COM_CH21_TX_EVTRTRGMODE      BSW_COM_CFG_CH21_EVTTXRTRGMODE
#define BSW_COM_CH22_TX_EVTRTRGMODE      BSW_COM_CFG_CH22_EVTTXRTRGMODE
#define BSW_COM_CH23_TX_EVTRTRGMODE      BSW_COM_CFG_CH23_EVTTXRTRGMODE
#define BSW_COM_CH24_TX_EVTRTRGMODE      BSW_COM_CFG_CH24_EVTTXRTRGMODE
#define BSW_COM_CH25_TX_EVTRTRGMODE      BSW_COM_CFG_CH25_EVTTXRTRGMODE
#define BSW_COM_CH26_TX_EVTRTRGMODE      BSW_COM_CFG_CH26_EVTTXRTRGMODE
#define BSW_COM_CH27_TX_EVTRTRGMODE      BSW_COM_CFG_CH27_EVTTXRTRGMODE
#define BSW_COM_CH28_TX_EVTRTRGMODE      BSW_COM_CFG_CH28_EVTTXRTRGMODE
#define BSW_COM_CH29_TX_EVTRTRGMODE      BSW_COM_CFG_CH29_EVTTXRTRGMODE
#define BSW_COM_CH30_TX_EVTRTRGMODE      BSW_COM_CFG_CH30_EVTTXRTRGMODE
#define BSW_COM_CH31_TX_EVTRTRGMODE      BSW_COM_CFG_CH31_EVTTXRTRGMODE


#define BSW_COM_ALIVECOUNTER_PTN_CH00    BSW_COM_CFG_CH00_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH01    BSW_COM_CFG_CH01_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH02    BSW_COM_CFG_CH02_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH03    BSW_COM_CFG_CH03_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH04    BSW_COM_CFG_CH04_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH05    BSW_COM_CFG_CH05_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH06    BSW_COM_CFG_CH06_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH07    BSW_COM_CFG_CH07_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH08    BSW_COM_CFG_CH08_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH09    BSW_COM_CFG_CH09_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH10    BSW_COM_CFG_CH10_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH11    BSW_COM_CFG_CH11_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH12    BSW_COM_CFG_CH12_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH13    BSW_COM_CFG_CH13_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH14    BSW_COM_CFG_CH14_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH15    BSW_COM_CFG_CH15_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH16    BSW_COM_CFG_CH16_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH17    BSW_COM_CFG_CH17_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH18    BSW_COM_CFG_CH18_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH19    BSW_COM_CFG_CH19_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH20    BSW_COM_CFG_CH20_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH21    BSW_COM_CFG_CH21_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH22    BSW_COM_CFG_CH22_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH23    BSW_COM_CFG_CH23_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH24    BSW_COM_CFG_CH24_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH25    BSW_COM_CFG_CH25_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH26    BSW_COM_CFG_CH26_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH27    BSW_COM_CFG_CH27_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH28    BSW_COM_CFG_CH28_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH29    BSW_COM_CFG_CH29_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH30    BSW_COM_CFG_CH30_ALVCNTR_PTN
#define BSW_COM_ALIVECOUNTER_PTN_CH31    BSW_COM_CFG_CH31_ALVCNTR_PTN

#define BSW_COM_CHGPRDCH_CH00            BSW_COM_CFG_CH00_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH01            BSW_COM_CFG_CH01_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH02            BSW_COM_CFG_CH02_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH03            BSW_COM_CFG_CH03_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH04            BSW_COM_CFG_CH04_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH05            BSW_COM_CFG_CH05_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH06            BSW_COM_CFG_CH06_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH07            BSW_COM_CFG_CH07_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH08            BSW_COM_CFG_CH08_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH09            BSW_COM_CFG_CH09_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH10            BSW_COM_CFG_CH10_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH11            BSW_COM_CFG_CH11_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH12            BSW_COM_CFG_CH12_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH13            BSW_COM_CFG_CH13_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH14            BSW_COM_CFG_CH14_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH15            BSW_COM_CFG_CH15_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH16            BSW_COM_CFG_CH16_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH17            BSW_COM_CFG_CH17_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH18            BSW_COM_CFG_CH18_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH19            BSW_COM_CFG_CH19_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH20            BSW_COM_CFG_CH20_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH21            BSW_COM_CFG_CH21_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH22            BSW_COM_CFG_CH22_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH23            BSW_COM_CFG_CH23_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH24            BSW_COM_CFG_CH24_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH25            BSW_COM_CFG_CH25_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH26            BSW_COM_CFG_CH26_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH27            BSW_COM_CFG_CH27_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH28            BSW_COM_CFG_CH28_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH29            BSW_COM_CFG_CH29_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH30            BSW_COM_CFG_CH30_CHGPRDCH
#define BSW_COM_CHGPRDCH_CH31            BSW_COM_CFG_CH31_CHGPRDCH

#define BSW_COM_CH00_TXTIMESLIMIT        BSW_COM_CFG_CH00_TXTIMESLIMIT
#define BSW_COM_CH01_TXTIMESLIMIT        BSW_COM_CFG_CH01_TXTIMESLIMIT
#define BSW_COM_CH02_TXTIMESLIMIT        BSW_COM_CFG_CH02_TXTIMESLIMIT
#define BSW_COM_CH03_TXTIMESLIMIT        BSW_COM_CFG_CH03_TXTIMESLIMIT
#define BSW_COM_CH04_TXTIMESLIMIT        BSW_COM_CFG_CH04_TXTIMESLIMIT
#define BSW_COM_CH05_TXTIMESLIMIT        BSW_COM_CFG_CH05_TXTIMESLIMIT
#define BSW_COM_CH06_TXTIMESLIMIT        BSW_COM_CFG_CH06_TXTIMESLIMIT
#define BSW_COM_CH07_TXTIMESLIMIT        BSW_COM_CFG_CH07_TXTIMESLIMIT
#define BSW_COM_CH08_TXTIMESLIMIT        BSW_COM_CFG_CH08_TXTIMESLIMIT
#define BSW_COM_CH09_TXTIMESLIMIT        BSW_COM_CFG_CH09_TXTIMESLIMIT
#define BSW_COM_CH10_TXTIMESLIMIT        BSW_COM_CFG_CH10_TXTIMESLIMIT
#define BSW_COM_CH11_TXTIMESLIMIT        BSW_COM_CFG_CH11_TXTIMESLIMIT
#define BSW_COM_CH12_TXTIMESLIMIT        BSW_COM_CFG_CH12_TXTIMESLIMIT
#define BSW_COM_CH13_TXTIMESLIMIT        BSW_COM_CFG_CH13_TXTIMESLIMIT
#define BSW_COM_CH14_TXTIMESLIMIT        BSW_COM_CFG_CH14_TXTIMESLIMIT
#define BSW_COM_CH15_TXTIMESLIMIT        BSW_COM_CFG_CH15_TXTIMESLIMIT
#define BSW_COM_CH16_TXTIMESLIMIT        BSW_COM_CFG_CH16_TXTIMESLIMIT
#define BSW_COM_CH17_TXTIMESLIMIT        BSW_COM_CFG_CH17_TXTIMESLIMIT
#define BSW_COM_CH18_TXTIMESLIMIT        BSW_COM_CFG_CH18_TXTIMESLIMIT
#define BSW_COM_CH19_TXTIMESLIMIT        BSW_COM_CFG_CH19_TXTIMESLIMIT
#define BSW_COM_CH20_TXTIMESLIMIT        BSW_COM_CFG_CH20_TXTIMESLIMIT
#define BSW_COM_CH21_TXTIMESLIMIT        BSW_COM_CFG_CH21_TXTIMESLIMIT
#define BSW_COM_CH22_TXTIMESLIMIT        BSW_COM_CFG_CH22_TXTIMESLIMIT
#define BSW_COM_CH23_TXTIMESLIMIT        BSW_COM_CFG_CH23_TXTIMESLIMIT
#define BSW_COM_CH24_TXTIMESLIMIT        BSW_COM_CFG_CH24_TXTIMESLIMIT
#define BSW_COM_CH25_TXTIMESLIMIT        BSW_COM_CFG_CH25_TXTIMESLIMIT
#define BSW_COM_CH26_TXTIMESLIMIT        BSW_COM_CFG_CH26_TXTIMESLIMIT
#define BSW_COM_CH27_TXTIMESLIMIT        BSW_COM_CFG_CH27_TXTIMESLIMIT
#define BSW_COM_CH28_TXTIMESLIMIT        BSW_COM_CFG_CH28_TXTIMESLIMIT
#define BSW_COM_CH29_TXTIMESLIMIT        BSW_COM_CFG_CH29_TXTIMESLIMIT
#define BSW_COM_CH30_TXTIMESLIMIT        BSW_COM_CFG_CH30_TXTIMESLIMIT
#define BSW_COM_CH31_TXTIMESLIMIT        BSW_COM_CFG_CH31_TXTIMESLIMIT

#define BSW_COM_EVENTAWAKE_USE           BSW_COM_CFG_EVENTAWAKE_USE

#define BSW_COM_CH00_EVTWAKEUPNUM        BSW_COM_CFG_CH00_EVTWAKEUPNUM
#define BSW_COM_CH01_EVTWAKEUPNUM        BSW_COM_CFG_CH01_EVTWAKEUPNUM
#define BSW_COM_CH02_EVTWAKEUPNUM        BSW_COM_CFG_CH02_EVTWAKEUPNUM
#define BSW_COM_CH03_EVTWAKEUPNUM        BSW_COM_CFG_CH03_EVTWAKEUPNUM
#define BSW_COM_CH04_EVTWAKEUPNUM        BSW_COM_CFG_CH04_EVTWAKEUPNUM
#define BSW_COM_CH05_EVTWAKEUPNUM        BSW_COM_CFG_CH05_EVTWAKEUPNUM
#define BSW_COM_CH06_EVTWAKEUPNUM        BSW_COM_CFG_CH06_EVTWAKEUPNUM
#define BSW_COM_CH07_EVTWAKEUPNUM        BSW_COM_CFG_CH07_EVTWAKEUPNUM
#define BSW_COM_CH08_EVTWAKEUPNUM        BSW_COM_CFG_CH08_EVTWAKEUPNUM
#define BSW_COM_CH09_EVTWAKEUPNUM        BSW_COM_CFG_CH09_EVTWAKEUPNUM
#define BSW_COM_CH10_EVTWAKEUPNUM        BSW_COM_CFG_CH10_EVTWAKEUPNUM
#define BSW_COM_CH11_EVTWAKEUPNUM        BSW_COM_CFG_CH11_EVTWAKEUPNUM
#define BSW_COM_CH12_EVTWAKEUPNUM        BSW_COM_CFG_CH12_EVTWAKEUPNUM
#define BSW_COM_CH13_EVTWAKEUPNUM        BSW_COM_CFG_CH13_EVTWAKEUPNUM
#define BSW_COM_CH14_EVTWAKEUPNUM        BSW_COM_CFG_CH14_EVTWAKEUPNUM
#define BSW_COM_CH15_EVTWAKEUPNUM        BSW_COM_CFG_CH15_EVTWAKEUPNUM
#define BSW_COM_CH16_EVTWAKEUPNUM        BSW_COM_CFG_CH16_EVTWAKEUPNUM
#define BSW_COM_CH17_EVTWAKEUPNUM        BSW_COM_CFG_CH17_EVTWAKEUPNUM
#define BSW_COM_CH18_EVTWAKEUPNUM        BSW_COM_CFG_CH18_EVTWAKEUPNUM
#define BSW_COM_CH19_EVTWAKEUPNUM        BSW_COM_CFG_CH19_EVTWAKEUPNUM
#define BSW_COM_CH20_EVTWAKEUPNUM        BSW_COM_CFG_CH20_EVTWAKEUPNUM
#define BSW_COM_CH21_EVTWAKEUPNUM        BSW_COM_CFG_CH21_EVTWAKEUPNUM
#define BSW_COM_CH22_EVTWAKEUPNUM        BSW_COM_CFG_CH22_EVTWAKEUPNUM
#define BSW_COM_CH23_EVTWAKEUPNUM        BSW_COM_CFG_CH23_EVTWAKEUPNUM
#define BSW_COM_CH24_EVTWAKEUPNUM        BSW_COM_CFG_CH24_EVTWAKEUPNUM
#define BSW_COM_CH25_EVTWAKEUPNUM        BSW_COM_CFG_CH25_EVTWAKEUPNUM
#define BSW_COM_CH26_EVTWAKEUPNUM        BSW_COM_CFG_CH26_EVTWAKEUPNUM
#define BSW_COM_CH27_EVTWAKEUPNUM        BSW_COM_CFG_CH27_EVTWAKEUPNUM
#define BSW_COM_CH28_EVTWAKEUPNUM        BSW_COM_CFG_CH28_EVTWAKEUPNUM
#define BSW_COM_CH29_EVTWAKEUPNUM        BSW_COM_CFG_CH29_EVTWAKEUPNUM
#define BSW_COM_CH30_EVTWAKEUPNUM        BSW_COM_CFG_CH30_EVTWAKEUPNUM
#define BSW_COM_CH31_EVTWAKEUPNUM        BSW_COM_CFG_CH31_EVTWAKEUPNUM

#define BSW_COM_EVENTWAKEUPFRAME_USE     ((BSW_COM_EVENTWAKEUPFRAME_NUM > 0U) ? BSW_USE : BSW_NOUSE)
#define BSW_COM_EVENTWAKEUPFRAME_NUM     (BSW_COM_EVENTWAKEUPFRAME_NUM31)
#define BSW_COM_EVENTWAKEUPFRAME_NUM31   (BSW_COM_CH31_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM30)
#define BSW_COM_EVENTWAKEUPFRAME_NUM30   (BSW_COM_CH30_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM29)
#define BSW_COM_EVENTWAKEUPFRAME_NUM29   (BSW_COM_CH29_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM28)
#define BSW_COM_EVENTWAKEUPFRAME_NUM28   (BSW_COM_CH28_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM27)
#define BSW_COM_EVENTWAKEUPFRAME_NUM27   (BSW_COM_CH27_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM26)
#define BSW_COM_EVENTWAKEUPFRAME_NUM26   (BSW_COM_CH26_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM25)
#define BSW_COM_EVENTWAKEUPFRAME_NUM25   (BSW_COM_CH25_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM24)
#define BSW_COM_EVENTWAKEUPFRAME_NUM24   (BSW_COM_CH24_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM23)
#define BSW_COM_EVENTWAKEUPFRAME_NUM23   (BSW_COM_CH23_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM22)
#define BSW_COM_EVENTWAKEUPFRAME_NUM22   (BSW_COM_CH22_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM21)
#define BSW_COM_EVENTWAKEUPFRAME_NUM21   (BSW_COM_CH21_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM20)
#define BSW_COM_EVENTWAKEUPFRAME_NUM20   (BSW_COM_CH20_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM19)
#define BSW_COM_EVENTWAKEUPFRAME_NUM19   (BSW_COM_CH19_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM18)
#define BSW_COM_EVENTWAKEUPFRAME_NUM18   (BSW_COM_CH18_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM17)
#define BSW_COM_EVENTWAKEUPFRAME_NUM17   (BSW_COM_CH17_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM16)
#define BSW_COM_EVENTWAKEUPFRAME_NUM16   (BSW_COM_CH16_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM15)
#define BSW_COM_EVENTWAKEUPFRAME_NUM15   (BSW_COM_CH15_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM14)
#define BSW_COM_EVENTWAKEUPFRAME_NUM14   (BSW_COM_CH14_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM13)
#define BSW_COM_EVENTWAKEUPFRAME_NUM13   (BSW_COM_CH13_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM12)
#define BSW_COM_EVENTWAKEUPFRAME_NUM12   (BSW_COM_CH12_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM11)
#define BSW_COM_EVENTWAKEUPFRAME_NUM11   (BSW_COM_CH11_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM10)
#define BSW_COM_EVENTWAKEUPFRAME_NUM10   (BSW_COM_CH10_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM09)
#define BSW_COM_EVENTWAKEUPFRAME_NUM09   (BSW_COM_CH09_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM08)
#define BSW_COM_EVENTWAKEUPFRAME_NUM08   (BSW_COM_CH08_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM07)
#define BSW_COM_EVENTWAKEUPFRAME_NUM07   (BSW_COM_CH07_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM06)
#define BSW_COM_EVENTWAKEUPFRAME_NUM06   (BSW_COM_CH06_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM05)
#define BSW_COM_EVENTWAKEUPFRAME_NUM05   (BSW_COM_CH05_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM04)
#define BSW_COM_EVENTWAKEUPFRAME_NUM04   (BSW_COM_CH04_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM03)
#define BSW_COM_EVENTWAKEUPFRAME_NUM03   (BSW_COM_CH03_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM02)
#define BSW_COM_EVENTWAKEUPFRAME_NUM02   (BSW_COM_CH02_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM01)
#define BSW_COM_EVENTWAKEUPFRAME_NUM01   (BSW_COM_CH01_EVTWAKEUPNUM + BSW_COM_EVENTWAKEUPFRAME_NUM00)
#define BSW_COM_EVENTWAKEUPFRAME_NUM00   (BSW_COM_CH00_EVTWAKEUPNUM)

#define BSW_COM_ALIVECOUNTER_PTN2_USE    BSW_COM_ALVCNTR_PTN2_USE_CH00
#define BSW_COM_ALVCNTR_PTN2_USE_CH00    ((BSW_COM_CFG_CH00_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH01)
#define BSW_COM_ALVCNTR_PTN2_USE_CH01    ((BSW_COM_CFG_CH01_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH02)
#define BSW_COM_ALVCNTR_PTN2_USE_CH02    ((BSW_COM_CFG_CH02_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH03)
#define BSW_COM_ALVCNTR_PTN2_USE_CH03    ((BSW_COM_CFG_CH03_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH04)
#define BSW_COM_ALVCNTR_PTN2_USE_CH04    ((BSW_COM_CFG_CH04_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH05)
#define BSW_COM_ALVCNTR_PTN2_USE_CH05    ((BSW_COM_CFG_CH05_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH06)
#define BSW_COM_ALVCNTR_PTN2_USE_CH06    ((BSW_COM_CFG_CH06_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH07)
#define BSW_COM_ALVCNTR_PTN2_USE_CH07    ((BSW_COM_CFG_CH07_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH08)
#define BSW_COM_ALVCNTR_PTN2_USE_CH08    ((BSW_COM_CFG_CH08_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH09)
#define BSW_COM_ALVCNTR_PTN2_USE_CH09    ((BSW_COM_CFG_CH09_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH10)
#define BSW_COM_ALVCNTR_PTN2_USE_CH10    ((BSW_COM_CFG_CH10_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH11)
#define BSW_COM_ALVCNTR_PTN2_USE_CH11    ((BSW_COM_CFG_CH11_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH12)
#define BSW_COM_ALVCNTR_PTN2_USE_CH12    ((BSW_COM_CFG_CH12_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH13)
#define BSW_COM_ALVCNTR_PTN2_USE_CH13    ((BSW_COM_CFG_CH13_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH14)
#define BSW_COM_ALVCNTR_PTN2_USE_CH14    ((BSW_COM_CFG_CH14_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH15)
#define BSW_COM_ALVCNTR_PTN2_USE_CH15    ((BSW_COM_CFG_CH15_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH16)
#define BSW_COM_ALVCNTR_PTN2_USE_CH16    ((BSW_COM_CFG_CH16_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH17)
#define BSW_COM_ALVCNTR_PTN2_USE_CH17    ((BSW_COM_CFG_CH17_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH18)
#define BSW_COM_ALVCNTR_PTN2_USE_CH18    ((BSW_COM_CFG_CH18_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH19)
#define BSW_COM_ALVCNTR_PTN2_USE_CH19    ((BSW_COM_CFG_CH19_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH20)
#define BSW_COM_ALVCNTR_PTN2_USE_CH20    ((BSW_COM_CFG_CH20_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH21)
#define BSW_COM_ALVCNTR_PTN2_USE_CH21    ((BSW_COM_CFG_CH21_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH22)
#define BSW_COM_ALVCNTR_PTN2_USE_CH22    ((BSW_COM_CFG_CH22_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH23)
#define BSW_COM_ALVCNTR_PTN2_USE_CH23    ((BSW_COM_CFG_CH23_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH24)
#define BSW_COM_ALVCNTR_PTN2_USE_CH24    ((BSW_COM_CFG_CH24_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH25)
#define BSW_COM_ALVCNTR_PTN2_USE_CH25    ((BSW_COM_CFG_CH25_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH26)
#define BSW_COM_ALVCNTR_PTN2_USE_CH26    ((BSW_COM_CFG_CH26_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH27)
#define BSW_COM_ALVCNTR_PTN2_USE_CH27    ((BSW_COM_CFG_CH27_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH28)
#define BSW_COM_ALVCNTR_PTN2_USE_CH28    ((BSW_COM_CFG_CH28_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH29)
#define BSW_COM_ALVCNTR_PTN2_USE_CH29    ((BSW_COM_CFG_CH29_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH30)
#define BSW_COM_ALVCNTR_PTN2_USE_CH30    ((BSW_COM_CFG_CH30_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_COM_ALVCNTR_PTN2_USE_CH31)
#define BSW_COM_ALVCNTR_PTN2_USE_CH31    ((BSW_COM_CFG_CH31_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN2) ? BSW_USE : BSW_NOUSE)

#define BSW_COM_ALIVECOUNTER_PTN3_USE    BSW_COM_ALVCNTR_PTN3_USE_CH00
#define BSW_COM_ALVCNTR_PTN3_USE_CH00    ((BSW_COM_CFG_CH00_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH01)
#define BSW_COM_ALVCNTR_PTN3_USE_CH01    ((BSW_COM_CFG_CH01_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH02)
#define BSW_COM_ALVCNTR_PTN3_USE_CH02    ((BSW_COM_CFG_CH02_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH03)
#define BSW_COM_ALVCNTR_PTN3_USE_CH03    ((BSW_COM_CFG_CH03_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH04)
#define BSW_COM_ALVCNTR_PTN3_USE_CH04    ((BSW_COM_CFG_CH04_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH05)
#define BSW_COM_ALVCNTR_PTN3_USE_CH05    ((BSW_COM_CFG_CH05_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH06)
#define BSW_COM_ALVCNTR_PTN3_USE_CH06    ((BSW_COM_CFG_CH06_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH07)
#define BSW_COM_ALVCNTR_PTN3_USE_CH07    ((BSW_COM_CFG_CH07_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH08)
#define BSW_COM_ALVCNTR_PTN3_USE_CH08    ((BSW_COM_CFG_CH08_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH09)
#define BSW_COM_ALVCNTR_PTN3_USE_CH09    ((BSW_COM_CFG_CH09_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH10)
#define BSW_COM_ALVCNTR_PTN3_USE_CH10    ((BSW_COM_CFG_CH10_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH11)
#define BSW_COM_ALVCNTR_PTN3_USE_CH11    ((BSW_COM_CFG_CH11_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH12)
#define BSW_COM_ALVCNTR_PTN3_USE_CH12    ((BSW_COM_CFG_CH12_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH13)
#define BSW_COM_ALVCNTR_PTN3_USE_CH13    ((BSW_COM_CFG_CH13_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH14)
#define BSW_COM_ALVCNTR_PTN3_USE_CH14    ((BSW_COM_CFG_CH14_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH15)
#define BSW_COM_ALVCNTR_PTN3_USE_CH15    ((BSW_COM_CFG_CH15_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH16)
#define BSW_COM_ALVCNTR_PTN3_USE_CH16    ((BSW_COM_CFG_CH16_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH17)
#define BSW_COM_ALVCNTR_PTN3_USE_CH17    ((BSW_COM_CFG_CH17_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH18)
#define BSW_COM_ALVCNTR_PTN3_USE_CH18    ((BSW_COM_CFG_CH18_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH19)
#define BSW_COM_ALVCNTR_PTN3_USE_CH19    ((BSW_COM_CFG_CH19_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH20)
#define BSW_COM_ALVCNTR_PTN3_USE_CH20    ((BSW_COM_CFG_CH20_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH21)
#define BSW_COM_ALVCNTR_PTN3_USE_CH21    ((BSW_COM_CFG_CH21_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH22)
#define BSW_COM_ALVCNTR_PTN3_USE_CH22    ((BSW_COM_CFG_CH22_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH23)
#define BSW_COM_ALVCNTR_PTN3_USE_CH23    ((BSW_COM_CFG_CH23_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH24)
#define BSW_COM_ALVCNTR_PTN3_USE_CH24    ((BSW_COM_CFG_CH24_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH25)
#define BSW_COM_ALVCNTR_PTN3_USE_CH25    ((BSW_COM_CFG_CH25_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH26)
#define BSW_COM_ALVCNTR_PTN3_USE_CH26    ((BSW_COM_CFG_CH26_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH27)
#define BSW_COM_ALVCNTR_PTN3_USE_CH27    ((BSW_COM_CFG_CH27_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH28)
#define BSW_COM_ALVCNTR_PTN3_USE_CH28    ((BSW_COM_CFG_CH28_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH29)
#define BSW_COM_ALVCNTR_PTN3_USE_CH29    ((BSW_COM_CFG_CH29_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH30)
#define BSW_COM_ALVCNTR_PTN3_USE_CH30    ((BSW_COM_CFG_CH30_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_COM_ALVCNTR_PTN3_USE_CH31)
#define BSW_COM_ALVCNTR_PTN3_USE_CH31    ((BSW_COM_CFG_CH31_ALVCNTR_PTN == BSW_COM_ALIVECOUNTER_PTN3) ? BSW_USE : BSW_NOUSE)

#define BSW_COM_PRETX_MAX_MSGSIZE        BSW_COM_CFG_PRETX_MAX_MSGSIZE

#define BSW_COM_CH00_RXTOUTMSKSTOP       BSW_COM_CFG_CH00_RXTOUTMSKSTOP
#define BSW_COM_CH01_RXTOUTMSKSTOP       BSW_COM_CFG_CH01_RXTOUTMSKSTOP
#define BSW_COM_CH02_RXTOUTMSKSTOP       BSW_COM_CFG_CH02_RXTOUTMSKSTOP
#define BSW_COM_CH03_RXTOUTMSKSTOP       BSW_COM_CFG_CH03_RXTOUTMSKSTOP
#define BSW_COM_CH04_RXTOUTMSKSTOP       BSW_COM_CFG_CH04_RXTOUTMSKSTOP
#define BSW_COM_CH05_RXTOUTMSKSTOP       BSW_COM_CFG_CH05_RXTOUTMSKSTOP
#define BSW_COM_CH06_RXTOUTMSKSTOP       BSW_COM_CFG_CH06_RXTOUTMSKSTOP
#define BSW_COM_CH07_RXTOUTMSKSTOP       BSW_COM_CFG_CH07_RXTOUTMSKSTOP
#define BSW_COM_CH08_RXTOUTMSKSTOP       BSW_COM_CFG_CH08_RXTOUTMSKSTOP
#define BSW_COM_CH09_RXTOUTMSKSTOP       BSW_COM_CFG_CH09_RXTOUTMSKSTOP
#define BSW_COM_CH10_RXTOUTMSKSTOP       BSW_COM_CFG_CH10_RXTOUTMSKSTOP
#define BSW_COM_CH11_RXTOUTMSKSTOP       BSW_COM_CFG_CH11_RXTOUTMSKSTOP
#define BSW_COM_CH12_RXTOUTMSKSTOP       BSW_COM_CFG_CH12_RXTOUTMSKSTOP
#define BSW_COM_CH13_RXTOUTMSKSTOP       BSW_COM_CFG_CH13_RXTOUTMSKSTOP
#define BSW_COM_CH14_RXTOUTMSKSTOP       BSW_COM_CFG_CH14_RXTOUTMSKSTOP
#define BSW_COM_CH15_RXTOUTMSKSTOP       BSW_COM_CFG_CH15_RXTOUTMSKSTOP
#define BSW_COM_CH16_RXTOUTMSKSTOP       BSW_COM_CFG_CH16_RXTOUTMSKSTOP
#define BSW_COM_CH17_RXTOUTMSKSTOP       BSW_COM_CFG_CH17_RXTOUTMSKSTOP
#define BSW_COM_CH18_RXTOUTMSKSTOP       BSW_COM_CFG_CH18_RXTOUTMSKSTOP
#define BSW_COM_CH19_RXTOUTMSKSTOP       BSW_COM_CFG_CH19_RXTOUTMSKSTOP
#define BSW_COM_CH20_RXTOUTMSKSTOP       BSW_COM_CFG_CH20_RXTOUTMSKSTOP
#define BSW_COM_CH21_RXTOUTMSKSTOP       BSW_COM_CFG_CH21_RXTOUTMSKSTOP
#define BSW_COM_CH22_RXTOUTMSKSTOP       BSW_COM_CFG_CH22_RXTOUTMSKSTOP
#define BSW_COM_CH23_RXTOUTMSKSTOP       BSW_COM_CFG_CH23_RXTOUTMSKSTOP
#define BSW_COM_CH24_RXTOUTMSKSTOP       BSW_COM_CFG_CH24_RXTOUTMSKSTOP
#define BSW_COM_CH25_RXTOUTMSKSTOP       BSW_COM_CFG_CH25_RXTOUTMSKSTOP
#define BSW_COM_CH26_RXTOUTMSKSTOP       BSW_COM_CFG_CH26_RXTOUTMSKSTOP
#define BSW_COM_CH27_RXTOUTMSKSTOP       BSW_COM_CFG_CH27_RXTOUTMSKSTOP
#define BSW_COM_CH28_RXTOUTMSKSTOP       BSW_COM_CFG_CH28_RXTOUTMSKSTOP
#define BSW_COM_CH29_RXTOUTMSKSTOP       BSW_COM_CFG_CH29_RXTOUTMSKSTOP
#define BSW_COM_CH30_RXTOUTMSKSTOP       BSW_COM_CFG_CH30_RXTOUTMSKSTOP
#define BSW_COM_CH31_RXTOUTMSKSTOP       BSW_COM_CFG_CH31_RXTOUTMSKSTOP

#define BSW_COM_CH00_NONAWKPWON_WT       BSW_COM_CFG_CH00_NONAWKPWON_WT
#define BSW_COM_CH01_NONAWKPWON_WT       BSW_COM_CFG_CH01_NONAWKPWON_WT
#define BSW_COM_CH02_NONAWKPWON_WT       BSW_COM_CFG_CH02_NONAWKPWON_WT
#define BSW_COM_CH03_NONAWKPWON_WT       BSW_COM_CFG_CH03_NONAWKPWON_WT
#define BSW_COM_CH04_NONAWKPWON_WT       BSW_COM_CFG_CH04_NONAWKPWON_WT
#define BSW_COM_CH05_NONAWKPWON_WT       BSW_COM_CFG_CH05_NONAWKPWON_WT
#define BSW_COM_CH06_NONAWKPWON_WT       BSW_COM_CFG_CH06_NONAWKPWON_WT
#define BSW_COM_CH07_NONAWKPWON_WT       BSW_COM_CFG_CH07_NONAWKPWON_WT
#define BSW_COM_CH08_NONAWKPWON_WT       BSW_COM_CFG_CH08_NONAWKPWON_WT
#define BSW_COM_CH09_NONAWKPWON_WT       BSW_COM_CFG_CH09_NONAWKPWON_WT
#define BSW_COM_CH10_NONAWKPWON_WT       BSW_COM_CFG_CH10_NONAWKPWON_WT
#define BSW_COM_CH11_NONAWKPWON_WT       BSW_COM_CFG_CH11_NONAWKPWON_WT
#define BSW_COM_CH12_NONAWKPWON_WT       BSW_COM_CFG_CH12_NONAWKPWON_WT
#define BSW_COM_CH13_NONAWKPWON_WT       BSW_COM_CFG_CH13_NONAWKPWON_WT
#define BSW_COM_CH14_NONAWKPWON_WT       BSW_COM_CFG_CH14_NONAWKPWON_WT
#define BSW_COM_CH15_NONAWKPWON_WT       BSW_COM_CFG_CH15_NONAWKPWON_WT
#define BSW_COM_CH16_NONAWKPWON_WT       BSW_COM_CFG_CH16_NONAWKPWON_WT
#define BSW_COM_CH17_NONAWKPWON_WT       BSW_COM_CFG_CH17_NONAWKPWON_WT
#define BSW_COM_CH18_NONAWKPWON_WT       BSW_COM_CFG_CH18_NONAWKPWON_WT
#define BSW_COM_CH19_NONAWKPWON_WT       BSW_COM_CFG_CH19_NONAWKPWON_WT
#define BSW_COM_CH20_NONAWKPWON_WT       BSW_COM_CFG_CH20_NONAWKPWON_WT
#define BSW_COM_CH21_NONAWKPWON_WT       BSW_COM_CFG_CH21_NONAWKPWON_WT
#define BSW_COM_CH22_NONAWKPWON_WT       BSW_COM_CFG_CH22_NONAWKPWON_WT
#define BSW_COM_CH23_NONAWKPWON_WT       BSW_COM_CFG_CH23_NONAWKPWON_WT
#define BSW_COM_CH24_NONAWKPWON_WT       BSW_COM_CFG_CH24_NONAWKPWON_WT
#define BSW_COM_CH25_NONAWKPWON_WT       BSW_COM_CFG_CH25_NONAWKPWON_WT
#define BSW_COM_CH26_NONAWKPWON_WT       BSW_COM_CFG_CH26_NONAWKPWON_WT
#define BSW_COM_CH27_NONAWKPWON_WT       BSW_COM_CFG_CH27_NONAWKPWON_WT
#define BSW_COM_CH28_NONAWKPWON_WT       BSW_COM_CFG_CH28_NONAWKPWON_WT
#define BSW_COM_CH29_NONAWKPWON_WT       BSW_COM_CFG_CH29_NONAWKPWON_WT
#define BSW_COM_CH30_NONAWKPWON_WT       BSW_COM_CFG_CH30_NONAWKPWON_WT
#define BSW_COM_CH31_NONAWKPWON_WT       BSW_COM_CFG_CH31_NONAWKPWON_WT

#define BSW_COM_CH00_TX_TIMEOUTMODE      BSW_COM_CFG_CH00_TX_TIMEOUTMODE
#define BSW_COM_CH01_TX_TIMEOUTMODE      BSW_COM_CFG_CH01_TX_TIMEOUTMODE
#define BSW_COM_CH02_TX_TIMEOUTMODE      BSW_COM_CFG_CH02_TX_TIMEOUTMODE
#define BSW_COM_CH03_TX_TIMEOUTMODE      BSW_COM_CFG_CH03_TX_TIMEOUTMODE
#define BSW_COM_CH04_TX_TIMEOUTMODE      BSW_COM_CFG_CH04_TX_TIMEOUTMODE
#define BSW_COM_CH05_TX_TIMEOUTMODE      BSW_COM_CFG_CH05_TX_TIMEOUTMODE
#define BSW_COM_CH06_TX_TIMEOUTMODE      BSW_COM_CFG_CH06_TX_TIMEOUTMODE
#define BSW_COM_CH07_TX_TIMEOUTMODE      BSW_COM_CFG_CH07_TX_TIMEOUTMODE
#define BSW_COM_CH08_TX_TIMEOUTMODE      BSW_COM_CFG_CH08_TX_TIMEOUTMODE
#define BSW_COM_CH09_TX_TIMEOUTMODE      BSW_COM_CFG_CH09_TX_TIMEOUTMODE
#define BSW_COM_CH10_TX_TIMEOUTMODE      BSW_COM_CFG_CH10_TX_TIMEOUTMODE
#define BSW_COM_CH11_TX_TIMEOUTMODE      BSW_COM_CFG_CH11_TX_TIMEOUTMODE
#define BSW_COM_CH12_TX_TIMEOUTMODE      BSW_COM_CFG_CH12_TX_TIMEOUTMODE
#define BSW_COM_CH13_TX_TIMEOUTMODE      BSW_COM_CFG_CH13_TX_TIMEOUTMODE
#define BSW_COM_CH14_TX_TIMEOUTMODE      BSW_COM_CFG_CH14_TX_TIMEOUTMODE
#define BSW_COM_CH15_TX_TIMEOUTMODE      BSW_COM_CFG_CH15_TX_TIMEOUTMODE
#define BSW_COM_CH16_TX_TIMEOUTMODE      BSW_COM_CFG_CH16_TX_TIMEOUTMODE
#define BSW_COM_CH17_TX_TIMEOUTMODE      BSW_COM_CFG_CH17_TX_TIMEOUTMODE
#define BSW_COM_CH18_TX_TIMEOUTMODE      BSW_COM_CFG_CH18_TX_TIMEOUTMODE
#define BSW_COM_CH19_TX_TIMEOUTMODE      BSW_COM_CFG_CH19_TX_TIMEOUTMODE
#define BSW_COM_CH20_TX_TIMEOUTMODE      BSW_COM_CFG_CH20_TX_TIMEOUTMODE
#define BSW_COM_CH21_TX_TIMEOUTMODE      BSW_COM_CFG_CH21_TX_TIMEOUTMODE
#define BSW_COM_CH22_TX_TIMEOUTMODE      BSW_COM_CFG_CH22_TX_TIMEOUTMODE
#define BSW_COM_CH23_TX_TIMEOUTMODE      BSW_COM_CFG_CH23_TX_TIMEOUTMODE
#define BSW_COM_CH24_TX_TIMEOUTMODE      BSW_COM_CFG_CH24_TX_TIMEOUTMODE
#define BSW_COM_CH25_TX_TIMEOUTMODE      BSW_COM_CFG_CH25_TX_TIMEOUTMODE
#define BSW_COM_CH26_TX_TIMEOUTMODE      BSW_COM_CFG_CH26_TX_TIMEOUTMODE
#define BSW_COM_CH27_TX_TIMEOUTMODE      BSW_COM_CFG_CH27_TX_TIMEOUTMODE
#define BSW_COM_CH28_TX_TIMEOUTMODE      BSW_COM_CFG_CH28_TX_TIMEOUTMODE
#define BSW_COM_CH29_TX_TIMEOUTMODE      BSW_COM_CFG_CH29_TX_TIMEOUTMODE
#define BSW_COM_CH30_TX_TIMEOUTMODE      BSW_COM_CFG_CH30_TX_TIMEOUTMODE
#define BSW_COM_CH31_TX_TIMEOUTMODE      BSW_COM_CFG_CH31_TX_TIMEOUTMODE

#define BSW_COM_FIRSTTXTIMEOUT_USE       BSW_COM_FIRSTTXTIMEOUT_USE_CH00
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH00  ((BSW_COM_CH00_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH01)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH01  ((BSW_COM_CH01_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH02)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH02  ((BSW_COM_CH02_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH03)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH03  ((BSW_COM_CH03_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH04)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH04  ((BSW_COM_CH04_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH05)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH05  ((BSW_COM_CH05_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH06)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH06  ((BSW_COM_CH06_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH07)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH07  ((BSW_COM_CH07_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH08)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH08  ((BSW_COM_CH08_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH09)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH09  ((BSW_COM_CH09_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH10)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH10  ((BSW_COM_CH10_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH11)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH11  ((BSW_COM_CH11_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH12)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH12  ((BSW_COM_CH12_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH13)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH13  ((BSW_COM_CH13_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH14)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH14  ((BSW_COM_CH14_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH15)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH15  ((BSW_COM_CH15_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH16)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH16  ((BSW_COM_CH16_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH17)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH17  ((BSW_COM_CH17_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH18)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH18  ((BSW_COM_CH18_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH19)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH19  ((BSW_COM_CH19_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH20)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH20  ((BSW_COM_CH20_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH21)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH21  ((BSW_COM_CH21_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH22)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH22  ((BSW_COM_CH22_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH23)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH23  ((BSW_COM_CH23_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH24)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH24  ((BSW_COM_CH24_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH25)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH25  ((BSW_COM_CH25_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH26)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH26  ((BSW_COM_CH26_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH27)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH27  ((BSW_COM_CH27_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH28)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH28  ((BSW_COM_CH28_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH29)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH29  ((BSW_COM_CH29_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH30)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH30  ((BSW_COM_CH30_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_COM_FIRSTTXTIMEOUT_USE_CH31)
#define BSW_COM_FIRSTTXTIMEOUT_USE_CH31  ((BSW_COM_CH31_TX_TIMEOUTMODE == BSW_COM_TXTO_REQ_WAIT) ? BSW_USE : BSW_NOUSE)

#define BSW_COM_CH00_TXREQ_CONTINUE      BSW_COM_CFG_CH00_TXREQ_CONTINUE
#define BSW_COM_CH01_TXREQ_CONTINUE      BSW_COM_CFG_CH01_TXREQ_CONTINUE
#define BSW_COM_CH02_TXREQ_CONTINUE      BSW_COM_CFG_CH02_TXREQ_CONTINUE
#define BSW_COM_CH03_TXREQ_CONTINUE      BSW_COM_CFG_CH03_TXREQ_CONTINUE
#define BSW_COM_CH04_TXREQ_CONTINUE      BSW_COM_CFG_CH04_TXREQ_CONTINUE
#define BSW_COM_CH05_TXREQ_CONTINUE      BSW_COM_CFG_CH05_TXREQ_CONTINUE
#define BSW_COM_CH06_TXREQ_CONTINUE      BSW_COM_CFG_CH06_TXREQ_CONTINUE
#define BSW_COM_CH07_TXREQ_CONTINUE      BSW_COM_CFG_CH07_TXREQ_CONTINUE
#define BSW_COM_CH08_TXREQ_CONTINUE      BSW_COM_CFG_CH08_TXREQ_CONTINUE
#define BSW_COM_CH09_TXREQ_CONTINUE      BSW_COM_CFG_CH09_TXREQ_CONTINUE
#define BSW_COM_CH10_TXREQ_CONTINUE      BSW_COM_CFG_CH10_TXREQ_CONTINUE
#define BSW_COM_CH11_TXREQ_CONTINUE      BSW_COM_CFG_CH11_TXREQ_CONTINUE
#define BSW_COM_CH12_TXREQ_CONTINUE      BSW_COM_CFG_CH12_TXREQ_CONTINUE
#define BSW_COM_CH13_TXREQ_CONTINUE      BSW_COM_CFG_CH13_TXREQ_CONTINUE
#define BSW_COM_CH14_TXREQ_CONTINUE      BSW_COM_CFG_CH14_TXREQ_CONTINUE
#define BSW_COM_CH15_TXREQ_CONTINUE      BSW_COM_CFG_CH15_TXREQ_CONTINUE
#define BSW_COM_CH16_TXREQ_CONTINUE      BSW_COM_CFG_CH16_TXREQ_CONTINUE
#define BSW_COM_CH17_TXREQ_CONTINUE      BSW_COM_CFG_CH17_TXREQ_CONTINUE
#define BSW_COM_CH18_TXREQ_CONTINUE      BSW_COM_CFG_CH18_TXREQ_CONTINUE
#define BSW_COM_CH19_TXREQ_CONTINUE      BSW_COM_CFG_CH19_TXREQ_CONTINUE
#define BSW_COM_CH20_TXREQ_CONTINUE      BSW_COM_CFG_CH20_TXREQ_CONTINUE
#define BSW_COM_CH21_TXREQ_CONTINUE      BSW_COM_CFG_CH21_TXREQ_CONTINUE
#define BSW_COM_CH22_TXREQ_CONTINUE      BSW_COM_CFG_CH22_TXREQ_CONTINUE
#define BSW_COM_CH23_TXREQ_CONTINUE      BSW_COM_CFG_CH23_TXREQ_CONTINUE
#define BSW_COM_CH24_TXREQ_CONTINUE      BSW_COM_CFG_CH24_TXREQ_CONTINUE
#define BSW_COM_CH25_TXREQ_CONTINUE      BSW_COM_CFG_CH25_TXREQ_CONTINUE
#define BSW_COM_CH26_TXREQ_CONTINUE      BSW_COM_CFG_CH26_TXREQ_CONTINUE
#define BSW_COM_CH27_TXREQ_CONTINUE      BSW_COM_CFG_CH27_TXREQ_CONTINUE
#define BSW_COM_CH28_TXREQ_CONTINUE      BSW_COM_CFG_CH28_TXREQ_CONTINUE
#define BSW_COM_CH29_TXREQ_CONTINUE      BSW_COM_CFG_CH29_TXREQ_CONTINUE
#define BSW_COM_CH30_TXREQ_CONTINUE      BSW_COM_CFG_CH30_TXREQ_CONTINUE
#define BSW_COM_CH31_TXREQ_CONTINUE      BSW_COM_CFG_CH31_TXREQ_CONTINUE

#define BSW_COM_CH00_SENDNTIMESRTRG      BSW_COM_CFG_CH00_SENDNTIMESRTRG
#define BSW_COM_CH01_SENDNTIMESRTRG      BSW_COM_CFG_CH01_SENDNTIMESRTRG
#define BSW_COM_CH02_SENDNTIMESRTRG      BSW_COM_CFG_CH02_SENDNTIMESRTRG
#define BSW_COM_CH03_SENDNTIMESRTRG      BSW_COM_CFG_CH03_SENDNTIMESRTRG
#define BSW_COM_CH04_SENDNTIMESRTRG      BSW_COM_CFG_CH04_SENDNTIMESRTRG
#define BSW_COM_CH05_SENDNTIMESRTRG      BSW_COM_CFG_CH05_SENDNTIMESRTRG
#define BSW_COM_CH06_SENDNTIMESRTRG      BSW_COM_CFG_CH06_SENDNTIMESRTRG
#define BSW_COM_CH07_SENDNTIMESRTRG      BSW_COM_CFG_CH07_SENDNTIMESRTRG
#define BSW_COM_CH08_SENDNTIMESRTRG      BSW_COM_CFG_CH08_SENDNTIMESRTRG
#define BSW_COM_CH09_SENDNTIMESRTRG      BSW_COM_CFG_CH09_SENDNTIMESRTRG
#define BSW_COM_CH10_SENDNTIMESRTRG      BSW_COM_CFG_CH10_SENDNTIMESRTRG
#define BSW_COM_CH11_SENDNTIMESRTRG      BSW_COM_CFG_CH11_SENDNTIMESRTRG
#define BSW_COM_CH12_SENDNTIMESRTRG      BSW_COM_CFG_CH12_SENDNTIMESRTRG
#define BSW_COM_CH13_SENDNTIMESRTRG      BSW_COM_CFG_CH13_SENDNTIMESRTRG
#define BSW_COM_CH14_SENDNTIMESRTRG      BSW_COM_CFG_CH14_SENDNTIMESRTRG
#define BSW_COM_CH15_SENDNTIMESRTRG      BSW_COM_CFG_CH15_SENDNTIMESRTRG
#define BSW_COM_CH16_SENDNTIMESRTRG      BSW_COM_CFG_CH16_SENDNTIMESRTRG
#define BSW_COM_CH17_SENDNTIMESRTRG      BSW_COM_CFG_CH17_SENDNTIMESRTRG
#define BSW_COM_CH18_SENDNTIMESRTRG      BSW_COM_CFG_CH18_SENDNTIMESRTRG
#define BSW_COM_CH19_SENDNTIMESRTRG      BSW_COM_CFG_CH19_SENDNTIMESRTRG
#define BSW_COM_CH20_SENDNTIMESRTRG      BSW_COM_CFG_CH20_SENDNTIMESRTRG
#define BSW_COM_CH21_SENDNTIMESRTRG      BSW_COM_CFG_CH21_SENDNTIMESRTRG
#define BSW_COM_CH22_SENDNTIMESRTRG      BSW_COM_CFG_CH22_SENDNTIMESRTRG
#define BSW_COM_CH23_SENDNTIMESRTRG      BSW_COM_CFG_CH23_SENDNTIMESRTRG
#define BSW_COM_CH24_SENDNTIMESRTRG      BSW_COM_CFG_CH24_SENDNTIMESRTRG
#define BSW_COM_CH25_SENDNTIMESRTRG      BSW_COM_CFG_CH25_SENDNTIMESRTRG
#define BSW_COM_CH26_SENDNTIMESRTRG      BSW_COM_CFG_CH26_SENDNTIMESRTRG
#define BSW_COM_CH27_SENDNTIMESRTRG      BSW_COM_CFG_CH27_SENDNTIMESRTRG
#define BSW_COM_CH28_SENDNTIMESRTRG      BSW_COM_CFG_CH28_SENDNTIMESRTRG
#define BSW_COM_CH29_SENDNTIMESRTRG      BSW_COM_CFG_CH29_SENDNTIMESRTRG
#define BSW_COM_CH30_SENDNTIMESRTRG      BSW_COM_CFG_CH30_SENDNTIMESRTRG
#define BSW_COM_CH31_SENDNTIMESRTRG      BSW_COM_CFG_CH31_SENDNTIMESRTRG

#define BSW_COM_FUNC_PNCIPDU             (BSW_BSWM_CS_FUNC_PNCIPDU)

#define BSW_COM_TX_DISTIMBYMSG      (BSW_COM_CH00_TX_DISTIMBYMSG)
#define BSW_COM_CH00_TX_DISTIMBYMSG ((BSW_COM_CFG_CH00_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH01_TX_DISTIMBYMSG)
#define BSW_COM_CH01_TX_DISTIMBYMSG ((BSW_COM_CFG_CH01_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH02_TX_DISTIMBYMSG)
#define BSW_COM_CH02_TX_DISTIMBYMSG ((BSW_COM_CFG_CH02_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH03_TX_DISTIMBYMSG)
#define BSW_COM_CH03_TX_DISTIMBYMSG ((BSW_COM_CFG_CH03_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH04_TX_DISTIMBYMSG)
#define BSW_COM_CH04_TX_DISTIMBYMSG ((BSW_COM_CFG_CH04_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH05_TX_DISTIMBYMSG)
#define BSW_COM_CH05_TX_DISTIMBYMSG ((BSW_COM_CFG_CH05_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH06_TX_DISTIMBYMSG)
#define BSW_COM_CH06_TX_DISTIMBYMSG ((BSW_COM_CFG_CH06_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH07_TX_DISTIMBYMSG)
#define BSW_COM_CH07_TX_DISTIMBYMSG ((BSW_COM_CFG_CH07_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH08_TX_DISTIMBYMSG)
#define BSW_COM_CH08_TX_DISTIMBYMSG ((BSW_COM_CFG_CH08_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH09_TX_DISTIMBYMSG)
#define BSW_COM_CH09_TX_DISTIMBYMSG ((BSW_COM_CFG_CH09_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH10_TX_DISTIMBYMSG)
#define BSW_COM_CH10_TX_DISTIMBYMSG ((BSW_COM_CFG_CH10_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH11_TX_DISTIMBYMSG)
#define BSW_COM_CH11_TX_DISTIMBYMSG ((BSW_COM_CFG_CH11_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH12_TX_DISTIMBYMSG)
#define BSW_COM_CH12_TX_DISTIMBYMSG ((BSW_COM_CFG_CH12_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH13_TX_DISTIMBYMSG)
#define BSW_COM_CH13_TX_DISTIMBYMSG ((BSW_COM_CFG_CH13_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH14_TX_DISTIMBYMSG)
#define BSW_COM_CH14_TX_DISTIMBYMSG ((BSW_COM_CFG_CH14_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH15_TX_DISTIMBYMSG)
#define BSW_COM_CH15_TX_DISTIMBYMSG ((BSW_COM_CFG_CH15_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH16_TX_DISTIMBYMSG)
#define BSW_COM_CH16_TX_DISTIMBYMSG ((BSW_COM_CFG_CH16_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH17_TX_DISTIMBYMSG)
#define BSW_COM_CH17_TX_DISTIMBYMSG ((BSW_COM_CFG_CH17_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH18_TX_DISTIMBYMSG)
#define BSW_COM_CH18_TX_DISTIMBYMSG ((BSW_COM_CFG_CH18_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH19_TX_DISTIMBYMSG)
#define BSW_COM_CH19_TX_DISTIMBYMSG ((BSW_COM_CFG_CH19_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH20_TX_DISTIMBYMSG)
#define BSW_COM_CH20_TX_DISTIMBYMSG ((BSW_COM_CFG_CH20_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH21_TX_DISTIMBYMSG)
#define BSW_COM_CH21_TX_DISTIMBYMSG ((BSW_COM_CFG_CH21_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH22_TX_DISTIMBYMSG)
#define BSW_COM_CH22_TX_DISTIMBYMSG ((BSW_COM_CFG_CH22_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH23_TX_DISTIMBYMSG)
#define BSW_COM_CH23_TX_DISTIMBYMSG ((BSW_COM_CFG_CH23_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH24_TX_DISTIMBYMSG)
#define BSW_COM_CH24_TX_DISTIMBYMSG ((BSW_COM_CFG_CH24_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH25_TX_DISTIMBYMSG)
#define BSW_COM_CH25_TX_DISTIMBYMSG ((BSW_COM_CFG_CH25_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH26_TX_DISTIMBYMSG)
#define BSW_COM_CH26_TX_DISTIMBYMSG ((BSW_COM_CFG_CH26_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH27_TX_DISTIMBYMSG)
#define BSW_COM_CH27_TX_DISTIMBYMSG ((BSW_COM_CFG_CH27_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH28_TX_DISTIMBYMSG)
#define BSW_COM_CH28_TX_DISTIMBYMSG ((BSW_COM_CFG_CH28_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH29_TX_DISTIMBYMSG)
#define BSW_COM_CH29_TX_DISTIMBYMSG ((BSW_COM_CFG_CH29_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH30_TX_DISTIMBYMSG)
#define BSW_COM_CH30_TX_DISTIMBYMSG ((BSW_COM_CFG_CH30_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_COM_CH31_TX_DISTIMBYMSG)
#define BSW_COM_CH31_TX_DISTIMBYMSG ((BSW_COM_CFG_CH31_TX_DISTIMBYMSG == BSW_USE) ? BSW_USE : BSW_NOUSE)

#define BSW_COM_TXCLRSTOPTOUT      (BSW_COM_CH00_TXCLRSTOPTOUT)
#define BSW_COM_CH00_TXCLRSTOPTOUT ((BSW_COM_CFG_CH00_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH01_TXCLRSTOPTOUT)
#define BSW_COM_CH01_TXCLRSTOPTOUT ((BSW_COM_CFG_CH01_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH02_TXCLRSTOPTOUT)
#define BSW_COM_CH02_TXCLRSTOPTOUT ((BSW_COM_CFG_CH02_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH03_TXCLRSTOPTOUT)
#define BSW_COM_CH03_TXCLRSTOPTOUT ((BSW_COM_CFG_CH03_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH04_TXCLRSTOPTOUT)
#define BSW_COM_CH04_TXCLRSTOPTOUT ((BSW_COM_CFG_CH04_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH05_TXCLRSTOPTOUT)
#define BSW_COM_CH05_TXCLRSTOPTOUT ((BSW_COM_CFG_CH05_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH06_TXCLRSTOPTOUT)
#define BSW_COM_CH06_TXCLRSTOPTOUT ((BSW_COM_CFG_CH06_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH07_TXCLRSTOPTOUT)
#define BSW_COM_CH07_TXCLRSTOPTOUT ((BSW_COM_CFG_CH07_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH08_TXCLRSTOPTOUT)
#define BSW_COM_CH08_TXCLRSTOPTOUT ((BSW_COM_CFG_CH08_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH09_TXCLRSTOPTOUT)
#define BSW_COM_CH09_TXCLRSTOPTOUT ((BSW_COM_CFG_CH09_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH10_TXCLRSTOPTOUT)
#define BSW_COM_CH10_TXCLRSTOPTOUT ((BSW_COM_CFG_CH10_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH11_TXCLRSTOPTOUT)
#define BSW_COM_CH11_TXCLRSTOPTOUT ((BSW_COM_CFG_CH11_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH12_TXCLRSTOPTOUT)
#define BSW_COM_CH12_TXCLRSTOPTOUT ((BSW_COM_CFG_CH12_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH13_TXCLRSTOPTOUT)
#define BSW_COM_CH13_TXCLRSTOPTOUT ((BSW_COM_CFG_CH13_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH14_TXCLRSTOPTOUT)
#define BSW_COM_CH14_TXCLRSTOPTOUT ((BSW_COM_CFG_CH14_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH15_TXCLRSTOPTOUT)
#define BSW_COM_CH15_TXCLRSTOPTOUT ((BSW_COM_CFG_CH15_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH16_TXCLRSTOPTOUT)
#define BSW_COM_CH16_TXCLRSTOPTOUT ((BSW_COM_CFG_CH16_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH17_TXCLRSTOPTOUT)
#define BSW_COM_CH17_TXCLRSTOPTOUT ((BSW_COM_CFG_CH17_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH18_TXCLRSTOPTOUT)
#define BSW_COM_CH18_TXCLRSTOPTOUT ((BSW_COM_CFG_CH18_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH19_TXCLRSTOPTOUT)
#define BSW_COM_CH19_TXCLRSTOPTOUT ((BSW_COM_CFG_CH19_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH20_TXCLRSTOPTOUT)
#define BSW_COM_CH20_TXCLRSTOPTOUT ((BSW_COM_CFG_CH20_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH21_TXCLRSTOPTOUT)
#define BSW_COM_CH21_TXCLRSTOPTOUT ((BSW_COM_CFG_CH21_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH22_TXCLRSTOPTOUT)
#define BSW_COM_CH22_TXCLRSTOPTOUT ((BSW_COM_CFG_CH22_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH23_TXCLRSTOPTOUT)
#define BSW_COM_CH23_TXCLRSTOPTOUT ((BSW_COM_CFG_CH23_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH24_TXCLRSTOPTOUT)
#define BSW_COM_CH24_TXCLRSTOPTOUT ((BSW_COM_CFG_CH24_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH25_TXCLRSTOPTOUT)
#define BSW_COM_CH25_TXCLRSTOPTOUT ((BSW_COM_CFG_CH25_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH26_TXCLRSTOPTOUT)
#define BSW_COM_CH26_TXCLRSTOPTOUT ((BSW_COM_CFG_CH26_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH27_TXCLRSTOPTOUT)
#define BSW_COM_CH27_TXCLRSTOPTOUT ((BSW_COM_CFG_CH27_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH28_TXCLRSTOPTOUT)
#define BSW_COM_CH28_TXCLRSTOPTOUT ((BSW_COM_CFG_CH28_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH29_TXCLRSTOPTOUT)
#define BSW_COM_CH29_TXCLRSTOPTOUT ((BSW_COM_CFG_CH29_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH30_TXCLRSTOPTOUT)
#define BSW_COM_CH30_TXCLRSTOPTOUT ((BSW_COM_CFG_CH30_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_COM_CH31_TXCLRSTOPTOUT)
#define BSW_COM_CH31_TXCLRSTOPTOUT ((BSW_COM_CFG_CH31_TXCLRSTOPTOUT == BSW_USE) ? BSW_USE : BSW_NOUSE)

/*--------------------------------------------------------------------------*/
/* Types                                                                    */
/*--------------------------------------------------------------------------*/


/*--------------------------------------------------------------------------*/
/* Function Prototypes                                                      */
/*--------------------------------------------------------------------------*/


/*--------------------------------------------------------------------------*/
/* Data                                                                     */
/*--------------------------------------------------------------------------*/


/*--------------------------------------------------------------------------*/
/* Constants                                                                */
/*--------------------------------------------------------------------------*/


#endif  /* BSW_COM_CONFIG_H */

/****************************************************************************/
/* History                                                                  */
/*  Version         :Date                                                   */
/*  v1-0-0          :2017/08/28                                             */
/*  v1-1-0          :2018/09/14                                             */
/*  v1-2-0          :2019/09/27                                             */
/*  v2-0-0          :2021/08/06                                             */
/*  v2-1-0          :2022/11/18                                             */
/*  v2-2-0          :2023/05/23                                             */
/*  v3-0-0          :2024/10/10                                             */
/****************************************************************************/

/**** End of File ***********************************************************/
