/* bsw_vdat_config_h_v3-0-0                                                 */
/****************************************************************************/
/* Protected                                                                */
/* Copyright DENSO CORPORATION                                              */
/****************************************************************************/

/****************************************************************************/
/* Object Name  | BSW/VDAT/CONFIG/HEADER                                    */
/*--------------------------------------------------------------------------*/
/* Notes        |                                                           */
/****************************************************************************/

#ifndef BSW_VDAT_CONFIG_H
#define BSW_VDAT_CONFIG_H

/*--------------------------------------------------------------------------*/
/* Macros                                                                   */
/*--------------------------------------------------------------------------*/
/* Ipc USE / NOUSE */
#define BSW_VDAT_IPC_FUNC           BSW_VDAT_IPC_FUNC_00
#define BSW_VDAT_IPC_FUNC_00        ( (BSW_VDAT_CFG_COM_FUNC00 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_01 )
#define BSW_VDAT_IPC_FUNC_01        ( (BSW_VDAT_CFG_COM_FUNC01 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_02 )
#define BSW_VDAT_IPC_FUNC_02        ( (BSW_VDAT_CFG_COM_FUNC02 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_03 )
#define BSW_VDAT_IPC_FUNC_03        ( (BSW_VDAT_CFG_COM_FUNC03 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_04 )
#define BSW_VDAT_IPC_FUNC_04        ( (BSW_VDAT_CFG_COM_FUNC04 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_05 )
#define BSW_VDAT_IPC_FUNC_05        ( (BSW_VDAT_CFG_COM_FUNC05 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_06 )
#define BSW_VDAT_IPC_FUNC_06        ( (BSW_VDAT_CFG_COM_FUNC06 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_07 )
#define BSW_VDAT_IPC_FUNC_07        ( (BSW_VDAT_CFG_COM_FUNC07 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_08 )
#define BSW_VDAT_IPC_FUNC_08        ( (BSW_VDAT_CFG_COM_FUNC08 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_09 )
#define BSW_VDAT_IPC_FUNC_09        ( (BSW_VDAT_CFG_COM_FUNC09 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_10 )
#define BSW_VDAT_IPC_FUNC_10        ( (BSW_VDAT_CFG_COM_FUNC10 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_11 )
#define BSW_VDAT_IPC_FUNC_11        ( (BSW_VDAT_CFG_COM_FUNC11 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_12 )
#define BSW_VDAT_IPC_FUNC_12        ( (BSW_VDAT_CFG_COM_FUNC12 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_13 )
#define BSW_VDAT_IPC_FUNC_13        ( (BSW_VDAT_CFG_COM_FUNC13 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_14 )
#define BSW_VDAT_IPC_FUNC_14        ( (BSW_VDAT_CFG_COM_FUNC14 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_15 )
#define BSW_VDAT_IPC_FUNC_15        ( (BSW_VDAT_CFG_COM_FUNC15 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_16 )
#define BSW_VDAT_IPC_FUNC_16        ( (BSW_VDAT_CFG_COM_FUNC16 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_17 )
#define BSW_VDAT_IPC_FUNC_17        ( (BSW_VDAT_CFG_COM_FUNC17 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_18 )
#define BSW_VDAT_IPC_FUNC_18        ( (BSW_VDAT_CFG_COM_FUNC18 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_19 )
#define BSW_VDAT_IPC_FUNC_19        ( (BSW_VDAT_CFG_COM_FUNC19 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_20 )
#define BSW_VDAT_IPC_FUNC_20        ( (BSW_VDAT_CFG_COM_FUNC20 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_21 )
#define BSW_VDAT_IPC_FUNC_21        ( (BSW_VDAT_CFG_COM_FUNC21 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_22 )
#define BSW_VDAT_IPC_FUNC_22        ( (BSW_VDAT_CFG_COM_FUNC22 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_23 )
#define BSW_VDAT_IPC_FUNC_23        ( (BSW_VDAT_CFG_COM_FUNC23 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_24 )
#define BSW_VDAT_IPC_FUNC_24        ( (BSW_VDAT_CFG_COM_FUNC24 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_25 )
#define BSW_VDAT_IPC_FUNC_25        ( (BSW_VDAT_CFG_COM_FUNC25 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_26 )
#define BSW_VDAT_IPC_FUNC_26        ( (BSW_VDAT_CFG_COM_FUNC26 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_27 )
#define BSW_VDAT_IPC_FUNC_27        ( (BSW_VDAT_CFG_COM_FUNC27 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_28 )
#define BSW_VDAT_IPC_FUNC_28        ( (BSW_VDAT_CFG_COM_FUNC28 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_29 )
#define BSW_VDAT_IPC_FUNC_29        ( (BSW_VDAT_CFG_COM_FUNC29 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_30 )
#define BSW_VDAT_IPC_FUNC_30        ( (BSW_VDAT_CFG_COM_FUNC30 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_31 )
#define BSW_VDAT_IPC_FUNC_31        ( (BSW_VDAT_CFG_COM_FUNC31 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_32 )
#define BSW_VDAT_IPC_FUNC_32        ( (BSW_VDAT_CFG_COM_FUNC32 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_33 )
#define BSW_VDAT_IPC_FUNC_33        ( (BSW_VDAT_CFG_COM_FUNC33 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_34 )
#define BSW_VDAT_IPC_FUNC_34        ( (BSW_VDAT_CFG_COM_FUNC34 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_35 )
#define BSW_VDAT_IPC_FUNC_35        ( (BSW_VDAT_CFG_COM_FUNC35 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_36 )
#define BSW_VDAT_IPC_FUNC_36        ( (BSW_VDAT_CFG_COM_FUNC36 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_37 )
#define BSW_VDAT_IPC_FUNC_37        ( (BSW_VDAT_CFG_COM_FUNC37 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_38 )
#define BSW_VDAT_IPC_FUNC_38        ( (BSW_VDAT_CFG_COM_FUNC38 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_39 )
#define BSW_VDAT_IPC_FUNC_39        ( (BSW_VDAT_CFG_COM_FUNC39 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_40 )
#define BSW_VDAT_IPC_FUNC_40        ( (BSW_VDAT_CFG_COM_FUNC40 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_41 )
#define BSW_VDAT_IPC_FUNC_41        ( (BSW_VDAT_CFG_COM_FUNC41 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_42 )
#define BSW_VDAT_IPC_FUNC_42        ( (BSW_VDAT_CFG_COM_FUNC42 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_43 )
#define BSW_VDAT_IPC_FUNC_43        ( (BSW_VDAT_CFG_COM_FUNC43 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_44 )
#define BSW_VDAT_IPC_FUNC_44        ( (BSW_VDAT_CFG_COM_FUNC44 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_45 )
#define BSW_VDAT_IPC_FUNC_45        ( (BSW_VDAT_CFG_COM_FUNC45 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_46 )
#define BSW_VDAT_IPC_FUNC_46        ( (BSW_VDAT_CFG_COM_FUNC46 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_47 )
#define BSW_VDAT_IPC_FUNC_47        ( (BSW_VDAT_CFG_COM_FUNC47 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_48 )
#define BSW_VDAT_IPC_FUNC_48        ( (BSW_VDAT_CFG_COM_FUNC48 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_49 )
#define BSW_VDAT_IPC_FUNC_49        ( (BSW_VDAT_CFG_COM_FUNC49 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_50 )
#define BSW_VDAT_IPC_FUNC_50        ( (BSW_VDAT_CFG_COM_FUNC50 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_51 )
#define BSW_VDAT_IPC_FUNC_51        ( (BSW_VDAT_CFG_COM_FUNC51 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_52 )
#define BSW_VDAT_IPC_FUNC_52        ( (BSW_VDAT_CFG_COM_FUNC52 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_53 )
#define BSW_VDAT_IPC_FUNC_53        ( (BSW_VDAT_CFG_COM_FUNC53 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_54 )
#define BSW_VDAT_IPC_FUNC_54        ( (BSW_VDAT_CFG_COM_FUNC54 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_55 )
#define BSW_VDAT_IPC_FUNC_55        ( (BSW_VDAT_CFG_COM_FUNC55 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_56 )
#define BSW_VDAT_IPC_FUNC_56        ( (BSW_VDAT_CFG_COM_FUNC56 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_57 )
#define BSW_VDAT_IPC_FUNC_57        ( (BSW_VDAT_CFG_COM_FUNC57 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_58 )
#define BSW_VDAT_IPC_FUNC_58        ( (BSW_VDAT_CFG_COM_FUNC58 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_59 )
#define BSW_VDAT_IPC_FUNC_59        ( (BSW_VDAT_CFG_COM_FUNC59 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_60 )
#define BSW_VDAT_IPC_FUNC_60        ( (BSW_VDAT_CFG_COM_FUNC60 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_61 )
#define BSW_VDAT_IPC_FUNC_61        ( (BSW_VDAT_CFG_COM_FUNC61 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_62 )
#define BSW_VDAT_IPC_FUNC_62        ( (BSW_VDAT_CFG_COM_FUNC62 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_IPC_FUNC_63 )
#define BSW_VDAT_IPC_FUNC_63        ( (BSW_VDAT_CFG_COM_FUNC63 == BSW_VDAT_KIND_IPC) ? BSW_VDAT_USE : BSW_VDAT_NOUSE )

/* VCC USE / NOUSE */
#define BSW_VDAT_VCC_FUNC           BSW_VDAT_VCC_FUNC_00
#define BSW_VDAT_VCC_FUNC_00        ( (BSW_VDAT_CFG_COM_FUNC00 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_01 )
#define BSW_VDAT_VCC_FUNC_01        ( (BSW_VDAT_CFG_COM_FUNC01 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_02 )
#define BSW_VDAT_VCC_FUNC_02        ( (BSW_VDAT_CFG_COM_FUNC02 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_03 )
#define BSW_VDAT_VCC_FUNC_03        ( (BSW_VDAT_CFG_COM_FUNC03 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_04 )
#define BSW_VDAT_VCC_FUNC_04        ( (BSW_VDAT_CFG_COM_FUNC04 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_05 )
#define BSW_VDAT_VCC_FUNC_05        ( (BSW_VDAT_CFG_COM_FUNC05 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_06 )
#define BSW_VDAT_VCC_FUNC_06        ( (BSW_VDAT_CFG_COM_FUNC06 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_07 )
#define BSW_VDAT_VCC_FUNC_07        ( (BSW_VDAT_CFG_COM_FUNC07 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_08 )
#define BSW_VDAT_VCC_FUNC_08        ( (BSW_VDAT_CFG_COM_FUNC08 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_09 )
#define BSW_VDAT_VCC_FUNC_09        ( (BSW_VDAT_CFG_COM_FUNC09 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_10 )
#define BSW_VDAT_VCC_FUNC_10        ( (BSW_VDAT_CFG_COM_FUNC10 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_11 )
#define BSW_VDAT_VCC_FUNC_11        ( (BSW_VDAT_CFG_COM_FUNC11 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_12 )
#define BSW_VDAT_VCC_FUNC_12        ( (BSW_VDAT_CFG_COM_FUNC12 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_13 )
#define BSW_VDAT_VCC_FUNC_13        ( (BSW_VDAT_CFG_COM_FUNC13 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_14 )
#define BSW_VDAT_VCC_FUNC_14        ( (BSW_VDAT_CFG_COM_FUNC14 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_15 )
#define BSW_VDAT_VCC_FUNC_15        ( (BSW_VDAT_CFG_COM_FUNC15 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_16 )
#define BSW_VDAT_VCC_FUNC_16        ( (BSW_VDAT_CFG_COM_FUNC16 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_17 )
#define BSW_VDAT_VCC_FUNC_17        ( (BSW_VDAT_CFG_COM_FUNC17 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_18 )
#define BSW_VDAT_VCC_FUNC_18        ( (BSW_VDAT_CFG_COM_FUNC18 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_19 )
#define BSW_VDAT_VCC_FUNC_19        ( (BSW_VDAT_CFG_COM_FUNC19 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_20 )
#define BSW_VDAT_VCC_FUNC_20        ( (BSW_VDAT_CFG_COM_FUNC20 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_21 )
#define BSW_VDAT_VCC_FUNC_21        ( (BSW_VDAT_CFG_COM_FUNC21 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_22 )
#define BSW_VDAT_VCC_FUNC_22        ( (BSW_VDAT_CFG_COM_FUNC22 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_23 )
#define BSW_VDAT_VCC_FUNC_23        ( (BSW_VDAT_CFG_COM_FUNC23 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_24 )
#define BSW_VDAT_VCC_FUNC_24        ( (BSW_VDAT_CFG_COM_FUNC24 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_25 )
#define BSW_VDAT_VCC_FUNC_25        ( (BSW_VDAT_CFG_COM_FUNC25 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_26 )
#define BSW_VDAT_VCC_FUNC_26        ( (BSW_VDAT_CFG_COM_FUNC26 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_27 )
#define BSW_VDAT_VCC_FUNC_27        ( (BSW_VDAT_CFG_COM_FUNC27 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_28 )
#define BSW_VDAT_VCC_FUNC_28        ( (BSW_VDAT_CFG_COM_FUNC28 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_29 )
#define BSW_VDAT_VCC_FUNC_29        ( (BSW_VDAT_CFG_COM_FUNC29 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_30 )
#define BSW_VDAT_VCC_FUNC_30        ( (BSW_VDAT_CFG_COM_FUNC30 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_31 )
#define BSW_VDAT_VCC_FUNC_31        ( (BSW_VDAT_CFG_COM_FUNC31 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_32 )
#define BSW_VDAT_VCC_FUNC_32        ( (BSW_VDAT_CFG_COM_FUNC32 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_33 )
#define BSW_VDAT_VCC_FUNC_33        ( (BSW_VDAT_CFG_COM_FUNC33 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_34 )
#define BSW_VDAT_VCC_FUNC_34        ( (BSW_VDAT_CFG_COM_FUNC34 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_35 )
#define BSW_VDAT_VCC_FUNC_35        ( (BSW_VDAT_CFG_COM_FUNC35 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_36 )
#define BSW_VDAT_VCC_FUNC_36        ( (BSW_VDAT_CFG_COM_FUNC36 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_37 )
#define BSW_VDAT_VCC_FUNC_37        ( (BSW_VDAT_CFG_COM_FUNC37 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_38 )
#define BSW_VDAT_VCC_FUNC_38        ( (BSW_VDAT_CFG_COM_FUNC38 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_39 )
#define BSW_VDAT_VCC_FUNC_39        ( (BSW_VDAT_CFG_COM_FUNC39 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_40 )
#define BSW_VDAT_VCC_FUNC_40        ( (BSW_VDAT_CFG_COM_FUNC40 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_41 )
#define BSW_VDAT_VCC_FUNC_41        ( (BSW_VDAT_CFG_COM_FUNC41 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_42 )
#define BSW_VDAT_VCC_FUNC_42        ( (BSW_VDAT_CFG_COM_FUNC42 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_43 )
#define BSW_VDAT_VCC_FUNC_43        ( (BSW_VDAT_CFG_COM_FUNC43 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_44 )
#define BSW_VDAT_VCC_FUNC_44        ( (BSW_VDAT_CFG_COM_FUNC44 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_45 )
#define BSW_VDAT_VCC_FUNC_45        ( (BSW_VDAT_CFG_COM_FUNC45 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_46 )
#define BSW_VDAT_VCC_FUNC_46        ( (BSW_VDAT_CFG_COM_FUNC46 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_47 )
#define BSW_VDAT_VCC_FUNC_47        ( (BSW_VDAT_CFG_COM_FUNC47 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_48 )
#define BSW_VDAT_VCC_FUNC_48        ( (BSW_VDAT_CFG_COM_FUNC48 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_49 )
#define BSW_VDAT_VCC_FUNC_49        ( (BSW_VDAT_CFG_COM_FUNC49 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_50 )
#define BSW_VDAT_VCC_FUNC_50        ( (BSW_VDAT_CFG_COM_FUNC50 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_51 )
#define BSW_VDAT_VCC_FUNC_51        ( (BSW_VDAT_CFG_COM_FUNC51 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_52 )
#define BSW_VDAT_VCC_FUNC_52        ( (BSW_VDAT_CFG_COM_FUNC52 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_53 )
#define BSW_VDAT_VCC_FUNC_53        ( (BSW_VDAT_CFG_COM_FUNC53 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_54 )
#define BSW_VDAT_VCC_FUNC_54        ( (BSW_VDAT_CFG_COM_FUNC54 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_55 )
#define BSW_VDAT_VCC_FUNC_55        ( (BSW_VDAT_CFG_COM_FUNC55 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_56 )
#define BSW_VDAT_VCC_FUNC_56        ( (BSW_VDAT_CFG_COM_FUNC56 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_57 )
#define BSW_VDAT_VCC_FUNC_57        ( (BSW_VDAT_CFG_COM_FUNC57 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_58 )
#define BSW_VDAT_VCC_FUNC_58        ( (BSW_VDAT_CFG_COM_FUNC58 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_59 )
#define BSW_VDAT_VCC_FUNC_59        ( (BSW_VDAT_CFG_COM_FUNC59 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_60 )
#define BSW_VDAT_VCC_FUNC_60        ( (BSW_VDAT_CFG_COM_FUNC60 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_61 )
#define BSW_VDAT_VCC_FUNC_61        ( (BSW_VDAT_CFG_COM_FUNC61 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_62 )
#define BSW_VDAT_VCC_FUNC_62        ( (BSW_VDAT_CFG_COM_FUNC62 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_VCC_FUNC_63 )
#define BSW_VDAT_VCC_FUNC_63        ( (BSW_VDAT_CFG_COM_FUNC63 == BSW_VDAT_KIND_VCC) ? BSW_VDAT_USE : BSW_VDAT_NOUSE )

/*--------------------------------------------------------------------------*/
/* Types                                                                    */
/*--------------------------------------------------------------------------*/

/*--------------------------------------------------------------------------*/
/* Function Prototypes                                                      */
/*--------------------------------------------------------------------------*/

/*--------------------------------------------------------------------------*/
/* Data                                                                     */
/*--------------------------------------------------------------------------*/

/*--------------------------------------------------------------------------*/
/* Constants                                                                */
/*--------------------------------------------------------------------------*/

#endif  /* BSW_VDAT_CONFIG_H */

/****************************************************************************/
/* History                                                                  */
/*  Version         :Date                                                   */
/*  v2-0-0          :2021/11/15                                             */
/*  v2-1-0          :2023/03/13                                             */
/*  v3-0-0          :2024/08/30                                             */
/****************************************************************************/

/**** End of File ***********************************************************/
