# coding: utf-8

################################################################################
# [IN_FILE]                                                                    #
#------------------------------------------------------------------------------#
#   [IN]  SrecFile | Motorola S-record(S3) ファイル                            #
################################################################################
[IN_FILE]
SrecFile  = W:\src\DevRRPG\Runfiles\host.run
StartFile = False
EndFile   = False


################################################################################
# [PLAINTEXT]                                                                  #
#------------------------------------------------------------------------------#
#   [OUT] PlainRunFile        | Motorola S-record(S3) 結合ファイル             #
################################################################################
[PLAINTEXT]
PlainRunFile        = W:\src\DevRRPG\Tool\CombineMOT\APL.run

