/* comm_cfg_h_v3-0-0                                                        */
/****************************************************************************/
/* Protected                                                                */
/* Copyright DENSO CORPORATION                                              */
/****************************************************************************/

/****************************************************************************/
/* Object Name  | COMM/CFG/HEADER                                           */
/*--------------------------------------------------------------------------*/
/* Notes        |                                                           */
/****************************************************************************/
#ifndef BSW_COMM_CFG_H
#define BSW_COMM_CFG_H

/*--------------------------------------------------------------------------*/
/* Macros                                                                   */
/*--------------------------------------------------------------------------*/
/* Number Of Channel */
#define BSW_COMM_CFG_CHNUM             (1U)

/* Bus Type */
#define BSW_COMM_CFG_BUS_TYPE_0        (BSW_COMM_BUS_TYPE_CAN)
#define BSW_COMM_CFG_BUS_TYPE_1        (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_2        (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_3        (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_4        (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_5        (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_6        (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_7        (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_8        (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_9        (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_10       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_11       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_12       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_13       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_14       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_15       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_16       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_17       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_18       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_19       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_20       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_21       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_22       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_23       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_24       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_25       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_26       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_27       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_28       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_29       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_30       (BSW_COMM_BUS_TYPE_INVALID)
#define BSW_COMM_CFG_BUS_TYPE_31       (BSW_COMM_BUS_TYPE_INVALID)

/* Channel Attribute */
#define BSW_COMM_CFG_CH_ATTRIBUTE_0    (BSW_COMM_CH_ATTRBT_VIRTUAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_1    (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_2    (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_3    (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_4    (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_5    (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_6    (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_7    (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_8    (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_9    (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_10   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_11   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_12   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_13   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_14   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_15   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_16   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_17   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_18   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_19   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_20   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_21   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_22   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_23   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_24   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_25   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_26   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_27   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_28   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_29   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_30   (BSW_COMM_CH_ATTRBT_PHYSICAL)
#define BSW_COMM_CFG_CH_ATTRIBUTE_31   (BSW_COMM_CH_ATTRBT_PHYSICAL)

/* Communication Activated User Awake Factor */
#define BSW_COMM_CFG_COM_CH_USERAWK_0  (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_1  (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_2  (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_3  (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_4  (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_5  (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_6  (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_7  (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_8  (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_9  (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_10 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_11 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_12 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_13 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_14 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_15 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_16 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_17 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_18 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_19 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_20 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_21 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_22 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_23 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_24 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_25 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_26 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_27 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_28 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_29 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_30 (BSW_COMM_USERAWAKE_NONE)
#define BSW_COMM_CFG_COM_CH_USERAWK_31 (BSW_COMM_USERAWAKE_NONE)

/* Support Of Partial Networking */
#define BSW_COMM_CFG_PNC                    (BSW_NOUSE)

/* Interface Type For Partial Networking */
#define BSW_COMM_CFG_PNC_IF_TYPE            (BSW_COMM_PNC_IF_TYPE_AR_COMPLIANCE)

/* Number Of PNC */
#define BSW_COMM_CFG_CH_PNCNUM_0            (0U)
#define BSW_COMM_CFG_CH_PNCNUM_1            (0U)
#define BSW_COMM_CFG_CH_PNCNUM_2            (0U)
#define BSW_COMM_CFG_CH_PNCNUM_3            (0U)
#define BSW_COMM_CFG_CH_PNCNUM_4            (0U)
#define BSW_COMM_CFG_CH_PNCNUM_5            (0U)
#define BSW_COMM_CFG_CH_PNCNUM_6            (0U)
#define BSW_COMM_CFG_CH_PNCNUM_7            (0U)
#define BSW_COMM_CFG_CH_PNCNUM_8            (0U)
#define BSW_COMM_CFG_CH_PNCNUM_9            (0U)
#define BSW_COMM_CFG_CH_PNCNUM_10           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_11           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_12           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_13           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_14           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_15           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_16           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_17           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_18           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_19           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_20           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_21           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_22           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_23           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_24           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_25           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_26           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_27           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_28           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_29           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_30           (0U)
#define BSW_COMM_CFG_CH_PNCNUM_31           (0U)

/* EIRA Reset Time */
#define BSW_COMM_CFG_PNC_RESETTIME_0        (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_1        (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_2        (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_3        (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_4        (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_5        (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_6        (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_7        (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_8        (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_9        (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_10       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_11       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_12       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_13       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_14       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_15       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_16       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_17       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_18       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_19       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_20       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_21       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_22       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_23       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_24       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_25       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_26       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_27       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_28       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_29       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_30       (0U)
#define BSW_COMM_CFG_PNC_RESETTIME_31       (0U)

/* Communication Activated Factor From PNC */
#define BSW_COMM_CFG_PNC_PER_CH_0UP         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_0LO         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_1UP         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_1LO         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_2UP         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_2LO         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_3UP         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_3LO         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_4UP         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_4LO         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_5UP         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_5LO         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_6UP         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_6LO         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_7UP         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_7LO         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_8UP         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_8LO         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_9UP         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_9LO         (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_10UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_10LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_11UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_11LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_12UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_12LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_13UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_13LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_14UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_14LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_15UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_15LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_16UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_16LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_17UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_17LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_18UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_18LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_19UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_19LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_20UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_20LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_21UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_21LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_22UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_22LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_23UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_23LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_24UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_24LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_25UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_25LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_26UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_26LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_27UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_27LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_28UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_28LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_29UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_29LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_30UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_30LO        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_31UP        (BSW_COMM_PNCAWAKE_NONE)
#define BSW_COMM_CFG_PNC_PER_CH_31LO        (BSW_COMM_PNCAWAKE_NONE)

/* Wait Time In BSW_COMM_PNC_PREPARE_SLEEP */
#define BSW_COMM_CFG_PNC_PREPSLPTIME_0      (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_1      (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_2      (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_3      (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_4      (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_5      (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_6      (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_7      (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_8      (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_9      (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_10     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_11     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_12     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_13     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_14     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_15     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_16     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_17     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_18     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_19     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_20     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_21     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_22     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_23     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_24     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_25     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_26     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_27     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_28     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_29     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_30     (0U)
#define BSW_COMM_CFG_PNC_PREPSLPTIME_31     (0U)

/* Wakeup Request by PNC Awake USE/NOUSE */
#define BSW_COMM_CFG_PNC_WAKEUPREQ_0        (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_1        (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_2        (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_3        (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_4        (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_5        (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_6        (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_7        (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_8        (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_9        (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_10       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_11       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_12       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_13       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_14       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_15       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_16       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_17       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_18       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_19       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_20       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_21       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_22       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_23       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_24       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_25       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_26       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_27       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_28       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_29       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_30       (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_WAKEUPREQ_31       (BSW_NOUSE)

/* Synchronous Wakeup USE/NOUSE */
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_0      (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_1      (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_2      (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_3      (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_4      (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_5      (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_6      (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_7      (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_8      (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_9      (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_10     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_11     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_12     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_13     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_14     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_15     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_16     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_17     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_18     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_19     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_20     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_21     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_22     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_23     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_24     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_25     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_26     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_27     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_28     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_29     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_30     (BSW_NOUSE)
#define BSW_COMM_CFG_PNC_SYNC_WAKEUP_31     (BSW_NOUSE)

/* Wakeup Request by Channel Awake USE/NOUSE */
#define BSW_COMM_CFG_CH_WAKEUPREQ_0         (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_1         (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_2         (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_3         (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_4         (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_5         (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_6         (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_7         (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_8         (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_9         (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_10        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_11        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_12        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_13        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_14        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_15        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_16        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_17        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_18        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_19        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_20        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_21        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_22        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_23        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_24        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_25        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_26        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_27        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_28        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_29        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_30        (BSW_NOUSE)
#define BSW_COMM_CFG_CH_WAKEUPREQ_31        (BSW_NOUSE)

/* Wakeup Request by Passive wakeup USE/NOUSE */
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_0      (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_1      (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_2      (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_3      (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_4      (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_5      (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_6      (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_7      (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_8      (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_9      (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_10     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_11     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_12     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_13     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_14     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_15     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_16     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_17     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_18     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_19     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_20     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_21     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_22     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_23     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_24     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_25     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_26     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_27     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_28     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_29     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_30     (BSW_NOUSE)
#define BSW_COMM_CFG_CH_PSVWAKEUPREQ_31     (BSW_NOUSE)


/* PNC Awake power supply USE/NOUSE */
#define BSW_COMM_CFG_PNC_AWAKEPW            (BSW_NOUSE)

/* Network management function action type */
#define BSW_COMM_CFG_NM_ACT_TYPE_0          (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_1          (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_2          (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_3          (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_4          (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_5          (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_6          (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_7          (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_8          (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_9          (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_10         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_11         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_12         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_13         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_14         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_15         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_16         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_17         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_18         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_19         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_20         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_21         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_22         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_23         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_24         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_25         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_26         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_27         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_28         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_29         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_30         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)
#define BSW_COMM_CFG_NM_ACT_TYPE_31         (BSW_COMM_NM_ACT_TYPE_NO_BSSLP)

/* Symbolic Name Reference - Channel Id */
#define ComMConf_ComMChannel_CDC_VCAN_BUS                   (0U)

/* Symbolic Name Reference - PNC No. */

/* Symbolic Name Reference - SysStatus */
#define ComMConf_SysStatusName_BAT                          (BSW_COMM_PWSTAT_BAT)
#define ComMConf_SysStatusName_ACC                          (BSW_COMM_PWSTAT_ACC)
#define ComMConf_SysStatusName_IG                           (BSW_COMM_PWSTAT_IG)
#define ComMConf_SysStatusName_PBA                          (BSW_COMM_PWSTAT_USER1)
#define ComMConf_SysStatusName_IGR                          (BSW_COMM_PWSTAT_USER2)
#define ComMConf_SysStatusName_Special                      (BSW_COMM_PWSTAT_USER3)

/* Symbolic Name Reference - UserAwake */
#define ComMConf_UserAwakeName_UserAwake1                   (BSW_COMM_USERAWAKE_1)

/*--------------------------------------------------------------------------*/
/* Types                                                                    */
/*--------------------------------------------------------------------------*/

/*--------------------------------------------------------------------------*/
/* Function Prototypes                                                      */
/*--------------------------------------------------------------------------*/

/*--------------------------------------------------------------------------*/
/* Data                                                                     */
/*--------------------------------------------------------------------------*/

/*--------------------------------------------------------------------------*/
/* Constants                                                                */
/*--------------------------------------------------------------------------*/

#endif /* BSW_COMM_CFG_H */

/****************************************************************************/
/* History                                                                  */
/*  Version         :Date                                                   */
/*  v1-0-0          :2017/05/16                                             */
/*  v1-1-0          :2018/07/02                                             */
/*  v2-0-0          :2022/03/10                                             */
/*  v2-1-0          :2022/05/26                                             */
/*  v3-0-0          :2024/11/11                                             */
/****************************************************************************/
/****************************************************************************/
/* AUBIST Configurator Version                                              */
/*  Framework          :v2-0-2                                              */
/*  BSW plug-in        :v3-0-0                                              */
/****************************************************************************/

/**** End of File ***********************************************************/
