/* Copyright  : DENSO CORPORATION */
#ifndef BSW_CFG_H
#define BSW_CFG_H

#define BSW_CFG_GETSPINLOCK_SPI()
#define BSW_CFG_RELEASESPINLOCK_SPI()


/* MCAL_SPI */
#define		SPI_CFG_MODEA_USE	(ON)
#define		SPI_CFG_MODEB_USE	(OFF)
#define		SPI_CFG_MODEC_USE	(OFF)


#ifndef	SPI_CFG_MODEA_USE
#define	SPI_CFG_MODEA_USE	(OFF)
#endif
#ifndef	SPI_CFG_MODEB_USE
#define	SPI_CFG_MODEB_USE	(OFF)
#endif
#ifndef	SPI_CFG_MODEC_USE
#define	SPI_CFG_MODEC_USE	(OFF)
#endif

#define	SPI_CFG_SYNCSEND_TIMEOUT		(0xFFFFFFFF)
#define	SPI_CFG_SYNCRECEIVE_TIMEOUT		(0xFFFFFFFF)
#define	SPI_CFG_SENDDMASTOP_TIMEOUT		(0xFFFFFFFF)
#define	SPI_CFG_RECEIVEDMASTOP_TIMEOUT	(0xFFFFFFFF)
#define	SPI_CFG_ASYNCDMASTART_TIMEOUT	(0xFFFFFFFF)

#define SPI_CFG_SEC_RAM0					(BSW_SEC_B_LRAM1_CPU0_ASIL_SDA)
#define SPI_CFG_MODEC_FSLEVEL				(SPI_QM)

#define BSW_CFG_GETSPINLOCK_PIL_SPI()
#define BSW_CFG_RELEASESPINLOCK_PIL_SPI()

#define Bswlib_GetCoreId()	((U4)0)

#endif /* BSW_CFG_H */

