/* Copyright  : DENSO CORPORATION */
#ifndef RTE_BSWUCFG_H
#define RTE_BSWUCFG_H

/* MCAL_SPI */
/* Spi Communication Mode A Channel ID (SPI_COMA_ID xxx) */
#define		SPI_COMA_ID_CANTRCV_0				(0)

#define		SPI_UCFG_MODEA_CHANNEL_NUM			(1)

#define		SPI_UCFG_MODEA_CH0_HARDCH			PIL_SPI_CH6_0
#define		SPI_UCFG_MODEA_CH0_SHIFTCLOCKIDLELEVEL	(PIL_SPI_CKR_LOW)
#define		SPI_UCFG_MODEA_CH0_SOUTFUNCTION		(PIL_SPI_SOLS_LOW)
#define		SPI_UCFG_MODEA_CH0_CLOCKIDLELEVEL	(LO)
#define		SPI_UCFG_MODEA_CH0_STARTEDGE		(PIL_SPI_STARTEDGE_CLK)
#define		SPI_UCFG_MODEA_CH0_BITRATE_PATTERN	PIL_SPI_BITRATE_0_91M
#define		SPI_UCFG_MODEA_CH0_BITDIRECTION		(PIL_SPI_DIRECTION_MSBFIRST)
#define		SPI_UCFG_MODEA_CH0_DATASIZE			(PIL_SPI_LENGTH_16BIT)
#define		SPI_UCFG_MODEA_CH0_CSACTIVELEVEL	(LO)
#define		SPI_UCFG_MODEA_CH0_CSID				(PIL_SPI_CSID_0)
#define		SPI_UCFG_MODEA_CH0_CS2CLKDELAY		(PIL_SPI_DELAY_200NS)
#define		SPI_UCFG_MODEA_CH0_CLK2CSDELAY		(PIL_SPI_DELAY_200NS)
#define		SPI_UCFG_MODEA_CH0_INTERDATATIME	(0)
#define		SPI_UCFG_MODEA_CH0_COREID			(u4BSW_CORE_ID_CORE0)

#define		SPI_COMA_SEQID_CANTRCV				(0)

#define		SPI_UCFG_MODEA_SEQUENCE_NUM			(1)

#define		SPI_UCFG_SEQ0_CHID      			(SPI_COMA_ID_CANTRCV_0)

/* Spi Communication ModeC ID (SPI_COMC_ID xxx) */
#define		SPI_UCFG_MODEC_CHANNEL_NUM			(0)

#define		IOC_SPINLOCK_ID_PIL_SPI				(0)
#define		IOC_SPINLOCK_ID_SPI	    			(0)


/*-- End Of File -------------------------------------------------------------------------------*/
#endif /* RTE_BSWUCFG_H */
