/* bsw_cantp_config_c_v3-0-0                                                */
/****************************************************************************/
/* Protected                                                                */
/* Copyright DENSO CORPORATION                                              */
/****************************************************************************/

/****************************************************************************/
/* Object Name  | BSW/CANTP/CONFIG/CODE                                     */
/*--------------------------------------------------------------------------*/
/* Notes        |                                                           */
/****************************************************************************/

/*--------------------------------------------------------------------------*/
/* Include Files                                                            */
/*--------------------------------------------------------------------------*/
#include <Std_Types.h>
#include <cs/bsw_cs_common.h>
#include <cs/bsw_cs_system.h>
#include "../inc/bsw_cantp_MemMap.h"

#include <bswm_cs/bsw_bswm_cs.h>
#include <comm/bsw_comm.h>
#include "../../ComM/inc/bsw_comm_config.h"
#include "../../BswM_CS/inc/bsw_bswm_cs_config.h"

#if( BSW_BSWM_CS_FUNC_CANTP == BSW_USE )
#include <cantp/bsw_cantp.h>
#include <pdur/bsw_pdur.h>

#include "../cfg/CanTp_Cfg.h"
#include "../inc/bsw_cantp_cmn.h"

#include "../inc/bsw_cantp_config.h"

#include "../inc/bsw_cantp_st.h"

/*--------------------------------------------------------------------------*/
/* Macros                                                                   */
/*--------------------------------------------------------------------------*/
/* The total number of RxNPdus */
#define BSW_CANTP_RXNPDUNUM_0_7 \
   (  BSW_CANTP_CFG_RXNPDUNUM_CH00 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH01 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH02 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH03 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH04 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH05 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH06 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH07 )

#define BSW_CANTP_RXNPDUNUM_8_15 \
   (  BSW_CANTP_CFG_RXNPDUNUM_CH08 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH09 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH10 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH11 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH12 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH13 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH14 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH15 )

#define BSW_CANTP_RXNPDUNUM_16_23 \
   (  BSW_CANTP_CFG_RXNPDUNUM_CH16 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH17 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH18 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH19 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH20 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH21 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH22 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH23 )

#define BSW_CANTP_RXNPDUNUM_24_31 \
   (  BSW_CANTP_CFG_RXNPDUNUM_CH24 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH25 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH26 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH27 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH28 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH29 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH30 \
    + BSW_CANTP_CFG_RXNPDUNUM_CH31 )

#define BSW_CANTP_RXNPDUNUM ( BSW_CANTP_RXNPDUNUM_0_7 + BSW_CANTP_RXNPDUNUM_8_15 \
        + BSW_CANTP_RXNPDUNUM_16_23 + BSW_CANTP_RXNPDUNUM_24_31 )

 /* The total number of TxNPdus */
#define BSW_CANTP_TXNPDUNUM_0_7 \
   (  BSW_CANTP_CFG_TXNPDUNUM_CH00 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH01 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH02 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH03 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH04 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH05 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH06 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH07 )

#define BSW_CANTP_TXNPDUNUM_8_15 \
   (  BSW_CANTP_CFG_TXNPDUNUM_CH08 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH09 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH10 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH11 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH12 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH13 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH14 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH15 )

#define BSW_CANTP_TXNPDUNUM_16_23 \
   (  BSW_CANTP_CFG_TXNPDUNUM_CH16 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH17 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH18 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH19 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH20 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH21 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH22 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH23 )

#define BSW_CANTP_TXNPDUNUM_24_31 \
   (  BSW_CANTP_CFG_TXNPDUNUM_CH24 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH25 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH26 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH27 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH28 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH29 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH30 \
    + BSW_CANTP_CFG_TXNPDUNUM_CH31 )

#define BSW_CANTP_TXNPDUNUM ( BSW_CANTP_TXNPDUNUM_0_7 + BSW_CANTP_TXNPDUNUM_8_15 \
        + BSW_CANTP_TXNPDUNUM_16_23 + BSW_CANTP_TXNPDUNUM_24_31 )

/* RxNSduTbl Index */
#define BSW_CANTP_RXNSDUTBLIDX_CH00 (0U)
#define BSW_CANTP_RXNSDUTBLIDX_CH01 (BSW_CANTP_RXNSDUTBLIDX_CH00 + BSW_CANTP_CFG_RXNSDUNUM_CH00)
#define BSW_CANTP_RXNSDUTBLIDX_CH02 (BSW_CANTP_RXNSDUTBLIDX_CH01 + BSW_CANTP_CFG_RXNSDUNUM_CH01)
#define BSW_CANTP_RXNSDUTBLIDX_CH03 (BSW_CANTP_RXNSDUTBLIDX_CH02 + BSW_CANTP_CFG_RXNSDUNUM_CH02)
#define BSW_CANTP_RXNSDUTBLIDX_CH04 (BSW_CANTP_RXNSDUTBLIDX_CH03 + BSW_CANTP_CFG_RXNSDUNUM_CH03)
#define BSW_CANTP_RXNSDUTBLIDX_CH05 (BSW_CANTP_RXNSDUTBLIDX_CH04 + BSW_CANTP_CFG_RXNSDUNUM_CH04)
#define BSW_CANTP_RXNSDUTBLIDX_CH06 (BSW_CANTP_RXNSDUTBLIDX_CH05 + BSW_CANTP_CFG_RXNSDUNUM_CH05)
#define BSW_CANTP_RXNSDUTBLIDX_CH07 (BSW_CANTP_RXNSDUTBLIDX_CH06 + BSW_CANTP_CFG_RXNSDUNUM_CH06)
#define BSW_CANTP_RXNSDUTBLIDX_CH08 (BSW_CANTP_RXNSDUTBLIDX_CH07 + BSW_CANTP_CFG_RXNSDUNUM_CH07)
#define BSW_CANTP_RXNSDUTBLIDX_CH09 (BSW_CANTP_RXNSDUTBLIDX_CH08 + BSW_CANTP_CFG_RXNSDUNUM_CH08)
#define BSW_CANTP_RXNSDUTBLIDX_CH10 (BSW_CANTP_RXNSDUTBLIDX_CH09 + BSW_CANTP_CFG_RXNSDUNUM_CH09)
#define BSW_CANTP_RXNSDUTBLIDX_CH11 (BSW_CANTP_RXNSDUTBLIDX_CH10 + BSW_CANTP_CFG_RXNSDUNUM_CH10)
#define BSW_CANTP_RXNSDUTBLIDX_CH12 (BSW_CANTP_RXNSDUTBLIDX_CH11 + BSW_CANTP_CFG_RXNSDUNUM_CH11)
#define BSW_CANTP_RXNSDUTBLIDX_CH13 (BSW_CANTP_RXNSDUTBLIDX_CH12 + BSW_CANTP_CFG_RXNSDUNUM_CH12)
#define BSW_CANTP_RXNSDUTBLIDX_CH14 (BSW_CANTP_RXNSDUTBLIDX_CH13 + BSW_CANTP_CFG_RXNSDUNUM_CH13)
#define BSW_CANTP_RXNSDUTBLIDX_CH15 (BSW_CANTP_RXNSDUTBLIDX_CH14 + BSW_CANTP_CFG_RXNSDUNUM_CH14)
#define BSW_CANTP_RXNSDUTBLIDX_CH16 (BSW_CANTP_RXNSDUTBLIDX_CH15 + BSW_CANTP_CFG_RXNSDUNUM_CH15)
#define BSW_CANTP_RXNSDUTBLIDX_CH17 (BSW_CANTP_RXNSDUTBLIDX_CH16 + BSW_CANTP_CFG_RXNSDUNUM_CH16)
#define BSW_CANTP_RXNSDUTBLIDX_CH18 (BSW_CANTP_RXNSDUTBLIDX_CH17 + BSW_CANTP_CFG_RXNSDUNUM_CH17)
#define BSW_CANTP_RXNSDUTBLIDX_CH19 (BSW_CANTP_RXNSDUTBLIDX_CH18 + BSW_CANTP_CFG_RXNSDUNUM_CH18)
#define BSW_CANTP_RXNSDUTBLIDX_CH20 (BSW_CANTP_RXNSDUTBLIDX_CH19 + BSW_CANTP_CFG_RXNSDUNUM_CH19)
#define BSW_CANTP_RXNSDUTBLIDX_CH21 (BSW_CANTP_RXNSDUTBLIDX_CH20 + BSW_CANTP_CFG_RXNSDUNUM_CH20)
#define BSW_CANTP_RXNSDUTBLIDX_CH22 (BSW_CANTP_RXNSDUTBLIDX_CH21 + BSW_CANTP_CFG_RXNSDUNUM_CH21)
#define BSW_CANTP_RXNSDUTBLIDX_CH23 (BSW_CANTP_RXNSDUTBLIDX_CH22 + BSW_CANTP_CFG_RXNSDUNUM_CH22)
#define BSW_CANTP_RXNSDUTBLIDX_CH24 (BSW_CANTP_RXNSDUTBLIDX_CH23 + BSW_CANTP_CFG_RXNSDUNUM_CH23)
#define BSW_CANTP_RXNSDUTBLIDX_CH25 (BSW_CANTP_RXNSDUTBLIDX_CH24 + BSW_CANTP_CFG_RXNSDUNUM_CH24)
#define BSW_CANTP_RXNSDUTBLIDX_CH26 (BSW_CANTP_RXNSDUTBLIDX_CH25 + BSW_CANTP_CFG_RXNSDUNUM_CH25)
#define BSW_CANTP_RXNSDUTBLIDX_CH27 (BSW_CANTP_RXNSDUTBLIDX_CH26 + BSW_CANTP_CFG_RXNSDUNUM_CH26)
#define BSW_CANTP_RXNSDUTBLIDX_CH28 (BSW_CANTP_RXNSDUTBLIDX_CH27 + BSW_CANTP_CFG_RXNSDUNUM_CH27)
#define BSW_CANTP_RXNSDUTBLIDX_CH29 (BSW_CANTP_RXNSDUTBLIDX_CH28 + BSW_CANTP_CFG_RXNSDUNUM_CH28)
#define BSW_CANTP_RXNSDUTBLIDX_CH30 (BSW_CANTP_RXNSDUTBLIDX_CH29 + BSW_CANTP_CFG_RXNSDUNUM_CH29)
#define BSW_CANTP_RXNSDUTBLIDX_CH31 (BSW_CANTP_RXNSDUTBLIDX_CH30 + BSW_CANTP_CFG_RXNSDUNUM_CH30)

/* TxNSduTbl Index */
#define BSW_CANTP_TXNSDUTBLIDX_CH00 (0U)
#define BSW_CANTP_TXNSDUTBLIDX_CH01 (BSW_CANTP_TXNSDUTBLIDX_CH00 + BSW_CANTP_CFG_TXNSDUNUM_CH00)
#define BSW_CANTP_TXNSDUTBLIDX_CH02 (BSW_CANTP_TXNSDUTBLIDX_CH01 + BSW_CANTP_CFG_TXNSDUNUM_CH01)
#define BSW_CANTP_TXNSDUTBLIDX_CH03 (BSW_CANTP_TXNSDUTBLIDX_CH02 + BSW_CANTP_CFG_TXNSDUNUM_CH02)
#define BSW_CANTP_TXNSDUTBLIDX_CH04 (BSW_CANTP_TXNSDUTBLIDX_CH03 + BSW_CANTP_CFG_TXNSDUNUM_CH03)
#define BSW_CANTP_TXNSDUTBLIDX_CH05 (BSW_CANTP_TXNSDUTBLIDX_CH04 + BSW_CANTP_CFG_TXNSDUNUM_CH04)
#define BSW_CANTP_TXNSDUTBLIDX_CH06 (BSW_CANTP_TXNSDUTBLIDX_CH05 + BSW_CANTP_CFG_TXNSDUNUM_CH05)
#define BSW_CANTP_TXNSDUTBLIDX_CH07 (BSW_CANTP_TXNSDUTBLIDX_CH06 + BSW_CANTP_CFG_TXNSDUNUM_CH06)
#define BSW_CANTP_TXNSDUTBLIDX_CH08 (BSW_CANTP_TXNSDUTBLIDX_CH07 + BSW_CANTP_CFG_TXNSDUNUM_CH07)
#define BSW_CANTP_TXNSDUTBLIDX_CH09 (BSW_CANTP_TXNSDUTBLIDX_CH08 + BSW_CANTP_CFG_TXNSDUNUM_CH08)
#define BSW_CANTP_TXNSDUTBLIDX_CH10 (BSW_CANTP_TXNSDUTBLIDX_CH09 + BSW_CANTP_CFG_TXNSDUNUM_CH09)
#define BSW_CANTP_TXNSDUTBLIDX_CH11 (BSW_CANTP_TXNSDUTBLIDX_CH10 + BSW_CANTP_CFG_TXNSDUNUM_CH10)
#define BSW_CANTP_TXNSDUTBLIDX_CH12 (BSW_CANTP_TXNSDUTBLIDX_CH11 + BSW_CANTP_CFG_TXNSDUNUM_CH11)
#define BSW_CANTP_TXNSDUTBLIDX_CH13 (BSW_CANTP_TXNSDUTBLIDX_CH12 + BSW_CANTP_CFG_TXNSDUNUM_CH12)
#define BSW_CANTP_TXNSDUTBLIDX_CH14 (BSW_CANTP_TXNSDUTBLIDX_CH13 + BSW_CANTP_CFG_TXNSDUNUM_CH13)
#define BSW_CANTP_TXNSDUTBLIDX_CH15 (BSW_CANTP_TXNSDUTBLIDX_CH14 + BSW_CANTP_CFG_TXNSDUNUM_CH14)
#define BSW_CANTP_TXNSDUTBLIDX_CH16 (BSW_CANTP_TXNSDUTBLIDX_CH15 + BSW_CANTP_CFG_TXNSDUNUM_CH15)
#define BSW_CANTP_TXNSDUTBLIDX_CH17 (BSW_CANTP_TXNSDUTBLIDX_CH16 + BSW_CANTP_CFG_TXNSDUNUM_CH16)
#define BSW_CANTP_TXNSDUTBLIDX_CH18 (BSW_CANTP_TXNSDUTBLIDX_CH17 + BSW_CANTP_CFG_TXNSDUNUM_CH17)
#define BSW_CANTP_TXNSDUTBLIDX_CH19 (BSW_CANTP_TXNSDUTBLIDX_CH18 + BSW_CANTP_CFG_TXNSDUNUM_CH18)
#define BSW_CANTP_TXNSDUTBLIDX_CH20 (BSW_CANTP_TXNSDUTBLIDX_CH19 + BSW_CANTP_CFG_TXNSDUNUM_CH19)
#define BSW_CANTP_TXNSDUTBLIDX_CH21 (BSW_CANTP_TXNSDUTBLIDX_CH20 + BSW_CANTP_CFG_TXNSDUNUM_CH20)
#define BSW_CANTP_TXNSDUTBLIDX_CH22 (BSW_CANTP_TXNSDUTBLIDX_CH21 + BSW_CANTP_CFG_TXNSDUNUM_CH21)
#define BSW_CANTP_TXNSDUTBLIDX_CH23 (BSW_CANTP_TXNSDUTBLIDX_CH22 + BSW_CANTP_CFG_TXNSDUNUM_CH22)
#define BSW_CANTP_TXNSDUTBLIDX_CH24 (BSW_CANTP_TXNSDUTBLIDX_CH23 + BSW_CANTP_CFG_TXNSDUNUM_CH23)
#define BSW_CANTP_TXNSDUTBLIDX_CH25 (BSW_CANTP_TXNSDUTBLIDX_CH24 + BSW_CANTP_CFG_TXNSDUNUM_CH24)
#define BSW_CANTP_TXNSDUTBLIDX_CH26 (BSW_CANTP_TXNSDUTBLIDX_CH25 + BSW_CANTP_CFG_TXNSDUNUM_CH25)
#define BSW_CANTP_TXNSDUTBLIDX_CH27 (BSW_CANTP_TXNSDUTBLIDX_CH26 + BSW_CANTP_CFG_TXNSDUNUM_CH26)
#define BSW_CANTP_TXNSDUTBLIDX_CH28 (BSW_CANTP_TXNSDUTBLIDX_CH27 + BSW_CANTP_CFG_TXNSDUNUM_CH27)
#define BSW_CANTP_TXNSDUTBLIDX_CH29 (BSW_CANTP_TXNSDUTBLIDX_CH28 + BSW_CANTP_CFG_TXNSDUNUM_CH28)
#define BSW_CANTP_TXNSDUTBLIDX_CH30 (BSW_CANTP_TXNSDUTBLIDX_CH29 + BSW_CANTP_CFG_TXNSDUNUM_CH29)
#define BSW_CANTP_TXNSDUTBLIDX_CH31 (BSW_CANTP_TXNSDUTBLIDX_CH30 + BSW_CANTP_CFG_TXNSDUNUM_CH30)

/* The max value of timer */
#define BSW_CANTP_TIMER_MAX                      (5000U)

/* STmin to MainFunction cycle count */
/*-----------------------------------------*/
/* 0x00:0   to 0x7F:127     0ms to 127ms   */
/* 0x80:128 to 0xF0:240     Reserved       */
/* 0xF1:241 to 0xF9:249     100us to 900us */
/* 0xFA:250 to 0xFF:255     Reserved       */
/*-----------------------------------------*/
#define BSW_CANTP_u1STMIN2MAINCYC_OFFS           ((uint8)2U)
#if ( BSW_BSWM_CS_MPU_TICKTIME != 500UL )
#define BSW_CANTP_u4STMIN_RESERVE_TM_US          (127000UL)
#else
#define BSW_CANTP_u4STMIN_RESERVE_TM_US          (126500UL)
#endif /* BSW_BSWM_CS_MPU_TICKTIME != 500UL */

#define BSW_CANTP_u1STMIN_US2MAIN_CYCLE(us) \
    ((uint8)(BSW_CANTP_u4DIV_CEILING((us), ((uint32)BSW_CANTP_MAINFUNCTION_PERIOD * (uint32)BSW_BSWM_CS_MPU_TICKTIME))))


/*--------------------------------------------------------------------------*/
/* Types                                                                    */
/*--------------------------------------------------------------------------*/

/*--------------------------------------------------------------------------*/
/* Function Prototypes                                                      */
/*--------------------------------------------------------------------------*/

/*--------------------------------------------------------------------------*/
/* Data                                                                     */
/*--------------------------------------------------------------------------*/
Bsw_CanTp_st_ChStatType    bsw_cantp_st_stChStatTbl[BSW_CANTP_MAX_CH_CNT];
#if( BSW_CANTP_CFG_CHANGE_RXPARAM == BSW_USE )
Bsw_CanTp_BSSTminType      bsw_cantp_stBSSTminTbl[BSW_CANTP_MAX_RXNSDUNUM];
#endif /* BSW_CANTP_CFG_CHANGE_RXPARAM == BSW_USE */

/*--------------------------------------------------------------------------*/
/* Constants                                                                */
/*--------------------------------------------------------------------------*/
/* Padding Byte Data                     */
BswConst uint8  bsw_cantp_u1PaddingByte         = (uint8)BSW_CANTP_CFG_PADDINGBYTE;

#if( BSW_CANTP_CFG_DYNBSSTMIN_ADOPT == BSW_CANTP_FIXED_BSSTMIN )
/* BS/STmin fixed value                  */
BswConst uint8  bsw_cantp_u1FixedBS             = (uint8)BSW_CANTP_CFG_FIXED_BS;
BswConst uint8  bsw_cantp_u1FixedSTmin          = (uint8)BSW_CANTP_CFG_FIXED_STMIN;
#endif  /* BSW_CANTP_CFG_DYNBSSTMIN_ADOPT == BSW_CANTP_FIXED_BSSTMIN */

/* The max number of RxNSdus             */
#if( (BSW_CANTP_CFG_CHANGE_RXPARAM == BSW_USE) || (BSW_CANTP_CFG_LOWCOSTOPERATION == BSW_USE) )
BswConst uint16  bsw_cantp_u2MaxRxNSduNum       = (uint16)BSW_CANTP_MAX_RXNSDUNUM;
#endif /* ( (BSW_CANTP_CFG_CHANGE_RXPARAM == BSW_USE) || (BSW_CANTP_CFG_LOWCOSTOPERATION == BSW_USE) ) */

/* The max number of Connection Channels */
BswConst uint8  bsw_cantp_u1MaxChCnt            = (uint8)BSW_CANTP_MAX_CH_CNT;

/* The max value of MainFunc cycle       */
BswConst uint16 bsw_cantp_u2TimerCycleMax       = BSW_CANTP_u2MS2MAINFUNC_CYCLE(BSW_CANTP_TIMER_MAX);

/* The max Length of Pdu                 */
BswConst uint32 bsw_cantp_u4MaxPduLength        = (uint32)BSW_CANTP_CFG_MAXPDULENGTH;

#if( BSW_CANTP_CFG_LOWCOSTOPERATION == BSW_USE )
BswConst uint8 bsw_cantp_u1TxCancelFunc         = (uint8)BSW_CANTP_TXCANCELFUNC;
BswConst uint8 bsw_cantp_u1UnexpectedRxFunc     = (uint8)BSW_CANTP_UNEXPECTEDRXFUNC;
#endif /* BSW_CANTP_CFG_LOWCOSTOPERATION == BSW_USE */
BswConst uint16 bsw_cantp_u2FcWaitTxPeriodTime  = BSW_CANTP_u2MS2MAINFUNC_CYCLE(BSW_CANTP_CFG_FCWAIT_TXPDTIME);
BswConst uint16 bsw_cantp_u2FcTxTimeout         = BSW_CANTP_u2MS2MAINFUNC_CYCLE(BSW_CANTP_CFG_FC_TXTIMEOUT);
BswConst uint16 bsw_cantp_u2CfTxTimeout         = BSW_CANTP_u2MS2MAINFUNC_CYCLE(BSW_CANTP_CFG_CF_TXTIMEOUT);

#if( BSW_CANTP_CFG_FDSUPPORT == BSW_USE )
BswConst uint8 bsw_cantp_u1OptimizedCanDlTbl[BSW_CANTP_CAN_DL_PTN_NUM] =
{
    BSW_CANTP_u1CAN_DL_INVAL, /*  0 */
    BSW_CANTP_u1CAN_DL_INVAL, /*  1 */

    BSW_CANTP_u1CAN_DL_02,    /*  2 */
    BSW_CANTP_u1CAN_DL_03,    /*  3 */
    BSW_CANTP_u1CAN_DL_04,    /*  4 */
    BSW_CANTP_u1CAN_DL_05,    /*  5 */
    BSW_CANTP_u1CAN_DL_06,    /*  6 */
    BSW_CANTP_u1CAN_DL_07,    /*  7 */
    BSW_CANTP_u1CAN_DL_08,    /*  8 */

    BSW_CANTP_u1CAN_DL_12,    /*  9 */
    BSW_CANTP_u1CAN_DL_12,    /* 10 */
    BSW_CANTP_u1CAN_DL_12,    /* 11 */
    BSW_CANTP_u1CAN_DL_12,    /* 12 */

    BSW_CANTP_u1CAN_DL_16,    /* 13 */
    BSW_CANTP_u1CAN_DL_16,    /* 14 */
    BSW_CANTP_u1CAN_DL_16,    /* 15 */
    BSW_CANTP_u1CAN_DL_16,    /* 16 */

    BSW_CANTP_u1CAN_DL_20,    /* 17 */
    BSW_CANTP_u1CAN_DL_20,    /* 18 */
    BSW_CANTP_u1CAN_DL_20,    /* 19 */
    BSW_CANTP_u1CAN_DL_20,    /* 20 */

    BSW_CANTP_u1CAN_DL_24,    /* 21 */
    BSW_CANTP_u1CAN_DL_24,    /* 22 */
    BSW_CANTP_u1CAN_DL_24,    /* 23 */
    BSW_CANTP_u1CAN_DL_24,    /* 24 */

    BSW_CANTP_u1CAN_DL_32,    /* 25 */
    BSW_CANTP_u1CAN_DL_32,    /* 26 */
    BSW_CANTP_u1CAN_DL_32,    /* 27 */
    BSW_CANTP_u1CAN_DL_32,    /* 28 */
    BSW_CANTP_u1CAN_DL_32,    /* 29 */
    BSW_CANTP_u1CAN_DL_32,    /* 30 */
    BSW_CANTP_u1CAN_DL_32,    /* 31 */
    BSW_CANTP_u1CAN_DL_32,    /* 32 */

    BSW_CANTP_u1CAN_DL_48,    /* 33 */
    BSW_CANTP_u1CAN_DL_48,    /* 34 */
    BSW_CANTP_u1CAN_DL_48,    /* 35 */
    BSW_CANTP_u1CAN_DL_48,    /* 36 */
    BSW_CANTP_u1CAN_DL_48,    /* 37 */
    BSW_CANTP_u1CAN_DL_48,    /* 38 */
    BSW_CANTP_u1CAN_DL_48,    /* 39 */
    BSW_CANTP_u1CAN_DL_48,    /* 40 */
    BSW_CANTP_u1CAN_DL_48,    /* 41 */
    BSW_CANTP_u1CAN_DL_48,    /* 42 */
    BSW_CANTP_u1CAN_DL_48,    /* 43 */
    BSW_CANTP_u1CAN_DL_48,    /* 44 */
    BSW_CANTP_u1CAN_DL_48,    /* 45 */
    BSW_CANTP_u1CAN_DL_48,    /* 46 */
    BSW_CANTP_u1CAN_DL_48,    /* 47 */
    BSW_CANTP_u1CAN_DL_48,    /* 48 */

    BSW_CANTP_u1CAN_DL_64,    /* 49 */
    BSW_CANTP_u1CAN_DL_64,    /* 50 */
    BSW_CANTP_u1CAN_DL_64,    /* 51 */
    BSW_CANTP_u1CAN_DL_64,    /* 52 */
    BSW_CANTP_u1CAN_DL_64,    /* 53 */
    BSW_CANTP_u1CAN_DL_64,    /* 54 */
    BSW_CANTP_u1CAN_DL_64,    /* 55 */
    BSW_CANTP_u1CAN_DL_64,    /* 56 */
    BSW_CANTP_u1CAN_DL_64,    /* 57 */
    BSW_CANTP_u1CAN_DL_64,    /* 58 */
    BSW_CANTP_u1CAN_DL_64,    /* 59 */
    BSW_CANTP_u1CAN_DL_64,    /* 60 */
    BSW_CANTP_u1CAN_DL_64,    /* 61 */
    BSW_CANTP_u1CAN_DL_64,    /* 62 */
    BSW_CANTP_u1CAN_DL_64,    /* 63 */
    BSW_CANTP_u1CAN_DL_64,    /* 64 */
};
#endif /* BSW_CANTP_CFG_FDSUPPORT == BSW_USE */


/* MainFunc cycle value for STmin        */
BswConst uint8  bsw_cantp_u1STminCycleTbl[BSW_CANTP_STMIN_RANGE_SIZE] =
{
    /*************************/
    /* ms range 0x00         */
    /*************************/
    (uint8)1U,                                                                                          /*   0 0x00 */

    /*************************/
    /* ms range 0x01 to 0x7F */
    /*************************/
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(  1000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*   1 0x01 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(  2000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*   2 0x02 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(  3000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*   3 0x03 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(  4000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*   4 0x04 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(  5000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*   5 0x05 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(  6000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*   6 0x06 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(  7000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*   7 0x07 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(  8000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*   8 0x08 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(  9000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*   9 0x09 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 10000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  10 0x0A */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 11000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  11 0x0B */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 12000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  12 0x0C */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 13000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  13 0x0D */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 14000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  14 0x0E */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 15000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  15 0x0F */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 16000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  16 0x10 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 17000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  17 0x11 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 18000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  18 0x12 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 19000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  19 0x13 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 20000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  20 0x14 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 21000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  21 0x15 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 22000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  22 0x16 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 23000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  23 0x17 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 24000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  24 0x18 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 25000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  25 0x19 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 26000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  26 0x1A */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 27000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  27 0x1B */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 28000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  28 0x1C */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 29000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  29 0x1D */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 30000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  30 0x1E */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 31000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  31 0x1F */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 32000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  32 0x20 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 33000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  33 0x21 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 34000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  34 0x22 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 35000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  35 0x23 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 36000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  36 0x24 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 37000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  37 0x25 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 38000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  38 0x26 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 39000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  39 0x27 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 40000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  40 0x28 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 41000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  41 0x29 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 42000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  42 0x2A */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 43000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  43 0x2B */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 44000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  44 0x2C */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 45000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  45 0x2D */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 46000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  46 0x2E */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 47000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  47 0x2F */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 48000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  48 0x30 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 49000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  49 0x31 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 50000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  50 0x32 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 51000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  51 0x33 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 52000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  52 0x34 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 53000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  53 0x35 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 54000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  54 0x36 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 55000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  55 0x37 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 56000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  56 0x38 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 57000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  57 0x39 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 58000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  58 0x3A */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 59000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  59 0x3B */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 60000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  60 0x3C */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 61000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  61 0x3D */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 62000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  62 0x3E */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 63000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  63 0x3F */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 64000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  64 0x40 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 65000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  65 0x41 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 66000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  66 0x42 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 67000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  67 0x43 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 68000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  68 0x44 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 69000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  69 0x45 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 70000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  70 0x46 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 71000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  71 0x47 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 72000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  72 0x48 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 73000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  73 0x49 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 74000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  74 0x4A */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 75000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  75 0x4B */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 76000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  76 0x4C */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 77000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  77 0x4D */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 78000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  78 0x4E */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 79000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  79 0x4F */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 80000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  80 0x50 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 81000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  81 0x51 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 82000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  82 0x52 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 83000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  83 0x53 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 84000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  84 0x54 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 85000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  85 0x55 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 86000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  86 0x56 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 87000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  87 0x57 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 88000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  88 0x58 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 89000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  89 0x59 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 90000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  90 0x5A */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 91000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  91 0x5B */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 92000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  92 0x5C */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 93000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  93 0x5D */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 94000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  94 0x5E */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 95000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  95 0x5F */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 96000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  96 0x60 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 97000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  97 0x61 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 98000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  98 0x62 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE( 99000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /*  99 0x63 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(100000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 100 0x64 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(101000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 101 0x65 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(102000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 102 0x66 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(103000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 103 0x67 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(104000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 104 0x68 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(105000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 105 0x69 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(106000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 106 0x6A */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(107000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 107 0x6B */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(108000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 108 0x6C */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(109000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 109 0x6D */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(110000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 110 0x6E */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(111000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 111 0x6F */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(112000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 112 0x70 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(113000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 113 0x71 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(114000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 114 0x72 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(115000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 115 0x73 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(116000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 116 0x74 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(117000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 117 0x75 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(118000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 118 0x76 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(119000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 119 0x77 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(120000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 120 0x78 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(121000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 121 0x79 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(122000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 122 0x7A */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(123000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 123 0x7B */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(124000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 124 0x7C */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(125000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 125 0x7D */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(126000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 126 0x7E */
#if ( BSW_BSWM_CS_MPU_TICKTIME != 500UL )
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(127000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 127 0x7F */
#else
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(126500UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 127 0x7F */
#endif /* BSW_BSWM_CS_MPU_TICKTIME != 500UL */

    /*************************/
    /* Reserved 0x80 to 0xF0 */
    /*************************/
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 128 0x80 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 129 0x81 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 130 0x82 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 131 0x83 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 132 0x84 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 133 0x85 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 134 0x86 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 135 0x87 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 136 0x88 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 137 0x89 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 138 0x8A */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 139 0x8B */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 140 0x8C */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 141 0x8D */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 142 0x8E */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 143 0x8F */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 144 0x90 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 145 0x91 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 146 0x92 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 147 0x93 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 148 0x94 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 149 0x95 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 150 0x96 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 151 0x97 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 152 0x98 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 153 0x99 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 154 0x9A */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 155 0x9B */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 156 0x9C */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 157 0x9D */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 158 0x9E */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 159 0x9F */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 160 0xA0 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 161 0xA1 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 162 0xA2 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 163 0xA3 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 164 0xA4 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 165 0xA5 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 166 0xA6 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 167 0xA7 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 168 0xA8 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 169 0xA9 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 170 0xAA */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 171 0xAB */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 172 0xAC */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 173 0xAD */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 174 0xAE */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 175 0xAF */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 176 0xB0 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 177 0xB1 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 178 0xB2 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 179 0xB3 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 180 0xB4 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 181 0xB5 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 182 0xB6 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 183 0xB7 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 184 0xB8 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 185 0xB9 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 186 0xBA */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 187 0xBB */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 188 0xBC */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 189 0xBD */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 190 0xBE */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 191 0xBF */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 192 0xC0 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 193 0xC1 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 194 0xC2 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 195 0xC3 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 196 0xC4 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 197 0xC5 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 198 0xC6 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 199 0xC7 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 200 0xC8 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 201 0xC9 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 202 0xCA */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 203 0xCB */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 204 0xCC */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 205 0xCD */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 206 0xCE */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 207 0xCF */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 208 0xD0 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 209 0xD1 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 210 0xD2 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 211 0xD3 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 212 0xD4 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 213 0xD5 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 214 0xD6 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 215 0xD7 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 216 0xD8 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 217 0xD9 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 218 0xDA */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 219 0xDB */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 220 0xDC */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 221 0xDD */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 222 0xDE */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 223 0xDF */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 224 0xE0 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 225 0xE1 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 226 0xE2 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 227 0xE3 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 228 0xE4 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 229 0xE5 */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 230 0xE6 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 231 0xE7 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 232 0xE8 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 233 0xE9 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 234 0xEA */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 235 0xEB */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 236 0xEC */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 237 0xED */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 238 0xEE */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 239 0xEF */

    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 240 0xF0 */

    /*************************/
    /* us range 0xF1 to 0xF9 */
    /*************************/
#if( BSW_CANTP_CFG_STMIN_USDEF == BSW_CANTP_USSTMIN_NORMAL )
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(100UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                            /* 241 0xF1 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(200UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                            /* 242 0xF2 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(300UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                            /* 243 0xF3 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(400UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                            /* 244 0xF4 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(500UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                            /* 245 0xF5 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(600UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                            /* 246 0xF6 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(700UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                            /* 247 0xF7 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(800UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                            /* 248 0xF8 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(900UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                            /* 249 0xF9 */
#else   /* BSW_CANTP_CFG_STMIN_USDEF == BSW_CANTP_USSTMIN_MAX */
#if ( BSW_BSWM_CS_MPU_TICKTIME != 500UL )
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(127000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 241 0xF1 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(127000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 242 0xF2 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(127000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 243 0xF3 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(127000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 244 0xF4 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(127000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 245 0xF5 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(127000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 246 0xF6 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(127000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 247 0xF7 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(127000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 248 0xF8 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(127000UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 249 0xF9 */
#else
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(126500UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 241 0xF1 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(126500UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 242 0xF2 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(126500UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 243 0xF3 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(126500UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 244 0xF4 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(126500UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 245 0xF5 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(126500UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 246 0xF6 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(126500UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 247 0xF7 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(126500UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 248 0xF8 */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(126500UL) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,                         /* 249 0xF9 */
#endif /* BSW_BSWM_CS_MPU_TICKTIME != 500UL */
#endif  /* BSW_CANTP_CFG_STMIN_USDEF */

    /*************************/
    /* Reserved 0xFA to 0xFF */
    /*************************/
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 250 0xFA */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 251 0xFB */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 252 0xFC */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 253 0xFD */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS,   /* 254 0xFE */
    BSW_CANTP_u1STMIN_US2MAIN_CYCLE(BSW_CANTP_u4STMIN_RESERVE_TM_US) + BSW_CANTP_u1STMIN2MAINCYC_OFFS    /* 255 0xFF */
};


/*==================================================================*/
/* Connection Channel Table                                         */
/*==================================================================*/
static BswConst Bsw_CanTp_ChCfgType bsw_cantp_stChCfgTbl[BSW_CANTP_CFG_CHNUM] =
{
    {
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH00]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH00]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH00                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH00                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH00                   /* Connection Channel Mode      */
       ,(uint8)0U                                               /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#if (BSW_CANTP_CFG_CHNUM > 1U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH01]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH01]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH01                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH01                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH01                   /* Connection Channel Mode      */
       ,(uint8)1U                                               /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 1U */
#if (BSW_CANTP_CFG_CHNUM > 2U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH02]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH02]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH02                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH02                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH02                   /* Connection Channel Mode      */
       ,(uint8)2U                                               /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 2U */
#if (BSW_CANTP_CFG_CHNUM > 3U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH03]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH03]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH03                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH03                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH03                   /* Connection Channel Mode      */
       ,(uint8)3U                                               /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 3U */
#if (BSW_CANTP_CFG_CHNUM > 4U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH04]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH04]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH04                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH04                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH04                   /* Connection Channel Mode      */
       ,(uint8)4U                                               /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 4U */
#if (BSW_CANTP_CFG_CHNUM > 5U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH05]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH05]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH05                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH05                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH05                   /* Connection Channel Mode      */
       ,(uint8)5U                                               /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 5U */
#if (BSW_CANTP_CFG_CHNUM > 6U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH06]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH06]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH06                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH06                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH06                   /* Connection Channel Mode      */
       ,(uint8)6U                                               /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 6U */
#if (BSW_CANTP_CFG_CHNUM > 7U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH07]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH07]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH07                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH07                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH07                   /* Connection Channel Mode      */
       ,(uint8)7U                                               /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 7U */
#if (BSW_CANTP_CFG_CHNUM > 8U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH08]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH08]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH08                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH08                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH08                   /* Connection Channel Mode      */
       ,(uint8)8U                                               /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 8U */
#if (BSW_CANTP_CFG_CHNUM > 9U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH09]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH09]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH09                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH09                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH09                   /* Connection Channel Mode      */
       ,(uint8)9U                                               /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 9U */
#if (BSW_CANTP_CFG_CHNUM > 10U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH10]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH10]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH10                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH10                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH10                   /* Connection Channel Mode      */
       ,(uint8)10U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 10U */
#if (BSW_CANTP_CFG_CHNUM > 11U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH11]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH11]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH11                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH11                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH11                   /* Connection Channel Mode      */
       ,(uint8)11U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 11U */
#if (BSW_CANTP_CFG_CHNUM > 12U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH12]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH12]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH12                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH12                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH12                   /* Connection Channel Mode      */
       ,(uint8)12U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 12U */
#if (BSW_CANTP_CFG_CHNUM > 13U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH13]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH13]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH13                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH13                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH13                   /* Connection Channel Mode      */
       ,(uint8)13U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 13U */
#if (BSW_CANTP_CFG_CHNUM > 14U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH14]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH14]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH14                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH14                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH14                   /* Connection Channel Mode      */
       ,(uint8)14U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 14U */
#if (BSW_CANTP_CFG_CHNUM > 15U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH15]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH15]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH15                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH15                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH15                   /* Connection Channel Mode      */
       ,(uint8)15U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 15U */
#if (BSW_CANTP_CFG_CHNUM > 16U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH16]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH16]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH16                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH16                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH16                   /* Connection Channel Mode      */
       ,(uint8)16U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 16U */
#if (BSW_CANTP_CFG_CHNUM > 17U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH17]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH17]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH17                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH17                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH17                   /* Connection Channel Mode      */
       ,(uint8)17U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 17U */
#if (BSW_CANTP_CFG_CHNUM > 18U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH18]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH18]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH18                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH18                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH18                   /* Connection Channel Mode      */
       ,(uint8)18U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 18U */
#if (BSW_CANTP_CFG_CHNUM > 19U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH19]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH19]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH19                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH19                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH19                   /* Connection Channel Mode      */
       ,(uint8)19U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 19U */
#if (BSW_CANTP_CFG_CHNUM > 20U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH20]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH20]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH20                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH20                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH20                   /* Connection Channel Mode      */
       ,(uint8)20U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 20U */
#if (BSW_CANTP_CFG_CHNUM > 21U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH21]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH21]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH21                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH21                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH21                   /* Connection Channel Mode      */
       ,(uint8)21U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 21U */
#if (BSW_CANTP_CFG_CHNUM > 22U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH22]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH22]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH22                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH22                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH22                   /* Connection Channel Mode      */
       ,(uint8)22U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 22U */
#if (BSW_CANTP_CFG_CHNUM > 23U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH23]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH23]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH23                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH23                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH23                   /* Connection Channel Mode      */
       ,(uint8)23U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 23U */
#if (BSW_CANTP_CFG_CHNUM > 24U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH24]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH24]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH24                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH24                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH24                   /* Connection Channel Mode      */
       ,(uint8)24U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 24U */
#if (BSW_CANTP_CFG_CHNUM > 25U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH25]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH25]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH25                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH25                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH25                   /* Connection Channel Mode      */
       ,(uint8)25U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 25U */
#if (BSW_CANTP_CFG_CHNUM > 26U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH26]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH26]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH26                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH26                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH26                   /* Connection Channel Mode      */
       ,(uint8)26U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 26U */
#if (BSW_CANTP_CFG_CHNUM > 27U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH27]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH27]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH27                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH27                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH27                   /* Connection Channel Mode      */
       ,(uint8)27U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 27U */
#if (BSW_CANTP_CFG_CHNUM > 28U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH28]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH28]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH28                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH28                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH28                   /* Connection Channel Mode      */
       ,(uint8)28U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 28U */
#if (BSW_CANTP_CFG_CHNUM > 29U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH29]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH29]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH29                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH29                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH29                   /* Connection Channel Mode      */
       ,(uint8)29U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 29U */
#if (BSW_CANTP_CFG_CHNUM > 30U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH30]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH30]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH30                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH30                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH30                   /* Connection Channel Mode      */
       ,(uint8)30U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 30U */
#if (BSW_CANTP_CFG_CHNUM > 31U)
   ,{
        &bsw_cantp_stRxNSduCfgTbl[BSW_CANTP_RXNSDUTBLIDX_CH31]  /* Pointer to RxNSduTbl         */
       ,&bsw_cantp_stTxNSduCfgTbl[BSW_CANTP_TXNSDUTBLIDX_CH31]  /* Pointer to TxNSduTbl         */
       ,(uint16)BSW_CANTP_CFG_RXNSDUNUM_CH31                    /* The number of RxNSdu         */
       ,(uint16)BSW_CANTP_CFG_TXNSDUNUM_CH31                    /* The number of TxNSdu         */
       ,(uint8)BSW_CANTP_CFG_CHANNELMODE_CH31                   /* Connection Channel Mode      */
       ,(uint8)31U                                              /* Connection Channel ID        */
       ,{
            (uint8)0U                                           /* Padding                      */
           ,(uint8)0U                                           /* Padding                      */
        }
    }
#endif /* BSW_CANTP_CFG_CHNUM > 31U */
};

/*==================================================================*/
/* CanTp Config Table                                               */
/*==================================================================*/
BswConst Bsw_CanTp_CfgType bsw_cantp_stCfgTbl =
{
    &bsw_cantp_stChCfgTbl[0U]                                   /* Pointer to ChCfgTbl          */
   ,(uint16)BSW_CANTP_CFG_MIN_RXNSDUID                          /* Minimum RxNSduId             */
   ,(uint16)BSW_CANTP_CFG_MIN_TXNSDUID                          /* Minimum TxNSduId             */
   ,(uint16)BSW_CANTP_CFG_MIN_RXNPDUID                          /* Minimum RxNPduId             */
   ,(uint16)BSW_CANTP_CFG_MIN_TXNPDUID                          /* Minimum TxNPduId             */
   ,(uint16)BSW_CANTP_RXNSDUNUM                                 /* The total number of RxNSdu   */
   ,(uint16)BSW_CANTP_TXNSDUNUM                                 /* The total number of TxNSdu   */
   ,(uint16)BSW_CANTP_RXNPDUNUM                                 /* The total number of RxNPdu   */
   ,(uint16)BSW_CANTP_TXNPDUNUM                                 /* The total number of TxNPdu   */
   ,(uint8)BSW_CANTP_CFG_CHNUM                                  /* The number of Channels       */
   ,{
        (uint8)0U                                               /* Padding                      */
       ,(uint8)0U                                               /* Padding                      */
       ,(uint8)0U                                               /* Padding                      */
    }
};


/****************************************************************************/
/* External Functions                                                       */
/****************************************************************************/

/****************************************************************************/
/* Internal Functions                                                       */
/****************************************************************************/

#endif /* BSW_BSWM_CS_FUNC_CANTP == BSW_USE */

/****************************************************************************/
/* History                                                                  */
/*  Version         :Date                                                   */
/*  v1-0-0          :2017/09/25                                             */
/*  v1-1-0          :2018/12/13                                             */
/*  v1-2-0          :2020/02/03                                             */
/*  v2-0-0          :2021/09/07                                             */
/*  v2-1-0          :2022/10/05                                             */
/*  v3-0-0          :2024/08/30                                             */
/****************************************************************************/

/**** End of File ***********************************************************/
