# coding: utf-8

################################################################################
# [IN_FILE]                                                                    #
#------------------------------------------------------------------------------#
#   [IN]  SrecFile | Motorola S-record(S3) ファイル                            #
################################################################################
[IN_FILE]
SrecFile  = vm0_temp.mot
StartFile = False
EndFile   = False


################################################################################
# [PLAINTEXT]                                                                  #
#------------------------------------------------------------------------------#
#   [OUT] PlainRunFile        | Motorola S-record(S3) 結合ファイル             #
################################################################################
[PLAINTEXT]
PlainRunFile        = W:\tool\XMerge\CDC_Hypervisor_U2A16.x

