/* bsw_bswm_cs_config_h_v2-2-0                                              */
/****************************************************************************/
/* Protected                                                                */
/* Copyright AUBASS CO., LTD.                                               */
/****************************************************************************/

/****************************************************************************/
/* Object Name  | BSW/BSWM/CS/CONFIG/HEADER                                 */
/*--------------------------------------------------------------------------*/
/* Notes        |                                                           */
/****************************************************************************/
#ifndef BSW_BSWM_CS_CONFIG_H
#define BSW_BSWM_CS_CONFIG_H

#include "../cfg/BswM_CS_Cfg.h"
/*--------------------------------------------------------------------------*/
/* Macros                                                                   */
/*--------------------------------------------------------------------------*/
#define BSW_BSWM_CS_MPU_TICKTIME                (BSW_BSWM_CS_CFG_MPU_TICKTIME)        /* Tick time [us]                 */
#define BSW_BSWM_CS_TICKTIME_HIGH               (BSW_BSWM_CS_CFG_TICKTIME_HIGH)       /* Drive period of high-priority period [Tick] */
#define BSW_BSWM_CS_TICKTIME_MID                (BSW_BSWM_CS_CFG_TICKTIME_MID)        /* Drive cycle at medium-priority[Tick] */
#define BSW_BSWM_CS_u4TICKTIME_HIGH             ((BswU4)BSW_BSWM_CS_TICKTIME_HIGH)    /* Drive period of high-priority period [Tick] */
#define BSW_BSWM_CS_u4TICKTIME_MID              ((BswU4)BSW_BSWM_CS_TICKTIME_MID)     /* Drive cycle at medium-priority[Tick] */

#define BSW_BSWM_CS_ECU_SLEEP                   (BSW_BSWM_CS_CFG_ECU_SLEEP)           /* Microcomputer sleep/wake-up setting */

#define BSW_BSWM_CS_ECU_FAIL                    (BSW_BSWM_CS_CFG_ECU_FAIL)            /* Use/not use of ECU failure detection mechanism */

/* Message distribution task for each bus type */
#define BSW_BSWM_CS_MSG_DELIVER                 (BSW_BSWM_CS_CFG_MSGDELIVER)

/* ms->Tick conversion */
#define BSW_BSWM_CS_u2MILSEC2TICK_HIGH(msTime)  ((BswU2)(((((BswU4)(msTime))*1000UL)+((BSW_BSWM_CS_MPU_TICKTIME*BSW_BSWM_CS_u4TICKTIME_HIGH)/(2UL)))/(BSW_BSWM_CS_MPU_TICKTIME*BSW_BSWM_CS_u4TICKTIME_HIGH))) /* Rounding half up */
#define BSW_BSWM_CS_u2MILSEC2TICK_MID(msTime)   ((BswU2)(((((BswU4)(msTime))*1000UL)+((BSW_BSWM_CS_MPU_TICKTIME*BSW_BSWM_CS_u4TICKTIME_MID )/(2UL)))/(BSW_BSWM_CS_MPU_TICKTIME*BSW_BSWM_CS_u4TICKTIME_MID ))) /* Rounding half up */
#define BSW_BSWM_CS_u2MS2TICK_RUP_HIGH(msTime)  ((BswU2)(((((BswU4)(msTime))*1000UL)+((BSW_BSWM_CS_MPU_TICKTIME*BSW_BSWM_CS_u4TICKTIME_HIGH)-(1UL)))/(BSW_BSWM_CS_MPU_TICKTIME*BSW_BSWM_CS_u4TICKTIME_HIGH))) /* Rounding up */
#define BSW_BSWM_CS_u2MS2TICK_RUP_MID(msTime)   ((BswU2)(((((BswU4)(msTime))*1000UL)+((BSW_BSWM_CS_MPU_TICKTIME*BSW_BSWM_CS_u4TICKTIME_MID )-(1UL)))/(BSW_BSWM_CS_MPU_TICKTIME*BSW_BSWM_CS_u4TICKTIME_MID ))) /* Rounding up */
#define BSW_BSWM_CS_u4MS2TICK_RUP_HIGH(msTime)  ((BswU4)(((((BswU4)(msTime))*1000UL)+((BSW_BSWM_CS_MPU_TICKTIME*BSW_BSWM_CS_u4TICKTIME_HIGH)-(1UL)))/(BSW_BSWM_CS_MPU_TICKTIME*BSW_BSWM_CS_u4TICKTIME_HIGH))) /* Rounding up (Range:0-4000000) */
#define BSW_BSWM_CS_u4MS2TICK_RUP_MID(msTime)   ((BswU4)(((((BswU4)(msTime))*1000UL)+((BSW_BSWM_CS_MPU_TICKTIME*BSW_BSWM_CS_u4TICKTIME_MID )-(1UL)))/(BSW_BSWM_CS_MPU_TICKTIME*BSW_BSWM_CS_u4TICKTIME_MID ))) /* Rounding up (Range:0-4000000) */

/* Built-in functions Set */
#define BSW_BSWM_CS_FUNC_BSWMCS     (BSW_BSWM_CS_CFG_FUNC_BSWMCS)
#define BSW_BSWM_CS_FUNC_COM        (BSW_BSWM_CS_CFG_FUNC_COM)
#define BSW_BSWM_CS_FUNC_LDCOM      (BSW_BSWM_CS_CFG_FUNC_LDCOM)
#define BSW_BSWM_CS_FUNC_DCM        (BSW_BSWM_CS_CFG_FUNC_DCM)
#define BSW_BSWM_CS_FUNC_XCP        (BSW_BSWM_CS_CFG_FUNC_XCP)
#define BSW_BSWM_CS_FUNC_UPPERCDD1  (BSW_BSWM_CS_CFG_FUNC_UPPERCDD1)
#define BSW_BSWM_CS_FUNC_UPPERCDD2  (BSW_BSWM_CS_CFG_FUNC_UPPERCDD2)
#define BSW_BSWM_CS_FUNC_COMM       (BSW_BSWM_CS_CFG_FUNC_COMM)
#define BSW_BSWM_CS_FUNC_PDUR       (BSW_BSWM_CS_CFG_FUNC_PDUR)
#define BSW_BSWM_CS_FUNC_NM         (BSW_BSWM_CS_CFG_FUNC_NM)
#define BSW_BSWM_CS_FUNC_SECOC      (BSW_BSWM_CS_CFG_FUNC_SECOC)
#define BSW_BSWM_CS_FUNC_IPDUM      (BSW_BSWM_CS_CFG_FUNC_IPDUM)
#define BSW_BSWM_CS_FUNC_SOMEIP     (BSW_BSWM_CS_CFG_FUNC_SOMEIP)
#define BSW_BSWM_CS_FUNC_PNCIPDU    (BSW_BSWM_CS_CFG_FUNC_PNCIPDU)

#if ((BSW_BSWM_CS_CFG_FUNC_CANRX == BSW_USE) || (BSW_BSWM_CS_CFG_FUNC_CANTX == BSW_USE))
#define BSW_BSWM_CS_FUNC_CAN        (BSW_USE)
#else
#define BSW_BSWM_CS_FUNC_CAN        (BSW_NOUSE)
#endif
#define BSW_BSWM_CS_FUNC_BSWMCAN    (BSW_BSWM_CS_CFG_FUNC_BSWMCAN)
#define BSW_BSWM_CS_FUNC_CANSM      (BSW_BSWM_CS_CFG_FUNC_CANSM)
#define BSW_BSWM_CS_FUNC_CANIF      (BSW_BSWM_CS_CFG_FUNC_CANIF)
#define BSW_BSWM_CS_FUNC_CANRX      (BSW_BSWM_CS_CFG_FUNC_CANRX)
#define BSW_BSWM_CS_FUNC_CANTX      (BSW_BSWM_CS_CFG_FUNC_CANTX)
#define BSW_BSWM_CS_FUNC_CANTX_PHY  (BSW_BSWM_CS_CFG_FUNC_CANTX_PHY)
#define BSW_BSWM_CS_FUNC_CANTX_VIR  (BSW_BSWM_CS_CFG_FUNC_CANTX_VIR)
#define BSW_BSWM_CS_FUNC_CANTP      (BSW_BSWM_CS_CFG_FUNC_CANTP)
#define BSW_BSWM_CS_FUNC_CANNM      (BSW_BSWM_CS_CFG_FUNC_CANNM)
#define BSW_BSWM_CS_FUNC_CANDRV     (BSW_BSWM_CS_CFG_FUNC_CANDRV)
#define BSW_BSWM_CS_FUNC_VCAN       (BSW_BSWM_CS_CFG_FUNC_VCAN)

#define BSW_BSWM_CS_FUNC_LIN        (BSW_BSWM_CS_CFG_FUNC_LIN)
#define BSW_BSWM_CS_FUNC_BSWMLIN    (BSW_BSWM_CS_CFG_FUNC_LIN)
#define BSW_BSWM_CS_FUNC_LINSM      (BSW_BSWM_CS_CFG_FUNC_LIN)
#define BSW_BSWM_CS_FUNC_LINIF      (BSW_BSWM_CS_CFG_FUNC_LIN)
#define BSW_BSWM_CS_FUNC_LINRX      (BSW_BSWM_CS_CFG_FUNC_LIN)
#define BSW_BSWM_CS_FUNC_LINTX      (BSW_BSWM_CS_CFG_FUNC_LIN)
#define BSW_BSWM_CS_FUNC_LINTP      (BSW_BSWM_CS_CFG_FUNC_LINTP)
#define BSW_BSWM_CS_FUNC_LINNM      (BSW_BSWM_CS_CFG_FUNC_LIN)

#define BSW_BSWM_CS_FUNC_ETH        (BSW_BSWM_CS_CFG_FUNC_ETH)
#define BSW_BSWM_CS_FUNC_BSWMETH    (BSW_BSWM_CS_CFG_FUNC_ETH)
#define BSW_BSWM_CS_FUNC_ETHSM      (BSW_BSWM_CS_CFG_FUNC_ETH)
#define BSW_BSWM_CS_FUNC_ETHIF      (BSW_BSWM_CS_CFG_FUNC_ETH)
#define BSW_BSWM_CS_FUNC_ETHRX      (BSW_BSWM_CS_CFG_FUNC_ETH)
#define BSW_BSWM_CS_FUNC_ETHTX      (BSW_BSWM_CS_CFG_FUNC_ETH)
#define BSW_BSWM_CS_FUNC_SOAD       (BSW_BSWM_CS_CFG_FUNC_ETH)
#define BSW_BSWM_CS_FUNC_TCPIP      (BSW_BSWM_CS_CFG_FUNC_ETH)
#define BSW_BSWM_CS_FUNC_DOIP       (BSW_BSWM_CS_CFG_FUNC_DOIP)
#define BSW_BSWM_CS_FUNC_UDPNM      (BSW_BSWM_CS_CFG_FUNC_ETH)
#define BSW_BSWM_CS_FUNC_VETH       (BSW_BSWM_CS_CFG_FUNC_VETH)
#define BSW_BSWM_CS_FUNC_ETHTSYN    (BSW_BSWM_CS_CFG_FUNC_ETHTSYN)

#define BSW_BSWM_CS_FUNC_CDD1       (BSW_BSWM_CS_CFG_FUNC_CDD1)
#define BSW_BSWM_CS_FUNC_BSWMCDD1   (BSW_BSWM_CS_CFG_FUNC_CDD1)
#define BSW_BSWM_CS_FUNC_CDD1SM     (BSW_BSWM_CS_CFG_FUNC_CDD1)
#define BSW_BSWM_CS_FUNC_CDD1IF     (BSW_BSWM_CS_CFG_FUNC_CDD1)
#define BSW_BSWM_CS_FUNC_CDD1RX     (BSW_BSWM_CS_CFG_FUNC_CDD1)
#define BSW_BSWM_CS_FUNC_CDD1TX     (BSW_BSWM_CS_CFG_FUNC_CDD1)
#define BSW_BSWM_CS_FUNC_CDD1TP     (BSW_BSWM_CS_CFG_FUNC_CDD1TP)
#define BSW_BSWM_CS_FUNC_GENERICNM1 (BSW_BSWM_CS_CFG_FUNC_CDD1)

#define BSW_BSWM_CS_FUNC_CDD2       (BSW_BSWM_CS_CFG_FUNC_CDD2)
#define BSW_BSWM_CS_FUNC_BSWMCDD2   (BSW_BSWM_CS_CFG_FUNC_CDD2)
#define BSW_BSWM_CS_FUNC_CDD2SM     (BSW_BSWM_CS_CFG_FUNC_CDD2)
#define BSW_BSWM_CS_FUNC_CDD2IF     (BSW_BSWM_CS_CFG_FUNC_CDD2)
#define BSW_BSWM_CS_FUNC_CDD2RX     (BSW_BSWM_CS_CFG_FUNC_CDD2)
#define BSW_BSWM_CS_FUNC_CDD2TX     (BSW_BSWM_CS_CFG_FUNC_CDD2)
#define BSW_BSWM_CS_FUNC_CDD2TP     (BSW_BSWM_CS_CFG_FUNC_CDD2TP)
#define BSW_BSWM_CS_FUNC_GENERICNM2 (BSW_BSWM_CS_CFG_FUNC_CDD2)

#define BSW_BSWM_CS_FUNC_CANCDD1    (BSW_BSWM_CS_CFG_FUNC_CANCDD1)
#define BSW_BSWM_CS_FUNC_LINCDD1    (BSW_BSWM_CS_CFG_FUNC_LINCDD1)
#define BSW_BSWM_CS_FUNC_ETHCDD1    (BSW_BSWM_CS_CFG_FUNC_ETHCDD1)

#define BSW_BSWM_CS_FUNC_CANCDD2    (BSW_BSWM_CS_CFG_FUNC_CANCDD2)
#define BSW_BSWM_CS_FUNC_LINCDD2    (BSW_BSWM_CS_CFG_FUNC_LINCDD2)
#define BSW_BSWM_CS_FUNC_ETHCDD2    (BSW_BSWM_CS_CFG_FUNC_ETHCDD2)

#define BSW_BSWM_CS_CHRSTCTRL_FUNC  (BSW_BSWM_CS_CFG_CHRSTCTRL)    /* Use/not use channel restart function */
#define BSW_BSWM_CS_DMCTRL_FUNC     (BSW_BSWM_CS_CFG_DMCTRL)       /* Use/Unuse receive disconnection monitoring function   */

#define BSW_BSWM_CS_XCP_KIND        (BSW_BSWM_CS_CFG_XCP_KIND)

/* Use/Unuse the transmission stop/resume function */
#define BSW_BSWM_CS_TXCTRL_FUNC    (BSW_BSWM_CS_TXCTRL_FUNC0)
#define BSW_BSWM_CS_TXCTRL_FUNC0  ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_0 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC1)
#define BSW_BSWM_CS_TXCTRL_FUNC1  ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_1 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC2)
#define BSW_BSWM_CS_TXCTRL_FUNC2  ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_2 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC3)
#define BSW_BSWM_CS_TXCTRL_FUNC3  ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_3 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC4)
#define BSW_BSWM_CS_TXCTRL_FUNC4  ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_4 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC5)
#define BSW_BSWM_CS_TXCTRL_FUNC5  ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_5 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC6)
#define BSW_BSWM_CS_TXCTRL_FUNC6  ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_6 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC7)
#define BSW_BSWM_CS_TXCTRL_FUNC7  ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_7 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC8)
#define BSW_BSWM_CS_TXCTRL_FUNC8  ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_8 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC9)
#define BSW_BSWM_CS_TXCTRL_FUNC9  ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_9 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC10)
#define BSW_BSWM_CS_TXCTRL_FUNC10 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_10 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC11)
#define BSW_BSWM_CS_TXCTRL_FUNC11 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_11 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC12)
#define BSW_BSWM_CS_TXCTRL_FUNC12 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_12 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC13)
#define BSW_BSWM_CS_TXCTRL_FUNC13 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_13 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC14)
#define BSW_BSWM_CS_TXCTRL_FUNC14 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_14 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC15)
#define BSW_BSWM_CS_TXCTRL_FUNC15 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_15 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC16)
#define BSW_BSWM_CS_TXCTRL_FUNC16 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_16 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC17)
#define BSW_BSWM_CS_TXCTRL_FUNC17 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_17 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC18)
#define BSW_BSWM_CS_TXCTRL_FUNC18 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_18 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC19)
#define BSW_BSWM_CS_TXCTRL_FUNC19 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_19 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC20)
#define BSW_BSWM_CS_TXCTRL_FUNC20 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_20 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC21)
#define BSW_BSWM_CS_TXCTRL_FUNC21 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_21 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC22)
#define BSW_BSWM_CS_TXCTRL_FUNC22 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_22 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC23)
#define BSW_BSWM_CS_TXCTRL_FUNC23 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_23 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC24)
#define BSW_BSWM_CS_TXCTRL_FUNC24 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_24 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC25)
#define BSW_BSWM_CS_TXCTRL_FUNC25 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_25 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC26)
#define BSW_BSWM_CS_TXCTRL_FUNC26 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_26 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC27)
#define BSW_BSWM_CS_TXCTRL_FUNC27 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_27 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC28)
#define BSW_BSWM_CS_TXCTRL_FUNC28 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_28 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC29)
#define BSW_BSWM_CS_TXCTRL_FUNC29 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_29 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC30)
#define BSW_BSWM_CS_TXCTRL_FUNC30 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_30 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_BSWM_CS_TXCTRL_FUNC31)
#define BSW_BSWM_CS_TXCTRL_FUNC31 ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_31 != BSW_BSWM_CS_TXCTRL_NOUSE) ? BSW_USE : BSW_NOUSE)

#define BSW_BSWM_CS_SENDSTPW_INVALID               (0U)    /* Invalid value for  transmission start wait time at power-on */
#define BSW_BSWM_CS_NETWORK(type, channel)         (BSW_COMM_BUS_TYPE_OFFSET(type) + (channel))    /* Channel -> Network handle conversion macro */
#define BSW_BSWM_CS_SND_START_PW_DIRECT(channel)   (BSW_BSWM_CS_CFG_SENDSTART_PW_##channel)
#define BSW_BSWM_CS_SND_START_PNC(channel)         (BSW_BSWM_CS_CFG_SENDSTART_PN_##channel)
#define BSW_BSWM_CS_ENABLE_PERI_PNC(channel)       (BSW_BSWM_CS_CFG_ENABLPERI_PN_##channel)

/* Transmission start waiting time getting macro for protocol       */
/* type   :Protocol type                       */
/* -------------------------------------------- */
/*  Protocols       | Setting value                   */
/* -------------------------------------------- */
/*  Can              | CAN                      */
/*  Ethernet         | ETH                      */
/*  Lin              | LIN                      */
/*  CDD1             | CDD1                     */
/*  CDD2             | CDD2                     */
/* -------------------------------------------- */
/* channel: Relative channel number for each protocol    */
#define BSW_BSWM_CS_SEND_START_PW(type, channel)    BSW_BSWM_CS_SEND_START_PW_0(type, channel)
#define BSW_BSWM_CS_SEND_START_PW_0(type, channel)  ((BSW_BSWM_CS_NETWORK(type, channel) == 0U)  ? BSW_BSWM_CS_CFG_SENDSTART_PW_0  : BSW_BSWM_CS_SEND_START_PW_1(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_1(type, channel)  ((BSW_BSWM_CS_NETWORK(type, channel) == 1U)  ? BSW_BSWM_CS_CFG_SENDSTART_PW_1  : BSW_BSWM_CS_SEND_START_PW_2(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_2(type, channel)  ((BSW_BSWM_CS_NETWORK(type, channel) == 2U)  ? BSW_BSWM_CS_CFG_SENDSTART_PW_2  : BSW_BSWM_CS_SEND_START_PW_3(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_3(type, channel)  ((BSW_BSWM_CS_NETWORK(type, channel) == 3U)  ? BSW_BSWM_CS_CFG_SENDSTART_PW_3  : BSW_BSWM_CS_SEND_START_PW_4(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_4(type, channel)  ((BSW_BSWM_CS_NETWORK(type, channel) == 4U)  ? BSW_BSWM_CS_CFG_SENDSTART_PW_4  : BSW_BSWM_CS_SEND_START_PW_5(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_5(type, channel)  ((BSW_BSWM_CS_NETWORK(type, channel) == 5U)  ? BSW_BSWM_CS_CFG_SENDSTART_PW_5  : BSW_BSWM_CS_SEND_START_PW_6(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_6(type, channel)  ((BSW_BSWM_CS_NETWORK(type, channel) == 6U)  ? BSW_BSWM_CS_CFG_SENDSTART_PW_6  : BSW_BSWM_CS_SEND_START_PW_7(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_7(type, channel)  ((BSW_BSWM_CS_NETWORK(type, channel) == 7U)  ? BSW_BSWM_CS_CFG_SENDSTART_PW_7  : BSW_BSWM_CS_SEND_START_PW_8(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_8(type, channel)  ((BSW_BSWM_CS_NETWORK(type, channel) == 8U)  ? BSW_BSWM_CS_CFG_SENDSTART_PW_8  : BSW_BSWM_CS_SEND_START_PW_9(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_9(type, channel)  ((BSW_BSWM_CS_NETWORK(type, channel) == 9U)  ? BSW_BSWM_CS_CFG_SENDSTART_PW_9  : BSW_BSWM_CS_SEND_START_PW_10(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_10(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 10U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_10 : BSW_BSWM_CS_SEND_START_PW_11(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_11(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 11U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_11 : BSW_BSWM_CS_SEND_START_PW_12(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_12(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 12U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_12 : BSW_BSWM_CS_SEND_START_PW_13(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_13(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 13U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_13 : BSW_BSWM_CS_SEND_START_PW_14(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_14(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 14U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_14 : BSW_BSWM_CS_SEND_START_PW_15(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_15(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 15U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_15 : BSW_BSWM_CS_SEND_START_PW_16(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_16(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 16U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_16 : BSW_BSWM_CS_SEND_START_PW_17(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_17(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 17U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_17 : BSW_BSWM_CS_SEND_START_PW_18(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_18(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 18U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_18 : BSW_BSWM_CS_SEND_START_PW_19(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_19(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 19U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_19 : BSW_BSWM_CS_SEND_START_PW_20(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_20(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 20U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_20 : BSW_BSWM_CS_SEND_START_PW_21(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_21(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 21U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_21 : BSW_BSWM_CS_SEND_START_PW_22(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_22(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 22U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_22 : BSW_BSWM_CS_SEND_START_PW_23(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_23(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 23U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_23 : BSW_BSWM_CS_SEND_START_PW_24(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_24(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 24U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_24 : BSW_BSWM_CS_SEND_START_PW_25(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_25(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 25U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_25 : BSW_BSWM_CS_SEND_START_PW_26(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_26(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 26U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_26 : BSW_BSWM_CS_SEND_START_PW_27(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_27(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 27U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_27 : BSW_BSWM_CS_SEND_START_PW_28(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_28(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 28U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_28 : BSW_BSWM_CS_SEND_START_PW_29(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_29(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 29U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_29 : BSW_BSWM_CS_SEND_START_PW_30(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_30(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 30U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_30 : BSW_BSWM_CS_SEND_START_PW_31(type, channel))
#define BSW_BSWM_CS_SEND_START_PW_31(type, channel) ((BSW_BSWM_CS_NETWORK(type, channel) == 31U) ? BSW_BSWM_CS_CFG_SENDSTART_PW_31 : BSW_BSWM_CS_SENDSTPW_INVALID )

/* Macro to get the periodic switching transmission function used/unused */
#define BSW_BSWM_CS_TXCTRL_CYCCHG_USE       (BSW_BSWM_CS_TXCTRL_CYCCHG0_USE)
#define BSW_BSWM_CS_TXCTRL_CYCCHG0_USE      ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_0 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG1_USE  )
#define BSW_BSWM_CS_TXCTRL_CYCCHG1_USE      ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_1 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG2_USE  )
#define BSW_BSWM_CS_TXCTRL_CYCCHG2_USE      ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_2 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG3_USE  )
#define BSW_BSWM_CS_TXCTRL_CYCCHG3_USE      ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_3 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG4_USE  )
#define BSW_BSWM_CS_TXCTRL_CYCCHG4_USE      ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_4 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG5_USE  )
#define BSW_BSWM_CS_TXCTRL_CYCCHG5_USE      ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_5 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG6_USE  )
#define BSW_BSWM_CS_TXCTRL_CYCCHG6_USE      ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_6 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG7_USE  )
#define BSW_BSWM_CS_TXCTRL_CYCCHG7_USE      ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_7 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG8_USE  )
#define BSW_BSWM_CS_TXCTRL_CYCCHG8_USE      ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_8 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG9_USE  )
#define BSW_BSWM_CS_TXCTRL_CYCCHG9_USE      ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_9 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG10_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG10_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_10 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG11_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG11_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_11 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG12_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG12_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_12 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG13_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG13_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_13 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG14_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG14_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_14 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG15_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG15_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_15 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG16_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG16_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_16 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG17_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG17_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_17 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG18_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG18_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_18 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG19_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG19_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_19 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG20_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG20_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_20 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG21_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG21_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_21 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG22_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG22_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_22 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG23_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG23_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_23 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG24_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG24_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_24 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG25_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG25_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_25 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG26_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG26_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_26 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG27_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG27_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_27 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG28_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG28_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_28 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG29_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG29_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_29 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG30_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG30_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_30 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_BSWM_CS_TXCTRL_CYCCHG31_USE )
#define BSW_BSWM_CS_TXCTRL_CYCCHG31_USE     ( ((BSW_BSWM_CS_CFG_TXCTRL_TYPE_31 & BSW_BSWM_CS_TXCTRL_CYCCHG)  == BSW_BSWM_CS_TXCTRL_CYCCHG) ? BSW_USE : BSW_NOUSE                       )

/* Message authentication pattern of multiplexer PDU */
#define BSW_BSWM_CS_MUX_MA_PTN              (BSW_BSWM_CS_CFG_MUX_MA_PTN)

/* Receive enable type of PNC I-PDU control */
#define BSW_BSWM_CS_PNCIPDU_RX(channel)     (BSW_BSWM_CS_CFG_PNCIPDU_RX_##channel)

/*--------------------------------------------------------------------------*/
/* Types                                                                    */
/*--------------------------------------------------------------------------*/

/*--------------------------------------------------------------------------*/
/* Function Prototypes                                                      */
/*--------------------------------------------------------------------------*/

/*--------------------------------------------------------------------------*/
/* Data                                                                     */
/*--------------------------------------------------------------------------*/

/*--------------------------------------------------------------------------*/
/* Constants                                                                */
/*--------------------------------------------------------------------------*/

#endif /* BSW_BSWM_CS_CONFIG_H */

/****************************************************************************/
/* History                                                                  */
/*  Version         :Date                                                   */
/*  v1-0-0          :2017/04/28                                             */
/*  v1-0-1          :2018/01/30                                             */
/*  v1-1-0          :2018/12/13                                             */
/*  v2-0-0          :2021/12/08                                             */
/*  v2-1-0          :2023/01/26                                             */
/*  v2-2-0          :2023/05/09                                             */
/****************************************************************************/

/**** End of File ***********************************************************/
