/* Copyright  : DENSO CORPORATION */
#ifndef ERRH_CFG_H
#define ERRH_CFG_H


extern	void	__SYNCP( void );

void ErrH_AlarmInterruptCallout( uint16 t_u2ErrorID );
void ErrH_ProtectionHookCallout( void );

/* BSW_CFG_TARGET = 10	RH850/U2B6  292Pin 使用コア2 */
/* BSW_CFG_TARGET = 11	RH850/U2B10 292Pin 使用コア2 */
/* BSW_CFG_TARGET = 12	RH850/U2B10 373Pin 使用コア2 */
/* BSW_CFG_TARGET = 13	RH850/U2B10 292Pin 使用コア2 */
/* BSW_CFG_TARGET = 14	RH850/U2B10 373Pin 使用コア2 */
/* BSW_CFG_TARGET = 15	RH850/U2B6  292Pin 使用コア3 */
/* BSW_CFG_TARGET = 16	RH850/U2B10 292Pin 使用コア3 */
/* BSW_CFG_TARGET = 17	RH850/U2B10 373Pin 使用コア3 */
/* BSW_CFG_TARGET = 18	RH850/U2B10 292Pin 使用コア3 */
/* BSW_CFG_TARGET = 19	RH850/U2B10 373Pin 使用コア3 */
/* BSW_CFG_TARGET = 20	RH850/U2B10 292Pin 使用コア4 */
/* BSW_CFG_TARGET = 21	RH850/U2B10 373Pin 使用コア4 */
/* BSW_CFG_TARGET = 22	RH850/U2A6  292Pin 使用コア2 */
/* BSW_CFG_TARGET = 23	RH850/U2A16 373Pin 使用コア4 */
#if	MCAL_PKG_U2A_TARGET == MCAL_PKG_U2A6_292PIN
#define		BSW_CFG_TARGET					(22U)
#elif MCAL_PKG_U2A_TARGET == MCAL_PKG_U2A16_373PIN
#define		BSW_CFG_TARGET					(23U)
#elif MCAL_PKG_U2A_TARGET == MCAL_PKG_U2A16_516PIN
#error "U2A16 516PIN is not supported"
#elif MCAL_PKG_U2A_TARGET == MCAL_PKG_U2A8_292PIN
#error "U2A8 292PIN is not supported"
#else
#error "Unknown MCU type"
#endif

#define	DI_ALL()	SuspendAllInterrupts()

#define	EI_ALL()	ResumeAllInterrupts()

/************************************************************************************************/
/*	Service name		:	GetCoreId															*/
/*	Reentrancy			:	Concurrency safe													*/
/*	Parameters(in)		:	none																*/
/*	Return value		:	Core ID																*/
/*	Caveat				:	none																*/
/************************************************************************************************/
#define Bswlib_GetCoreId()	((U4)u4_g_GetCoreId())



/************************************************************************************************/
/*	Service name		:	Sync_Pipeline_1														*/
/*	Reentrancy			:	Concurrency safe													*/
/*	Parameters(in)		:	Register															*/
/*	Return value		:	none																*/
/*	Caveat				:	U1型のレジスタ以外で使用しないこと。								*/
/************************************************************************************************/
#define		Bswlib_Sync_Pipeline_1( t_u1Data )													\
	do																							\
	{																							\
		volatile	U1	t_u1BswLibDummy;														\
		t_u1BswLibDummy = (t_u1Data);															\
		__SYNCP();																				\
	}	while(0)

/************************************************************************************************/
/*	Service name		:	Sync_Pipeline_2														*/
/*	Reentrancy			:	Concurrency safe													*/
/*	Parameters(in)		:	Register															*/
/*	Return value		:	none																*/
/*	Caveat				:	U2型のレジスタ以外で使用しないこと。								*/
/************************************************************************************************/
#define		Bswlib_Sync_Pipeline_2( t_u2Data )													\
	do																							\
	{																							\
		volatile	U2	t_u2BswLibDummy;														\
		t_u2BswLibDummy = (t_u2Data);															\
		__SYNCP();																				\
	}	while(0)

/************************************************************************************************/
/*	Service name		:	Sync_Pipeline_4														*/
/*	Reentrancy			:	Concurrency safe													*/
/*	Parameters(in)		:	Register															*/
/*	Return value		:	none																*/
/*	Caveat				:	U4型のレジスタ以外で使用しないこと。								*/
/************************************************************************************************/
#define		Bswlib_Sync_Pipeline_4( t_u4Data )													\
	do																							\
	{																							\
		volatile	U4	t_u4BswLibDummy;														\
		t_u4BswLibDummy = (t_u4Data);															\
		__SYNCP();																				\
	}	while(0)




/* 							  EI/FE選択					 割り込み許可				エラー時リセット		初期通知設定				  エラー端子出力			   U2A16 U2A6			*/
/* 							  ECMISCFG					 ECMISCFG					ECMIRCFG											  ECMEMK					    373  292			*/
#define ERRH_UCFG_NCF0_MODE   (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 0:   x    x     エラー出力モニタ */
#define ERRH_UCFG_NCF1_MODE   (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 1:   -    -     予約 */
#define ERRH_UCFG_NCF2_MODE   (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 2:   x    x     ECMmESET モニタ */
#define ERRH_UCFG_NCF3_MODE   (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 3:   x    x     ECMmESET0 モニタ */
#define ERRH_UCFG_NCF4_MODE   (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 4:   x    x     ECMmESET1 モニタ */
#define ERRH_UCFG_NCF5_MODE   (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 5:   x    -     ECMmESET2 モニタ */
#define ERRH_UCFG_NCF6_MODE   (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 6:   x    -     ECMmESET3 モニタ */
#define ERRH_UCFG_NCF7_MODE   (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 7:   -    -     予約 */
#define ERRH_UCFG_NCF8_MODE   (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 8:   -    -     予約 */
#define ERRH_UCFG_NCF9_MODE   (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 9:   -    -     予約 */
#define ERRH_UCFG_NCF10_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 10:  -    -     予約 */
#define ERRH_UCFG_NCF11_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 11:  x    x     ディレイタイマオーバーフロー(エラー出力) */
#define ERRH_UCFG_NCF12_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 12:  -    -     予約 */
#define ERRH_UCFG_NCF13_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 13:  -    -     予約 */
#define ERRH_UCFG_NCF14_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 14:  -    -     予約 */
#define ERRH_UCFG_NCF15_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 15:  -    -     予約 */
#define ERRH_UCFG_NCF16_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 16:  -    -     予約 */
#define ERRH_UCFG_NCF17_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 17:  -    -     予約 */
#define ERRH_UCFG_NCF18_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 18:  -    -     予約 */
#define ERRH_UCFG_NCF19_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 19:  -    -     予約 */
#define ERRH_UCFG_NCF20_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 20:  x    x     ECM コンペアエラー */
#define ERRH_UCFG_NCF21_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 21:  -    -     予約 */
#define ERRH_UCFG_NCF22_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 22:  -    -     予約 */
#define ERRH_UCFG_NCF23_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 23:  -    -     予約 */
#define ERRH_UCFG_NCF24_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 24:  x    x     モードエラー 製造テストモードの意図しないアクティブ化 */
#define ERRH_UCFG_NCF25_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 25:  x    x     モードエラー 通常動作モードの意図しないアクティブ化 */
#define ERRH_UCFG_NCF26_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 26:  x    x     モードエラー 通常動作モードの意図しない非アクティブ化 */
#define ERRH_UCFG_NCF27_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 27:  x    x     モードエラー シリアルプログラミングモードの意図しないアクティブ化 */
#define ERRH_UCFG_NCF28_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 28:  x    x     モードエラー ユーザブートモードの意図しないアクティブ化 */
#define ERRH_UCFG_NCF29_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 29:  x    x     モードエラー ユーザブートモードの意図しない非アクティブ化 */
#define ERRH_UCFG_NCF30_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 30:  x    x     モードエラー モードチェックエラー */
#define ERRH_UCFG_NCF31_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 31:  -    -     予約 */
#define ERRH_UCFG_NCF32_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 32:  x    x     フラッシュアクセスエラー */
#define ERRH_UCFG_NCF33_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 33:  x    x     FACI リセット転送エラー */
#define ERRH_UCFG_NCF34_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 34:  x    x     BIST パラメータ転送エラー */
#define ERRH_UCFG_NCF35_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 35:  -    -     予約 */
#define ERRH_UCFG_NCF36_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 36:  x    x     DTS コンペアエラー */
#define ERRH_UCFG_NCF37_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 37:  x    x     sDMACのバスブリッジコンペアエラー */
#define ERRH_UCFG_NCF38_MODE  (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE0 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 38:  x    x     バスブリッジコンペアエラー */
#define ERRH_UCFG_NCF39_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 39:  -    -     予約 */
#define ERRH_UCFG_NCF40_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 40:  x    x     プロセッサ間要素バスルーティングエラー */
#define ERRH_UCFG_NCF41_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 41:  x    x     クラスタ間バス(IBus)ルーティングエラー */
#define ERRH_UCFG_NCF42_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 42:  x    x     周辺機器バス(P-Bus)ルーティングエラー */
#define ERRH_UCFG_NCF43_MODE  (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE0 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 43:  x    x     CRAMバスルーティングエラー */
#define ERRH_UCFG_NCF44_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 44:  x    x     システムバスルーティングエラー */
#define ERRH_UCFG_NCF45_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 45:  x    x     グローバルフラッシュバスルーティングエラー */
#define ERRH_UCFG_NCF46_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 46:  x    x     ローカルフラッシュバスルーティングエラー */
#define ERRH_UCFG_NCF47_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 47:  -    -     予約 */
#define ERRH_UCFG_NCF48_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 48:  x    x     CLK_MOSCのクロックモニタエラー */
#define ERRH_UCFG_NCF49_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 49:  x    x     CLK_WDTのクロックモニタエラー */
#define ERRH_UCFG_NCF50_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 50:  x    x     CLK_LSIOSCのクロックモニタエラー */
#define ERRH_UCFG_NCF51_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 51:  x    x     CLK_LSBのクロックモニタエラー */
#define ERRH_UCFG_NCF52_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 52:  x    x     CLK_UHSBのクロックモニタエラー */
#define ERRH_UCFG_NCF53_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 53:  x    x     CLK_HBUSのクロックモニタエラー */
#define ERRH_UCFG_NCF54_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 54:  -    -     予約 */
#define ERRH_UCFG_NCF55_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 55:  -    -     予約 */
#define ERRH_UCFG_NCF56_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 56:  x    x     OSTM1割り込み */
#define ERRH_UCFG_NCF57_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 57:  x    x     OSTM2割り込み */
#define ERRH_UCFG_NCF58_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 58:  x    x     OSTM3割り込み */
#define ERRH_UCFG_NCF59_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 59:  x    x     OSTM4割り込み */
#define ERRH_UCFG_NCF60_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 60:  x    x     OSTM5割り込み */
#define ERRH_UCFG_NCF61_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 61:  x    -     OSTM6割り込み */
#define ERRH_UCFG_NCF62_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 62:  x    -     OSTM7割り込み */
#define ERRH_UCFG_NCF63_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 63:  x    x     OSTM8割り込み */
#define ERRH_UCFG_NCF64_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 64:  x    x     OSTM9割り込み */
#define ERRH_UCFG_NCF65_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 65:  -    -     予約 */
#define ERRH_UCFG_NCF66_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 66:  -    -     予約 */
#define ERRH_UCFG_NCF67_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 67:  -    -     予約 */
#define ERRH_UCFG_NCF68_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 68:  -    -     予約 */
#define ERRH_UCFG_NCF69_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 69:  -    -     予約 */
#define ERRH_UCFG_NCF70_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 70:  -    -     予約 */
#define ERRH_UCFG_NCF71_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 71:  -    -     予約 */
#define ERRH_UCFG_NCF72_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 72:  x    x     A/Dコンバータパリティエラー */
#define ERRH_UCFG_NCF73_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 73:  -    -     予約 */
#define ERRH_UCFG_NCF74_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 74:  -    -     予約 */
#define ERRH_UCFG_NCF75_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 75:  -    -     予約 */
#define ERRH_UCFG_NCF76_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 76:  x    x     温度センサーエラー */
#define ERRH_UCFG_NCF77_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 77:  -    -     予約 */
#define ERRH_UCFG_NCF78_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 78:  -    -     予約 */
#define ERRH_UCFG_NCF79_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 79:  -    -     予約 */
#define ERRH_UCFG_NCF80_MODE  (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE0 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 80:  x    x     コードフラッシュ、アドレスパリティエラー */
#define ERRH_UCFG_NCF81_MODE  (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE0 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 81:  x    x     コードフラッシュ、データECC 2ビットエラー */
#define ERRH_UCFG_NCF82_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 82:  x    x     コードフラッシュ、データECC 1ビットエラー */
#define ERRH_UCFG_NCF83_MODE  (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE0 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 83:  x    x     コードフラッシュ、ECCオーバーフローエラー */
#define ERRH_UCFG_NCF84_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 84:  -    -     予約 */
#define ERRH_UCFG_NCF85_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 85:  -    -     予約 */
#define ERRH_UCFG_NCF86_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 86:  -    -     予約 */
#define ERRH_UCFG_NCF87_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 87:  -    -     予約 */
#define ERRH_UCFG_NCF88_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 88:  x    x     データフラッシュ、データECC 2ビットエラー */
#define ERRH_UCFG_NCF89_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 89:  x    x     データフラッシュ、データECC 1ビットエラー */
#define ERRH_UCFG_NCF90_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 90:  x    x     データフラッシュ、ECCオーバーフローエラー */
#define ERRH_UCFG_NCF91_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 91:  -    -     予約 */
#define ERRH_UCFG_NCF92_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 92:  -    -     予約 */
#define ERRH_UCFG_NCF93_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 93:  -    -     予約 */
#define ERRH_UCFG_NCF94_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 94:  -    -     予約 */
#define ERRH_UCFG_NCF95_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 95:  -    -     予約 */
#define ERRH_UCFG_NCF96_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 96:  x    x     Local RAM、データECC 2ビットエラー */
#define ERRH_UCFG_NCF97_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 97:  x    x     Local RAM、データECC 1ビットエラー */
#define ERRH_UCFG_NCF98_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 98:  x    x     Local RAM、ECCオーバーフローエラー */
#define ERRH_UCFG_NCF99_MODE  (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 99:  -    -     予約 */
#define ERRH_UCFG_NCF100_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 100: -    -     予約 */
#define ERRH_UCFG_NCF101_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 101: -    -     予約 */
#define ERRH_UCFG_NCF102_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 102: -    -     予約 */
#define ERRH_UCFG_NCF103_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 103: -    -     予約 */
#define ERRH_UCFG_NCF104_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE0 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 104: x    x     クラスタRAM、アドレスフィードバックコンペアエラー、データECC 2ビットエラー */
#define ERRH_UCFG_NCF105_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE0 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 105: x    x     クラスタRAM、データECC 1ビットエラー */
#define ERRH_UCFG_NCF106_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE0 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 106: x    x     クラスタRAM、ECCオーバーフローエラー */
#define ERRH_UCFG_NCF107_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 107: -    -     予約 */
#define ERRH_UCFG_NCF108_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 108: -    -     予約 */
#define ERRH_UCFG_NCF109_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 109: -    -     予約 */
#define ERRH_UCFG_NCF110_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 110: -    -     予約 */
#define ERRH_UCFG_NCF111_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 111: -    -     予約 */
#define ERRH_UCFG_NCF112_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 112: x    x     DTSRAM、アドレスフィードバックコンペアエラー、データECC 2ビットエラー */
#define ERRH_UCFG_NCF113_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 113: x    x     DTSRAM、データECC 1ビットエラー */
#define ERRH_UCFG_NCF114_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 114: x    x     DTSRAM、ECCオーバーフローエラー */
#define ERRH_UCFG_NCF115_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 115: -    -     予約 */
#define ERRH_UCFG_NCF116_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 116: -    -     予約 */
#define ERRH_UCFG_NCF117_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 117: -    -     予約 */
#define ERRH_UCFG_NCF118_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 118: -    -     予約 */
#define ERRH_UCFG_NCF119_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 119: -    -     予約 */
#define ERRH_UCFG_NCF120_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 120: x    x     sDMAC0 RAM ECC 2ビットエラー */
#define ERRH_UCFG_NCF121_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 121: x    x     sDMAC0 RAM ECC 1ビットエラー */
#define ERRH_UCFG_NCF122_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 122: x    x     sDMAC1 RAM ECC 2ビットエラー */
#define ERRH_UCFG_NCF123_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 123: x    x     sDMAC1 RAM ECC 1ビットエラー */
#define ERRH_UCFG_NCF124_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 124: -    -     予約 */
#define ERRH_UCFG_NCF125_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 125: -    -     予約 */
#define ERRH_UCFG_NCF126_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 126: -    -     予約 */
#define ERRH_UCFG_NCF127_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 127: -    -     予約 */
#define ERRH_UCFG_NCF128_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 128: x    x     周辺(FlexRay RAM) ECC 2ビットエラー */
#define ERRH_UCFG_NCF129_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 129: x    x     周辺(FlexRay RAM) ECC 1ビットエラー */
#define ERRH_UCFG_NCF130_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 130: x    x     周辺(RS-CANFD) RAM ECC 2ビットエラー */
#define ERRH_UCFG_NCF131_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 131: x    x     周辺(RS-CANFD) RAM ECC 1ビットエラー */
#define ERRH_UCFG_NCF132_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 132: x    x     周辺(MSPI) RAM ECC 2ビットエラー */
#define ERRH_UCFG_NCF133_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 133: x    x     周辺(MSPI) RAM ECC 1ビットエラー */
#define ERRH_UCFG_NCF134_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 134: x    x     周辺(GTM) RAM ECC 2ビットエラー */
#define ERRH_UCFG_NCF135_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 135: x    x     周辺(GTM) RAM ECC 1ビットエラー */
#define ERRH_UCFG_NCF136_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 136: x    x     周辺(ファーストイーサネット) RAM ECC 2ビットエラー */
#define ERRH_UCFG_NCF137_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 137: x    x     周辺(ファーストイーサネット) RAM ECC 1ビットエラー */
#define ERRH_UCFG_NCF138_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 138: x    -     周辺(ギガビットイーサネット) RAM ECC 2ビットエラー */
#define ERRH_UCFG_NCF139_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 139: x    -     周辺(ギガビットイーサネット) RAM ECC 1ビットエラー */
#define ERRH_UCFG_NCF140_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 140: x    x     周辺(MMCA) RAM ECC 2ビットエラー */
#define ERRH_UCFG_NCF141_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 141: x    x     周辺(MMCA) RAM ECC 1ビットエラー */
#define ERRH_UCFG_NCF142_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 142: -    -     予約 */
#define ERRH_UCFG_NCF143_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 143: -    -     予約 */
#define ERRH_UCFG_NCF144_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 144: -    -     予約 */
#define ERRH_UCFG_NCF145_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 145: -    -     予約 */
#define ERRH_UCFG_NCF146_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 146: -    -     予約 */
#define ERRH_UCFG_NCF147_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 147: -    -     予約 */
#define ERRH_UCFG_NCF148_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 148: -    -     予約 */
#define ERRH_UCFG_NCF149_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 149: -    -     予約 */
#define ERRH_UCFG_NCF150_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 150: -    -     予約 */
#define ERRH_UCFG_NCF151_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 151: -    -     予約 */
#define ERRH_UCFG_NCF152_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 152: -    -     予約 */
#define ERRH_UCFG_NCF153_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 153: -    -     予約 */
#define ERRH_UCFG_NCF154_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 154: -    -     予約 */
#define ERRH_UCFG_NCF155_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 155: -    -     予約 */
#define ERRH_UCFG_NCF156_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 156: -    -     予約 */
#define ERRH_UCFG_NCF157_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 157: -    -     予約 */
#define ERRH_UCFG_NCF158_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 158: -    -     予約 */
#define ERRH_UCFG_NCF159_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 159: x    x     周辺(DTSを除く) RAM エラーアドレスオーバフロー */
#define ERRH_UCFG_NCF160_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE0 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 160: x    x     Data transfer path アドレスEDC エラー */
#define ERRH_UCFG_NCF161_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE0 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 161: x    x     Data transfer path ECC 2ビットエラー */
#define ERRH_UCFG_NCF162_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 162: x    x     Data transfer path ECC 1ビットエラー */
#define ERRH_UCFG_NCF163_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 163: -    -     予約 */
#define ERRH_UCFG_NCF164_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 164: -    -     予約 */
#define ERRH_UCFG_NCF165_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 165: -    -     予約 */
#define ERRH_UCFG_NCF166_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 166: -    -     予約 */
#define ERRH_UCFG_NCF167_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 167: -    -     予約 */
#define ERRH_UCFG_NCF168_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 168: x    x     CRAM ガードエラー */
#define ERRH_UCFG_NCF169_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 169: x    x     I-Bus ガードエラー */
#define ERRH_UCFG_NCF170_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 170: x    x     P-Bus ガードエラー (including INTC2, DTS and sDMAC Guard error) */
#define ERRH_UCFG_NCF171_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 171: x    x     H-Bus ガードエラー */
#define ERRH_UCFG_NCF172_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 172: -    -     予約 */
#define ERRH_UCFG_NCF173_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 173: -    -     予約 */
#define ERRH_UCFG_NCF174_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 174: -    -     予約 */
#define ERRH_UCFG_NCF175_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 175: -    -     予約 */
#define ERRH_UCFG_NCF176_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 176: -    -     予約 */
#define ERRH_UCFG_NCF177_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 177: -    -     予約 */
#define ERRH_UCFG_NCF178_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 178: -    -     予約 */
#define ERRH_UCFG_NCF179_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 179: -    -     予約 */
#define ERRH_UCFG_NCF180_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 180: -    -     予約 */
#define ERRH_UCFG_NCF181_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 181: -    -     予約 */
#define ERRH_UCFG_NCF182_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 182: x    x     DTS 転送エラー/DMA アドレスエラー */
#define ERRH_UCFG_NCF183_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 183: x    x     H-Bus マスタ転送エラー */
#define ERRH_UCFG_NCF184_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 184: x    x     外部エラー入力 0 */
#define ERRH_UCFG_NCF185_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 185: x    x     外部エラー入力 1 */
#define ERRH_UCFG_NCF186_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 186: x    -     外部エラー入力 2 */
#define ERRH_UCFG_NCF187_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 187: x    -     外部エラー入力 3 */
#define ERRH_UCFG_NCF188_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 188: -    -     予約 */
#define ERRH_UCFG_NCF189_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 189: -    -     予約 */
#define ERRH_UCFG_NCF190_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 190: -    -     予約 */
#define ERRH_UCFG_NCF191_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 191: -    -     予約 */
#define ERRH_UCFG_NCF192_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 192: x    x     ソフトウェアアラーム 0 */
#define ERRH_UCFG_NCF193_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 193: x    x     ソフトウェアアラーム 1 */
#define ERRH_UCFG_NCF194_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 194: x    -     ソフトウェアアラーム 2 */
#define ERRH_UCFG_NCF195_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 195: x    -     ソフトウェアアラーム 3 */
#define ERRH_UCFG_NCF196_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 196: -    -     予約 */
#define ERRH_UCFG_NCF197_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 197: -    -     予約 */
#define ERRH_UCFG_NCF198_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 198: -    -     予約 */
#define ERRH_UCFG_NCF199_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 199: -    -     予約 */
#define ERRH_UCFG_NCF200_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 200: -    -     予約 */
#define ERRH_UCFG_NCF201_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 201: -    -     予約 */
#define ERRH_UCFG_NCF202_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 202: -    -     予約 */
#define ERRH_UCFG_NCF203_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 203: -    -     予約 */
#define ERRH_UCFG_NCF204_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 204: -    -     予約 */
#define ERRH_UCFG_NCF205_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 205: -    -     予約 */
#define ERRH_UCFG_NCF206_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 206: -    -     予約 */
#define ERRH_UCFG_NCF207_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 207: -    -     予約 */
#define ERRH_UCFG_NCF208_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 208: -    -     予約 */
#define ERRH_UCFG_NCF209_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 209: -    -     予約 */
#define ERRH_UCFG_NCF210_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 210: -    -     予約 */
#define ERRH_UCFG_NCF211_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 211: -    -     予約 */
#define ERRH_UCFG_NCF212_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 212: -    -     予約 */
#define ERRH_UCFG_NCF213_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 213: -    -     予約 */
#define ERRH_UCFG_NCF214_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 214: -    -     予約 */
#define ERRH_UCFG_NCF215_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 215: -    -     予約 */
#define ERRH_UCFG_NCF216_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 216: -    -     予約 */
#define ERRH_UCFG_NCF217_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 217: -    -     予約 */
#define ERRH_UCFG_NCF218_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 218: -    -     予約 */
#define ERRH_UCFG_NCF219_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 219: -    -     予約 */
#define ERRH_UCFG_NCF220_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 220: -    -     予約 */
#define ERRH_UCFG_NCF221_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 221: -    -     予約 */
#define ERRH_UCFG_NCF222_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 222: -    -     予約 */
#define ERRH_UCFG_NCF223_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 223: -    -     予約 */
#define ERRH_UCFG_NCF224_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 224: x    x     DCLS コンペアエラー(PE0) */
#define ERRH_UCFG_NCF225_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 225: -    -     予約 */
#define ERRH_UCFG_NCF226_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 226: -    -     予約 */
#define ERRH_UCFG_NCF227_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 227: x    x     意図しないデバッグ許可を検出(PE0) */
#define ERRH_UCFG_NCF228_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_1 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 228: x    x     ウォッチドッグタイマエラー(PE0) */
#define ERRH_UCFG_NCF229_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 229: x    x     クロックモニタエラー (CLMA6) (PE0) */
#define ERRH_UCFG_NCF230_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 230: -    -     予約 */
#define ERRH_UCFG_NCF231_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 231: -    -     予約 */
#define ERRH_UCFG_NCF232_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE0 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 232: x    x     Local RAM (PE0) ECC 2ビットエラー, アドレスフィードバックコンペアエラー */
#define ERRH_UCFG_NCF233_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 233: x    x     Local RAM (PE0) ECC 1ビットエラー */
#define ERRH_UCFG_NCF234_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE0 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 234: x    x     Local RAM (PE0) エラーアドレスオーバフロー */
#define ERRH_UCFG_NCF235_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 235: -    -     予約 */
#define ERRH_UCFG_NCF236_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE0 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 236: x    x     命令キャッシュRAM(PE0) データEDCエラー, アドレスフィードバックコンペアエラー */
#define ERRH_UCFG_NCF237_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 237: -    -     予約 */
#define ERRH_UCFG_NCF238_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 238: -    -     予約 */
#define ERRH_UCFG_NCF239_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 239: -    -     予約 */
#define ERRH_UCFG_NCF240_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 240: x    x     PE ガードエラー (PE0) */
#define ERRH_UCFG_NCF241_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 241: x    x     PE ガードエラー (PE0) PE0 から他のLRAM へのリード要求を検出 */
#define ERRH_UCFG_NCF242_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 242: -    -     予約 */
#define ERRH_UCFG_NCF243_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 243: -    -     予約 */
#define ERRH_UCFG_NCF244_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 244: -    -     予約 */
#define ERRH_UCFG_NCF245_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 245: -    -     予約 */
#define ERRH_UCFG_NCF246_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 246: -    -     予約 */
#define ERRH_UCFG_NCF247_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 247: -    -     予約 */
#define ERRH_UCFG_NCF248_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 248: -    -     予約 */
#define ERRH_UCFG_NCF249_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 249: -    -     予約 */
#define ERRH_UCFG_NCF250_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 250: -    -     予約 */
#define ERRH_UCFG_NCF251_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 251: -    -     予約 */
#define ERRH_UCFG_NCF252_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 252: -    -     予約 */
#define ERRH_UCFG_NCF253_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 253: -    -     予約 */
#define ERRH_UCFG_NCF254_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 254: -    -     予約 */
#define ERRH_UCFG_NCF255_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 255: x    x     データアクセスエラー (PE0) */
#define ERRH_UCFG_NCF256_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 256: x    x     DCLS コンペアエラー (PE1) */
#define ERRH_UCFG_NCF257_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 257: -    -     予約 */
#define ERRH_UCFG_NCF258_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 258: -    -     予約 */
#define ERRH_UCFG_NCF259_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 259: x    x     意図しないデバッグ許可を検出 (PE1) */
#define ERRH_UCFG_NCF260_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_1 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 260: x    x     ウォッチドッグタイマエラー (PE1) */
#define ERRH_UCFG_NCF261_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 261: x    x     クロックモニタエラー (CLMA7) (PE1) */
#define ERRH_UCFG_NCF262_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 262: -    -     予約 */
#define ERRH_UCFG_NCF263_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 263: -    -     予約 */
#define ERRH_UCFG_NCF264_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE1 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 264: x    x     Local RAM (PE1) ECC 2ビットエラー, アドレスフィードバックコンペアエラー */
#define ERRH_UCFG_NCF265_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 265: x    x     Local RAM (PE1) ECC 1ビットエラー */
#define ERRH_UCFG_NCF266_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE1 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 266: x    x     Local RAM (PE1) エラーアドレスオーバフロー */
#define ERRH_UCFG_NCF267_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 267: -    -     予約 */
#define ERRH_UCFG_NCF268_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE1 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 268: x    x     命令キャッシュRAM(PE1) データEDCエラー, アドレスフィードバックコンペアエラー */
#define ERRH_UCFG_NCF269_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 269: -    -     予約 */
#define ERRH_UCFG_NCF270_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 270: -    -     予約 */
#define ERRH_UCFG_NCF271_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 271: -    -     予約 */
#define ERRH_UCFG_NCF272_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 272: x    x     PE ガードエラー (PE1) */
#define ERRH_UCFG_NCF273_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 273: x    x     PE ガードエラー (PE1) PE1 から他のLRAM へのリード要求を検出 */
#define ERRH_UCFG_NCF274_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 274: -    -     予約 */
#define ERRH_UCFG_NCF275_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 275: -    -     予約 */
#define ERRH_UCFG_NCF276_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 276: -    -     予約 */
#define ERRH_UCFG_NCF277_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 277: -    -     予約 */
#define ERRH_UCFG_NCF278_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 278: -    -     予約 */
#define ERRH_UCFG_NCF279_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 279: -    -     予約 */
#define ERRH_UCFG_NCF280_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 280: -    -     予約 */
#define ERRH_UCFG_NCF281_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 281: -    -     予約 */
#define ERRH_UCFG_NCF282_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 282: -    -     予約 */
#define ERRH_UCFG_NCF283_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 283: -    -     予約 */
#define ERRH_UCFG_NCF284_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 284: -    -     予約 */
#define ERRH_UCFG_NCF285_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 285: -    -     予約 */
#define ERRH_UCFG_NCF286_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 286: -    -     予約 */
#define ERRH_UCFG_NCF287_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 287: x    x     データアクセスエラー(PE1) */
#define ERRH_UCFG_NCF288_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 288: x    -     DCLS コンペアエラー (PE2) */
#define ERRH_UCFG_NCF289_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 289: -    -     予約 */
#define ERRH_UCFG_NCF290_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 290: -    -     予約 */
#define ERRH_UCFG_NCF291_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 291: x    -     意図しないデバッグ許可を検出 (PE2) */
#define ERRH_UCFG_NCF292_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_1 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 292: x    -     ウォッチドッグタイマエラー (PE2) */
#define ERRH_UCFG_NCF293_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 293: x    -     クロックモニタエラー (CLMA8) (PE2) */
#define ERRH_UCFG_NCF294_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 294: -    -     予約 */
#define ERRH_UCFG_NCF295_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 295: -    -     予約 */
#define ERRH_UCFG_NCF296_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE2 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 296: x    -     Local RAM (PE2) ECC 2ビットエラー, アドレスフィードバックコンペアエラー */
#define ERRH_UCFG_NCF297_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 297: x    -     Local RAM (PE2) ECC 1ビットエラー */
#define ERRH_UCFG_NCF298_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE2 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 298: x    -     Local RAM (PE2) エラーアドレスオーバフロー */
#define ERRH_UCFG_NCF299_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 299: -    -     予約 */
#define ERRH_UCFG_NCF300_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE2 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 300: x    -     命令キャッシュRAM(PE2) ECC 2ビットエラー, アドレスフィードバックコンペアエラー */
#define ERRH_UCFG_NCF301_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 301: -    -     予約 */
#define ERRH_UCFG_NCF302_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 302: -    -     予約 */
#define ERRH_UCFG_NCF303_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 303: -    -     予約 */
#define ERRH_UCFG_NCF304_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 304: x    -     PE ガードエラー (PE2) */
#define ERRH_UCFG_NCF305_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 305: x    -     PE ガードエラー (PE2) PE2 から他のLRAM へのリード要求を検出 */
#define ERRH_UCFG_NCF306_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 306: -    -     予約 */
#define ERRH_UCFG_NCF307_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 307: -    -     予約 */
#define ERRH_UCFG_NCF308_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 308: -    -     予約 */
#define ERRH_UCFG_NCF309_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 309: -    -     予約 */
#define ERRH_UCFG_NCF310_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 310: -    -     予約 */
#define ERRH_UCFG_NCF311_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 311: -    -     予約 */
#define ERRH_UCFG_NCF312_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 312: -    -     予約 */
#define ERRH_UCFG_NCF313_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 313: -    -     予約 */
#define ERRH_UCFG_NCF314_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 314: -    -     予約 */
#define ERRH_UCFG_NCF315_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 315: -    -     予約 */
#define ERRH_UCFG_NCF316_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 316: -    -     予約 */
#define ERRH_UCFG_NCF317_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 317: -    -     予約 */
#define ERRH_UCFG_NCF318_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 318: -    -     予約 */
#define ERRH_UCFG_NCF319_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 319: x    -     データアクセスエラー (PE2) */
#define ERRH_UCFG_NCF320_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 320: x    -     DCLS コンペアエラー (PE3) */
#define ERRH_UCFG_NCF321_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 321: -    -     予約 */
#define ERRH_UCFG_NCF322_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 322: -    -     予約 */
#define ERRH_UCFG_NCF323_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 323: x    -     意図しないデバッグ許可を検出 (PE3) */
#define ERRH_UCFG_NCF324_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_1 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 324: x    -     ウォッチドッグタイマエラー　(PE3) */
#define ERRH_UCFG_NCF325_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 325: x    -     クロックモニタエラー (CLMA9) (PE3) */
#define ERRH_UCFG_NCF326_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 326: -    -     予約 */
#define ERRH_UCFG_NCF327_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 327: -    -     予約 */
#define ERRH_UCFG_NCF328_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE3 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 328: x    -     Local RAM (PE3) ECC 2ビットエラー, アドレスフィードバックコンペアエラー */
#define ERRH_UCFG_NCF329_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 329: x    -     Local RAM (PE3) ECC 1ビットエラー */
#define ERRH_UCFG_NCF330_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE3 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 330: x    -     Local RAM (PE3) エラーアドレスオーバフロー */
#define ERRH_UCFG_NCF331_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 331: -    -     予約 */
#define ERRH_UCFG_NCF332_MODE (ERRH_NCF_MODE_IRTYPE_FE + ERRH_NCF_MODE_NOTIF_CORE3 + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 332: x    -     命令キャッシュRAM (PE3) データEDCエラー, アドレスフィードバックコンペアエラー */
#define ERRH_UCFG_NCF333_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 333: -    -     予約 */
#define ERRH_UCFG_NCF334_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 334: -    -     予約 */
#define ERRH_UCFG_NCF335_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 335: -    -     予約 */
#define ERRH_UCFG_NCF336_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 336: x    -     PEガードエラー (PE3) */
#define ERRH_UCFG_NCF337_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 337: x    -     PE ガードエラー (PE3) PE3 から他のLRAM へのリード要求を検出 */
#define ERRH_UCFG_NCF338_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 338: -    -     予約 */
#define ERRH_UCFG_NCF339_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 339: -    -     予約 */
#define ERRH_UCFG_NCF340_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 340: -    -     予約 */
#define ERRH_UCFG_NCF341_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 341: -    -     予約 */
#define ERRH_UCFG_NCF342_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 342: -    -     予約 */
#define ERRH_UCFG_NCF343_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 343: -    -     予約 */
#define ERRH_UCFG_NCF344_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 344: -    -     予約 */
#define ERRH_UCFG_NCF345_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 345: -    -     予約 */
#define ERRH_UCFG_NCF346_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 346: -    -     予約 */
#define ERRH_UCFG_NCF347_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 347: -    -     予約 */
#define ERRH_UCFG_NCF348_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 348: -    -     予約 */
#define ERRH_UCFG_NCF349_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 349: -    -     予約 */
#define ERRH_UCFG_NCF350_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 350: -    -     予約 */
#define ERRH_UCFG_NCF351_MODE (ERRH_NCF_MODE_IRTYPE_EI + ERRH_NCF_MODE_NOTIF_NONE  + ERRH_NCF_MODE_RESET_0 + ERRH_NCF_MODE_INIT_INFORM_0 + ERRH_NCF_MODE_EOUT_0) /* 351: x    -     データアクセスエラー (PE3) */





// #define		ERRH_UCFG_SPIDMASK_SDMAC1							(0x08000001U)
// #define		ERRH_UCFG_SPIDMASK_SDMAC0							(0x10000001U)
// #define		ERRH_UCFG_SPIDMASK_DTS								(0x20000001U)



#endif /* ERRH_CFG_H */
/*-- End Of File -------------------------------------------------------------------------------*/
