/* bsw_canif_config_h_v3-0-0                                                */
/****************************************************************************/
/* Protected                                                                */
/* Copyright DENSO CORPORATION                                              */
/****************************************************************************/

/****************************************************************************/
/* Object Name  | BSW/CANIF/CONFIG/HEADER                                   */
/*--------------------------------------------------------------------------*/
/* Notes        |                                                           */
/****************************************************************************/

#ifndef     BSW_CANIF_CONFIG_H
#define     BSW_CANIF_CONFIG_H

#include "../cfg/CanIf_Cfg.h"

/*--------------------------------------------------------------------------*/
/* Macros                                                                   */
/*--------------------------------------------------------------------------*/
/* Fail detection pattern */
#define BSW_CANIF_CHKSUM_PTN_CH0           BSW_CANIF_CFG_CH0_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH1           BSW_CANIF_CFG_CH1_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH2           BSW_CANIF_CFG_CH2_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH3           BSW_CANIF_CFG_CH3_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH4           BSW_CANIF_CFG_CH4_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH5           BSW_CANIF_CFG_CH5_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH6           BSW_CANIF_CFG_CH6_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH7           BSW_CANIF_CFG_CH7_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH8           BSW_CANIF_CFG_CH8_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH9           BSW_CANIF_CFG_CH9_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH10          BSW_CANIF_CFG_CH10_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH11          BSW_CANIF_CFG_CH11_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH12          BSW_CANIF_CFG_CH12_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH13          BSW_CANIF_CFG_CH13_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH14          BSW_CANIF_CFG_CH14_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH15          BSW_CANIF_CFG_CH15_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH16          BSW_CANIF_CFG_CH16_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH17          BSW_CANIF_CFG_CH17_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH18          BSW_CANIF_CFG_CH18_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH19          BSW_CANIF_CFG_CH19_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH20          BSW_CANIF_CFG_CH20_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH21          BSW_CANIF_CFG_CH21_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH22          BSW_CANIF_CFG_CH22_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH23          BSW_CANIF_CFG_CH23_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH24          BSW_CANIF_CFG_CH24_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH25          BSW_CANIF_CFG_CH25_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH26          BSW_CANIF_CFG_CH26_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH27          BSW_CANIF_CFG_CH27_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH28          BSW_CANIF_CFG_CH28_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH29          BSW_CANIF_CFG_CH29_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH30          BSW_CANIF_CFG_CH30_CHKSUM_PTN
#define BSW_CANIF_CHKSUM_PTN_CH31          BSW_CANIF_CFG_CH31_CHKSUM_PTN

#define BSW_CANIF_DLCCHK_PTN_CH0           BSW_CANIF_CFG_CH0_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH1           BSW_CANIF_CFG_CH1_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH2           BSW_CANIF_CFG_CH2_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH3           BSW_CANIF_CFG_CH3_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH4           BSW_CANIF_CFG_CH4_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH5           BSW_CANIF_CFG_CH5_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH6           BSW_CANIF_CFG_CH6_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH7           BSW_CANIF_CFG_CH7_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH8           BSW_CANIF_CFG_CH8_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH9           BSW_CANIF_CFG_CH9_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH10          BSW_CANIF_CFG_CH10_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH11          BSW_CANIF_CFG_CH11_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH12          BSW_CANIF_CFG_CH12_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH13          BSW_CANIF_CFG_CH13_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH14          BSW_CANIF_CFG_CH14_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH15          BSW_CANIF_CFG_CH15_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH16          BSW_CANIF_CFG_CH16_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH17          BSW_CANIF_CFG_CH17_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH18          BSW_CANIF_CFG_CH18_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH19          BSW_CANIF_CFG_CH19_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH20          BSW_CANIF_CFG_CH20_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH21          BSW_CANIF_CFG_CH21_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH22          BSW_CANIF_CFG_CH22_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH23          BSW_CANIF_CFG_CH23_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH24          BSW_CANIF_CFG_CH24_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH25          BSW_CANIF_CFG_CH25_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH26          BSW_CANIF_CFG_CH26_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH27          BSW_CANIF_CFG_CH27_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH28          BSW_CANIF_CFG_CH28_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH29          BSW_CANIF_CFG_CH29_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH30          BSW_CANIF_CFG_CH30_DLCCHK_PTN
#define BSW_CANIF_DLCCHK_PTN_CH31          BSW_CANIF_CFG_CH31_DLCCHK_PTN

#define BSW_CANIF_CANTPDLCCHK_PTN_CH0      BSW_CANIF_CFG_CH0_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH1      BSW_CANIF_CFG_CH1_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH2      BSW_CANIF_CFG_CH2_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH3      BSW_CANIF_CFG_CH3_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH4      BSW_CANIF_CFG_CH4_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH5      BSW_CANIF_CFG_CH5_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH6      BSW_CANIF_CFG_CH6_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH7      BSW_CANIF_CFG_CH7_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH8      BSW_CANIF_CFG_CH8_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH9      BSW_CANIF_CFG_CH9_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH10     BSW_CANIF_CFG_CH10_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH11     BSW_CANIF_CFG_CH11_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH12     BSW_CANIF_CFG_CH12_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH13     BSW_CANIF_CFG_CH13_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH14     BSW_CANIF_CFG_CH14_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH15     BSW_CANIF_CFG_CH15_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH16     BSW_CANIF_CFG_CH16_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH17     BSW_CANIF_CFG_CH17_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH18     BSW_CANIF_CFG_CH18_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH19     BSW_CANIF_CFG_CH19_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH20     BSW_CANIF_CFG_CH20_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH21     BSW_CANIF_CFG_CH21_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH22     BSW_CANIF_CFG_CH22_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH23     BSW_CANIF_CFG_CH23_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH24     BSW_CANIF_CFG_CH24_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH25     BSW_CANIF_CFG_CH25_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH26     BSW_CANIF_CFG_CH26_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH27     BSW_CANIF_CFG_CH27_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH28     BSW_CANIF_CFG_CH28_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH29     BSW_CANIF_CFG_CH29_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH30     BSW_CANIF_CFG_CH30_CANTPDLC_PTN
#define BSW_CANIF_CANTPDLCCHK_PTN_CH31     BSW_CANIF_CFG_CH31_CANTPDLC_PTN

/* Communication protocol type */
#define BSW_CANIF_PROTOCOL_CH0             BSW_CANIF_CFG_CH0_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH1             BSW_CANIF_CFG_CH1_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH2             BSW_CANIF_CFG_CH2_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH3             BSW_CANIF_CFG_CH3_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH4             BSW_CANIF_CFG_CH4_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH5             BSW_CANIF_CFG_CH5_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH6             BSW_CANIF_CFG_CH6_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH7             BSW_CANIF_CFG_CH7_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH8             BSW_CANIF_CFG_CH8_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH9             BSW_CANIF_CFG_CH9_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH10            BSW_CANIF_CFG_CH10_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH11            BSW_CANIF_CFG_CH11_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH12            BSW_CANIF_CFG_CH12_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH13            BSW_CANIF_CFG_CH13_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH14            BSW_CANIF_CFG_CH14_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH15            BSW_CANIF_CFG_CH15_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH16            BSW_CANIF_CFG_CH16_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH17            BSW_CANIF_CFG_CH17_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH18            BSW_CANIF_CFG_CH18_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH19            BSW_CANIF_CFG_CH19_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH20            BSW_CANIF_CFG_CH20_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH21            BSW_CANIF_CFG_CH21_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH22            BSW_CANIF_CFG_CH22_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH23            BSW_CANIF_CFG_CH23_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH24            BSW_CANIF_CFG_CH24_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH25            BSW_CANIF_CFG_CH25_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH26            BSW_CANIF_CFG_CH26_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH27            BSW_CANIF_CFG_CH27_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH28            BSW_CANIF_CFG_CH28_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH29            BSW_CANIF_CFG_CH29_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH30            BSW_CANIF_CFG_CH30_PROTOCOL
#define BSW_CANIF_PROTOCOL_CH31            BSW_CANIF_CFG_CH31_PROTOCOL

/* MPU CAN Number of controllers */
#if ( BSW_BSWM_CS_FUNC_VCAN == BSW_USE )
#define BSW_CANIF_MPU_VCTRLNUM             BSW_CANIF_CFG_MPU_VCNTRLLRNUM
#endif

/* Channel attribute (CAN Channel) */
#define BSW_CANIF_CH_ATTRBT(ch)            ((BSW_COMM_CH_ATTRBT(CAN, ch) == COMM_CH_ATTRBT_PHYSICAL) ? BSW_CANIF_SW_CHATT_PHYSICAL  : BSW_CANIF_SW_CHATT_VIRTUAL)

#if ( BSW_BSWM_CS_FUNC_VCAN == BSW_USE )
/* VCan HRH Total Number */
#define BSW_CANIF_TBL_VHRHNUM              ( BSW_CANIF_TBL_VHRHNUM_0_7 + BSW_CANIF_TBL_VHRHNUM_8_15 \
 + BSW_CANIF_TBL_VHRHNUM_16_23 + BSW_CANIF_TBL_VHRHNUM_24_31 )
#define BSW_CANIF_TBL_VHRHNUM_0_7          ( BSW_CANIF_CFG_0_VHRHNUM \
 + BSW_CANIF_CFG_1_VHRHNUM \
 + BSW_CANIF_CFG_2_VHRHNUM \
 + BSW_CANIF_CFG_3_VHRHNUM \
 + BSW_CANIF_CFG_4_VHRHNUM \
 + BSW_CANIF_CFG_5_VHRHNUM \
 + BSW_CANIF_CFG_6_VHRHNUM \
 + BSW_CANIF_CFG_7_VHRHNUM )
#define BSW_CANIF_TBL_VHRHNUM_8_15         ( BSW_CANIF_CFG_8_VHRHNUM \
 + BSW_CANIF_CFG_9_VHRHNUM \
 + BSW_CANIF_CFG_10_VHRHNUM \
 + BSW_CANIF_CFG_11_VHRHNUM \
 + BSW_CANIF_CFG_12_VHRHNUM \
 + BSW_CANIF_CFG_13_VHRHNUM \
 + BSW_CANIF_CFG_14_VHRHNUM \
 + BSW_CANIF_CFG_15_VHRHNUM )
#define BSW_CANIF_TBL_VHRHNUM_16_23        ( BSW_CANIF_CFG_16_VHRHNUM \
 + BSW_CANIF_CFG_17_VHRHNUM \
 + BSW_CANIF_CFG_18_VHRHNUM \
 + BSW_CANIF_CFG_19_VHRHNUM \
 + BSW_CANIF_CFG_20_VHRHNUM \
 + BSW_CANIF_CFG_21_VHRHNUM \
 + BSW_CANIF_CFG_22_VHRHNUM \
 + BSW_CANIF_CFG_23_VHRHNUM )
#define BSW_CANIF_TBL_VHRHNUM_24_31        ( BSW_CANIF_CFG_24_VHRHNUM \
 + BSW_CANIF_CFG_25_VHRHNUM \
 + BSW_CANIF_CFG_26_VHRHNUM \
 + BSW_CANIF_CFG_27_VHRHNUM \
 + BSW_CANIF_CFG_28_VHRHNUM \
 + BSW_CANIF_CFG_29_VHRHNUM \
 + BSW_CANIF_CFG_30_VHRHNUM \
 + BSW_CANIF_CFG_31_VHRHNUM )
#endif

/******************/
/* Unit internal public definition */
/******************/
/* Number of channels to use */
#define BSW_CANIF_TBL_CHNUM                ( BSW_CANIF_TBL_CHNUM_0_7 + BSW_CANIF_TBL_CHNUM_8_15 \
 + BSW_CANIF_TBL_CHNUM_16_23 + BSW_CANIF_TBL_CHNUM_24_31 \
 + BSW_CANIF_TBL_VCHNUM_0_7 + BSW_CANIF_TBL_VCHNUM_8_15 \
 + BSW_CANIF_TBL_VCHNUM_16_23 + BSW_CANIF_TBL_VCHNUM_24_31 )
#define BSW_CANIF_TBL_CHNUM_0_7            ( BSW_CANIF_TBL_CNTCH(0) \
 + BSW_CANIF_TBL_CNTCH(1) \
 + BSW_CANIF_TBL_CNTCH(2) \
 + BSW_CANIF_TBL_CNTCH(3) \
 + BSW_CANIF_TBL_CNTCH(4) \
 + BSW_CANIF_TBL_CNTCH(5) \
 + BSW_CANIF_TBL_CNTCH(6) \
 + BSW_CANIF_TBL_CNTCH(7) )
#define BSW_CANIF_TBL_CHNUM_8_15           ( BSW_CANIF_TBL_CNTCH(8) \
 + BSW_CANIF_TBL_CNTCH(9) \
 + BSW_CANIF_TBL_CNTCH(10) \
 + BSW_CANIF_TBL_CNTCH(11) \
 + BSW_CANIF_TBL_CNTCH(12) \
 + BSW_CANIF_TBL_CNTCH(13) \
 + BSW_CANIF_TBL_CNTCH(14) \
 + BSW_CANIF_TBL_CNTCH(15) )
#define BSW_CANIF_TBL_CHNUM_16_23          ( BSW_CANIF_TBL_CNTCH(16) \
 + BSW_CANIF_TBL_CNTCH(17) \
 + BSW_CANIF_TBL_CNTCH(18) \
 + BSW_CANIF_TBL_CNTCH(19) \
 + BSW_CANIF_TBL_CNTCH(20) \
 + BSW_CANIF_TBL_CNTCH(21) \
 + BSW_CANIF_TBL_CNTCH(22) \
 + BSW_CANIF_TBL_CNTCH(23) )
#define BSW_CANIF_TBL_CHNUM_24_31          ( BSW_CANIF_TBL_CNTCH(24) \
 + BSW_CANIF_TBL_CNTCH(25) \
 + BSW_CANIF_TBL_CNTCH(26) \
 + BSW_CANIF_TBL_CNTCH(27) \
 + BSW_CANIF_TBL_CNTCH(28) \
 + BSW_CANIF_TBL_CNTCH(29) \
 + BSW_CANIF_TBL_CNTCH(30) \
 + BSW_CANIF_TBL_CNTCH(31) )
#if ( BSW_BSWM_CS_FUNC_VCAN == BSW_USE )
#define BSW_CANIF_TBL_VCHNUM_0_7           ( BSW_CANIF_TBL_VCAN_CNTCH(0) \
 + BSW_CANIF_TBL_VCAN_CNTCH(1) \
 + BSW_CANIF_TBL_VCAN_CNTCH(2) \
 + BSW_CANIF_TBL_VCAN_CNTCH(3) \
 + BSW_CANIF_TBL_VCAN_CNTCH(4) \
 + BSW_CANIF_TBL_VCAN_CNTCH(5) \
 + BSW_CANIF_TBL_VCAN_CNTCH(6) \
 + BSW_CANIF_TBL_VCAN_CNTCH(7) )
#define BSW_CANIF_TBL_VCHNUM_8_15          ( BSW_CANIF_TBL_VCAN_CNTCH(8) \
 + BSW_CANIF_TBL_VCAN_CNTCH(9) \
 + BSW_CANIF_TBL_VCAN_CNTCH(10) \
 + BSW_CANIF_TBL_VCAN_CNTCH(11) \
 + BSW_CANIF_TBL_VCAN_CNTCH(12) \
 + BSW_CANIF_TBL_VCAN_CNTCH(13) \
 + BSW_CANIF_TBL_VCAN_CNTCH(14) \
 + BSW_CANIF_TBL_VCAN_CNTCH(15) )
#define BSW_CANIF_TBL_VCHNUM_16_23         ( BSW_CANIF_TBL_VCAN_CNTCH(16) \
 + BSW_CANIF_TBL_VCAN_CNTCH(17) \
 + BSW_CANIF_TBL_VCAN_CNTCH(18) \
 + BSW_CANIF_TBL_VCAN_CNTCH(19) \
 + BSW_CANIF_TBL_VCAN_CNTCH(20) \
 + BSW_CANIF_TBL_VCAN_CNTCH(21) \
 + BSW_CANIF_TBL_VCAN_CNTCH(22) \
 + BSW_CANIF_TBL_VCAN_CNTCH(23) )
#define BSW_CANIF_TBL_VCHNUM_24_31         ( BSW_CANIF_TBL_VCAN_CNTCH(24) \
 + BSW_CANIF_TBL_VCAN_CNTCH(25) \
 + BSW_CANIF_TBL_VCAN_CNTCH(26) \
 + BSW_CANIF_TBL_VCAN_CNTCH(27) \
 + BSW_CANIF_TBL_VCAN_CNTCH(28) \
 + BSW_CANIF_TBL_VCAN_CNTCH(29) \
 + BSW_CANIF_TBL_VCAN_CNTCH(30) \
 + BSW_CANIF_TBL_VCAN_CNTCH(31) )
#else
#define BSW_CANIF_TBL_VCHNUM_0_7           (0U)
#define BSW_CANIF_TBL_VCHNUM_8_15          (0U)
#define BSW_CANIF_TBL_VCHNUM_16_23         (0U)
#define BSW_CANIF_TBL_VCHNUM_24_31         (0U)
#endif

/* Macro for measuring the number of channels used */
#define BSW_CANIF_TBL_CNTCH( ch )                                                                   \
  ( (BSW_CANIF_CFG_CH_CONTROLLER0 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_CNTCH_1( ch ) )
#define BSW_CANIF_TBL_CNTCH_1( ch )                                                                 \
  ( (BSW_CANIF_CFG_CH_CONTROLLER1 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_CNTCH_2( ch ) )
#define BSW_CANIF_TBL_CNTCH_2( ch )                                                                 \
  ( (BSW_CANIF_CFG_CH_CONTROLLER2 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_CNTCH_3( ch ) )
#define BSW_CANIF_TBL_CNTCH_3( ch )                                                                 \
  ( (BSW_CANIF_CFG_CH_CONTROLLER3 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_CNTCH_4( ch ) )
#define BSW_CANIF_TBL_CNTCH_4( ch )                                                                 \
  ( (BSW_CANIF_CFG_CH_CONTROLLER4 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_CNTCH_5( ch ) )
#define BSW_CANIF_TBL_CNTCH_5( ch )                                                                 \
  ( (BSW_CANIF_CFG_CH_CONTROLLER5 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_CNTCH_6( ch ) )
#define BSW_CANIF_TBL_CNTCH_6( ch )                                                                 \
  ( (BSW_CANIF_CFG_CH_CONTROLLER6 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_CNTCH_7( ch ) )
#define BSW_CANIF_TBL_CNTCH_7( ch )                                                                 \
  ( (BSW_CANIF_CFG_CH_CONTROLLER7 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_CNTCH_8( ch ) )
#define BSW_CANIF_TBL_CNTCH_8( ch )                                                                 \
  ( (BSW_CANIF_CFG_CH_CONTROLLER8 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_CNTCH_9( ch ) )
#define BSW_CANIF_TBL_CNTCH_9( ch )                                                                 \
  ( (BSW_CANIF_CFG_CH_CONTROLLER9 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_CNTCH_10( ch ) )
#define BSW_CANIF_TBL_CNTCH_10( ch )                                                                \
  ( (BSW_CANIF_CFG_CH_CONTROLLER10 == BSW_CANIF_CH##ch) ? (1U) : BSW_CANIF_TBL_CNTCH_11( ch ) )
#define BSW_CANIF_TBL_CNTCH_11( ch )                                                                \
  ( (BSW_CANIF_CFG_CH_CONTROLLER11 == BSW_CANIF_CH##ch) ? (1U) : BSW_CANIF_TBL_CNTCH_12( ch ) )
#define BSW_CANIF_TBL_CNTCH_12( ch )                                                                \
  ( (BSW_CANIF_CFG_CH_CONTROLLER12 == BSW_CANIF_CH##ch) ? (1U) : BSW_CANIF_TBL_CNTCH_13( ch ) )
#define BSW_CANIF_TBL_CNTCH_13( ch )                                                                \
  ( (BSW_CANIF_CFG_CH_CONTROLLER13 == BSW_CANIF_CH##ch) ? (1U) : BSW_CANIF_TBL_CNTCH_14( ch ) )
#define BSW_CANIF_TBL_CNTCH_14( ch )                                                                \
  ( (BSW_CANIF_CFG_CH_CONTROLLER14 == BSW_CANIF_CH##ch) ? (1U) : BSW_CANIF_TBL_CNTCH_15( ch ) )
#define BSW_CANIF_TBL_CNTCH_15( ch )                                                                \
  ( (BSW_CANIF_CFG_CH_CONTROLLER15 == BSW_CANIF_CH##ch) ? (1U) : (0U) )

/* Macro for calculating the number of VCAN channels used (ch: channel number 0 to 31) */
#if ( BSW_BSWM_CS_FUNC_VCAN == BSW_USE )
#define BSW_CANIF_TBL_VCAN_CNTCH( ch )                                                                \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER0 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_1( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_1( ch )                                                              \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER1 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_2( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_2( ch )                                                              \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER2 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_3( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_3( ch )                                                              \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER3 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_4( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_4( ch )                                                              \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER4 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_5( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_5( ch )                                                              \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER5 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_6( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_6( ch )                                                              \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER6 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_7( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_7( ch )                                                              \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER7 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_8( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_8( ch )                                                              \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER8 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_9( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_9( ch )                                                              \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER9 == BSW_CANIF_CH##ch)  ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_10( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_10( ch )                                                             \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER10 == BSW_CANIF_CH##ch) ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_11( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_11( ch )                                                             \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER11 == BSW_CANIF_CH##ch) ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_12( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_12( ch )                                                             \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER12 == BSW_CANIF_CH##ch) ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_13( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_13( ch )                                                             \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER13 == BSW_CANIF_CH##ch) ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_14( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_14( ch )                                                             \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER14 == BSW_CANIF_CH##ch) ? (1U) : BSW_CANIF_TBL_VCAN_CNTCH_15( ch ) )
#define BSW_CANIF_TBL_VCAN_CNTCH_15( ch )                                                             \
  ( (BSW_CANIF_CFG_CH_VCONTROLLER15 == BSW_CANIF_CH##ch) ? (1U) : (0U) )
#endif

#define BSW_CANIF_TXPDURPDUNUM              ( BSW_CANIF_TXPDURPDUNUM31 )
#define BSW_CANIF_TXPDURPDUNUM31            ( BSW_CANIF_CFG_31_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM30 )
#define BSW_CANIF_TXPDURPDUNUM30            ( BSW_CANIF_CFG_30_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM29 )
#define BSW_CANIF_TXPDURPDUNUM29            ( BSW_CANIF_CFG_29_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM28 )
#define BSW_CANIF_TXPDURPDUNUM28            ( BSW_CANIF_CFG_28_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM27 )
#define BSW_CANIF_TXPDURPDUNUM27            ( BSW_CANIF_CFG_27_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM26 )
#define BSW_CANIF_TXPDURPDUNUM26            ( BSW_CANIF_CFG_26_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM25 )
#define BSW_CANIF_TXPDURPDUNUM25            ( BSW_CANIF_CFG_25_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM24 )
#define BSW_CANIF_TXPDURPDUNUM24            ( BSW_CANIF_CFG_24_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM23 )
#define BSW_CANIF_TXPDURPDUNUM23            ( BSW_CANIF_CFG_23_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM22 )
#define BSW_CANIF_TXPDURPDUNUM22            ( BSW_CANIF_CFG_22_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM21 )
#define BSW_CANIF_TXPDURPDUNUM21            ( BSW_CANIF_CFG_21_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM20 )
#define BSW_CANIF_TXPDURPDUNUM20            ( BSW_CANIF_CFG_20_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM19 )
#define BSW_CANIF_TXPDURPDUNUM19            ( BSW_CANIF_CFG_19_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM18 )
#define BSW_CANIF_TXPDURPDUNUM18            ( BSW_CANIF_CFG_18_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM17 )
#define BSW_CANIF_TXPDURPDUNUM17            ( BSW_CANIF_CFG_17_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM16 )
#define BSW_CANIF_TXPDURPDUNUM16            ( BSW_CANIF_CFG_16_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM15 )
#define BSW_CANIF_TXPDURPDUNUM15            ( BSW_CANIF_CFG_15_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM14 )
#define BSW_CANIF_TXPDURPDUNUM14            ( BSW_CANIF_CFG_14_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM13 )
#define BSW_CANIF_TXPDURPDUNUM13            ( BSW_CANIF_CFG_13_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM12 )
#define BSW_CANIF_TXPDURPDUNUM12            ( BSW_CANIF_CFG_12_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM11 )
#define BSW_CANIF_TXPDURPDUNUM11            ( BSW_CANIF_CFG_11_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM10 )
#define BSW_CANIF_TXPDURPDUNUM10            ( BSW_CANIF_CFG_10_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM09 )
#define BSW_CANIF_TXPDURPDUNUM09            ( BSW_CANIF_CFG_9_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM08 )
#define BSW_CANIF_TXPDURPDUNUM08            ( BSW_CANIF_CFG_8_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM07 )
#define BSW_CANIF_TXPDURPDUNUM07            ( BSW_CANIF_CFG_7_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM06 )
#define BSW_CANIF_TXPDURPDUNUM06            ( BSW_CANIF_CFG_6_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM05 )
#define BSW_CANIF_TXPDURPDUNUM05            ( BSW_CANIF_CFG_5_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM04 )
#define BSW_CANIF_TXPDURPDUNUM04            ( BSW_CANIF_CFG_4_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM03 )
#define BSW_CANIF_TXPDURPDUNUM03            ( BSW_CANIF_CFG_3_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM02 )
#define BSW_CANIF_TXPDURPDUNUM02            ( BSW_CANIF_CFG_2_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM01 )
#define BSW_CANIF_TXPDURPDUNUM01            ( BSW_CANIF_CFG_1_TXPDURPDUNUM + BSW_CANIF_TXPDURPDUNUM00 )
#define BSW_CANIF_TXPDURPDUNUM00            ( BSW_CANIF_CFG_0_TXPDURPDUNUM )

#define BSW_CANIF_TXCANNMPDUNUM             ( BSW_CANIF_TXCANNMPDUNUM31 )
#define BSW_CANIF_TXCANNMPDUNUM31           ( BSW_CANIF_CFG_31_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM30 )
#define BSW_CANIF_TXCANNMPDUNUM30           ( BSW_CANIF_CFG_30_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM29 )
#define BSW_CANIF_TXCANNMPDUNUM29           ( BSW_CANIF_CFG_29_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM28 )
#define BSW_CANIF_TXCANNMPDUNUM28           ( BSW_CANIF_CFG_28_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM27 )
#define BSW_CANIF_TXCANNMPDUNUM27           ( BSW_CANIF_CFG_27_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM26 )
#define BSW_CANIF_TXCANNMPDUNUM26           ( BSW_CANIF_CFG_26_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM25 )
#define BSW_CANIF_TXCANNMPDUNUM25           ( BSW_CANIF_CFG_25_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM24 )
#define BSW_CANIF_TXCANNMPDUNUM24           ( BSW_CANIF_CFG_24_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM23 )
#define BSW_CANIF_TXCANNMPDUNUM23           ( BSW_CANIF_CFG_23_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM22 )
#define BSW_CANIF_TXCANNMPDUNUM22           ( BSW_CANIF_CFG_22_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM21 )
#define BSW_CANIF_TXCANNMPDUNUM21           ( BSW_CANIF_CFG_21_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM20 )
#define BSW_CANIF_TXCANNMPDUNUM20           ( BSW_CANIF_CFG_20_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM19 )
#define BSW_CANIF_TXCANNMPDUNUM19           ( BSW_CANIF_CFG_19_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM18 )
#define BSW_CANIF_TXCANNMPDUNUM18           ( BSW_CANIF_CFG_18_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM17 )
#define BSW_CANIF_TXCANNMPDUNUM17           ( BSW_CANIF_CFG_17_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM16 )
#define BSW_CANIF_TXCANNMPDUNUM16           ( BSW_CANIF_CFG_16_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM15 )
#define BSW_CANIF_TXCANNMPDUNUM15           ( BSW_CANIF_CFG_15_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM14 )
#define BSW_CANIF_TXCANNMPDUNUM14           ( BSW_CANIF_CFG_14_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM13 )
#define BSW_CANIF_TXCANNMPDUNUM13           ( BSW_CANIF_CFG_13_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM12 )
#define BSW_CANIF_TXCANNMPDUNUM12           ( BSW_CANIF_CFG_12_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM11 )
#define BSW_CANIF_TXCANNMPDUNUM11           ( BSW_CANIF_CFG_11_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM10 )
#define BSW_CANIF_TXCANNMPDUNUM10           ( BSW_CANIF_CFG_10_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM09 )
#define BSW_CANIF_TXCANNMPDUNUM09           ( BSW_CANIF_CFG_9_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM08 )
#define BSW_CANIF_TXCANNMPDUNUM08           ( BSW_CANIF_CFG_8_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM07 )
#define BSW_CANIF_TXCANNMPDUNUM07           ( BSW_CANIF_CFG_7_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM06 )
#define BSW_CANIF_TXCANNMPDUNUM06           ( BSW_CANIF_CFG_6_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM05 )
#define BSW_CANIF_TXCANNMPDUNUM05           ( BSW_CANIF_CFG_5_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM04 )
#define BSW_CANIF_TXCANNMPDUNUM04           ( BSW_CANIF_CFG_4_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM03 )
#define BSW_CANIF_TXCANNMPDUNUM03           ( BSW_CANIF_CFG_3_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM02 )
#define BSW_CANIF_TXCANNMPDUNUM02           ( BSW_CANIF_CFG_2_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM01 )
#define BSW_CANIF_TXCANNMPDUNUM01           ( BSW_CANIF_CFG_1_TXCANNMPDUNUM + BSW_CANIF_TXCANNMPDUNUM00 )
#define BSW_CANIF_TXCANNMPDUNUM00           ( BSW_CANIF_CFG_0_TXCANNMPDUNUM )

#define BSW_CANIF_TXCANTPPDUNUM             ( BSW_CANIF_TXCANTPPDUNUM31 )
#define BSW_CANIF_TXCANTPPDUNUM31           ( BSW_CANIF_CFG_31_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM30 )
#define BSW_CANIF_TXCANTPPDUNUM30           ( BSW_CANIF_CFG_30_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM29 )
#define BSW_CANIF_TXCANTPPDUNUM29           ( BSW_CANIF_CFG_29_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM28 )
#define BSW_CANIF_TXCANTPPDUNUM28           ( BSW_CANIF_CFG_28_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM27 )
#define BSW_CANIF_TXCANTPPDUNUM27           ( BSW_CANIF_CFG_27_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM26 )
#define BSW_CANIF_TXCANTPPDUNUM26           ( BSW_CANIF_CFG_26_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM25 )
#define BSW_CANIF_TXCANTPPDUNUM25           ( BSW_CANIF_CFG_25_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM24 )
#define BSW_CANIF_TXCANTPPDUNUM24           ( BSW_CANIF_CFG_24_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM23 )
#define BSW_CANIF_TXCANTPPDUNUM23           ( BSW_CANIF_CFG_23_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM22 )
#define BSW_CANIF_TXCANTPPDUNUM22           ( BSW_CANIF_CFG_22_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM21 )
#define BSW_CANIF_TXCANTPPDUNUM21           ( BSW_CANIF_CFG_21_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM20 )
#define BSW_CANIF_TXCANTPPDUNUM20           ( BSW_CANIF_CFG_20_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM19 )
#define BSW_CANIF_TXCANTPPDUNUM19           ( BSW_CANIF_CFG_19_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM18 )
#define BSW_CANIF_TXCANTPPDUNUM18           ( BSW_CANIF_CFG_18_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM17 )
#define BSW_CANIF_TXCANTPPDUNUM17           ( BSW_CANIF_CFG_17_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM16 )
#define BSW_CANIF_TXCANTPPDUNUM16           ( BSW_CANIF_CFG_16_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM15 )
#define BSW_CANIF_TXCANTPPDUNUM15           ( BSW_CANIF_CFG_15_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM14 )
#define BSW_CANIF_TXCANTPPDUNUM14           ( BSW_CANIF_CFG_14_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM13 )
#define BSW_CANIF_TXCANTPPDUNUM13           ( BSW_CANIF_CFG_13_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM12 )
#define BSW_CANIF_TXCANTPPDUNUM12           ( BSW_CANIF_CFG_12_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM11 )
#define BSW_CANIF_TXCANTPPDUNUM11           ( BSW_CANIF_CFG_11_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM10 )
#define BSW_CANIF_TXCANTPPDUNUM10           ( BSW_CANIF_CFG_10_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM09 )
#define BSW_CANIF_TXCANTPPDUNUM09           ( BSW_CANIF_CFG_9_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM08 )
#define BSW_CANIF_TXCANTPPDUNUM08           ( BSW_CANIF_CFG_8_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM07 )
#define BSW_CANIF_TXCANTPPDUNUM07           ( BSW_CANIF_CFG_7_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM06 )
#define BSW_CANIF_TXCANTPPDUNUM06           ( BSW_CANIF_CFG_6_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM05 )
#define BSW_CANIF_TXCANTPPDUNUM05           ( BSW_CANIF_CFG_5_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM04 )
#define BSW_CANIF_TXCANTPPDUNUM04           ( BSW_CANIF_CFG_4_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM03 )
#define BSW_CANIF_TXCANTPPDUNUM03           ( BSW_CANIF_CFG_3_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM02 )
#define BSW_CANIF_TXCANTPPDUNUM02           ( BSW_CANIF_CFG_2_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM01 )
#define BSW_CANIF_TXCANTPPDUNUM01           ( BSW_CANIF_CFG_1_TXCANTPPDUNUM + BSW_CANIF_TXCANTPPDUNUM00 )
#define BSW_CANIF_TXCANTPPDUNUM00           ( BSW_CANIF_CFG_0_TXCANTPPDUNUM )

#define BSW_CANIF_TXCDD1PDUNUM              ( BSW_CANIF_TXCDD1PDUNUM31 )
#define BSW_CANIF_TXCDD1PDUNUM31            ( BSW_CANIF_CFG_31_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM30 )
#define BSW_CANIF_TXCDD1PDUNUM30            ( BSW_CANIF_CFG_30_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM29 )
#define BSW_CANIF_TXCDD1PDUNUM29            ( BSW_CANIF_CFG_29_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM28 )
#define BSW_CANIF_TXCDD1PDUNUM28            ( BSW_CANIF_CFG_28_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM27 )
#define BSW_CANIF_TXCDD1PDUNUM27            ( BSW_CANIF_CFG_27_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM26 )
#define BSW_CANIF_TXCDD1PDUNUM26            ( BSW_CANIF_CFG_26_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM25 )
#define BSW_CANIF_TXCDD1PDUNUM25            ( BSW_CANIF_CFG_25_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM24 )
#define BSW_CANIF_TXCDD1PDUNUM24            ( BSW_CANIF_CFG_24_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM23 )
#define BSW_CANIF_TXCDD1PDUNUM23            ( BSW_CANIF_CFG_23_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM22 )
#define BSW_CANIF_TXCDD1PDUNUM22            ( BSW_CANIF_CFG_22_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM21 )
#define BSW_CANIF_TXCDD1PDUNUM21            ( BSW_CANIF_CFG_21_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM20 )
#define BSW_CANIF_TXCDD1PDUNUM20            ( BSW_CANIF_CFG_20_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM19 )
#define BSW_CANIF_TXCDD1PDUNUM19            ( BSW_CANIF_CFG_19_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM18 )
#define BSW_CANIF_TXCDD1PDUNUM18            ( BSW_CANIF_CFG_18_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM17 )
#define BSW_CANIF_TXCDD1PDUNUM17            ( BSW_CANIF_CFG_17_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM16 )
#define BSW_CANIF_TXCDD1PDUNUM16            ( BSW_CANIF_CFG_16_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM15 )
#define BSW_CANIF_TXCDD1PDUNUM15            ( BSW_CANIF_CFG_15_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM14 )
#define BSW_CANIF_TXCDD1PDUNUM14            ( BSW_CANIF_CFG_14_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM13 )
#define BSW_CANIF_TXCDD1PDUNUM13            ( BSW_CANIF_CFG_13_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM12 )
#define BSW_CANIF_TXCDD1PDUNUM12            ( BSW_CANIF_CFG_12_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM11 )
#define BSW_CANIF_TXCDD1PDUNUM11            ( BSW_CANIF_CFG_11_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM10 )
#define BSW_CANIF_TXCDD1PDUNUM10            ( BSW_CANIF_CFG_10_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM09 )
#define BSW_CANIF_TXCDD1PDUNUM09            ( BSW_CANIF_CFG_9_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM08 )
#define BSW_CANIF_TXCDD1PDUNUM08            ( BSW_CANIF_CFG_8_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM07 )
#define BSW_CANIF_TXCDD1PDUNUM07            ( BSW_CANIF_CFG_7_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM06 )
#define BSW_CANIF_TXCDD1PDUNUM06            ( BSW_CANIF_CFG_6_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM05 )
#define BSW_CANIF_TXCDD1PDUNUM05            ( BSW_CANIF_CFG_5_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM04 )
#define BSW_CANIF_TXCDD1PDUNUM04            ( BSW_CANIF_CFG_4_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM03 )
#define BSW_CANIF_TXCDD1PDUNUM03            ( BSW_CANIF_CFG_3_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM02 )
#define BSW_CANIF_TXCDD1PDUNUM02            ( BSW_CANIF_CFG_2_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM01 )
#define BSW_CANIF_TXCDD1PDUNUM01            ( BSW_CANIF_CFG_1_TXCDD1PDUNUM + BSW_CANIF_TXCDD1PDUNUM00 )
#define BSW_CANIF_TXCDD1PDUNUM00            ( BSW_CANIF_CFG_0_TXCDD1PDUNUM )

#define BSW_CANIF_TXCDD2PDUNUM              ( BSW_CANIF_TXCDD2PDUNUM31 )
#define BSW_CANIF_TXCDD2PDUNUM31            ( BSW_CANIF_CFG_31_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM30 )
#define BSW_CANIF_TXCDD2PDUNUM30            ( BSW_CANIF_CFG_30_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM29 )
#define BSW_CANIF_TXCDD2PDUNUM29            ( BSW_CANIF_CFG_29_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM28 )
#define BSW_CANIF_TXCDD2PDUNUM28            ( BSW_CANIF_CFG_28_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM27 )
#define BSW_CANIF_TXCDD2PDUNUM27            ( BSW_CANIF_CFG_27_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM26 )
#define BSW_CANIF_TXCDD2PDUNUM26            ( BSW_CANIF_CFG_26_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM25 )
#define BSW_CANIF_TXCDD2PDUNUM25            ( BSW_CANIF_CFG_25_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM24 )
#define BSW_CANIF_TXCDD2PDUNUM24            ( BSW_CANIF_CFG_24_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM23 )
#define BSW_CANIF_TXCDD2PDUNUM23            ( BSW_CANIF_CFG_23_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM22 )
#define BSW_CANIF_TXCDD2PDUNUM22            ( BSW_CANIF_CFG_22_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM21 )
#define BSW_CANIF_TXCDD2PDUNUM21            ( BSW_CANIF_CFG_21_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM20 )
#define BSW_CANIF_TXCDD2PDUNUM20            ( BSW_CANIF_CFG_20_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM19 )
#define BSW_CANIF_TXCDD2PDUNUM19            ( BSW_CANIF_CFG_19_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM18 )
#define BSW_CANIF_TXCDD2PDUNUM18            ( BSW_CANIF_CFG_18_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM17 )
#define BSW_CANIF_TXCDD2PDUNUM17            ( BSW_CANIF_CFG_17_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM16 )
#define BSW_CANIF_TXCDD2PDUNUM16            ( BSW_CANIF_CFG_16_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM15 )
#define BSW_CANIF_TXCDD2PDUNUM15            ( BSW_CANIF_CFG_15_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM14 )
#define BSW_CANIF_TXCDD2PDUNUM14            ( BSW_CANIF_CFG_14_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM13 )
#define BSW_CANIF_TXCDD2PDUNUM13            ( BSW_CANIF_CFG_13_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM12 )
#define BSW_CANIF_TXCDD2PDUNUM12            ( BSW_CANIF_CFG_12_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM11 )
#define BSW_CANIF_TXCDD2PDUNUM11            ( BSW_CANIF_CFG_11_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM10 )
#define BSW_CANIF_TXCDD2PDUNUM10            ( BSW_CANIF_CFG_10_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM09 )
#define BSW_CANIF_TXCDD2PDUNUM09            ( BSW_CANIF_CFG_9_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM08 )
#define BSW_CANIF_TXCDD2PDUNUM08            ( BSW_CANIF_CFG_8_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM07 )
#define BSW_CANIF_TXCDD2PDUNUM07            ( BSW_CANIF_CFG_7_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM06 )
#define BSW_CANIF_TXCDD2PDUNUM06            ( BSW_CANIF_CFG_6_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM05 )
#define BSW_CANIF_TXCDD2PDUNUM05            ( BSW_CANIF_CFG_5_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM04 )
#define BSW_CANIF_TXCDD2PDUNUM04            ( BSW_CANIF_CFG_4_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM03 )
#define BSW_CANIF_TXCDD2PDUNUM03            ( BSW_CANIF_CFG_3_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM02 )
#define BSW_CANIF_TXCDD2PDUNUM02            ( BSW_CANIF_CFG_2_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM01 )
#define BSW_CANIF_TXCDD2PDUNUM01            ( BSW_CANIF_CFG_1_TXCDD2PDUNUM + BSW_CANIF_TXCDD2PDUNUM00 )
#define BSW_CANIF_TXCDD2PDUNUM00            ( BSW_CANIF_CFG_0_TXCDD2PDUNUM )

#define BSW_CANIF_TXXCPPDUNUM               ( BSW_CANIF_TXXCPPDUNUM31 )
#define BSW_CANIF_TXXCPPDUNUM31             ( BSW_CANIF_CFG_31_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM30 )
#define BSW_CANIF_TXXCPPDUNUM30             ( BSW_CANIF_CFG_30_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM29 )
#define BSW_CANIF_TXXCPPDUNUM29             ( BSW_CANIF_CFG_29_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM28 )
#define BSW_CANIF_TXXCPPDUNUM28             ( BSW_CANIF_CFG_28_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM27 )
#define BSW_CANIF_TXXCPPDUNUM27             ( BSW_CANIF_CFG_27_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM26 )
#define BSW_CANIF_TXXCPPDUNUM26             ( BSW_CANIF_CFG_26_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM25 )
#define BSW_CANIF_TXXCPPDUNUM25             ( BSW_CANIF_CFG_25_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM24 )
#define BSW_CANIF_TXXCPPDUNUM24             ( BSW_CANIF_CFG_24_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM23 )
#define BSW_CANIF_TXXCPPDUNUM23             ( BSW_CANIF_CFG_23_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM22 )
#define BSW_CANIF_TXXCPPDUNUM22             ( BSW_CANIF_CFG_22_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM21 )
#define BSW_CANIF_TXXCPPDUNUM21             ( BSW_CANIF_CFG_21_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM20 )
#define BSW_CANIF_TXXCPPDUNUM20             ( BSW_CANIF_CFG_20_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM19 )
#define BSW_CANIF_TXXCPPDUNUM19             ( BSW_CANIF_CFG_19_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM18 )
#define BSW_CANIF_TXXCPPDUNUM18             ( BSW_CANIF_CFG_18_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM17 )
#define BSW_CANIF_TXXCPPDUNUM17             ( BSW_CANIF_CFG_17_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM16 )
#define BSW_CANIF_TXXCPPDUNUM16             ( BSW_CANIF_CFG_16_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM15 )
#define BSW_CANIF_TXXCPPDUNUM15             ( BSW_CANIF_CFG_15_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM14 )
#define BSW_CANIF_TXXCPPDUNUM14             ( BSW_CANIF_CFG_14_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM13 )
#define BSW_CANIF_TXXCPPDUNUM13             ( BSW_CANIF_CFG_13_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM12 )
#define BSW_CANIF_TXXCPPDUNUM12             ( BSW_CANIF_CFG_12_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM11 )
#define BSW_CANIF_TXXCPPDUNUM11             ( BSW_CANIF_CFG_11_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM10 )
#define BSW_CANIF_TXXCPPDUNUM10             ( BSW_CANIF_CFG_10_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM09 )
#define BSW_CANIF_TXXCPPDUNUM09             ( BSW_CANIF_CFG_9_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM08 )
#define BSW_CANIF_TXXCPPDUNUM08             ( BSW_CANIF_CFG_8_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM07 )
#define BSW_CANIF_TXXCPPDUNUM07             ( BSW_CANIF_CFG_7_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM06 )
#define BSW_CANIF_TXXCPPDUNUM06             ( BSW_CANIF_CFG_6_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM05 )
#define BSW_CANIF_TXXCPPDUNUM05             ( BSW_CANIF_CFG_5_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM04 )
#define BSW_CANIF_TXXCPPDUNUM04             ( BSW_CANIF_CFG_4_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM03 )
#define BSW_CANIF_TXXCPPDUNUM03             ( BSW_CANIF_CFG_3_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM02 )
#define BSW_CANIF_TXXCPPDUNUM02             ( BSW_CANIF_CFG_2_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM01 )
#define BSW_CANIF_TXXCPPDUNUM01             ( BSW_CANIF_CFG_1_TXXCPPDUNUM + BSW_CANIF_TXXCPPDUNUM00 )
#define BSW_CANIF_TXXCPPDUNUM00             ( BSW_CANIF_CFG_0_TXXCPPDUNUM )

#define BSW_CANIF_RXPDURPDUNUM              ( BSW_CANIF_RXPDURPDUNUM31 )
#define BSW_CANIF_RXPDURPDUNUM31            ( BSW_CANIF_CFG_31_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM30 )
#define BSW_CANIF_RXPDURPDUNUM30            ( BSW_CANIF_CFG_30_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM29 )
#define BSW_CANIF_RXPDURPDUNUM29            ( BSW_CANIF_CFG_29_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM28 )
#define BSW_CANIF_RXPDURPDUNUM28            ( BSW_CANIF_CFG_28_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM27 )
#define BSW_CANIF_RXPDURPDUNUM27            ( BSW_CANIF_CFG_27_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM26 )
#define BSW_CANIF_RXPDURPDUNUM26            ( BSW_CANIF_CFG_26_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM25 )
#define BSW_CANIF_RXPDURPDUNUM25            ( BSW_CANIF_CFG_25_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM24 )
#define BSW_CANIF_RXPDURPDUNUM24            ( BSW_CANIF_CFG_24_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM23 )
#define BSW_CANIF_RXPDURPDUNUM23            ( BSW_CANIF_CFG_23_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM22 )
#define BSW_CANIF_RXPDURPDUNUM22            ( BSW_CANIF_CFG_22_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM21 )
#define BSW_CANIF_RXPDURPDUNUM21            ( BSW_CANIF_CFG_21_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM20 )
#define BSW_CANIF_RXPDURPDUNUM20            ( BSW_CANIF_CFG_20_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM19 )
#define BSW_CANIF_RXPDURPDUNUM19            ( BSW_CANIF_CFG_19_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM18 )
#define BSW_CANIF_RXPDURPDUNUM18            ( BSW_CANIF_CFG_18_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM17 )
#define BSW_CANIF_RXPDURPDUNUM17            ( BSW_CANIF_CFG_17_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM16 )
#define BSW_CANIF_RXPDURPDUNUM16            ( BSW_CANIF_CFG_16_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM15 )
#define BSW_CANIF_RXPDURPDUNUM15            ( BSW_CANIF_CFG_15_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM14 )
#define BSW_CANIF_RXPDURPDUNUM14            ( BSW_CANIF_CFG_14_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM13 )
#define BSW_CANIF_RXPDURPDUNUM13            ( BSW_CANIF_CFG_13_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM12 )
#define BSW_CANIF_RXPDURPDUNUM12            ( BSW_CANIF_CFG_12_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM11 )
#define BSW_CANIF_RXPDURPDUNUM11            ( BSW_CANIF_CFG_11_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM10 )
#define BSW_CANIF_RXPDURPDUNUM10            ( BSW_CANIF_CFG_10_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM09 )
#define BSW_CANIF_RXPDURPDUNUM09            ( BSW_CANIF_CFG_9_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM08 )
#define BSW_CANIF_RXPDURPDUNUM08            ( BSW_CANIF_CFG_8_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM07 )
#define BSW_CANIF_RXPDURPDUNUM07            ( BSW_CANIF_CFG_7_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM06 )
#define BSW_CANIF_RXPDURPDUNUM06            ( BSW_CANIF_CFG_6_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM05 )
#define BSW_CANIF_RXPDURPDUNUM05            ( BSW_CANIF_CFG_5_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM04 )
#define BSW_CANIF_RXPDURPDUNUM04            ( BSW_CANIF_CFG_4_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM03 )
#define BSW_CANIF_RXPDURPDUNUM03            ( BSW_CANIF_CFG_3_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM02 )
#define BSW_CANIF_RXPDURPDUNUM02            ( BSW_CANIF_CFG_2_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM01 )
#define BSW_CANIF_RXPDURPDUNUM01            ( BSW_CANIF_CFG_1_RXPDURPDUNUM + BSW_CANIF_RXPDURPDUNUM00 )
#define BSW_CANIF_RXPDURPDUNUM00            ( BSW_CANIF_CFG_0_RXPDURPDUNUM )

#define BSW_CANIF_RXCANNMPDUNUM             ( BSW_CANIF_RXCANNMPDUNUM31 )
#define BSW_CANIF_RXCANNMPDUNUM31           ( BSW_CANIF_CFG_31_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM30 )
#define BSW_CANIF_RXCANNMPDUNUM30           ( BSW_CANIF_CFG_30_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM29 )
#define BSW_CANIF_RXCANNMPDUNUM29           ( BSW_CANIF_CFG_29_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM28 )
#define BSW_CANIF_RXCANNMPDUNUM28           ( BSW_CANIF_CFG_28_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM27 )
#define BSW_CANIF_RXCANNMPDUNUM27           ( BSW_CANIF_CFG_27_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM26 )
#define BSW_CANIF_RXCANNMPDUNUM26           ( BSW_CANIF_CFG_26_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM25 )
#define BSW_CANIF_RXCANNMPDUNUM25           ( BSW_CANIF_CFG_25_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM24 )
#define BSW_CANIF_RXCANNMPDUNUM24           ( BSW_CANIF_CFG_24_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM23 )
#define BSW_CANIF_RXCANNMPDUNUM23           ( BSW_CANIF_CFG_23_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM22 )
#define BSW_CANIF_RXCANNMPDUNUM22           ( BSW_CANIF_CFG_22_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM21 )
#define BSW_CANIF_RXCANNMPDUNUM21           ( BSW_CANIF_CFG_21_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM20 )
#define BSW_CANIF_RXCANNMPDUNUM20           ( BSW_CANIF_CFG_20_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM19 )
#define BSW_CANIF_RXCANNMPDUNUM19           ( BSW_CANIF_CFG_19_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM18 )
#define BSW_CANIF_RXCANNMPDUNUM18           ( BSW_CANIF_CFG_18_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM17 )
#define BSW_CANIF_RXCANNMPDUNUM17           ( BSW_CANIF_CFG_17_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM16 )
#define BSW_CANIF_RXCANNMPDUNUM16           ( BSW_CANIF_CFG_16_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM15 )
#define BSW_CANIF_RXCANNMPDUNUM15           ( BSW_CANIF_CFG_15_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM14 )
#define BSW_CANIF_RXCANNMPDUNUM14           ( BSW_CANIF_CFG_14_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM13 )
#define BSW_CANIF_RXCANNMPDUNUM13           ( BSW_CANIF_CFG_13_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM12 )
#define BSW_CANIF_RXCANNMPDUNUM12           ( BSW_CANIF_CFG_12_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM11 )
#define BSW_CANIF_RXCANNMPDUNUM11           ( BSW_CANIF_CFG_11_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM10 )
#define BSW_CANIF_RXCANNMPDUNUM10           ( BSW_CANIF_CFG_10_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM09 )
#define BSW_CANIF_RXCANNMPDUNUM09           ( BSW_CANIF_CFG_9_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM08 )
#define BSW_CANIF_RXCANNMPDUNUM08           ( BSW_CANIF_CFG_8_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM07 )
#define BSW_CANIF_RXCANNMPDUNUM07           ( BSW_CANIF_CFG_7_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM06 )
#define BSW_CANIF_RXCANNMPDUNUM06           ( BSW_CANIF_CFG_6_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM05 )
#define BSW_CANIF_RXCANNMPDUNUM05           ( BSW_CANIF_CFG_5_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM04 )
#define BSW_CANIF_RXCANNMPDUNUM04           ( BSW_CANIF_CFG_4_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM03 )
#define BSW_CANIF_RXCANNMPDUNUM03           ( BSW_CANIF_CFG_3_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM02 )
#define BSW_CANIF_RXCANNMPDUNUM02           ( BSW_CANIF_CFG_2_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM01 )
#define BSW_CANIF_RXCANNMPDUNUM01           ( BSW_CANIF_CFG_1_RXCANNMPDUNUM + BSW_CANIF_RXCANNMPDUNUM00 )
#define BSW_CANIF_RXCANNMPDUNUM00           ( BSW_CANIF_CFG_0_RXCANNMPDUNUM )

#define BSW_CANIF_RXCANTPPDUNUM             ( BSW_CANIF_RXCANTPPDUNUM31 )
#define BSW_CANIF_RXCANTPPDUNUM31           ( BSW_CANIF_CFG_31_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM30 )
#define BSW_CANIF_RXCANTPPDUNUM30           ( BSW_CANIF_CFG_30_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM29 )
#define BSW_CANIF_RXCANTPPDUNUM29           ( BSW_CANIF_CFG_29_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM28 )
#define BSW_CANIF_RXCANTPPDUNUM28           ( BSW_CANIF_CFG_28_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM27 )
#define BSW_CANIF_RXCANTPPDUNUM27           ( BSW_CANIF_CFG_27_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM26 )
#define BSW_CANIF_RXCANTPPDUNUM26           ( BSW_CANIF_CFG_26_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM25 )
#define BSW_CANIF_RXCANTPPDUNUM25           ( BSW_CANIF_CFG_25_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM24 )
#define BSW_CANIF_RXCANTPPDUNUM24           ( BSW_CANIF_CFG_24_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM23 )
#define BSW_CANIF_RXCANTPPDUNUM23           ( BSW_CANIF_CFG_23_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM22 )
#define BSW_CANIF_RXCANTPPDUNUM22           ( BSW_CANIF_CFG_22_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM21 )
#define BSW_CANIF_RXCANTPPDUNUM21           ( BSW_CANIF_CFG_21_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM20 )
#define BSW_CANIF_RXCANTPPDUNUM20           ( BSW_CANIF_CFG_20_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM19 )
#define BSW_CANIF_RXCANTPPDUNUM19           ( BSW_CANIF_CFG_19_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM18 )
#define BSW_CANIF_RXCANTPPDUNUM18           ( BSW_CANIF_CFG_18_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM17 )
#define BSW_CANIF_RXCANTPPDUNUM17           ( BSW_CANIF_CFG_17_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM16 )
#define BSW_CANIF_RXCANTPPDUNUM16           ( BSW_CANIF_CFG_16_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM15 )
#define BSW_CANIF_RXCANTPPDUNUM15           ( BSW_CANIF_CFG_15_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM14 )
#define BSW_CANIF_RXCANTPPDUNUM14           ( BSW_CANIF_CFG_14_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM13 )
#define BSW_CANIF_RXCANTPPDUNUM13           ( BSW_CANIF_CFG_13_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM12 )
#define BSW_CANIF_RXCANTPPDUNUM12           ( BSW_CANIF_CFG_12_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM11 )
#define BSW_CANIF_RXCANTPPDUNUM11           ( BSW_CANIF_CFG_11_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM10 )
#define BSW_CANIF_RXCANTPPDUNUM10           ( BSW_CANIF_CFG_10_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM09 )
#define BSW_CANIF_RXCANTPPDUNUM09           ( BSW_CANIF_CFG_9_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM08 )
#define BSW_CANIF_RXCANTPPDUNUM08           ( BSW_CANIF_CFG_8_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM07 )
#define BSW_CANIF_RXCANTPPDUNUM07           ( BSW_CANIF_CFG_7_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM06 )
#define BSW_CANIF_RXCANTPPDUNUM06           ( BSW_CANIF_CFG_6_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM05 )
#define BSW_CANIF_RXCANTPPDUNUM05           ( BSW_CANIF_CFG_5_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM04 )
#define BSW_CANIF_RXCANTPPDUNUM04           ( BSW_CANIF_CFG_4_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM03 )
#define BSW_CANIF_RXCANTPPDUNUM03           ( BSW_CANIF_CFG_3_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM02 )
#define BSW_CANIF_RXCANTPPDUNUM02           ( BSW_CANIF_CFG_2_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM01 )
#define BSW_CANIF_RXCANTPPDUNUM01           ( BSW_CANIF_CFG_1_RXCANTPPDUNUM + BSW_CANIF_RXCANTPPDUNUM00 )
#define BSW_CANIF_RXCANTPPDUNUM00           ( BSW_CANIF_CFG_0_RXCANTPPDUNUM )

#define BSW_CANIF_RXCDD1PDUNUM              ( BSW_CANIF_RXCDD1PDUNUM31 )
#define BSW_CANIF_RXCDD1PDUNUM31            ( BSW_CANIF_CFG_31_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM30 )
#define BSW_CANIF_RXCDD1PDUNUM30            ( BSW_CANIF_CFG_30_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM29 )
#define BSW_CANIF_RXCDD1PDUNUM29            ( BSW_CANIF_CFG_29_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM28 )
#define BSW_CANIF_RXCDD1PDUNUM28            ( BSW_CANIF_CFG_28_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM27 )
#define BSW_CANIF_RXCDD1PDUNUM27            ( BSW_CANIF_CFG_27_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM26 )
#define BSW_CANIF_RXCDD1PDUNUM26            ( BSW_CANIF_CFG_26_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM25 )
#define BSW_CANIF_RXCDD1PDUNUM25            ( BSW_CANIF_CFG_25_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM24 )
#define BSW_CANIF_RXCDD1PDUNUM24            ( BSW_CANIF_CFG_24_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM23 )
#define BSW_CANIF_RXCDD1PDUNUM23            ( BSW_CANIF_CFG_23_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM22 )
#define BSW_CANIF_RXCDD1PDUNUM22            ( BSW_CANIF_CFG_22_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM21 )
#define BSW_CANIF_RXCDD1PDUNUM21            ( BSW_CANIF_CFG_21_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM20 )
#define BSW_CANIF_RXCDD1PDUNUM20            ( BSW_CANIF_CFG_20_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM19 )
#define BSW_CANIF_RXCDD1PDUNUM19            ( BSW_CANIF_CFG_19_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM18 )
#define BSW_CANIF_RXCDD1PDUNUM18            ( BSW_CANIF_CFG_18_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM17 )
#define BSW_CANIF_RXCDD1PDUNUM17            ( BSW_CANIF_CFG_17_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM16 )
#define BSW_CANIF_RXCDD1PDUNUM16            ( BSW_CANIF_CFG_16_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM15 )
#define BSW_CANIF_RXCDD1PDUNUM15            ( BSW_CANIF_CFG_15_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM14 )
#define BSW_CANIF_RXCDD1PDUNUM14            ( BSW_CANIF_CFG_14_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM13 )
#define BSW_CANIF_RXCDD1PDUNUM13            ( BSW_CANIF_CFG_13_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM12 )
#define BSW_CANIF_RXCDD1PDUNUM12            ( BSW_CANIF_CFG_12_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM11 )
#define BSW_CANIF_RXCDD1PDUNUM11            ( BSW_CANIF_CFG_11_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM10 )
#define BSW_CANIF_RXCDD1PDUNUM10            ( BSW_CANIF_CFG_10_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM09 )
#define BSW_CANIF_RXCDD1PDUNUM09            ( BSW_CANIF_CFG_9_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM08 )
#define BSW_CANIF_RXCDD1PDUNUM08            ( BSW_CANIF_CFG_8_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM07 )
#define BSW_CANIF_RXCDD1PDUNUM07            ( BSW_CANIF_CFG_7_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM06 )
#define BSW_CANIF_RXCDD1PDUNUM06            ( BSW_CANIF_CFG_6_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM05 )
#define BSW_CANIF_RXCDD1PDUNUM05            ( BSW_CANIF_CFG_5_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM04 )
#define BSW_CANIF_RXCDD1PDUNUM04            ( BSW_CANIF_CFG_4_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM03 )
#define BSW_CANIF_RXCDD1PDUNUM03            ( BSW_CANIF_CFG_3_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM02 )
#define BSW_CANIF_RXCDD1PDUNUM02            ( BSW_CANIF_CFG_2_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM01 )
#define BSW_CANIF_RXCDD1PDUNUM01            ( BSW_CANIF_CFG_1_RXCDD1PDUNUM + BSW_CANIF_RXCDD1PDUNUM00 )
#define BSW_CANIF_RXCDD1PDUNUM00            ( BSW_CANIF_CFG_0_RXCDD1PDUNUM )

#define BSW_CANIF_RXCDD2PDUNUM              ( BSW_CANIF_RXCDD2PDUNUM31 )
#define BSW_CANIF_RXCDD2PDUNUM31            ( BSW_CANIF_CFG_31_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM30 )
#define BSW_CANIF_RXCDD2PDUNUM30            ( BSW_CANIF_CFG_30_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM29 )
#define BSW_CANIF_RXCDD2PDUNUM29            ( BSW_CANIF_CFG_29_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM28 )
#define BSW_CANIF_RXCDD2PDUNUM28            ( BSW_CANIF_CFG_28_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM27 )
#define BSW_CANIF_RXCDD2PDUNUM27            ( BSW_CANIF_CFG_27_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM26 )
#define BSW_CANIF_RXCDD2PDUNUM26            ( BSW_CANIF_CFG_26_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM25 )
#define BSW_CANIF_RXCDD2PDUNUM25            ( BSW_CANIF_CFG_25_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM24 )
#define BSW_CANIF_RXCDD2PDUNUM24            ( BSW_CANIF_CFG_24_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM23 )
#define BSW_CANIF_RXCDD2PDUNUM23            ( BSW_CANIF_CFG_23_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM22 )
#define BSW_CANIF_RXCDD2PDUNUM22            ( BSW_CANIF_CFG_22_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM21 )
#define BSW_CANIF_RXCDD2PDUNUM21            ( BSW_CANIF_CFG_21_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM20 )
#define BSW_CANIF_RXCDD2PDUNUM20            ( BSW_CANIF_CFG_20_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM19 )
#define BSW_CANIF_RXCDD2PDUNUM19            ( BSW_CANIF_CFG_19_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM18 )
#define BSW_CANIF_RXCDD2PDUNUM18            ( BSW_CANIF_CFG_18_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM17 )
#define BSW_CANIF_RXCDD2PDUNUM17            ( BSW_CANIF_CFG_17_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM16 )
#define BSW_CANIF_RXCDD2PDUNUM16            ( BSW_CANIF_CFG_16_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM15 )
#define BSW_CANIF_RXCDD2PDUNUM15            ( BSW_CANIF_CFG_15_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM14 )
#define BSW_CANIF_RXCDD2PDUNUM14            ( BSW_CANIF_CFG_14_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM13 )
#define BSW_CANIF_RXCDD2PDUNUM13            ( BSW_CANIF_CFG_13_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM12 )
#define BSW_CANIF_RXCDD2PDUNUM12            ( BSW_CANIF_CFG_12_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM11 )
#define BSW_CANIF_RXCDD2PDUNUM11            ( BSW_CANIF_CFG_11_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM10 )
#define BSW_CANIF_RXCDD2PDUNUM10            ( BSW_CANIF_CFG_10_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM09 )
#define BSW_CANIF_RXCDD2PDUNUM09            ( BSW_CANIF_CFG_9_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM08 )
#define BSW_CANIF_RXCDD2PDUNUM08            ( BSW_CANIF_CFG_8_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM07 )
#define BSW_CANIF_RXCDD2PDUNUM07            ( BSW_CANIF_CFG_7_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM06 )
#define BSW_CANIF_RXCDD2PDUNUM06            ( BSW_CANIF_CFG_6_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM05 )
#define BSW_CANIF_RXCDD2PDUNUM05            ( BSW_CANIF_CFG_5_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM04 )
#define BSW_CANIF_RXCDD2PDUNUM04            ( BSW_CANIF_CFG_4_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM03 )
#define BSW_CANIF_RXCDD2PDUNUM03            ( BSW_CANIF_CFG_3_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM02 )
#define BSW_CANIF_RXCDD2PDUNUM02            ( BSW_CANIF_CFG_2_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM01 )
#define BSW_CANIF_RXCDD2PDUNUM01            ( BSW_CANIF_CFG_1_RXCDD2PDUNUM + BSW_CANIF_RXCDD2PDUNUM00 )
#define BSW_CANIF_RXCDD2PDUNUM00            ( BSW_CANIF_CFG_0_RXCDD2PDUNUM )

#define BSW_CANIF_RXXCPPDUNUM               ( BSW_CANIF_RXXCPPDUNUM31 )
#define BSW_CANIF_RXXCPPDUNUM31             ( BSW_CANIF_CFG_31_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM30 )
#define BSW_CANIF_RXXCPPDUNUM30             ( BSW_CANIF_CFG_30_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM29 )
#define BSW_CANIF_RXXCPPDUNUM29             ( BSW_CANIF_CFG_29_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM28 )
#define BSW_CANIF_RXXCPPDUNUM28             ( BSW_CANIF_CFG_28_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM27 )
#define BSW_CANIF_RXXCPPDUNUM27             ( BSW_CANIF_CFG_27_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM26 )
#define BSW_CANIF_RXXCPPDUNUM26             ( BSW_CANIF_CFG_26_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM25 )
#define BSW_CANIF_RXXCPPDUNUM25             ( BSW_CANIF_CFG_25_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM24 )
#define BSW_CANIF_RXXCPPDUNUM24             ( BSW_CANIF_CFG_24_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM23 )
#define BSW_CANIF_RXXCPPDUNUM23             ( BSW_CANIF_CFG_23_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM22 )
#define BSW_CANIF_RXXCPPDUNUM22             ( BSW_CANIF_CFG_22_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM21 )
#define BSW_CANIF_RXXCPPDUNUM21             ( BSW_CANIF_CFG_21_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM20 )
#define BSW_CANIF_RXXCPPDUNUM20             ( BSW_CANIF_CFG_20_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM19 )
#define BSW_CANIF_RXXCPPDUNUM19             ( BSW_CANIF_CFG_19_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM18 )
#define BSW_CANIF_RXXCPPDUNUM18             ( BSW_CANIF_CFG_18_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM17 )
#define BSW_CANIF_RXXCPPDUNUM17             ( BSW_CANIF_CFG_17_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM16 )
#define BSW_CANIF_RXXCPPDUNUM16             ( BSW_CANIF_CFG_16_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM15 )
#define BSW_CANIF_RXXCPPDUNUM15             ( BSW_CANIF_CFG_15_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM14 )
#define BSW_CANIF_RXXCPPDUNUM14             ( BSW_CANIF_CFG_14_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM13 )
#define BSW_CANIF_RXXCPPDUNUM13             ( BSW_CANIF_CFG_13_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM12 )
#define BSW_CANIF_RXXCPPDUNUM12             ( BSW_CANIF_CFG_12_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM11 )
#define BSW_CANIF_RXXCPPDUNUM11             ( BSW_CANIF_CFG_11_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM10 )
#define BSW_CANIF_RXXCPPDUNUM10             ( BSW_CANIF_CFG_10_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM09 )
#define BSW_CANIF_RXXCPPDUNUM09             ( BSW_CANIF_CFG_9_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM08 )
#define BSW_CANIF_RXXCPPDUNUM08             ( BSW_CANIF_CFG_8_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM07 )
#define BSW_CANIF_RXXCPPDUNUM07             ( BSW_CANIF_CFG_7_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM06 )
#define BSW_CANIF_RXXCPPDUNUM06             ( BSW_CANIF_CFG_6_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM05 )
#define BSW_CANIF_RXXCPPDUNUM05             ( BSW_CANIF_CFG_5_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM04 )
#define BSW_CANIF_RXXCPPDUNUM04             ( BSW_CANIF_CFG_4_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM03 )
#define BSW_CANIF_RXXCPPDUNUM03             ( BSW_CANIF_CFG_3_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM02 )
#define BSW_CANIF_RXXCPPDUNUM02             ( BSW_CANIF_CFG_2_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM01 )
#define BSW_CANIF_RXXCPPDUNUM01             ( BSW_CANIF_CFG_1_RXXCPPDUNUM + BSW_CANIF_RXXCPPDUNUM00 )
#define BSW_CANIF_RXXCPPDUNUM00             ( BSW_CANIF_CFG_0_RXXCPPDUNUM )

#define BSW_CANIF_PKTCAN_EXTA1_USE            BSW_CANIF_PKTCAN_EXTA1_USE_CH0      /* Communication protocol type:Extended CAN (TypeA1) used/unused definition */
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH0        ((BSW_CANIF_CFG_CH0_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH1)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH1        ((BSW_CANIF_CFG_CH1_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH2)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH2        ((BSW_CANIF_CFG_CH2_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH3)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH3        ((BSW_CANIF_CFG_CH3_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH4)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH4        ((BSW_CANIF_CFG_CH4_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH5)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH5        ((BSW_CANIF_CFG_CH5_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH6)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH6        ((BSW_CANIF_CFG_CH6_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH7)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH7        ((BSW_CANIF_CFG_CH7_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH8)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH8        ((BSW_CANIF_CFG_CH8_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH9)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH9        ((BSW_CANIF_CFG_CH9_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH10)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH10       ((BSW_CANIF_CFG_CH10_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH11)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH11       ((BSW_CANIF_CFG_CH11_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH12)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH12       ((BSW_CANIF_CFG_CH12_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH13)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH13       ((BSW_CANIF_CFG_CH13_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH14)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH14       ((BSW_CANIF_CFG_CH14_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH15)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH15       ((BSW_CANIF_CFG_CH15_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH16)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH16       ((BSW_CANIF_CFG_CH16_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH17)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH17       ((BSW_CANIF_CFG_CH17_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH18)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH18       ((BSW_CANIF_CFG_CH18_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH19)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH19       ((BSW_CANIF_CFG_CH19_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH20)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH20       ((BSW_CANIF_CFG_CH20_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH21)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH21       ((BSW_CANIF_CFG_CH21_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH22)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH22       ((BSW_CANIF_CFG_CH22_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH23)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH23       ((BSW_CANIF_CFG_CH23_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH24)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH24       ((BSW_CANIF_CFG_CH24_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH25)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH25       ((BSW_CANIF_CFG_CH25_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH26)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH26       ((BSW_CANIF_CFG_CH26_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH27)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH27       ((BSW_CANIF_CFG_CH27_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH28)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH28       ((BSW_CANIF_CFG_CH28_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH29)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH29       ((BSW_CANIF_CFG_CH29_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH30)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH30       ((BSW_CANIF_CFG_CH30_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA1_USE_CH31)
#define BSW_CANIF_PKTCAN_EXTA1_USE_CH31       ((BSW_CANIF_CFG_CH31_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A1) ? BSW_USE : BSW_NOUSE )

#define BSW_CANIF_PKTCAN_EXTA2_USE            BSW_CANIF_PKTCAN_EXTA2_USE_CH0      /* Communication protocol type:Extended CAN (TypeA2) used/unused definition */
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH0        ((BSW_CANIF_CFG_CH0_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH1)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH1        ((BSW_CANIF_CFG_CH1_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH2)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH2        ((BSW_CANIF_CFG_CH2_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH3)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH3        ((BSW_CANIF_CFG_CH3_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH4)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH4        ((BSW_CANIF_CFG_CH4_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH5)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH5        ((BSW_CANIF_CFG_CH5_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH6)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH6        ((BSW_CANIF_CFG_CH6_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH7)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH7        ((BSW_CANIF_CFG_CH7_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH8)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH8        ((BSW_CANIF_CFG_CH8_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH9)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH9        ((BSW_CANIF_CFG_CH9_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH10)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH10       ((BSW_CANIF_CFG_CH10_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH11)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH11       ((BSW_CANIF_CFG_CH11_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH12)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH12       ((BSW_CANIF_CFG_CH12_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH13)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH13       ((BSW_CANIF_CFG_CH13_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH14)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH14       ((BSW_CANIF_CFG_CH14_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH15)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH15       ((BSW_CANIF_CFG_CH15_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH16)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH16       ((BSW_CANIF_CFG_CH16_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH17)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH17       ((BSW_CANIF_CFG_CH17_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH18)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH18       ((BSW_CANIF_CFG_CH18_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH19)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH19       ((BSW_CANIF_CFG_CH19_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH20)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH20       ((BSW_CANIF_CFG_CH20_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH21)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH21       ((BSW_CANIF_CFG_CH21_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH22)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH22       ((BSW_CANIF_CFG_CH22_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH23)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH23       ((BSW_CANIF_CFG_CH23_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH24)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH24       ((BSW_CANIF_CFG_CH24_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH25)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH25       ((BSW_CANIF_CFG_CH25_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH26)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH26       ((BSW_CANIF_CFG_CH26_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH27)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH27       ((BSW_CANIF_CFG_CH27_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH28)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH28       ((BSW_CANIF_CFG_CH28_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH29)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH29       ((BSW_CANIF_CFG_CH29_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH30)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH30       ((BSW_CANIF_CFG_CH30_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_CANIF_PKTCAN_EXTA2_USE_CH31)
#define BSW_CANIF_PKTCAN_EXTA2_USE_CH31       ((BSW_CANIF_CFG_CH31_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_A2) ? BSW_USE : BSW_NOUSE )

#define BSW_CANIF_PKTCAN_EXTB_USE             BSW_CANIF_PKTCAN_EXTB_USE_CH0       /* Communication protocol type:Extended CAN (TypeB) used/unused definition */
#define BSW_CANIF_PKTCAN_EXTB_USE_CH0         ((BSW_CANIF_CFG_CH0_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH1)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH1         ((BSW_CANIF_CFG_CH1_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH2)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH2         ((BSW_CANIF_CFG_CH2_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH3)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH3         ((BSW_CANIF_CFG_CH3_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH4)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH4         ((BSW_CANIF_CFG_CH4_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH5)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH5         ((BSW_CANIF_CFG_CH5_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH6)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH6         ((BSW_CANIF_CFG_CH6_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH7)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH7         ((BSW_CANIF_CFG_CH7_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH8)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH8         ((BSW_CANIF_CFG_CH8_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH9)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH9         ((BSW_CANIF_CFG_CH9_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH10)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH10        ((BSW_CANIF_CFG_CH10_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH11)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH11        ((BSW_CANIF_CFG_CH11_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH12)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH12        ((BSW_CANIF_CFG_CH12_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH13)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH13        ((BSW_CANIF_CFG_CH13_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH14)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH14        ((BSW_CANIF_CFG_CH14_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH15)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH15        ((BSW_CANIF_CFG_CH15_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH16)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH16        ((BSW_CANIF_CFG_CH16_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH17)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH17        ((BSW_CANIF_CFG_CH17_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH18)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH18        ((BSW_CANIF_CFG_CH18_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH19)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH19        ((BSW_CANIF_CFG_CH19_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH20)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH20        ((BSW_CANIF_CFG_CH20_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH21)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH21        ((BSW_CANIF_CFG_CH21_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH22)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH22        ((BSW_CANIF_CFG_CH22_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH23)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH23        ((BSW_CANIF_CFG_CH23_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH24)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH24        ((BSW_CANIF_CFG_CH24_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH25)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH25        ((BSW_CANIF_CFG_CH25_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH26)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH26        ((BSW_CANIF_CFG_CH26_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH27)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH27        ((BSW_CANIF_CFG_CH27_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH28)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH28        ((BSW_CANIF_CFG_CH28_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH29)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH29        ((BSW_CANIF_CFG_CH29_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH30)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH30        ((BSW_CANIF_CFG_CH30_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_CANIF_PKTCAN_EXTB_USE_CH31)
#define BSW_CANIF_PKTCAN_EXTB_USE_CH31        ((BSW_CANIF_CFG_CH31_PROTOCOL == BSW_CANIF_PROTOCOL_EXT_CAN_B) ? BSW_USE : BSW_NOUSE )

#define BSW_CANIF_CHKSUM_PTN2_USE             BSW_CANIF_CHKSUM_PTN2_USE_CH0       /* Checksum pattern:Pattern 2 Use/Unuse definition */
#define BSW_CANIF_CHKSUM_PTN2_USE_CH0         ((BSW_CANIF_CFG_CH0_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH1)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH1         ((BSW_CANIF_CFG_CH1_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH2)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH2         ((BSW_CANIF_CFG_CH2_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH3)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH3         ((BSW_CANIF_CFG_CH3_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH4)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH4         ((BSW_CANIF_CFG_CH4_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH5)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH5         ((BSW_CANIF_CFG_CH5_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH6)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH6         ((BSW_CANIF_CFG_CH6_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH7)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH7         ((BSW_CANIF_CFG_CH7_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH8)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH8         ((BSW_CANIF_CFG_CH8_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH9)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH9         ((BSW_CANIF_CFG_CH9_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH10)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH10        ((BSW_CANIF_CFG_CH10_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH11)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH11        ((BSW_CANIF_CFG_CH11_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH12)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH12        ((BSW_CANIF_CFG_CH12_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH13)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH13        ((BSW_CANIF_CFG_CH13_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH14)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH14        ((BSW_CANIF_CFG_CH14_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH15)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH15        ((BSW_CANIF_CFG_CH15_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH16)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH16        ((BSW_CANIF_CFG_CH16_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH17)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH17        ((BSW_CANIF_CFG_CH17_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH18)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH18        ((BSW_CANIF_CFG_CH18_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH19)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH19        ((BSW_CANIF_CFG_CH19_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH20)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH20        ((BSW_CANIF_CFG_CH20_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH21)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH21        ((BSW_CANIF_CFG_CH21_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH22)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH22        ((BSW_CANIF_CFG_CH22_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH23)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH23        ((BSW_CANIF_CFG_CH23_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH24)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH24        ((BSW_CANIF_CFG_CH24_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH25)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH25        ((BSW_CANIF_CFG_CH25_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH26)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH26        ((BSW_CANIF_CFG_CH26_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH27)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH27        ((BSW_CANIF_CFG_CH27_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH28)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH28        ((BSW_CANIF_CFG_CH28_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH29)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH29        ((BSW_CANIF_CFG_CH29_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH30)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH30        ((BSW_CANIF_CFG_CH30_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_CANIF_CHKSUM_PTN2_USE_CH31)
#define BSW_CANIF_CHKSUM_PTN2_USE_CH31        ((BSW_CANIF_CFG_CH31_CHKSUM_PTN == BSW_CANIF_CHKSUM_PTN2) ? BSW_USE : BSW_NOUSE )

#define BSW_CANIF_MSG_CYCL_TIME               (1000U)
#define BSW_CANIF_TIMEOUT_TIME                (3000U)

/*--------------------------------------------------------------------------*/
/* Types                                                                    */
/*--------------------------------------------------------------------------*/


/*--------------------------------------------------------------------------*/
/* Function Prototypes                                                      */
/*--------------------------------------------------------------------------*/


/*--------------------------------------------------------------------------*/
/* Data                                                                     */
/*--------------------------------------------------------------------------*/


/*--------------------------------------------------------------------------*/
/* Constants                                                                */
/*--------------------------------------------------------------------------*/


#endif  /* BSW_CANIF_CONFIG_H */

/****************************************************************************/
/* History                                                                  */
/*  Version         :Date                                                   */
/*  v1-0-0          :2017/02/22                                             */
/*  v2-0-0          :2021/12/02                                             */
/*  v3-0-0          :2024/08/30                                             */
/****************************************************************************/

/**** End of File ***********************************************************/
