/* 2.6.0 */
/*===================================================================================================================================*/
/*  Copyright DENSO Corporation                                                                                                      */
/*===================================================================================================================================*/
/*  Toyota IPC/MET : Vardef Electrical System Option.                                                                                */
/*                                                                                                                                   */
/*===================================================================================================================================*/

#ifndef VARDEF_ESOPT_CHANNEL_H
#define VARDEF_ESOPT_CHANNEL_H

/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Version                                                                                                                          */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define VARDEF_ESOPT_CHANNEL_H_MAJOR             (2)
#define VARDEF_ESOPT_CHANNEL_H_MINOR             (6)
#define VARDEF_ESOPT_CHANNEL_H_PATCH             (0)

/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Include Files                                                                                                                    */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Literal Definitions                                                                                                              */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define VDF_ESO_CH_LSB_AVA_IDX                   (5U)
#define VDF_ESO_CH_BIT_AVA_LSB                   (0x001fU)

/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define VDF_ESO_NUM_CH                           (267U)

#define VDF_ESO_CH_INDSPDALT                     (  0U)
#define VDF_ESO_CH_CNTR_DISP                     (  1U)
#define VDF_ESO_CH_AUDIO                         (  2U)
#define VDF_ESO_CH_RARCLCK                       (  3U)
#define VDF_ESO_CH_D_DPTZ                        (  4U)
#define VDF_ESO_CH_P_DPTZ                        (  5U)
#define VDF_ESO_CH_ECOFLAG                       (  6U)
#define VDF_ESO_CH_SBW                           (  7U)
#define VDF_ESO_CH_SHIFT                         (  8U)
#define VDF_ESO_CH_TPMS                          (  9U)
#define VDF_ESO_CH_TPMSCHN                       ( 10U)
#define VDF_ESO_CH_VSC                           ( 11U)
#define VDF_ESO_CH_EPB                           ( 12U)
#define VDF_ESO_CH_INFRA                         ( 13U)
#define VDF_ESO_CH_BSM                           ( 14U)
#define VDF_ESO_CH_FHL                           ( 15U)
#define VDF_ESO_CH_DOA                           ( 16U)
#define VDF_ESO_CH_RCD                           ( 17U)
#define VDF_ESO_CH_CSR_TTR                       ( 18U)
#define VDF_ESO_CH_ICS                           ( 19U)
#define VDF_ESO_CH_PDA                           ( 20U)
#define VDF_ESO_CH_PCS                           ( 21U)
#define VDF_ESO_CH_LTA                           ( 22U)
#define VDF_ESO_CH_DS1_LDA                       ( 23U)
#define VDF_ESO_CH_RSA                           ( 24U)
#define VDF_ESO_CH_AHB                           ( 25U)
#define VDF_ESO_CH_ACC                           ( 26U)
#define VDF_ESO_CH_SW_LCS                        ( 27U)
#define VDF_ESO_CH_LCS                           ( 28U)
#define VDF_ESO_CH_TMN                           ( 29U)
#define VDF_ESO_CH_LVN                           ( 30U)
#define VDF_ESO_CH_ISA                           ( 31U)
#define VDF_ESO_CH_DSC                           ( 32U)
#define VDF_ESO_CH_CSR                           ( 33U)
#define VDF_ESO_CH_AUTOP                         ( 34U)
#define VDF_ESO_CH_RCTA                          ( 35U)
#define VDF_ESO_CH_AHS                           ( 36U)
#define VDF_ESO_CH_BRKHLD                        ( 37U)
#define VDF_ESO_CH_SW_PCS                        ( 38U)
#define VDF_ESO_CH_CXSWS1S02                     ( 39U)
#define VDF_ESO_CH_SW_PDA                        ( 40U)
#define VDF_ESO_CH_CXSWS1S04                     ( 41U)
#define VDF_ESO_CH_CXMPS1S01                     ( 42U)
#define VDF_ESO_CH_AISMM                         ( 43U)
#define VDF_ESO_CH_NE_MET                        ( 44U)
#define VDF_ESO_CH_HV_NE                         ( 45U)
#define VDF_ESO_CH_MM_AUDIO                      ( 46U)
#define VDF_ESO_CH_MM_TEL                        ( 47U)
#define VDF_ESO_CH_MT                            ( 48U)
#define VDF_ESO_CH_AT                            ( 49U)
#define VDF_ESO_CH_DRVMD_NRML                    ( 50U)
#define VDF_ESO_CH_DRVMD_SPRT                    ( 51U)
#define VDF_ESO_CH_DRVMD_SPRT_S                  ( 52U)
#define VDF_ESO_CH_DRVMD_SPRT_SP                 ( 53U)
#define VDF_ESO_CH_DRVMD_ECO                     ( 54U)
#define VDF_ESO_CH_DRVMD_CMFRT                   ( 55U)
#define VDF_ESO_CH_DRVMD_CSTM                    ( 56U)
#define VDF_ESO_CH_SW_AC100V                     ( 57U)
#define VDF_ESO_CH_MM_NAVI                       ( 58U)
#define VDF_ESO_CH_OILMNT                        ( 59U)
#define VDF_ESO_CH_SW_BSM                        ( 60U)
#define VDF_ESO_CH_SW_CSR                        ( 61U)
#define VDF_ESO_CH_MMT_SMT                       ( 62U)
#define VDF_ESO_CH_NAVI_TAB                      ( 63U)
#define VDF_ESO_CH_SW_PBDHND                     ( 64U)
#define VDF_ESO_CH_DIGKEY                        ( 65U)
#define VDF_ESO_CH_SW_DIGKEY                     ( 66U)
#define VDF_ESO_CH_SW_PBD                        ( 67U)
#define VDF_ESO_CH_ROLAWA                        ( 68U)
#define VDF_ESO_CH_SW_PBDFLLOPN                  ( 69U)
#define VDF_ESO_CH_SW_PBDVOL                     ( 70U)
#define VDF_ESO_CH_SW_INFRACACC                  ( 71U)
#define VDF_ESO_CH_DMC                           ( 72U)
#define VDF_ESO_CH_SW_DMCDROW                    ( 73U)
#define VDF_ESO_CH_SW_INFRAEMGSET                ( 74U)
#define VDF_ESO_CH_SW_INFRAEMGONDIS              ( 75U)
#define VDF_ESO_CH_SW_LCA                        ( 76U)
#define VDF_ESO_CH_SW_INFRARDE                   ( 77U)
#define VDF_ESO_CH_SW_RTAN                       ( 78U)
#define VDF_ESO_CH_SW_RTANSUP                    ( 79U)
#define VDF_ESO_CH_SW_SEASNS                     ( 80U)
#define VDF_ESO_CH_SW_SEA                        ( 81U)
#define VDF_ESO_CH_SW_SEAIND                     ( 82U)
#define VDF_ESO_CH_SW_TSGONOFF                   ( 83U)
#define VDF_ESO_CH_SW_TSGTM                      ( 84U)
#define VDF_ESO_CH_SW_LDA                        ( 85U)
#define VDF_ESO_CH_SW_LDALSAST                   ( 86U)
#define VDF_ESO_CH_SW_ALTOPT_VB                  ( 87U)
#define VDF_ESO_CH_SW_ALTOPT_BOF                 ( 88U)
#define VDF_ESO_CH_SW_ALTOPT_VBOF                ( 89U)
#define VDF_ESO_CH_SW_LDWTEXT                    ( 90U)
#define VDF_ESO_CH_SW_SWSEXIST                   ( 91U)
#define VDF_ESO_CH_SW_BSD_ITCR                   ( 92U)
#define VDF_ESO_CH_SW_BSD_ILCR                   ( 93U)
#define VDF_ESO_CH_SW_PCSBZ                      ( 94U)
#define VDF_ESO_CH_SW_CSRVOL                     ( 95U)
#define VDF_ESO_CH_SW_CSRPOS                     ( 96U)
#define VDF_ESO_CH_SW_RCTA                       ( 97U)
#define VDF_ESO_CH_SW_RCTAVOL                    ( 98U)
#define VDF_ESO_CH_SW_RCD                        ( 99U)
#define VDF_ESO_CH_SW_PKSB                       (100U)
#define VDF_ESO_CH_SW_ACCCRS                     (101U)
#define VDF_ESO_CH_SW_ACCRSTA                    (102U)
#define VDF_ESO_CH_SW_ACCAPP                     (103U)
#define VDF_ESO_CH_SW_ACCSPD                     (104U)
#define VDF_ESO_CH_SW_ACCGUIDE                   (105U)
#define VDF_ESO_CH_SW_ACCCURV                    (106U)
#define VDF_ESO_CH_SW_FCTA                       (107U)
#define VDF_ESO_CH_SW_FCTATMN                    (108U)
#define VDF_ESO_CH_SW_RSR                        (109U)
#define VDF_ESO_CH_SW_DSC                        (110U)
#define VDF_ESO_CH_SW_THESEN                     (111U)
#define VDF_ESO_CH_SW_TPMS_VAR                   (112U)
#define VDF_ESO_CH_SW_BATCSW                     (113U)
#define VDF_ESO_CH_PEDPRO                        (114U)
#define VDF_ESO_CH_DRS                           (115U)
#define VDF_ESO_CH_SW_STPIND                     (116U)
#define VDF_ESO_CH_SW_LVN                        (117U)
#define VDF_ESO_CH_SW_TMN                        (118U)
#define VDF_ESO_CH_SW_LTA                        (119U)
#define VDF_ESO_CH_SW_LTA_NA                     (120U)
#define VDF_ESO_CH_GPF                           (121U)
#define VDF_ESO_CH_MWL                           (122U)
#define VDF_ESO_CH_SW_CVRS                       (123U)
#define VDF_ESO_CH_SW_BATWSW                     (124U)
#define VDF_ESO_CH_SW_DCLVICUS                   (125U)
#define VDF_ESO_CH_SW_DCLVMCUS                   (126U)
#define VDF_ESO_CH_SW_ACCACCL                    (127U)
#define VDF_ESO_CH_SW_PERSET                     (128U)
#define VDF_ESO_CH_CXCMB1S05                     (129U)
#define VDF_ESO_CH_CXCMB1S06                     (130U)
#define VDF_ESO_CH_SW_ACCDYNM                    (131U)
#define VDF_ESO_CH_SW_LTA_HOFDI                  (132U)
#define VDF_ESO_CH_SW_PDASA                      (133U)
#define VDF_ESO_CH_SW_PDADA                      (134U)
#define VDF_ESO_CH_SW_PDAOAA                     (135U)
#define VDF_ESO_CH_SW_RSA_TSRSWEXT               (136U)
#define VDF_ESO_CH_SW_RSA_OVRTKEXT_AUD           (137U)
#define VDF_ESO_CH_SW_RSA_NTFLVEXT               (138U)
#define VDF_ESO_CH_SW_RSA_OTHEREXT               (139U)
#define VDF_ESO_CH_SW_RSA_XSSPDEXT               (140U)
#define VDF_ESO_CH_GVIF2                         (141U)
#define VDF_ESO_CH_AISETH                        (142U)
#define VDF_ESO_CH_ETH_AUDIO                     (143U)
#define VDF_ESO_CH_ETH_TEL                       (144U)
#define VDF_ESO_CH_ETH_NAVI                      (145U)
#define VDF_ESO_CH_ETH_NAVI_TAB                  (146U)
#define VDF_ESO_CH_SW_RTWUCT                     (147U)
#define VDF_ESO_CH_SW_RSA_SPBZEXT                (148U)
#define VDF_ESO_CH_SW_BSM_BSDDISP1               (149U)
#define VDF_ESO_CH_SW_BSM_BSDDISP2               (150U)
#define VDF_ESO_CH_PVM                           (151U)
#define VDF_ESO_CH_MTM                           (152U)
#define VDF_ESO_CH_SIM                           (153U)
#define VDF_ESO_CH_DRVMD_RANGE                   (154U)
#define VDF_ESO_CH_DRVMD_RCMFRT                  (155U)
#define VDF_ESO_CH_AVS                           (156U)
#define VDF_ESO_CH_SW_RSA_OVRTKEXT_HAP           (157U)
#define VDF_ESO_CH_SW_PNCCUS                     (158U)
#define VDF_ESO_CH_SW_TBC                        (159U)
#define VDF_ESO_CH_SW_LCKCUS_UNLOCK              (160U)
#define VDF_ESO_CH_SW_LCKCUS_AUTOLOCK            (161U)
#define VDF_ESO_CH_EDSS                          (162U)
#define VDF_ESO_CH_CC                            (163U)
#define VDF_ESO_CH_4WDSYS                        (164U)
#define VDF_ESO_CH_ERM                           (165U)
#define VDF_ESO_CH_TM                            (166U)
#define VDF_ESO_CH_LBW                           (167U)
#define VDF_ESO_CH_FCTA                          (168U)
#define VDF_ESO_CH_SWS                           (169U)
#define VDF_ESO_CH_PMAR                          (170U)
#define VDF_ESO_CH_SW_AC100V_TESTMODE            (171U)
#define VDF_ESO_CH_SW_SRPCUS                     (172U)
#define VDF_ESO_CH_SW_DEPARTURE_PREVENT          (173U)
#define VDF_ESO_CH_SW_PCSEXIST                   (174U)
#define VDF_ESO_CH_SW_NOETY                      (175U)
#define VDF_ESO_CH_ECB                           (176U)
#define VDF_ESO_CH_MOP                           (177U)
#define VDF_ESO_CH_SYS_NOT_USED50                (178U)
#define VDF_ESO_CH_SYS_NOT_USED51                (179U)
#define VDF_ESO_CH_ADAS                          (180U)
#define VDF_ESO_CH_PTS_MILREQ                    (181U)
#define VDF_ESO_CH_AVSEXT                        (182U)
#define VDF_ESO_CH_OILLVG                        (183U)
#define VDF_ESO_CH_EPSSA                         (184U)
#define VDF_ESO_CH_TRLR_EQ                       (185U)
#define VDF_ESO_CH_GERPOS                        (186U)
#define VDF_ESO_CH_SW_PTL                        (187U)
#define VDF_ESO_CH_SOHDSP                        (188U)
#define VDF_ESO_CH_HVSYSIND                      (189U)
#define VDF_ESO_CH_SW_NOETY_RED                  (190U)
#define VDF_ESO_CH_SW_TRAILLER                   (191U)
#define VDF_ESO_CH_SW_ACCELERATION               (192U)
#define VDF_ESO_CH_SW_ECORUNLEV                  (193U)
#define VDF_ESO_CH_SW_INTERSECTION               (194U)
#define VDF_ESO_CH_SW_SWITCH_CC                  (195U)
#define VDF_ESO_CH_SW_SPDLIM_OFFSET              (196U)
#define VDF_ESO_CH_SW_SAS                        (197U)
#define VDF_ESO_CH_SW_PRECEDING_VEHCLE           (198U)
#define VDF_ESO_CH_SW_TRAFFIC_SIGNAL             (199U)
#define VDF_ESO_CH_SW_DM_CAMERA                  (200U)
#define VDF_ESO_CH_SW_WRN_SEN                    (201U)
#define VDF_ESO_CH_SW_SWIVEL                     (202U)
#define VDF_ESO_CH_SW_SHADING_AREA               (203U)
#define VDF_ESO_CH_SW_ACINV_1500W                (204U)
#define VDF_ESO_CH_SW_ACINV_2400W                (205U)
#define VDF_ESO_CH_SW_ACINV_7200W                (206U)
#define VDF_ESO_CH_BRPADW                        (207U)
#define VDF_ESO_CH_SW_VHCL_HCTRL                 (208U)
#define VDF_ESO_CH_SW_ACCESS_MODE                (209U)
#define VDF_ESO_CH_GVIF2_METDISP                 (210U)
#define VDF_ESO_CH_SYS_NOT_USED1                 (211U)
#define VDF_ESO_CH_SYS_RACE_TRACK                (212U)
#define VDF_ESO_CH_SGAUGE                        (213U)
#define VDF_ESO_CH_SYS_NOT_USED2                 (214U)
#define VDF_ESO_CH_EVMIL_RED                     (215U)
#define VDF_ESO_CH_EVMIL_AMBER                   (216U)
#define VDF_ESO_CH_SW_OMRBB                      (217U)
#define VDF_ESO_CH_SW_OMRBB_MLRSEL               (218U)
#define VDF_ESO_CH_SW_OMRBB_REVERSE              (219U)
#define VDF_ESO_CH_SW_OMRBB_AUTO                 (220U)
#define VDF_ESO_CH_SW_OMRBB_NONAUTO              (221U)
#define VDF_ESO_CH_SYS_NOT_USED8                 (222U)
#define VDF_ESO_CH_SYS_NOT_USED9                 (223U)
#define VDF_ESO_CH_SYS_NOT_USED10                (224U)
#define VDF_ESO_CH_SYS_NOT_USED11                (225U)
#define VDF_ESO_CH_SYS_NOT_USED12                (226U)
#define VDF_ESO_CH_SYS_NOT_USED13                (227U)
#define VDF_ESO_CH_SYS_NOT_USED14                (228U)
#define VDF_ESO_CH_SYS_NOT_USED15                (229U)
#define VDF_ESO_CH_ADIEXIST                      (230U)
#define VDF_ESO_CH_SYS_NOT_USED17                (231U)
#define VDF_ESO_CH_SW_TITE                       (232U)
#define VDF_ESO_CH_SYS_NOT_USED19                (233U)
#define VDF_ESO_CH_SW_HEDLMP_AUT                 (234U)
#define VDF_ESO_CH_SW_HEDLMP_HED                 (235U)
#define VDF_ESO_CH_SW_HEDLMP_TAL                 (236U)
#define VDF_ESO_CH_SW_HEDLMP_TAL_DBL             (237U)
#define VDF_ESO_CH_SW_HEDLMP_DRLOFF              (238U)
#define VDF_ESO_CH_SW_HEDLMP_OFF                 (239U)
#define VDF_ESO_CH_SW_HEDLMP_OFF_DBL             (240U)
#define VDF_ESO_CH_SW_HEDLMP_DRL                 (241U)
#define VDF_ESO_CH_SW_FRONT_FOG                  (242U)
#define VDF_ESO_CH_SW_REAR_FOG                   (243U)
#define VDF_ESO_CH_SYS_NOT_USED30                (244U)
#define VDF_ESO_CH_SW_RAINDROP_SENSOR            (245U)
#define VDF_ESO_CH_SW_INTTIME_AJUST              (246U)
#define VDF_ESO_CH_SW_REAR_WIPER_OFF             (247U)
#define VDF_ESO_CH_SW_REAR_WIPER_LO              (248U)
#define VDF_ESO_CH_SW_REAR_WIPER_INT             (249U)
#define VDF_ESO_CH_SW_REAR_WASHER                (250U)
#define VDF_ESO_CH_SW_SERVICE_POS                (251U)
#define VDF_ESO_CH_SYS_NOT_USED38                (252U)
#define VDF_ESO_CH_SW_WIPER_DEICER               (253U)
#define VDF_ESO_CH_SOLCHG                        (254U)
#define VDF_ESO_CH_SW_OBBPWL                     (255U)
#define VDF_ESO_CH_SYS_NOT_USED42                (256U)
#define VDF_ESO_CH_VHCOBBSD                      (257U)
#define VDF_ESO_CH_SW_OBBMODE                    (258U)
#define VDF_ESO_CH_ERM_ADU                       (259U)
#define VDF_ESO_CH_SW_OBBSAV                     (260U)
#define VDF_ESO_CH_SYS_NOT_USED47                (261U)
#define VDF_ESO_CH_SYS_NOT_USED48                (262U)
#define VDF_ESO_CH_SYS_NOT_USED49                (263U)
#define VDF_ESO_CH_SW_DPM1                       (264U)
#define VDF_ESO_CH_SW_DPM2                       (265U)
#define VDF_ESO_CH_SW_DPM3                       (266U)

#define VDF_ESO_CH_DA                            (255U)
#define VDF_ESO_CH_CXSWS1S01                     (255U)
#define VDF_ESO_CH_CXSWS1S03                     (255U)
#define VDF_ESO_CH_SW_DESA                       (255U)
#define VDF_ESO_CH_SW_PSD_LPSK                   (255U)
#define VDF_ESO_CH_SW_PSD_LPSV                   (255U)
#define VDF_ESO_CH_SW_PSD_RPSV                   (255U)
#define VDF_ESO_CH_SW_PSD_RPSK                   (255U)
#define VDF_ESO_CH_SW_RSA_OVRTKEXT               (255U)

/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define VDF_ESO_NOW_AVA                          ((VDF_ESO_NUM_CH + 31U) >> 5U)

#define VDF_ESO_INI_W0                           (0x00000801U)
#define VDF_ESO_INI_W1                           (0x00000000U)
#define VDF_ESO_INI_W2                           (0x00000000U)
#define VDF_ESO_INI_W3                           (0x00000000U)
#define VDF_ESO_INI_W4                           (0x00000001U)
#define VDF_ESO_INI_W5                           (0x00200000U)
#define VDF_ESO_INI_W6                           (0x00800000U)
#define VDF_ESO_INI_W7                           (0x00000000U)
#define VDF_ESO_INI_W8                           (0x00000000U)

#define VDF_ESO_NVM_W0                           (0x9FFDC600U)
#define VDF_ESO_NVM_W1                           (0x30000781U)
#define VDF_ESO_NVM_W2                           (0x3FA3D168U)
#define VDF_ESO_NVM_W3                           (0x0D8D0CBAU)
#define VDF_ESO_NVM_W4                           (0x507835FEU)
#define VDF_ESO_NVM_W5                           (0xC030E76CU)
#define VDF_ESO_NVM_W6                           (0x3F840FFFU)
#define VDF_ESO_NVM_W7                           (0xAFEFFD40U)
#define VDF_ESO_NVM_W8                           (0x0000071CU)

/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Macro Definitions                                                                                                                */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define u2_VDF_ESO_CH_TO_IDX(u2_ch)              ((U2)((u2_ch) >> VDF_ESO_CH_LSB_AVA_IDX))
#define u2_VDF_ESO_CH_TO_LSB(u2_ch)              ((u2_ch) & (U2)VDF_ESO_CH_BIT_AVA_LSB)
#define u4_VDF_ESO_CH_TO_BIT(u2_ch)              ((U4)((U4)0x00000001U << ((u2_ch) & (U2)VDF_ESO_CH_BIT_AVA_LSB)))
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Type Definitions                                                                                                                 */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Variable Externs                                                                                                                 */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Function Prototypes                                                                                                              */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Constant Externs                                                                                                                 */
/*-----------------------------------------------------------------------------------------------------------------------------------*/

#endif      /* VARDEF_ESOPT_ID_H */

/*===================================================================================================================================*/
/*                                                                                                                                   */
/*  Change History  :  vardef_esopt_cfg.c                                                                                            */
/*                                                                                                                                   */
/*===================================================================================================================================*/
