/* 2.6.0 */
/*===================================================================================================================================*/
/*  Copyright DENSO Corporation                                                                                                      */
/*===================================================================================================================================*/
/*  Toyota IPC/MET : Vardef Electrical System Option.                                                                                */
/*                                                                                                                                   */
/*===================================================================================================================================*/

#ifndef VARDEF_ESOPT_CHANNEL_H
#define VARDEF_ESOPT_CHANNEL_H

/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Version                                                                                                                          */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define VARDEF_ESOPT_CHANNEL_H_MAJOR             (2)
#define VARDEF_ESOPT_CHANNEL_H_MINOR             (6)
#define VARDEF_ESOPT_CHANNEL_H_PATCH             (0)

/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Include Files                                                                                                                    */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Literal Definitions                                                                                                              */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define VDF_ESO_CH_LSB_AVA_IDX                   (5U)
#define VDF_ESO_CH_BIT_AVA_LSB                   (0x001fU)

/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define VDF_ESO_NUM_CH                           (280U)

#define VDF_ESO_CH_INDSPDALT                     (  0U)
#define VDF_ESO_CH_SYS_NOT_USED_W0_01            (  1U)
#define VDF_ESO_CH_SYS_NOT_USED_W0_02            (  2U)
#define VDF_ESO_CH_SYS_NOT_USED_W0_03            (  3U)
#define VDF_ESO_CH_D_DPTZ                        (  4U)
#define VDF_ESO_CH_P_DPTZ                        (  5U)
#define VDF_ESO_CH_SYS_NOT_USED_W0_06            (  6U)
#define VDF_ESO_CH_SYS_NOT_USED_W0_07            (  7U)
#define VDF_ESO_CH_SYS_NOT_USED_W0_08            (  8U)
#define VDF_ESO_CH_TPMS                          (  9U)
#define VDF_ESO_CH_TPMSCHN                       ( 10U)
#define VDF_ESO_CH_VSC                           ( 11U)
#define VDF_ESO_CH_SYS_NOT_USED_W0_12            ( 12U)
#define VDF_ESO_CH_SYS_NOT_USED_W0_13            ( 13U)
#define VDF_ESO_CH_BSM                           ( 14U)
#define VDF_ESO_CH_FHL                           ( 15U)
#define VDF_ESO_CH_DOA                           ( 16U)
#define VDF_ESO_CH_RCD                           ( 17U)
#define VDF_ESO_CH_CSR_TTR                       ( 18U)
#define VDF_ESO_CH_ICS                           ( 19U)
#define VDF_ESO_CH_PDA                           ( 20U)
#define VDF_ESO_CH_PCS                           ( 21U)
#define VDF_ESO_CH_LTA                           ( 22U)
#define VDF_ESO_CH_DS1_LDA                       ( 23U)
#define VDF_ESO_CH_RSA                           ( 24U)
#define VDF_ESO_CH_AHB                           ( 25U)
#define VDF_ESO_CH_ACC                           ( 26U)
#define VDF_ESO_CH_SYS_NOT_USED_W0_27            ( 27U)
#define VDF_ESO_CH_LCS                           ( 28U)
#define VDF_ESO_CH_TMN                           ( 29U)
#define VDF_ESO_CH_LVN                           ( 30U)
#define VDF_ESO_CH_ISA                           ( 31U)
#define VDF_ESO_CH_DSC                           ( 32U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_01            ( 33U)
#define VDF_ESO_CH_AUTOP                         ( 34U)
#define VDF_ESO_CH_RCTA                          ( 35U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_04            ( 36U)
#define VDF_ESO_CH_BRKHLD                        ( 37U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_06            ( 38U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_07            ( 39U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_08            ( 40U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_09            ( 41U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_10            ( 42U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_11            ( 43U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_12            ( 44U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_13            ( 45U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_14            ( 46U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_15            ( 47U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_16            ( 48U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_17            ( 49U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_18            ( 50U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_19            ( 51U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_20            ( 52U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_21            ( 53U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_22            ( 54U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_23            ( 55U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_24            ( 56U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_25            ( 57U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_26            ( 58U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_27            ( 59U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_28            ( 60U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_29            ( 61U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_30            ( 62U)
#define VDF_ESO_CH_SYS_NOT_USED_W1_31            ( 63U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_00            ( 64U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_01            ( 65U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_02            ( 66U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_03            ( 67U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_04            ( 68U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_05            ( 69U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_06            ( 70U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_07            ( 71U)
#define VDF_ESO_CH_DMC                           ( 72U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_09            ( 73U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_10            ( 74U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_11            ( 75U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_12            ( 76U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_13            ( 77U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_14            ( 78U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_15            ( 79U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_16            ( 80U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_17            ( 81U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_18            ( 82U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_19            ( 83U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_20            ( 84U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_21            ( 85U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_22            ( 86U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_23            ( 87U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_24            ( 88U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_25            ( 89U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_26            ( 90U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_27            ( 91U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_28            ( 92U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_29            ( 93U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_30            ( 94U)
#define VDF_ESO_CH_SYS_NOT_USED_W2_31            ( 95U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_00            ( 96U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_01            ( 97U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_02            ( 98U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_03            ( 99U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_04            (100U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_05            (101U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_06            (102U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_07            (103U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_08            (104U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_09            (105U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_10            (106U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_11            (107U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_12            (108U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_13            (109U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_14            (110U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_15            (111U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_16            (112U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_17            (113U)
#define VDF_ESO_CH_PEDPRO                        (114U)
#define VDF_ESO_CH_DRS                           (115U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_20            (116U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_21            (117U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_22            (118U)
#define VDF_ESO_CH_SW_LTA                        (119U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_24            (120U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_25            (121U)
#define VDF_ESO_CH_MWL                           (122U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_27            (123U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_28            (124U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_29            (125U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_30            (126U)
#define VDF_ESO_CH_SYS_NOT_USED_W3_31            (127U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_00            (128U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_01            (129U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_02            (130U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_03            (131U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_04            (132U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_05            (133U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_06            (134U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_07            (135U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_08            (136U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_09            (137U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_10            (138U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_11            (139U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_12            (140U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_13            (141U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_14            (142U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_15            (143U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_16            (144U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_17            (145U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_18            (146U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_19            (147U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_20            (148U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_21            (149U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_22            (150U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_23            (151U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_24            (152U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_25            (153U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_26            (154U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_27            (155U)
#define VDF_ESO_CH_AVS                           (156U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_29            (157U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_30            (158U)
#define VDF_ESO_CH_SYS_NOT_USED_W4_31            (159U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_00            (160U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_01            (161U)
#define VDF_ESO_CH_EDSS                          (162U)
#define VDF_ESO_CH_CC                            (163U)
#define VDF_ESO_CH_4WDSYS                        (164U)
#define VDF_ESO_CH_ERM                           (165U)
#define VDF_ESO_CH_TM                            (166U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_07            (167U)
#define VDF_ESO_CH_FCTA                          (168U)
#define VDF_ESO_CH_SWS                           (169U)
#define VDF_ESO_CH_PMAR                          (170U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_11            (171U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_12            (172U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_13            (173U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_14            (174U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_15            (175U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_16            (176U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_17            (177U)
#define VDF_ESO_CH_SYS_ADASTT                    (178U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_19            (179U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_20            (180U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_21            (181U)
#define VDF_ESO_CH_AVSEXT                        (182U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_23            (183U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_24            (184U)
#define VDF_ESO_CH_TRLR_EQ                       (185U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_26            (186U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_27            (187U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_28            (188U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_29            (189U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_30            (190U)
#define VDF_ESO_CH_SYS_NOT_USED_W5_31            (191U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_00            (192U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_01            (193U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_02            (194U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_03            (195U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_04            (196U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_05            (197U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_06            (198U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_07            (199U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_08            (200U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_09            (201U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_10            (202U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_11            (203U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_12            (204U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_13            (205U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_14            (206U)
#define VDF_ESO_CH_BRPADW                        (207U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_16            (208U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_17            (209U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_18            (210U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_19            (211U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_20            (212U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_21            (213U)
#define VDF_ESO_CH_SYS_NOT_USED_W6_22            (214U)
#define VDF_ESO_CH_EVMIL_RED                     (215U)
#define VDF_ESO_CH_EVMIL_AMBER                   (216U)
#define VDF_ESO_CH_SW_OMRBB                      (217U)
#define VDF_ESO_CH_SW_OMRBB_MLRSEL               (218U)
#define VDF_ESO_CH_SW_OMRBB_REVERSE              (219U)
#define VDF_ESO_CH_SW_OMRBB_AUTO                 (220U)
#define VDF_ESO_CH_SW_OMRBB_NONAUTO              (221U)
#define VDF_ESO_CH_SYS_DMASSP                    (222U)
#define VDF_ESO_CH_SYS_DMASEC                    (223U)
#define VDF_ESO_CH_SYS_DMASDT                    (224U)
#define VDF_ESO_CH_SYS_DMASTM                    (225U)
#define VDF_ESO_CH_SYS_DMTODT                    (226U)
#define VDF_ESO_CH_SYS_DMTOTM                    (227U)
#define VDF_ESO_CH_SYS_DMTOSP                    (228U)
#define VDF_ESO_CH_SYS_DMINEC                    (229U)
#define VDF_ESO_CH_SYS_NOT_USED4                 (230U)
#define VDF_ESO_CH_SYS_PERSET                    (231U)
#define VDF_ESO_CH_SW_TITE                       (232U)
#define VDF_ESO_CH_SYS_EPS_EPSSBW                (233U)
#define VDF_ESO_CH_SW_HEDLMP_AUT                 (234U)
#define VDF_ESO_CH_SW_HEDLMP_HED                 (235U)
#define VDF_ESO_CH_SW_HEDLMP_TAL                 (236U)
#define VDF_ESO_CH_SW_HEDLMP_TAL_DBL             (237U)
#define VDF_ESO_CH_SW_HEDLMP_DRLOFF              (238U)
#define VDF_ESO_CH_SW_HEDLMP_OFF                 (239U)
#define VDF_ESO_CH_SW_HEDLMP_OFF_DBL             (240U)
#define VDF_ESO_CH_SW_HEDLMP_DRL                 (241U)
#define VDF_ESO_CH_SW_FRONT_FOG                  (242U)
#define VDF_ESO_CH_SW_REAR_FOG                   (243U)
#define VDF_ESO_CH_SYS_SW_MULTI_WEATHERLAMP      (244U)
#define VDF_ESO_CH_SW_RAINDROP_SENSOR            (245U)
#define VDF_ESO_CH_SW_INTTIME_AJUST              (246U)
#define VDF_ESO_CH_SW_REAR_WIPER_OFF             (247U)
#define VDF_ESO_CH_SW_REAR_WIPER_LO              (248U)
#define VDF_ESO_CH_SW_REAR_WIPER_INT             (249U)
#define VDF_ESO_CH_SW_REAR_WASHER                (250U)
#define VDF_ESO_CH_SW_SERVICE_POS                (251U)
#define VDF_ESO_CH_SYS_SW_CAMERA_WASHER          (252U)
#define VDF_ESO_CH_SW_WIPER_DEICER               (253U)
#define VDF_ESO_CH_SOLCHG                        (254U)
#define VDF_ESO_CH_SW_OBBPWL                     (255U)
#define VDF_ESO_CH_SYS_SW_OBBPBD                 (256U)
#define VDF_ESO_CH_VHCOBBSD                      (257U)
#define VDF_ESO_CH_SW_OBBMODE                    (258U)
#define VDF_ESO_CH_SYS_NOT_USED5                 (259U)
#define VDF_ESO_CH_SW_OBBSAV                     (260U)
#define VDF_ESO_CH_SYS_DMEVRNGE                  (261U)
#define VDF_ESO_CH_SYS_DMTOEC                    (262U)
#define VDF_ESO_CH_SYS_DMM1EC                    (263U)
#define VDF_ESO_CH_SW_DPM1                       (264U)
#define VDF_ESO_CH_SW_DPM2                       (265U)
#define VDF_ESO_CH_SW_DPM3                       (266U)
#define VDF_ESO_CH_SYS_ADADM_TT                  (267U)
#define VDF_ESO_CH_SYS_ADDOT_TT                  (268U)
#define VDF_ESO_CH_SYS_MSBBSW_NORMAL             (269U)
#define VDF_ESO_CH_SYS_MSBBSW_SPORT              (270U)
#define VDF_ESO_CH_SYS_MSBBSW_ECO                (271U)
#define VDF_ESO_CH_SYS_MSBBSW_CUSTOM             (272U)
#define VDF_ESO_CH_SYS_MSBBSW_RANGE              (273U)
#define VDF_ESO_CH_SYS_MSBBSW_RCMFRT             (274U)
#define VDF_ESO_CH_SYS_MSBBSW_SNOW               (275U)
#define VDF_ESO_CH_SYS_MSBBSW_TRACK              (276U)
#define VDF_ESO_CH_SYS_MSBBSW_TRAIL              (277U)
#define VDF_ESO_CH_SYS_MSBBSW_DAC                (278U)
#define VDF_ESO_CH_SYS_4WDSYS_DISCON             (279U)

#if 0   /* BEV Rebase provisionally */
#else   /* BEV Rebase provisionally */
#define VDF_ESO_CH_GVIF2                         (65535U)
#define VDF_ESO_CH_AISETH                        (65535U)
#endif   /* BEV Rebase provisionally */

/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define VDF_ESO_NOW_AVA                          ((VDF_ESO_NUM_CH + 31U) >> 5U)

#define VDF_ESO_INI_W0                           (0x00000801U)
#define VDF_ESO_INI_W1                           (0x00000000U)
#define VDF_ESO_INI_W2                           (0x00000000U)
#define VDF_ESO_INI_W3                           (0x00000000U)
#define VDF_ESO_INI_W4                           (0x00000000U)
#define VDF_ESO_INI_W5                           (0x00000000U)
#define VDF_ESO_INI_W6                           (0x00800000U)
#define VDF_ESO_INI_W7                           (0x00000000U)
#define VDF_ESO_INI_W8                           (0x00000000U)

#define VDF_ESO_NVM_W0                           (0x97FDC600U)
#define VDF_ESO_NVM_W1                           (0x00000001U)
#define VDF_ESO_NVM_W2                           (0x00000100U)
#define VDF_ESO_NVM_W3                           (0x048C0000U)
#define VDF_ESO_NVM_W4                           (0x10000000U)
#define VDF_ESO_NVM_W5                           (0x0004076CU)
#define VDF_ESO_NVM_W6                           (0x3F800000U)
#define VDF_ESO_NVM_W7                           (0xBFEFFD00U)
#define VDF_ESO_NVM_W8                           (0x007FF715U)

/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Macro Definitions                                                                                                                */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define u2_VDF_ESO_CH_TO_IDX(u2_ch)              ((U2)((u2_ch) >> VDF_ESO_CH_LSB_AVA_IDX))
#define u2_VDF_ESO_CH_TO_LSB(u2_ch)              ((u2_ch) & (U2)VDF_ESO_CH_BIT_AVA_LSB)
#define u4_VDF_ESO_CH_TO_BIT(u2_ch)              ((U4)((U4)0x00000001U << ((u2_ch) & (U2)VDF_ESO_CH_BIT_AVA_LSB)))
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Type Definitions                                                                                                                 */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Variable Externs                                                                                                                 */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Function Prototypes                                                                                                              */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Constant Externs                                                                                                                 */
/*-----------------------------------------------------------------------------------------------------------------------------------*/

#endif      /* VARDEF_ESOPT_ID_H */

/*===================================================================================================================================*/
/*                                                                                                                                   */
/*  Change History  :  vardef_esopt_cfg.c                                                                                            */
/*                                                                                                                                   */
/*===================================================================================================================================*/
