/* MCU-r04-303 */
/************************************************************************************************/
/*																								*/
/*		MCU Driver																				*/
/*																								*/
/*		Copyright : DENSO CORPORATION															*/
/*																								*/
/************************************************************************************************/

#ifndef MCU_CFG_H
#define	MCU_CFG_H


/*==============================================================================================*/
/* Callout specification																		*/
/*==============================================================================================*/
#define	MCU_CFG_USE_SLEEP_READY_CALLOUT		( STD_OFF )
#define	MCU_CFG_SLEEP_READY_CALLOUT			NULL_PTR

/*==============================================================================================*/
/* include files																				*/
/*==============================================================================================*/
/* The include of Mcu_Externals.h depends on whether Callout notifications is used. */
#if	( MCU_CFG_USE_SLEEP_READY_CALLOUT == STD_ON )
#include	"Mcu_Externals.h"
#endif	/* ( MCU_CFG_USE_SLEEP_READY_CALLOUT == STD_ON ) */

/*==============================================================================================*/
/* defines / data types / structs / unions / macros												*/
/*==============================================================================================*/
/*------------------*/
/* Clock Controller */
/*------------------*/
#define	MCU_CFG_INIT_CLOCK				( STD_ON )
#define	MCU_CFG_NO_PLL					( FALSE )

#define	MCU_CFG_MS_RSCFD_0_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RSCFD_1_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_FLXA_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_FLXA_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ETNB_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ETNB_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_2_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_3_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_4_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_5_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_6_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_7_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_8_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_9_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_10_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_11_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_12_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_13_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_14_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_15_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_16_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_17_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_18_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_19_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_20_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_21_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_22_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_23_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_24_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_25_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_26_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_27_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_28_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RSENT_29_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_MSPI_0_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_MSPI_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_MSPI_2_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_MSPI_3_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_MSPI_4_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_MSPI_5_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_MSPI_6_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_MSPI_7_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_MSPI_8_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_MSPI_9_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RLIN3_0_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_1_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_2_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_3_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_4_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_5_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_6_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_7_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_8_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_9_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_10_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_11_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_12_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_13_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_14_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_15_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_16_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_17_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_18_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_19_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_20_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_21_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_22_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RLIN3_23_TYPE_0 		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RIIC_0_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RIIC_1_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_TAUD_0_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_TAUD_1_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_TAUD_2_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_TAUD_3_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_TAUJ_ISO_0_TYPE_0	( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_TAUJ_ISO_1_TYPE_0	( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_TAUJ_AWO_2_TYPE_0	( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_TAUJ_AWO_3_TYPE_0	( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_OSTM_0_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_OSTM_1_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_OSTM_2_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_OSTM_3_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_OSTM_4_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_OSTM_5_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_OSTM_6_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_OSTM_7_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_OSTM_8_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_OSTM_9_TYPE_0		( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_RTCA_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_GTM_0_TYPE_0			( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ADCJ_ISO_0_TYPE_0	( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_ADCJ_ISO_1_TYPE_0	( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_ADCJ_AWO_2_TYPE_0	( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_CXPI_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_CXPI_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_CXPI_2_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_CXPI_3_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_MMCA_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ENCA_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ENCA_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_PSI5_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_PSI5_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_PSI5_2_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_PSI5_3_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_PSI5S_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_PSI5S_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_PWMD_TYPE_0			( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RHSIF_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RHSIF_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_SCI3_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_SCI3_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_SCI3_2_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_TAPA_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_TAPA_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_TAPA_2_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_TAPA_3_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_TAPA_4_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_TAPA_5_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_TPBA_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_TPBA_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_TSG3_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_TSG3_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_TSG3_2_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_SFMA_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RHSB_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RHSB_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RHSB_2_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RHSB_3_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ETN_0_TYPE_0			( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ETN_1_TYPE_0			( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ETN_2_TYPE_0			( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_HRPWM_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ADCK_ISO_0_TYPE_0	( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ADCK_ISO_1_TYPE_0	( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ADCK_ISO_2_TYPE_0	( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ADCK_ISO_3_TYPE_0	( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ADCK_ISO_4_TYPE_0	( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ADCK_ISO_5_TYPE_0	( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ADCK_ISO_6_TYPE_0	( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_ADCK_ISO_7_TYPE_0	( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_DSADC_CADC_0_TYPE_0	( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_DSADC_CADC_1_TYPE_0	( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_DSADC_CADC_2_TYPE_0	( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_DSADC_CADC_3_TYPE_0	( MCU_MS_CLOCK_SUPPLIED )
#define	MCU_CFG_MS_DFE_0_TYPE_0			( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_EMU_0_TYPE_0			( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_EMU_1_TYPE_0			( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RDC_0_TYPE_0			( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RDC_1_TYPE_0			( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RDC_2_TYPE_0			( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_RDC_3_TYPE_0			( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_FCOMP_0_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_FCOMP_1_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_FCOMP_2_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_FCOMP_3_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_FCOMP_4_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_FCOMP_5_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_FCOMP_6_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_FCOMP_7_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_FCOMP_8_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_FCOMP_9_TYPE_0		( MCU_MS_CLOCK_STOPPED )
#define	MCU_CFG_MS_FCOMP_10_TYPE_0		( MCU_MS_CLOCK_STOPPED )

#define	MCU_CFG_CLK_RLIN_TYPE_0			( MCU_CLK_RLIN_MOSC_1 )
#define	MCU_CFG_CLK_RCAN_TYPE_0			( MCU_CLK_RCAN_MOSC_2 )
#define	MCU_CFG_CLK_MSPI_A_TYPE_0		( MCU_CLK_MSPI_A_HSB_1 )
#define	MCU_CFG_CLK_WDTBA_A_TYPE_0		( MCU_CLK_WDTBA_A_LSIOSC_1 )
#define	MCU_CFG_CLK_ATAUJC_A_TYPE_0		( MCU_CLK_ATAUJC_A_MOSC_1 )
#define	MCU_CFG_CLK_ARTCAC_A_TYPE_0		( MCU_CLK_ARTCAC_A_MOSC_16 )
#define	MCU_CFG_CLK_FOUT0C_TYPE_0 		( MCU_CLK_FOUT0C_HSB_1 )
#define	MCU_CFG_CLKD_FOUT0C_TYPE_0		( (uint32)0U )
#define	MCU_CFG_CLK_WDTC_A_TYPE_0 		( MCU_CLK_WDTC_A_HSIOSC_640 )
#define	MCU_CFG_CLK_ADCJ_TYPE_0			( MCU_CLK_ADCJ_LSB_1 )
#define	MCU_CFG_CLK_AADCC_A_TYPE_0 		( MCU_CLK_AADCC_A_LSB_1 )
#define	MCU_CFG_CLKD_AADCC_TYPE_0		( MCU_CLKD_AADCC_1 )
#define	MCU_CFG_CLK_FOUT1C_TYPE_0 		( MCU_CLK_FOUT1C_HSB_1 )
#define	MCU_CFG_CLKD_FOUT1C_TYPE_0		( (uint32)0U )

#define	MCU_CFG_CLK_SSCG_SSMODE1_TYPE_0	( STD_OFF )
#define	MCU_CFG_CLK_SSCG_FREQ_TYPE_0	( MCU_CLK_SSCG_30 )
#define	MCU_CFG_CLK_SSCG_PERCENT_TYPE_0	( MCU_CLK_SSCG_DITHERED_1 )
#define	MCU_CFG_CLK_RLIN3_TYPE_0		( MCU_CLK_RLIN3_HSBC_1 )
#define	MCU_CFG_CLK_RLIN3_CH23_TYPE_0	( MCU_CLK_RLIN3_CH23_HBUSC_1 )
#define	MCU_CFG_CLK_CANFD_XIN_TYPE_0	( MCU_CLK_CANFD_XIN_MOSC_1 )
#define	MCU_CFG_CLK_CANFD_C_TYPE_0		( MCU_CLK_CANFD_C_HSBC_1 )
#define	MCU_CFG_CLK_MSPI_B_TYPE_0		( MCU_CLK_MSPI_B_MOSC_1 )
#define	MCU_CFG_CLK_WDTC_B_TYPE_0 		( MCU_CLK_WDTC_B_HSIOSC_640 )
#define	MCU_CFG_CLK_SWDT_TYPE_0 		( MCU_CLK_SWDT_HSIOSC_20 )

#define	MCU_CFG_CLK_EXTCLK0C_TYPE_0 	( MCU_CLK_EXTCLK0C_HSB_1 )
#define	MCU_CFG_CLKD_EXTCLK0C_TYPE_0	( (uint32)0U )
#define	MCU_CFG_CLK_EXTCLK1C_TYPE_0 	( MCU_CLK_EXTCLK1C_HSB_1 )
#define	MCU_CFG_CLKD_EXTCLK1C_TYPE_0	( (uint32)0U )

/*----------------------*/
/* Clock Monitor Config */
/*----------------------*/
#define	MCU_CFG_CLK_MONITOR				( STD_OFF )

#define	MCU_CFG_CLMA0CLME				( STD_OFF )
#define	MCU_CFG_CLMA1CLME				( STD_OFF )
#define	MCU_CFG_CLMA2CLME				( STD_OFF )
#define	MCU_CFG_CLMA3CLME				( STD_OFF )
#define	MCU_CFG_CLMA5CLME				( STD_OFF )
#define	MCU_CFG_CLMA6CLME				( STD_OFF )
#define	MCU_CFG_CLMA7CLME				( STD_OFF )
#define	MCU_CFG_CLMA8CLME				( STD_OFF )
#define	MCU_CFG_CLMA9CLME				( STD_OFF )
#define	MCU_CFG_CLMA13CLME				( STD_OFF )
#define	MCU_CFG_CLMA14CLME				( STD_OFF )
#define	MCU_CFG_CLMA15CLME				( STD_OFF )
#define	MCU_CFG_CLMA16CLME				( STD_OFF )
#define	MCU_CFG_CLMA17CLME				( STD_OFF )

#define	MCU_CFG_CLMA0CMPL				( (uint16)1 )
#define	MCU_CFG_CLMA1CMPL				( (uint16)1 )
#define	MCU_CFG_CLMA2CMPL				( (uint16)1 )
#define	MCU_CFG_CLMA3CMPL				( (uint16)1 )
#define	MCU_CFG_CLMA5CMPL				( (uint16)1 )
#define	MCU_CFG_CLMA6CMPL				( (uint16)1 )
#define	MCU_CFG_CLMA7CMPL				( (uint16)1 )
#define	MCU_CFG_CLMA8CMPL				( (uint16)1 )
#define	MCU_CFG_CLMA9CMPL				( (uint16)1 )
#define	MCU_CFG_CLMA13CMPL				( (uint16)1 )
#define	MCU_CFG_CLMA14CMPL				( (uint16)1 )
#define	MCU_CFG_CLMA15CMPL				( (uint16)1 )
#define	MCU_CFG_CLMA16CMPL				( (uint16)1 )
#define	MCU_CFG_CLMA17CMPL				( (uint16)1 )

#define	MCU_CFG_CLMA0CMPH				( (uint16)1023 )
#define	MCU_CFG_CLMA1CMPH				( (uint16)1023 )
#define	MCU_CFG_CLMA2CMPH				( (uint16)1023 )
#define	MCU_CFG_CLMA3CMPH				( (uint16)1023 )
#define	MCU_CFG_CLMA5CMPH				( (uint16)1023 )
#define	MCU_CFG_CLMA6CMPH				( (uint16)1023 )
#define	MCU_CFG_CLMA7CMPH				( (uint16)1023 )
#define	MCU_CFG_CLMA8CMPH				( (uint16)1023 )
#define	MCU_CFG_CLMA9CMPH				( (uint16)1023 )
#define	MCU_CFG_CLMA13CMPH				( (uint16)1023 )
#define	MCU_CFG_CLMA14CMPH				( (uint16)1023 )
#define	MCU_CFG_CLMA15CMPH				( (uint16)1023 )
#define	MCU_CFG_CLMA16CMPH				( (uint16)1023 )
#define	MCU_CFG_CLMA17CMPH				( (uint16)1023 )

#define	MCU_CFG_CLMABCE					( STD_OFF )

#define	MCU_CFG_DEM_SET_EVENT			( STD_OFF )

/*--------------------*/
/* Standby Controller */
/*--------------------*/
#define	MCU_CFG_STPMSK_RSCFD_TYPE_0		( MCU_STPMSK_CLOCK_STOPPED )
#define	MCU_CFG_STPMSK_RLIN3_TYPE_0		( MCU_STPMSK_CLOCK_STOPPED )
#define	MCU_CFG_STPMSK_RTCA_TYPE_0		( MCU_STPMSK_CLOCK_STOPPED )
#define	MCU_CFG_STPMSK_TAUJ_AWO_TYPE_0	( MCU_STPMSK_CLOCK_SUPPLIED )
#define	MCU_CFG_STPMSK_WDTB_AWO_TYPE_0	( MCU_STPMSK_CLOCK_STOPPED )
#define	MCU_CFG_STPMSK_ADCJ_AWO_TYPE_0	( MCU_STPMSK_CLOCK_STOPPED )
#define	MCU_CFG_STPMSK_MOSC_TYPE_0		( MCU_STPMSK_CLOCK_SUPPLIED )
#define	MCU_CFG_STPMSK_HSIOSC_TYPE_0	( MCU_STPMSK_CLOCK_STOPPED )

#define	MCU_CFG_CLK_FOUT0C_SLEEP 		( MCU_CLK_FOUT0C_MOSC_1 )
#define	MCU_CFG_CLKD_FOUT0C_SLEEP		( (uint32)0U )
#define	MCU_CFG_CLK_WDTBA_A_SLEEP		( MCU_CLK_WDTBA_A_LSIOSC_1 )
#define	MCU_CFG_CLK_ATAUJC_A_SLEEP		( MCU_CLK_ATAUJC_A_MOSC_1 )
#define	MCU_CFG_CLK_ARTCAC_A_SLEEP		( MCU_CLK_ARTCAC_A_MOSC_16 )
#define	MCU_CFG_CLK_WDTC_A_SLEEP		( MCU_CLK_WDTC_A_HSIOSC_640 )
#define	MCU_CFG_CLK_FOUT1C_SLEEP 		( MCU_CLK_FOUT1C_MOSC_1 )
#define	MCU_CFG_CLKD_FOUT1C_SLEEP		( (uint32)0U )
#define	MCU_CFG_CLK_AADCC_A_SLEEP 		( MCU_CLK_AADCC_A_MOSC_1 )
#define	MCU_CFG_CLKD_AADCC_SLEEP		( MCU_CLKD_AADCC_1 )

#define	MCU_CFG_ISOVDD_STBL_TIME		( 4200U )
#define	MCU_CFG_WAIT_SLEEP_TIMEOUT		( 0xFFFFFFFFU )

/*------------------*/
/* Reset Controller */
/*------------------*/
#define	MCU_CFG_PERFORM_RESET			( STD_OFF )
#define	MCU_CFG_RESET_SETTING			( MCU_SYSTEM_RESET_2 )
#define	MCU_CFG_RESET_REASON			( STD_OFF )

/*------------------*/
/* Register Check   */
/*------------------*/
#define	MCU_CFG_REG_CHK     			( STD_OFF )
#define	MCU_CFG_REG_REFRESH    			( STD_OFF )

/*==============================================================================================*/
/* variables																					*/
/*==============================================================================================*/

/*==============================================================================================*/
/* constants																					*/
/*==============================================================================================*/

#endif /* MCU_CFG_H */

/*-- End Of File -------------------------------------------------------------------------------*/
