/* can_cm_log_h_v2-1-2                                                      */
/****************************************************************************/
/* Protected                                                                */
/* Copyright AUBASS CO., LTD.                                               */
/****************************************************************************/

/****************************************************************************/
/* Object Name  | CAN/CM/LOGICAL/HEADER                                     */
/*--------------------------------------------------------------------------*/
/* Notes        |                                                           */
/****************************************************************************/
#ifndef CAN_CM_LOG_H
#define CAN_CM_LOG_H


/*--------------------------------------------------------------------------*/
/* Macros                                                                   */
/*--------------------------------------------------------------------------*/
#define CAN_USE                         (0U)
#define CAN_NOUSE                       (1U)

#define CAN_TRUE                        (0U)
#define CAN_FALSE                       (1U)

#define CAN_PROC_OK                     (0U)
#define CAN_PROC_NG                     (1U)
#define CAN_PROC_BUSY                   (2U)

#define CAN_EXIST                       (0U)
#define CAN_NONE                        (1U)

#define CAN_OPEMODE_CAN                 (0U)
#define CAN_OPEMODE_CANFD               (1U)

#define CAN_ADRSING_SHORT               (0U)
#define CAN_ADRSING_NORMAL              (1U)

#define CAN_MANUAL                      (0U)
#define CAN_AUTO                        (1U)

#define CAN_RESP_NOT_OK                 (0U)
#define CAN_RESP_OPT_NOT_OK             (1U)

#define CAN_INTERRUPT                   (0U)
#define CAN_POLLING                     (1U)

#define CAN_IDX0                        (0U)
#define CAN_IDX1                        (1U)
#define CAN_IDX2                        (2U)
#define CAN_IDX3                        (3U)
#define CAN_IDX4                        (4U)
#define CAN_IDX5                        (5U)
#define CAN_IDX6                        (6U)
#define CAN_IDX7                        (7U)
#define CAN_IDX8                        (8U)
#define CAN_IDX9                        (9U)
#define CAN_IDX10                       (10U)
#define CAN_IDX11                       (11U)
#define CAN_IDX12                       (12U)
#define CAN_IDX13                       (13U)
#define CAN_IDX14                       (14U)
#define CAN_IDX15                       (15U)

#define CAN_MB_NOUSE                    (0x00U)
#define CAN_MB_INTERRUPT                (0x01U)
#define CAN_MB_POLLING                  (0x02U)
#define CAN_MB_TRANSMIT                 (0x10U)
#define CAN_MB_RECEPTION                (0x20U)
#define CAN_MB_UTRANSMIT                (0x50U)

#define CAN_IDMODE                      (0U)
#define CAN_MBMODE                      (1U)

#define CAN_MB000                       (  0U)
#define CAN_MB001                       (  1U)
#define CAN_MB002                       (  2U)
#define CAN_MB003                       (  3U)
#define CAN_MB004                       (  4U)
#define CAN_MB005                       (  5U)
#define CAN_MB006                       (  6U)
#define CAN_MB007                       (  7U)
#define CAN_MB008                       (  8U)
#define CAN_MB009                       (  9U)
#define CAN_MB010                       ( 10U)
#define CAN_MB011                       ( 11U)
#define CAN_MB012                       ( 12U)
#define CAN_MB013                       ( 13U)
#define CAN_MB014                       ( 14U)
#define CAN_MB015                       ( 15U)
#define CAN_MB016                       ( 16U)
#define CAN_MB017                       ( 17U)
#define CAN_MB018                       ( 18U)
#define CAN_MB019                       ( 19U)
#define CAN_MB020                       ( 20U)
#define CAN_MB021                       ( 21U)
#define CAN_MB022                       ( 22U)
#define CAN_MB023                       ( 23U)
#define CAN_MB024                       ( 24U)
#define CAN_MB025                       ( 25U)
#define CAN_MB026                       ( 26U)
#define CAN_MB027                       ( 27U)
#define CAN_MB028                       ( 28U)
#define CAN_MB029                       ( 29U)
#define CAN_MB030                       ( 30U)
#define CAN_MB031                       ( 31U)
#define CAN_MB032                       ( 32U)
#define CAN_MB033                       ( 33U)
#define CAN_MB034                       ( 34U)
#define CAN_MB035                       ( 35U)
#define CAN_MB036                       ( 36U)
#define CAN_MB037                       ( 37U)
#define CAN_MB038                       ( 38U)
#define CAN_MB039                       ( 39U)
#define CAN_MB040                       ( 40U)
#define CAN_MB041                       ( 41U)
#define CAN_MB042                       ( 42U)
#define CAN_MB043                       ( 43U)
#define CAN_MB044                       ( 44U)
#define CAN_MB045                       ( 45U)
#define CAN_MB046                       ( 46U)
#define CAN_MB047                       ( 47U)
#define CAN_MB048                       ( 48U)
#define CAN_MB049                       ( 49U)
#define CAN_MB050                       ( 50U)
#define CAN_MB051                       ( 51U)
#define CAN_MB052                       ( 52U)
#define CAN_MB053                       ( 53U)
#define CAN_MB054                       ( 54U)
#define CAN_MB055                       ( 55U)
#define CAN_MB056                       ( 56U)
#define CAN_MB057                       ( 57U)
#define CAN_MB058                       ( 58U)
#define CAN_MB059                       ( 59U)
#define CAN_MB060                       ( 60U)
#define CAN_MB061                       ( 61U)
#define CAN_MB062                       ( 62U)
#define CAN_MB063                       ( 63U)
#define CAN_MB064                       ( 64U)
#define CAN_MB065                       ( 65U)
#define CAN_MB066                       ( 66U)
#define CAN_MB067                       ( 67U)
#define CAN_MB068                       ( 68U)
#define CAN_MB069                       ( 69U)
#define CAN_MB070                       ( 70U)
#define CAN_MB071                       ( 71U)
#define CAN_MB072                       ( 72U)
#define CAN_MB073                       ( 73U)
#define CAN_MB074                       ( 74U)
#define CAN_MB075                       ( 75U)
#define CAN_MB076                       ( 76U)
#define CAN_MB077                       ( 77U)
#define CAN_MB078                       ( 78U)
#define CAN_MB079                       ( 79U)
#define CAN_MB080                       ( 80U)
#define CAN_MB081                       ( 81U)
#define CAN_MB082                       ( 82U)
#define CAN_MB083                       ( 83U)
#define CAN_MB084                       ( 84U)
#define CAN_MB085                       ( 85U)
#define CAN_MB086                       ( 86U)
#define CAN_MB087                       ( 87U)
#define CAN_MB088                       ( 88U)
#define CAN_MB089                       ( 89U)
#define CAN_MB090                       ( 90U)
#define CAN_MB091                       ( 91U)
#define CAN_MB092                       ( 92U)
#define CAN_MB093                       ( 93U)
#define CAN_MB094                       ( 94U)
#define CAN_MB095                       ( 95U)
#define CAN_MB096                       ( 96U)
#define CAN_MB097                       ( 97U)
#define CAN_MB098                       ( 98U)
#define CAN_MB099                       ( 99U)
#define CAN_MB100                       (100U)
#define CAN_MB101                       (101U)
#define CAN_MB102                       (102U)
#define CAN_MB103                       (103U)
#define CAN_MB104                       (104U)
#define CAN_MB105                       (105U)
#define CAN_MB106                       (106U)
#define CAN_MB107                       (107U)
#define CAN_MB108                       (108U)
#define CAN_MB109                       (109U)
#define CAN_MB110                       (110U)
#define CAN_MB111                       (111U)
#define CAN_MB112                       (112U)
#define CAN_MB113                       (113U)
#define CAN_MB114                       (114U)
#define CAN_MB115                       (115U)
#define CAN_MB116                       (116U)
#define CAN_MB117                       (117U)
#define CAN_MB118                       (118U)
#define CAN_MB119                       (119U)
#define CAN_MB120                       (120U)
#define CAN_MB121                       (121U)
#define CAN_MB122                       (122U)
#define CAN_MB123                       (123U)
#define CAN_MB124                       (124U)
#define CAN_MB125                       (125U)
#define CAN_MB126                       (126U)
#define CAN_MB127                       (127U)
#define CAN_MB128                       (128U)
#define CAN_MB129                       (129U)
#define CAN_MB130                       (130U)
#define CAN_MB131                       (131U)
#define CAN_MB132                       (132U)
#define CAN_MB133                       (133U)
#define CAN_MB134                       (134U)
#define CAN_MB135                       (135U)
#define CAN_MB136                       (136U)
#define CAN_MB137                       (137U)
#define CAN_MB138                       (138U)
#define CAN_MB139                       (139U)
#define CAN_MB140                       (140U)
#define CAN_MB141                       (141U)
#define CAN_MB142                       (142U)
#define CAN_MB143                       (143U)
#define CAN_MB144                       (144U)
#define CAN_MB145                       (145U)
#define CAN_MB146                       (146U)
#define CAN_MB147                       (147U)
#define CAN_MB148                       (148U)
#define CAN_MB149                       (149U)
#define CAN_MB150                       (150U)
#define CAN_MB151                       (151U)
#define CAN_MB152                       (152U)
#define CAN_MB153                       (153U)
#define CAN_MB154                       (154U)
#define CAN_MB155                       (155U)
#define CAN_MB156                       (156U)
#define CAN_MB157                       (157U)
#define CAN_MB158                       (158U)
#define CAN_MB159                       (159U)
#define CAN_MB160                       (160U)
#define CAN_MB161                       (161U)
#define CAN_MB162                       (162U)
#define CAN_MB163                       (163U)
#define CAN_MB164                       (164U)
#define CAN_MB165                       (165U)
#define CAN_MB166                       (166U)
#define CAN_MB167                       (167U)
#define CAN_MB168                       (168U)
#define CAN_MB169                       (169U)
#define CAN_MB170                       (170U)
#define CAN_MB171                       (171U)
#define CAN_MB172                       (172U)
#define CAN_MB173                       (173U)
#define CAN_MB174                       (174U)
#define CAN_MB175                       (175U)
#define CAN_MB176                       (176U)
#define CAN_MB177                       (177U)
#define CAN_MB178                       (178U)
#define CAN_MB179                       (179U)
#define CAN_MB180                       (180U)
#define CAN_MB181                       (181U)
#define CAN_MB182                       (182U)
#define CAN_MB183                       (183U)
#define CAN_MB184                       (184U)
#define CAN_MB185                       (185U)
#define CAN_MB186                       (186U)
#define CAN_MB187                       (187U)
#define CAN_MB188                       (188U)
#define CAN_MB189                       (189U)
#define CAN_MB190                       (190U)
#define CAN_MB191                       (191U)

#define CAN_RXMASK_NOUSE                (0xFFU)
#define CAN_RXMASK_0                    ( 0U)
#define CAN_RXMASK_1                    ( 1U)
#define CAN_RXMASK_2                    ( 2U)
#define CAN_RXMASK_3                    ( 3U)
#define CAN_RXMASK_4                    ( 4U)
#define CAN_RXMASK_5                    ( 5U)
#define CAN_RXMASK_6                    ( 6U)
#define CAN_RXMASK_7                    ( 7U)
#define CAN_RXMASK_8                    ( 8U)
#define CAN_RXMASK_9                    ( 9U)
#define CAN_RXMASK_10                   (10U)
#define CAN_RXMASK_11                   (11U)
#define CAN_RXMASK_12                   (12U)
#define CAN_RXMASK_13                   (13U)
#define CAN_RXMASK_14                   (14U)
#define CAN_RXMASK_15                   (15U)
#define CAN_RXMASK_16                   (16U)
#define CAN_RXMASK_17                   (17U)
#define CAN_RXMASK_18                   (18U)
#define CAN_RXMASK_19                   (19U)
#define CAN_RXMASK_20                   (20U)
#define CAN_RXMASK_21                   (21U)
#define CAN_RXMASK_22                   (22U)
#define CAN_RXMASK_23                   (23U)
#define CAN_RXMASK_24                   (24U)
#define CAN_RXMASK_25                   (25U)
#define CAN_RXMASK_26                   (26U)
#define CAN_RXMASK_27                   (27U)
#define CAN_RXMASK_28                   (28U)
#define CAN_RXMASK_29                   (29U)
#define CAN_RXMASK_30                   (30U)
#define CAN_RXMASK_31                   (31U)
#define CAN_RXMASK_32                   (32U)
#define CAN_RXMASK_33                   (33U)
#define CAN_RXMASK_34                   (34U)
#define CAN_RXMASK_35                   (35U)
#define CAN_RXMASK_36                   (36U)
#define CAN_RXMASK_37                   (37U)
#define CAN_RXMASK_38                   (38U)
#define CAN_RXMASK_39                   (39U)
#define CAN_RXMASK_40                   (40U)
#define CAN_RXMASK_41                   (41U)
#define CAN_RXMASK_42                   (42U)
#define CAN_RXMASK_43                   (43U)
#define CAN_RXMASK_44                   (44U)
#define CAN_RXMASK_45                   (45U)
#define CAN_RXMASK_46                   (46U)
#define CAN_RXMASK_47                   (47U)
#define CAN_RXMASK_48                   (48U)
#define CAN_RXMASK_49                   (49U)
#define CAN_RXMASK_50                   (50U)
#define CAN_RXMASK_51                   (51U)
#define CAN_RXMASK_52                   (52U)
#define CAN_RXMASK_53                   (53U)
#define CAN_RXMASK_54                   (54U)
#define CAN_RXMASK_55                   (55U)
#define CAN_RXMASK_56                   (56U)
#define CAN_RXMASK_57                   (57U)
#define CAN_RXMASK_58                   (58U)
#define CAN_RXMASK_59                   (59U)
#define CAN_RXMASK_60                   (60U)
#define CAN_RXMASK_61                   (61U)
#define CAN_RXMASK_62                   (62U)
#define CAN_RXMASK_63                   (63U)
#define CAN_RXMASK_64                   (64U)
#define CAN_RXMASK_65                   (65U)
#define CAN_RXMASK_66                   (66U)
#define CAN_RXMASK_67                   (67U)
#define CAN_RXMASK_68                   (68U)
#define CAN_RXMASK_69                   (69U)
#define CAN_RXMASK_70                   (70U)
#define CAN_RXMASK_71                   (71U)
#define CAN_RXMASK_72                   (72U)
#define CAN_RXMASK_73                   (73U)
#define CAN_RXMASK_74                   (74U)
#define CAN_RXMASK_75                   (75U)
#define CAN_RXMASK_76                   (76U)
#define CAN_RXMASK_77                   (77U)
#define CAN_RXMASK_78                   (78U)
#define CAN_RXMASK_79                   (79U)
#define CAN_RXMASK_80                   (80U)
#define CAN_RXMASK_81                   (81U)
#define CAN_RXMASK_82                   (82U)
#define CAN_RXMASK_83                   (83U)
#define CAN_RXMASK_84                   (84U)
#define CAN_RXMASK_85                   (85U)
#define CAN_RXMASK_86                   (86U)
#define CAN_RXMASK_87                   (87U)
#define CAN_RXMASK_88                   (88U)
#define CAN_RXMASK_89                   (89U)
#define CAN_RXMASK_90                   (90U)
#define CAN_RXMASK_91                   (91U)
#define CAN_RXMASK_92                   (92U)
#define CAN_RXMASK_93                   (93U)
#define CAN_RXMASK_94                   (94U)
#define CAN_RXMASK_95                   (95U)
#define CAN_RXMASK_96                   (96U)
#define CAN_RXMASK_97                   (97U)
#define CAN_RXMASK_98                   (98U)
#define CAN_RXMASK_99                   (99U)
#define CAN_RXMASK_100                  (100U)
#define CAN_RXMASK_101                  (101U)
#define CAN_RXMASK_102                  (102U)
#define CAN_RXMASK_103                  (103U)
#define CAN_RXMASK_104                  (104U)
#define CAN_RXMASK_105                  (105U)
#define CAN_RXMASK_106                  (106U)
#define CAN_RXMASK_107                  (107U)
#define CAN_RXMASK_108                  (108U)
#define CAN_RXMASK_109                  (109U)
#define CAN_RXMASK_110                  (110U)
#define CAN_RXMASK_111                  (111U)
#define CAN_RXMASK_112                  (112U)
#define CAN_RXMASK_113                  (113U)
#define CAN_RXMASK_114                  (114U)
#define CAN_RXMASK_115                  (115U)
#define CAN_RXMASK_116                  (116U)
#define CAN_RXMASK_117                  (117U)
#define CAN_RXMASK_118                  (118U)
#define CAN_RXMASK_119                  (119U)
#define CAN_RXMASK_120                  (120U)
#define CAN_RXMASK_121                  (121U)
#define CAN_RXMASK_122                  (122U)
#define CAN_RXMASK_123                  (123U)
#define CAN_RXMASK_124                  (124U)
#define CAN_RXMASK_125                  (125U)
#define CAN_RXMASK_126                  (126U)
#define CAN_RXMASK_127                  (127U)

#define CAN_CONTROLLER_0                ( 0U)
#define CAN_CONTROLLER_1                ( 1U)
#define CAN_CONTROLLER_2                ( 2U)
#define CAN_CONTROLLER_3                ( 3U)
#define CAN_CONTROLLER_4                ( 4U)
#define CAN_CONTROLLER_5                ( 5U)
#define CAN_CONTROLLER_6                ( 6U)
#define CAN_CONTROLLER_7                ( 7U)
#define CAN_CONTROLLER_8                ( 8U)
#define CAN_CONTROLLER_9                ( 9U)
#define CAN_CONTROLLER_10               (10U)
#define CAN_CONTROLLER_11               (11U)
#define CAN_CONTROLLER_12               (12U)
#define CAN_CONTROLLER_13               (13U)
#define CAN_CONTROLLER_14               (14U)
#define CAN_CONTROLLER_15               (15U)


/*--------------------------------------------------------------------------*/
/* Types                                                                    */
/*--------------------------------------------------------------------------*/


/*--------------------------------------------------------------------------*/
/* Function Prototypes                                                      */
/*--------------------------------------------------------------------------*/


/*--------------------------------------------------------------------------*/
/* Data                                                                     */
/*--------------------------------------------------------------------------*/


/*--------------------------------------------------------------------------*/
/* Constants                                                                */
/*--------------------------------------------------------------------------*/


#endif  /* CAN_CM_LOG_H */

/****************************************************************************/
/* History                                                                  */
/*  Version        :Date                                                    */
/*  v2-0-0         :2017/02/22                                              */
/*  v2-1-0         :2017/12/15                                              */
/*  v2-1-1         :2018/04/04                                              */
/*  v2-1-2         :2021/12/01                                              */
/****************************************************************************/

/**** End of File ***********************************************************/
