/* Fee_Cfg.h                                                                */
/****************************************************************************/
/* Protected                                                                */
/* Copyright DENSO CORPORATION. All rights reserved.                        */
/****************************************************************************/

/****************************************************************************/
/* Object Name | FEE/CFG/HEADER                                             */
/*--------------------------------------------------------------------------*/
/* Notes       |                                                            */
/****************************************************************************/

#ifndef FEE_CFG_H
#define FEE_CFG_H

/*--------------------------------------------------------------------------*/
/* Include Files                                                            */
/*--------------------------------------------------------------------------*/
#include <MemIf_Types.h>    /* SWS_Fee_00002 */
#include <NvM_Cbk.h>        /* SWS_Fee_00002 */
#include <Fee_Types.h>

/*--------------------------------------------------------------------------*/
/* Macros                                                                   */
/*--------------------------------------------------------------------------*/
#define FEE_RECORDPOSTBL_ENABLE             (STD_OFF)
#define FEE_RECORDPOSTBL_FAILSAFE           (STD_OFF)
#define FEE_INTENT_RBLD_ENABLE              (STD_OFF)
#define FEE_USE_MEMACC                      (STD_ON)

#define FEE_MAIN_FUNCTION_PERIOD            (5U)

#define FEE_VOLMONI_DELAY_TIME              (400U)
#define FEE_VOLMONI_RETRY_NUM               (0U)

#define FEE_MAX_BLANK_CHECK_NUM             (490U)
#define FEE_RCRD_SPC_SRCH_NUM               (20U)
#define FEE_MAX_CALC_CHECKSUM_BYTES         (256U)

#define FEE_DATASET_SELECTION_BITS          (1U)


#define FEE_PHYSICAL_SECTOR_NUM_PER_VIRTUAL (1U)
#define FEE_AREA_NUM                        (49U)
#define FEE_SCTR_NUM_TOTAL                  (104U)

#define FEE_SCTR_NUM_A000                   (2U)
#define FEE_SCTR_NUM_A001                   (2U)
#define FEE_SCTR_NUM_A002                   (2U)
#define FEE_SCTR_NUM_A003                   (4U)
#define FEE_SCTR_NUM_A004                   (4U)
#define FEE_SCTR_NUM_A005                   (4U)
#define FEE_SCTR_NUM_A006                   (2U)
#define FEE_SCTR_NUM_A007                   (2U)
#define FEE_SCTR_NUM_A008                   (2U)
#define FEE_SCTR_NUM_A009                   (2U)
#define FEE_SCTR_NUM_A010                   (2U)
#define FEE_SCTR_NUM_A011                   (2U)
#define FEE_SCTR_NUM_A012                   (2U)
#define FEE_SCTR_NUM_A013                   (2U)
#define FEE_SCTR_NUM_A014                   (2U)
#define FEE_SCTR_NUM_A015                   (2U)
#define FEE_SCTR_NUM_A016                   (2U)
#define FEE_SCTR_NUM_A017                   (2U)
#define FEE_SCTR_NUM_A018                   (2U)
#define FEE_SCTR_NUM_A019                   (2U)
#define FEE_SCTR_NUM_A020                   (2U)
#define FEE_SCTR_NUM_A021                   (2U)
#define FEE_SCTR_NUM_A022                   (2U)
#define FEE_SCTR_NUM_A023                   (2U)
#define FEE_SCTR_NUM_A024                   (2U)
#define FEE_SCTR_NUM_A025                   (2U)
#define FEE_SCTR_NUM_A026                   (2U)
#define FEE_SCTR_NUM_A027                   (2U)
#define FEE_SCTR_NUM_A028                   (2U)
#define FEE_SCTR_NUM_A029                   (2U)
#define FEE_SCTR_NUM_A030                   (2U)
#define FEE_SCTR_NUM_A031                   (2U)
#define FEE_SCTR_NUM_A032                   (2U)
#define FEE_SCTR_NUM_A033                   (2U)
#define FEE_SCTR_NUM_A034                   (2U)
#define FEE_SCTR_NUM_A035                   (2U)
#define FEE_SCTR_NUM_A036                   (2U)
#define FEE_SCTR_NUM_A037                   (2U)
#define FEE_SCTR_NUM_A038                   (2U)
#define FEE_SCTR_NUM_A039                   (2U)
#define FEE_SCTR_NUM_A040                   (2U)
#define FEE_SCTR_NUM_A041                   (2U)
#define FEE_SCTR_NUM_A042                   (2U)
#define FEE_SCTR_NUM_A043                   (2U)
#define FEE_SCTR_NUM_A044                   (2U)
#define FEE_SCTR_NUM_A045                   (2U)
#define FEE_SCTR_NUM_A046                   (2U)
#define FEE_SCTR_NUM_A047                   (2U)
#define FEE_SCTR_NUM_A048                   (2U)

#define FEE_MAX_RCRD_NUM_A000               (127U)
#define FEE_MAX_RCRD_NUM_A001               (127U)
#define FEE_MAX_RCRD_NUM_A002               (127U)
#define FEE_MAX_RCRD_NUM_A003               (150U)
#define FEE_MAX_RCRD_NUM_A004               (150U)
#define FEE_MAX_RCRD_NUM_A005               (169U)
#define FEE_MAX_RCRD_NUM_A006               (169U)
#define FEE_MAX_RCRD_NUM_A007               (169U)
#define FEE_MAX_RCRD_NUM_A008               (169U)
#define FEE_MAX_RCRD_NUM_A009               (110U)
#define FEE_MAX_RCRD_NUM_A010               (110U)
#define FEE_MAX_RCRD_NUM_A011               (110U)
#define FEE_MAX_RCRD_NUM_A012               (110U)
#define FEE_MAX_RCRD_NUM_A013               (156U)
#define FEE_MAX_RCRD_NUM_A014               (78U)
#define FEE_MAX_RCRD_NUM_A015               (78U)
#define FEE_MAX_RCRD_NUM_A016               (117U)
#define FEE_MAX_RCRD_NUM_A017               (87U)
#define FEE_MAX_RCRD_NUM_A018               (152U)
#define FEE_MAX_RCRD_NUM_A019               (152U)
#define FEE_MAX_RCRD_NUM_A020               (169U)
#define FEE_MAX_RCRD_NUM_A021               (78U)
#define FEE_MAX_RCRD_NUM_A022               (78U)
#define FEE_MAX_RCRD_NUM_A023               (78U)
#define FEE_MAX_RCRD_NUM_A024               (78U)
#define FEE_MAX_RCRD_NUM_A025               (159U)
#define FEE_MAX_RCRD_NUM_A026               (159U)
#define FEE_MAX_RCRD_NUM_A027               (169U)
#define FEE_MAX_RCRD_NUM_A028               (136U)
#define FEE_MAX_RCRD_NUM_A029               (136U)
#define FEE_MAX_RCRD_NUM_A030               (169U)
#define FEE_MAX_RCRD_NUM_A031               (146U)
#define FEE_MAX_RCRD_NUM_A032               (146U)
#define FEE_MAX_RCRD_NUM_A033               (169U)
#define FEE_MAX_RCRD_NUM_A034               (149U)
#define FEE_MAX_RCRD_NUM_A035               (145U)
#define FEE_MAX_RCRD_NUM_A036               (146U)
#define FEE_MAX_RCRD_NUM_A037               (146U)
#define FEE_MAX_RCRD_NUM_A038               (169U)
#define FEE_MAX_RCRD_NUM_A039               (152U)
#define FEE_MAX_RCRD_NUM_A040               (89U)
#define FEE_MAX_RCRD_NUM_A041               (102U)
#define FEE_MAX_RCRD_NUM_A042               (98U)
#define FEE_MAX_RCRD_NUM_A043               (89U)
#define FEE_MAX_RCRD_NUM_A044               (122U)
#define FEE_MAX_RCRD_NUM_A045               (102U)
#define FEE_MAX_RCRD_NUM_A046               (159U)
#define FEE_MAX_RCRD_NUM_A047               (78U)
#define FEE_MAX_RCRD_NUM_A048               (78U)

#define FEE_RCRD_SRCH_NUM_A000              (127U)
#define FEE_RCRD_SRCH_NUM_A001              (127U)
#define FEE_RCRD_SRCH_NUM_A002              (127U)
#define FEE_RCRD_SRCH_NUM_A003              (150U)
#define FEE_RCRD_SRCH_NUM_A004              (150U)
#define FEE_RCRD_SRCH_NUM_A005              (169U)
#define FEE_RCRD_SRCH_NUM_A006              (169U)
#define FEE_RCRD_SRCH_NUM_A007              (169U)
#define FEE_RCRD_SRCH_NUM_A008              (169U)
#define FEE_RCRD_SRCH_NUM_A009              (110U)
#define FEE_RCRD_SRCH_NUM_A010              (110U)
#define FEE_RCRD_SRCH_NUM_A011              (110U)
#define FEE_RCRD_SRCH_NUM_A012              (110U)
#define FEE_RCRD_SRCH_NUM_A013              (156U)
#define FEE_RCRD_SRCH_NUM_A014              (78U)
#define FEE_RCRD_SRCH_NUM_A015              (78U)
#define FEE_RCRD_SRCH_NUM_A016              (117U)
#define FEE_RCRD_SRCH_NUM_A017              (87U)
#define FEE_RCRD_SRCH_NUM_A018              (152U)
#define FEE_RCRD_SRCH_NUM_A019              (152U)
#define FEE_RCRD_SRCH_NUM_A020              (169U)
#define FEE_RCRD_SRCH_NUM_A021              (78U)
#define FEE_RCRD_SRCH_NUM_A022              (78U)
#define FEE_RCRD_SRCH_NUM_A023              (78U)
#define FEE_RCRD_SRCH_NUM_A024              (78U)
#define FEE_RCRD_SRCH_NUM_A025              (159U)
#define FEE_RCRD_SRCH_NUM_A026              (159U)
#define FEE_RCRD_SRCH_NUM_A027              (169U)
#define FEE_RCRD_SRCH_NUM_A028              (136U)
#define FEE_RCRD_SRCH_NUM_A029              (136U)
#define FEE_RCRD_SRCH_NUM_A030              (169U)
#define FEE_RCRD_SRCH_NUM_A031              (146U)
#define FEE_RCRD_SRCH_NUM_A032              (146U)
#define FEE_RCRD_SRCH_NUM_A033              (169U)
#define FEE_RCRD_SRCH_NUM_A034              (149U)
#define FEE_RCRD_SRCH_NUM_A035              (145U)
#define FEE_RCRD_SRCH_NUM_A036              (146U)
#define FEE_RCRD_SRCH_NUM_A037              (146U)
#define FEE_RCRD_SRCH_NUM_A038              (169U)
#define FEE_RCRD_SRCH_NUM_A039              (152U)
#define FEE_RCRD_SRCH_NUM_A040              (89U)
#define FEE_RCRD_SRCH_NUM_A041              (102U)
#define FEE_RCRD_SRCH_NUM_A042              (98U)
#define FEE_RCRD_SRCH_NUM_A043              (89U)
#define FEE_RCRD_SRCH_NUM_A044              (122U)
#define FEE_RCRD_SRCH_NUM_A045              (102U)
#define FEE_RCRD_SRCH_NUM_A046              (159U)
#define FEE_RCRD_SRCH_NUM_A047              (78U)
#define FEE_RCRD_SRCH_NUM_A048              (78U)

#define FEE_RCRD_WRITE_RETRY_NUM_A000       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A001       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A002       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A003       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A004       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A005       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A006       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A007       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A008       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A009       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A010       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A011       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A012       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A013       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A014       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A015       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A016       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A017       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A018       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A019       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A020       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A021       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A022       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A023       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A024       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A025       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A026       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A027       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A028       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A029       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A030       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A031       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A032       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A033       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A034       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A035       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A036       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A037       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A038       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A039       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A040       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A041       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A042       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A043       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A044       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A045       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A046       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A047       (1U)
#define FEE_RCRD_WRITE_RETRY_NUM_A048       (1U)

#define FEE_INTENT_RBLD_BLOCK_ID_A000       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A001       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A002       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A003       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A004       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A005       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A006       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A007       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A008       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A009       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A010       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A011       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A012       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A013       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A014       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A015       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A016       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A017       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A018       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A019       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A020       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A021       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A022       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A023       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A024       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A025       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A026       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A027       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A028       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A029       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A030       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A031       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A032       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A033       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A034       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A035       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A036       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A037       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A038       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A039       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A040       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A041       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A042       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A043       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A044       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A045       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A046       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A047       (FEE_INTENT_RBLD_BLOCK_ID_NONE)
#define FEE_INTENT_RBLD_BLOCK_ID_A048       (FEE_INTENT_RBLD_BLOCK_ID_NONE)

#define FEE_BLOCK_NUM_A000_LV1              (1U)
#define FEE_BLOCK_NUM_A001_LV1              (1U)
#define FEE_BLOCK_NUM_A002_LV1              (1U)
#define FEE_BLOCK_NUM_A003_LV1              (52U)
#define FEE_BLOCK_NUM_A004_LV1              (52U)
#define FEE_BLOCK_NUM_A005_LV1              (37U)
#define FEE_BLOCK_NUM_A006_LV1              (2U)
#define FEE_BLOCK_NUM_A007_LV1              (2U)
#define FEE_BLOCK_NUM_A008_LV1              (2U)
#define FEE_BLOCK_NUM_A009_LV1              (11U)
#define FEE_BLOCK_NUM_A010_LV1              (21U)
#define FEE_BLOCK_NUM_A011_LV1              (21U)
#define FEE_BLOCK_NUM_A012_LV1              (21U)
#define FEE_BLOCK_NUM_A013_LV1              (12U)
#define FEE_BLOCK_NUM_A014_LV1              (27U)
#define FEE_BLOCK_NUM_A015_LV1              (27U)
#define FEE_BLOCK_NUM_A016_LV1              (9U)
#define FEE_BLOCK_NUM_A017_LV1              (25U)
#define FEE_BLOCK_NUM_A018_LV1              (14U)
#define FEE_BLOCK_NUM_A019_LV1              (14U)
#define FEE_BLOCK_NUM_A020_LV1              (12U)
#define FEE_BLOCK_NUM_A021_LV1              (5U)
#define FEE_BLOCK_NUM_A022_LV1              (5U)
#define FEE_BLOCK_NUM_A023_LV1              (5U)
#define FEE_BLOCK_NUM_A024_LV1              (5U)
#define FEE_BLOCK_NUM_A025_LV1              (23U)
#define FEE_BLOCK_NUM_A026_LV1              (23U)
#define FEE_BLOCK_NUM_A027_LV1              (21U)
#define FEE_BLOCK_NUM_A028_LV1              (15U)
#define FEE_BLOCK_NUM_A029_LV1              (15U)
#define FEE_BLOCK_NUM_A030_LV1              (9U)
#define FEE_BLOCK_NUM_A031_LV1              (10U)
#define FEE_BLOCK_NUM_A032_LV1              (10U)
#define FEE_BLOCK_NUM_A033_LV1              (8U)
#define FEE_BLOCK_NUM_A034_LV1              (74U)
#define FEE_BLOCK_NUM_A035_LV1              (75U)
#define FEE_BLOCK_NUM_A036_LV1              (10U)
#define FEE_BLOCK_NUM_A037_LV1              (10U)
#define FEE_BLOCK_NUM_A038_LV1              (8U)
#define FEE_BLOCK_NUM_A039_LV1              (6U)
#define FEE_BLOCK_NUM_A040_LV1              (21U)
#define FEE_BLOCK_NUM_A041_LV1              (41U)
#define FEE_BLOCK_NUM_A042_LV1              (17U)
#define FEE_BLOCK_NUM_A043_LV1              (21U)
#define FEE_BLOCK_NUM_A044_LV1              (41U)
#define FEE_BLOCK_NUM_A045_LV1              (21U)
#define FEE_BLOCK_NUM_A046_LV1              (40U)
#define FEE_BLOCK_NUM_A047_LV1              (32U)
#define FEE_BLOCK_NUM_A048_LV1              (31U)

#define FEE_BLOCK_NUM_A000_LV2              (0U)
#define FEE_BLOCK_NUM_A001_LV2              (0U)
#define FEE_BLOCK_NUM_A002_LV2              (0U)
#define FEE_BLOCK_NUM_A003_LV2              (0U)
#define FEE_BLOCK_NUM_A004_LV2              (0U)
#define FEE_BLOCK_NUM_A005_LV2              (0U)
#define FEE_BLOCK_NUM_A006_LV2              (0U)
#define FEE_BLOCK_NUM_A007_LV2              (0U)
#define FEE_BLOCK_NUM_A008_LV2              (0U)
#define FEE_BLOCK_NUM_A009_LV2              (0U)
#define FEE_BLOCK_NUM_A010_LV2              (0U)
#define FEE_BLOCK_NUM_A011_LV2              (0U)
#define FEE_BLOCK_NUM_A012_LV2              (0U)
#define FEE_BLOCK_NUM_A013_LV2              (0U)
#define FEE_BLOCK_NUM_A014_LV2              (0U)
#define FEE_BLOCK_NUM_A015_LV2              (0U)
#define FEE_BLOCK_NUM_A016_LV2              (0U)
#define FEE_BLOCK_NUM_A017_LV2              (0U)
#define FEE_BLOCK_NUM_A018_LV2              (0U)
#define FEE_BLOCK_NUM_A019_LV2              (0U)
#define FEE_BLOCK_NUM_A020_LV2              (0U)
#define FEE_BLOCK_NUM_A021_LV2              (0U)
#define FEE_BLOCK_NUM_A022_LV2              (0U)
#define FEE_BLOCK_NUM_A023_LV2              (0U)
#define FEE_BLOCK_NUM_A024_LV2              (0U)
#define FEE_BLOCK_NUM_A025_LV2              (0U)
#define FEE_BLOCK_NUM_A026_LV2              (0U)
#define FEE_BLOCK_NUM_A027_LV2              (0U)
#define FEE_BLOCK_NUM_A028_LV2              (0U)
#define FEE_BLOCK_NUM_A029_LV2              (0U)
#define FEE_BLOCK_NUM_A030_LV2              (0U)
#define FEE_BLOCK_NUM_A031_LV2              (0U)
#define FEE_BLOCK_NUM_A032_LV2              (0U)
#define FEE_BLOCK_NUM_A033_LV2              (0U)
#define FEE_BLOCK_NUM_A034_LV2              (0U)
#define FEE_BLOCK_NUM_A035_LV2              (0U)
#define FEE_BLOCK_NUM_A036_LV2              (0U)
#define FEE_BLOCK_NUM_A037_LV2              (0U)
#define FEE_BLOCK_NUM_A038_LV2              (0U)
#define FEE_BLOCK_NUM_A039_LV2              (0U)
#define FEE_BLOCK_NUM_A040_LV2              (0U)
#define FEE_BLOCK_NUM_A041_LV2              (0U)
#define FEE_BLOCK_NUM_A042_LV2              (0U)
#define FEE_BLOCK_NUM_A043_LV2              (0U)
#define FEE_BLOCK_NUM_A044_LV2              (0U)
#define FEE_BLOCK_NUM_A045_LV2              (0U)
#define FEE_BLOCK_NUM_A046_LV2              (0U)
#define FEE_BLOCK_NUM_A047_LV2              (0U)
#define FEE_BLOCK_NUM_A048_LV2              (0U)

#endif /* FEE_CFG_H */

/****************************************************************************/
/* AUBIST Configurator Version                                              */
/*  Framework          :v2-1-0                                              */
/*  BSW plug-in        :v2-0-0                                              */
/****************************************************************************/

/**** End of File ***********************************************************/

