/* 1.7.1 */
/*===================================================================================================================================*/
/*  Copyright DENSO Corporation                                                                                                      */
/*===================================================================================================================================*/
/*  Nvmc : Mgr                                                                                                                       */
/*                                                                                                                                   */
/*===================================================================================================================================*/

#ifndef NVMC_MGR_CFG_H
#define NVMC_MGR_CFG_H

/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Version                                                                                                                          */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
#define NVMC_MGR_CFG_H_MAJOR                     (1U)
#define NVMC_MGR_CFG_H_MINOR                     (7U)
#define NVMC_MGR_CFG_H_PATCH                     (1U)

/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Include Files                                                                                                                    */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Type Definitions                                                                                                                 */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Defines                                                                                                                          */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/* Device definition */
/* START : ##TOOL_OUT#NVMC_DEVICE_TYPE_NUM## */
#define NVMC_DEVICE_TYPE_NUM                     (1U)
/* END : ##TOOL_OUT#NVMC_DEVICE_TYPE_NUM## */

#define NVMC_DEVICE_TYPE_DTF                     (0U)
#define NVMC_DEVICE_TYPE_EEPROM                  (1U)
#define NVMC_DEVICE_TYPE_ALL                     (0xFFU)

/* NvmcId:DEVICE */
#define NVMC_ID_DEVICE_DTF                       (0x0000U) /* NVMC_DEVICE_TYPE_DTF    (0U) << NVMC_ID_DEVICE_SHIFT (14U) */
#define NVMC_ID_DEVICE_EEPROM                    (0x4000U) /* NVMC_DEVICE_TYPE_EEPROM (1U) << NVMC_ID_DEVICE_SHIFT (14U) */

/* NvmcId */
/* SAMPLE */
/* START : ##TOOL_OUT#NVMC_NVMCID## */
#define NVMCID_U1_SAMPLE_U1                      (0x0000U)
#define NVMCID_U2_SAMPLE_U2                      (0x0001U)
#define NVMCID_U4_SAMPLE_U4                      (0x0002U)
#define NVMCID_OTR_SAMPLE_OTR32                  (0x0003U)
#define NVMCID_OTR_SAMPLE_OTR32CS                (0x0004U)
#define NVMCID_U4_BSW_SECOC_TRIP_CNT             (0x0005U)
#define NVMCID_OTR_OXDC_TMSTP                    (0x0006U)
#define NVMCID_OTR_OXDC_ROE_A005                 (0x0007U)
#define NVMCID_OTR_OXDC_DTC_EVENT001             (0x0008U)
#define NVMCID_OTR_OXDC_DTC_EVENT002             (0x0009U)
#define NVMCID_OTR_OXDC_DTC_EVENT003             (0x000AU)
#define NVMCID_OTR_OXDC_DTC_EVENT004             (0x000BU)
#define NVMCID_OTR_OXDC_DTC_EVENT005             (0x000CU)
#define NVMCID_OTR_OXDC_DTC_EVENT006             (0x000DU)
#define NVMCID_OTR_OXDC_DTC_EVENT007             (0x000EU)
#define NVMCID_OTR_OXDC_DTC_EVENT008             (0x000FU)
#define NVMCID_OTR_OXDC_DTC_EVENT009             (0x0010U)
#define NVMCID_OTR_OXDC_DTC_EVENT010             (0x0011U)
#define NVMCID_OTR_OXDC_DTC_EVENT011             (0x0012U)
#define NVMCID_OTR_OXDC_DTC_EVENT012             (0x0013U)
#define NVMCID_OTR_OXDC_DTC_EVENT013             (0x0014U)
#define NVMCID_OTR_OXDC_DTC_EVENT014             (0x0015U)
#define NVMCID_OTR_OXDC_DTC_EVENT015             (0x0016U)
#define NVMCID_OTR_OXDC_DTC_EVENT016             (0x0017U)
#define NVMCID_OTR_OXDC_DTC_EVENT017             (0x0018U)
#define NVMCID_OTR_OXDC_DTC_EVENT018             (0x0019U)
#define NVMCID_OTR_OXDC_DTC_EVENT019             (0x001AU)
#define NVMCID_OTR_OXDC_DTC_EVENT020             (0x001BU)
#define NVMCID_OTR_OXDC_DTC_EVENT021             (0x001CU)
#define NVMCID_OTR_OXDC_DTC_FAULT001             (0x001DU)
#define NVMCID_OTR_OXDC_DTC_FAULT002             (0x001EU)
#define NVMCID_OTR_OXDC_DTC_FAULT003             (0x001FU)
#define NVMCID_OTR_OXDC_DTC_FAULT004             (0x0020U)
#define NVMCID_OTR_OXDC_DTC_FAULT005             (0x0021U)
#define NVMCID_OTR_OXDC_DTC_FAULT006             (0x0022U)
#define NVMCID_OTR_OXDC_DTC_FAULT007             (0x0023U)
#define NVMCID_OTR_OXDC_DTC_FAULT008             (0x0024U)
#define NVMCID_OTR_OXDC_DTC_FAULT009             (0x0025U)
#define NVMCID_OTR_OXDC_DTC_FAULT010             (0x0026U)
#define NVMCID_OTR_OXDC_DTC_FAULT011             (0x0027U)
#define NVMCID_OTR_OXDC_DTC_FAULT012             (0x0028U)
#define NVMCID_OTR_OXDC_DTC_FAULT013             (0x0029U)
#define NVMCID_OTR_OXDC_DTC_FAULT014             (0x002AU)
#define NVMCID_OTR_OXDC_DTC_FAULT015             (0x002BU)
#define NVMCID_OTR_OXDC_DTC_FAULT016             (0x002CU)
#define NVMCID_OTR_OXDC_DTC_FAULT017             (0x002DU)
#define NVMCID_OTR_OXDC_DTC_FAULT018             (0x002EU)
#define NVMCID_OTR_OXDC_DTC_FAULT019             (0x002FU)
#define NVMCID_OTR_OXDC_DTC_FAULT020             (0x0030U)
#define NVMCID_OTR_OXDC_DTC_FAULT021             (0x0031U)
#define NVMCID_OTR_OXDC_DTC_FFD001               (0x0032U)
#define NVMCID_OTR_OXDC_DTC_FFD002               (0x0033U)
#define NVMCID_OTR_OXDC_DTC_FFD003               (0x0034U)
#define NVMCID_OTR_OXDC_DTC_FFD004               (0x0035U)
#define NVMCID_OTR_OXDC_DTC_FFD005               (0x0036U)
#define NVMCID_OTR_OXDC_DTC_FFD006               (0x0037U)
#define NVMCID_OTR_OXDC_DTC_FFD007               (0x0038U)
#define NVMCID_OTR_OXDC_DTC_FFD008               (0x0039U)
#define NVMCID_OTR_OXDC_DTC_FFD009               (0x003AU)
#define NVMCID_OTR_OXDC_DTC_FFD010               (0x003BU)
#define NVMCID_OTR_OXDC_DTC_FFD011               (0x003CU)
#define NVMCID_OTR_OXDC_DTC_FFD012               (0x003DU)
#define NVMCID_OTR_OXDC_DTC_FFD013               (0x003EU)
#define NVMCID_OTR_OXDC_DTC_FFD014               (0x003FU)
#define NVMCID_OTR_OXDC_DTC_FFD015               (0x0040U)
#define NVMCID_OTR_OXDC_DTC_FFD016               (0x0041U)
#define NVMCID_OTR_OXDC_DTC_FFD017               (0x0042U)
#define NVMCID_OTR_OXDC_DTC_FFD018               (0x0043U)
#define NVMCID_OTR_OXDC_DTC_FFD019               (0x0044U)
#define NVMCID_OTR_OXDC_DTC_FFD020               (0x0045U)
#define NVMCID_OTR_OXDC_DTC_FFD021               (0x0046U)
#define NVMCID_OTR_OXDC_DTC_CLEARINFO            (0x0047U)
#define NVMCID_U4_OXDC_DTC_LOGRX1                (0x0048U)
#define NVMCID_U4_OXDC_OCC2_NM_EVENT001          (0x0049U)
#define NVMCID_U4_OXDC_OCC2_NM_EVENT002          (0x004AU)
#define NVMCID_U4_OXDC_OCC2_NM_EVENT003          (0x004BU)
#define NVMCID_U4_OXDC_OCC2_NM_EVENT004          (0x004CU)
#define NVMCID_U4_OXDC_OCC3_NM_EVENT005          (0x004DU)
#define NVMCID_U4_OXDC_OCC7_NM_EVENT006          (0x004EU)
#define NVMCID_OTR_OXDC_OCC2_NM_FAULT001         (0x004FU)
#define NVMCID_OTR_OXDC_OCC2_NM_FAULT002         (0x0050U)
#define NVMCID_OTR_OXDC_OCC2_NM_FAULT003         (0x0051U)
#define NVMCID_OTR_OXDC_OCC2_NM_FAULT004         (0x0052U)
#define NVMCID_OTR_OXDC_OCC3_NM_FAULT005         (0x0053U)
#define NVMCID_OTR_OXDC_OCC7_NM_FAULT006         (0x0054U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD001           (0x0055U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD002           (0x0056U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD003           (0x0057U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD004           (0x0058U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD005           (0x0059U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD006           (0x005AU)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD007           (0x005BU)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD008           (0x005CU)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD009           (0x005DU)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD010           (0x005EU)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD011           (0x005FU)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD012           (0x0060U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD013           (0x0061U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD014           (0x0062U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD015           (0x0063U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD016           (0x0064U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD017           (0x0065U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD018           (0x0066U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD019           (0x0067U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD020           (0x0068U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD021           (0x0069U)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD022           (0x006AU)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD023           (0x006BU)
#define NVMCID_OTR_OXDC_OCC2_NM_FFD024           (0x006CU)
#define NVMCID_OTR_OXDC_OCC3_NM_FFD025           (0x006DU)
#define NVMCID_OTR_OXDC_OCC3_NM_FFD026           (0x006EU)
#define NVMCID_OTR_OXDC_OCC3_NM_FFD027           (0x006FU)
#define NVMCID_OTR_OXDC_OCC3_NM_FFD028           (0x0070U)
#define NVMCID_OTR_OXDC_OCC3_NM_FFD029           (0x0071U)
#define NVMCID_OTR_OXDC_OCC3_NM_FFD030           (0x0072U)
#define NVMCID_OTR_OXDC_OCC3_NM_FFD031           (0x0073U)
#define NVMCID_OTR_OXDC_OCC3_NM_FFD032           (0x0074U)
#define NVMCID_OTR_OXDC_OCC3_NM_FFD033           (0x0075U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD034           (0x0076U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD035           (0x0077U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD036           (0x0078U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD037           (0x0079U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD038           (0x007AU)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD039           (0x007BU)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD040           (0x007CU)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD041           (0x007DU)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD042           (0x007EU)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD043           (0x007FU)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD044           (0x0080U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD045           (0x0081U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD046           (0x0082U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD047           (0x0083U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD048           (0x0084U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD049           (0x0085U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD050           (0x0086U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD051           (0x0087U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD052           (0x0088U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD053           (0x0089U)
#define NVMCID_OTR_OXDC_OCC7_NM_FFD054           (0x008AU)
#define NVMCID_U4_OXDC_MAT1_EVENT001             (0x008BU)
#define NVMCID_U4_OXDC_MAT1_EVENT002             (0x008CU)
#define NVMCID_OTR_OXDC_MAT1_FAULT001            (0x008DU)
#define NVMCID_OTR_OXDC_MAT1_FAULT002            (0x008EU)
#define NVMCID_OTR_OXDC_MAT1_FFD001              (0x008FU)
#define NVMCID_OTR_OXDC_MAT1_FFD002              (0x0090U)
#define NVMCID_U4_OXDC_SOP2_EVENT001             (0x0091U)
#define NVMCID_U4_OXDC_SOP2_EVENT002             (0x0092U)
#define NVMCID_OTR_OXDC_SOP2_FAULT001            (0x0093U)
#define NVMCID_OTR_OXDC_SOP2_FAULT002            (0x0094U)
#define NVMCID_OTR_OXDC_SOP2_FFD001              (0x0095U)
#define NVMCID_OTR_OXDC_SOP2_FFD002              (0x0096U)
#define NVMCID_OTR_OXDC_SOP2_FFD003              (0x0097U)
#define NVMCID_OTR_OXDC_SOP2_FFD004              (0x0098U)
#define NVMCID_U4_OXDC_OCC1_EVENT007             (0x0099U)
#define NVMCID_U4_OXDC_OCC1_EVENT008             (0x009AU)
#define NVMCID_U4_OXDC_OCC1_EVENT009             (0x009BU)
#define NVMCID_U4_OXDC_OCC1_EVENT010             (0x009CU)
#define NVMCID_U4_OXDC_OCC1_EVENT011             (0x009DU)
#define NVMCID_U4_OXDC_OCC1_EVENT012             (0x009EU)
#define NVMCID_U4_OXDC_OCC1_EVENT013             (0x009FU)
#define NVMCID_U4_OXDC_OCC1_EVENT014             (0x00A0U)
#define NVMCID_U4_OXDC_OCC1_EVENT015             (0x00A1U)
#define NVMCID_U4_OXDC_OCC1_EVENT016             (0x00A2U)
#define NVMCID_U4_OXDC_OCC1_EVENT017             (0x00A3U)
#define NVMCID_U4_OXDC_OCC1_EVENT018             (0x00A4U)
#define NVMCID_U4_OXDC_OCC1_EVENT019             (0x00A5U)
#define NVMCID_U4_OXDC_OCC1_EVENT020             (0x00A6U)
#define NVMCID_U4_OXDC_OCC1_EVENT021             (0x00A7U)
#define NVMCID_U4_OXDC_OCC1_EVENT022             (0x00A8U)
#define NVMCID_U4_OXDC_OCC1_EVENT023             (0x00A9U)
#define NVMCID_U4_OXDC_OCC1_EVENT024             (0x00AAU)
#define NVMCID_U4_OXDC_OCC1_EVENT025             (0x00ABU)
#define NVMCID_U4_OXDC_OCC2_EVENT026             (0x00ACU)
#define NVMCID_OTR_OXDC_OCC1_FAULT007            (0x00ADU)
#define NVMCID_OTR_OXDC_OCC1_FAULT008            (0x00AEU)
#define NVMCID_OTR_OXDC_OCC1_FAULT009            (0x00AFU)
#define NVMCID_OTR_OXDC_OCC1_FAULT010            (0x00B0U)
#define NVMCID_OTR_OXDC_OCC1_FAULT011            (0x00B1U)
#define NVMCID_OTR_OXDC_OCC1_FAULT012            (0x00B2U)
#define NVMCID_OTR_OXDC_OCC1_FAULT013            (0x00B3U)
#define NVMCID_OTR_OXDC_OCC1_FAULT014            (0x00B4U)
#define NVMCID_OTR_OXDC_OCC1_FAULT015            (0x00B5U)
#define NVMCID_OTR_OXDC_OCC1_FAULT016            (0x00B6U)
#define NVMCID_OTR_OXDC_OCC1_FAULT017            (0x00B7U)
#define NVMCID_OTR_OXDC_OCC1_FAULT018            (0x00B8U)
#define NVMCID_OTR_OXDC_OCC1_FAULT019            (0x00B9U)
#define NVMCID_OTR_OXDC_OCC1_FAULT020            (0x00BAU)
#define NVMCID_OTR_OXDC_OCC1_FAULT021            (0x00BBU)
#define NVMCID_OTR_OXDC_OCC1_FAULT022            (0x00BCU)
#define NVMCID_OTR_OXDC_OCC1_FAULT023            (0x00BDU)
#define NVMCID_OTR_OXDC_OCC1_FAULT024            (0x00BEU)
#define NVMCID_OTR_OXDC_OCC1_FAULT025            (0x00BFU)
#define NVMCID_OTR_OXDC_OCC2_FAULT026            (0x00C0U)
#define NVMCID_OTR_OXDC_OCC1_FFD055              (0x00C1U)
#define NVMCID_OTR_OXDC_OCC1_FFD056              (0x00C2U)
#define NVMCID_OTR_OXDC_OCC1_FFD057              (0x00C3U)
#define NVMCID_OTR_OXDC_OCC1_FFD058              (0x00C4U)
#define NVMCID_OTR_OXDC_OCC1_FFD059              (0x00C5U)
#define NVMCID_OTR_OXDC_OCC1_FFD060              (0x00C6U)
#define NVMCID_OTR_OXDC_OCC1_FFD061              (0x00C7U)
#define NVMCID_OTR_OXDC_OCC1_FFD062              (0x00C8U)
#define NVMCID_OTR_OXDC_OCC1_FFD063              (0x00C9U)
#define NVMCID_OTR_OXDC_OCC1_FFD064              (0x00CAU)
#define NVMCID_OTR_OXDC_OCC1_FFD065              (0x00CBU)
#define NVMCID_OTR_OXDC_OCC1_FFD066              (0x00CCU)
#define NVMCID_OTR_OXDC_OCC1_FFD067              (0x00CDU)
#define NVMCID_OTR_OXDC_OCC1_FFD068              (0x00CEU)
#define NVMCID_OTR_OXDC_OCC1_FFD069              (0x00CFU)
#define NVMCID_OTR_OXDC_OCC1_FFD070              (0x00D0U)
#define NVMCID_OTR_OXDC_OCC1_FFD071              (0x00D1U)
#define NVMCID_OTR_OXDC_OCC1_FFD072              (0x00D2U)
#define NVMCID_OTR_OXDC_OCC1_FFD073              (0x00D3U)
#define NVMCID_OTR_OXDC_OCC1_FFD074              (0x00D4U)
#define NVMCID_OTR_OXDC_OCC1_FFD075              (0x00D5U)
#define NVMCID_OTR_OXDC_OCC1_FFD076              (0x00D6U)
#define NVMCID_OTR_OXDC_OCC1_FFD077              (0x00D7U)
#define NVMCID_OTR_OXDC_OCC1_FFD078              (0x00D8U)
#define NVMCID_OTR_OXDC_OCC1_FFD079              (0x00D9U)
#define NVMCID_OTR_OXDC_OCC1_FFD080              (0x00DAU)
#define NVMCID_OTR_OXDC_OCC1_FFD081              (0x00DBU)
#define NVMCID_OTR_OXDC_OCC1_FFD082              (0x00DCU)
#define NVMCID_OTR_OXDC_OCC1_FFD083              (0x00DDU)
#define NVMCID_OTR_OXDC_OCC1_FFD084              (0x00DEU)
#define NVMCID_OTR_OXDC_OCC1_FFD085              (0x00DFU)
#define NVMCID_OTR_OXDC_OCC1_FFD086              (0x00E0U)
#define NVMCID_OTR_OXDC_OCC1_FFD087              (0x00E1U)
#define NVMCID_OTR_OXDC_OCC1_FFD088              (0x00E2U)
#define NVMCID_OTR_OXDC_OCC1_FFD089              (0x00E3U)
#define NVMCID_OTR_OXDC_OCC1_FFD090              (0x00E4U)
#define NVMCID_OTR_OXDC_OCC1_FFD091              (0x00E5U)
#define NVMCID_OTR_OXDC_OCC1_FFD092              (0x00E6U)
#define NVMCID_OTR_OXDC_OCC1_FFD093              (0x00E7U)
#define NVMCID_OTR_OXDC_OCC1_FFD094              (0x00E8U)
#define NVMCID_OTR_OXDC_OCC1_FFD095              (0x00E9U)
#define NVMCID_OTR_OXDC_OCC1_FFD096              (0x00EAU)
#define NVMCID_OTR_OXDC_OCC1_FFD097              (0x00EBU)
#define NVMCID_OTR_OXDC_OCC1_FFD098              (0x00ECU)
#define NVMCID_OTR_OXDC_OCC1_FFD099              (0x00EDU)
#define NVMCID_OTR_OXDC_OCC1_FFD100              (0x00EEU)
#define NVMCID_OTR_OXDC_OCC1_FFD101              (0x00EFU)
#define NVMCID_OTR_OXDC_OCC1_FFD102              (0x00F0U)
#define NVMCID_OTR_OXDC_OCC1_FFD103              (0x00F1U)
#define NVMCID_OTR_OXDC_OCC1_FFD104              (0x00F2U)
#define NVMCID_OTR_OXDC_OCC1_FFD105              (0x00F3U)
#define NVMCID_OTR_OXDC_OCC1_FFD106              (0x00F4U)
#define NVMCID_OTR_OXDC_OCC1_FFD107              (0x00F5U)
#define NVMCID_OTR_OXDC_OCC1_FFD108              (0x00F6U)
#define NVMCID_OTR_OXDC_OCC1_FFD109              (0x00F7U)
#define NVMCID_OTR_OXDC_OCC1_FFD110              (0x00F8U)
#define NVMCID_OTR_OXDC_OCC1_FFD111              (0x00F9U)
#define NVMCID_OTR_OXDC_OCC2_FFD112              (0x00FAU)
#define NVMCID_OTR_OXDC_OCC2_FFD113              (0x00FBU)
#define NVMCID_OTR_OXDC_OCC2_FFD114              (0x00FCU)
#define NVMCID_OTR_OXDC_OCC2_FFD115              (0x00FDU)
#define NVMCID_OTR_OXDC_OCC2_FFD116              (0x00FEU)
#define NVMCID_OTR_OXDC_OCC2_FFD117              (0x00FFU)
#define NVMCID_U4_OXDC_MAT1_EVENT003             (0x0100U)
#define NVMCID_OTR_OXDC_MAT1_FAULT003            (0x0101U)
#define NVMCID_OTR_OXDC_MAT1_FFD003              (0x0102U)
/* END : ##TOOL_OUT#NVMC_NVMCID## */

/* START : ##TOOL_OUT#NVMC_BLOCKID## */
/* END : ##TOOL_OUT#NVMC_BLOCKID## */

/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Macros                                                                                                                           */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Constant Variable Externs                                                                                                        */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Function Prototypes                                                                                                              */
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*-----------------------------------------------------------------------------------------------------------------------------------*/
/*  Variable Externs                                                                                                                 */
/*-----------------------------------------------------------------------------------------------------------------------------------*/

#endif /* NVMC_MGR_CFG_H */

/*===================================================================================================================================*/
/*                                                                                                                                   */
/*  Change History  :  see nvmc_mgr.c                                                                                                */
/*                                                                                                                                   */
/*===================================================================================================================================*/
