/* bsw_nm_config_h_v2-0-0                                                   */
/****************************************************************************/
/* Protected                                                                */
/* Copyright AUBASS CO., LTD.                                               */
/****************************************************************************/

/****************************************************************************/
/* Object Name  | BSW/NM/CONFIG/HEADER                                      */
/*--------------------------------------------------------------------------*/
/* Notes        |                                                           */
/****************************************************************************/

/*--------------------------------------------------------------------------*/
/* Include Files                                                            */
/*--------------------------------------------------------------------------*/
#ifndef BSW_NM_CONFIG_H
#define BSW_NM_CONFIG_H

#include "../cfg/Nm_Cfg.h"

/*--------------------------------------------------------------------------*/
/* Macros                                                                   */
/*--------------------------------------------------------------------------*/
#define BSW_NM_COM_CONTROL                 (BSW_NM_CFG_COM_CONTROL)
#define BSW_NM_USER_DATA                   (BSW_NM_CFG_USER_DATA)
#define BSW_NM_NODE_ID                     (BSW_NM_CFG_NODE_ID)
#define BSW_NM_PASSIVE_MODE                (BSW_NM_CFG_PASSIVE_MODE)
#define BSW_NM_SLEEPSYNC                   (BSW_NM_CFG_SLEEPSYNC)
#define BSW_NM_SYNC_PNC_SHUTDOWN           (BSW_NM_CFG_SYNC_PNC_SHUTDOWN)
#define BSW_NM_TYPE(ch)                    (BSW_COMM_BUSTYPE(ch))

#define BSW_NM_REQ_BUS_SYNC_USE             BSW_NM_REQ_BUS_SYNC_USE_CH0
#define BSW_NM_REQ_BUS_SYNC_USE_CH0         ((BSW_NM_CFG_REQ_BUS_SYNC_CH0 == BSW_USE)  ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH1)
#define BSW_NM_REQ_BUS_SYNC_USE_CH1         ((BSW_NM_CFG_REQ_BUS_SYNC_CH1 == BSW_USE)  ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH2)
#define BSW_NM_REQ_BUS_SYNC_USE_CH2         ((BSW_NM_CFG_REQ_BUS_SYNC_CH2 == BSW_USE)  ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH3)
#define BSW_NM_REQ_BUS_SYNC_USE_CH3         ((BSW_NM_CFG_REQ_BUS_SYNC_CH3 == BSW_USE)  ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH4)
#define BSW_NM_REQ_BUS_SYNC_USE_CH4         ((BSW_NM_CFG_REQ_BUS_SYNC_CH4 == BSW_USE)  ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH5)
#define BSW_NM_REQ_BUS_SYNC_USE_CH5         ((BSW_NM_CFG_REQ_BUS_SYNC_CH5 == BSW_USE)  ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH6)
#define BSW_NM_REQ_BUS_SYNC_USE_CH6         ((BSW_NM_CFG_REQ_BUS_SYNC_CH6 == BSW_USE)  ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH7)
#define BSW_NM_REQ_BUS_SYNC_USE_CH7         ((BSW_NM_CFG_REQ_BUS_SYNC_CH7 == BSW_USE)  ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH8)
#define BSW_NM_REQ_BUS_SYNC_USE_CH8         ((BSW_NM_CFG_REQ_BUS_SYNC_CH8 == BSW_USE)  ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH9)
#define BSW_NM_REQ_BUS_SYNC_USE_CH9         ((BSW_NM_CFG_REQ_BUS_SYNC_CH9 == BSW_USE)  ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH10)
#define BSW_NM_REQ_BUS_SYNC_USE_CH10        ((BSW_NM_CFG_REQ_BUS_SYNC_CH10 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH11)
#define BSW_NM_REQ_BUS_SYNC_USE_CH11        ((BSW_NM_CFG_REQ_BUS_SYNC_CH11 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH12)
#define BSW_NM_REQ_BUS_SYNC_USE_CH12        ((BSW_NM_CFG_REQ_BUS_SYNC_CH12 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH13)
#define BSW_NM_REQ_BUS_SYNC_USE_CH13        ((BSW_NM_CFG_REQ_BUS_SYNC_CH13 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH14)
#define BSW_NM_REQ_BUS_SYNC_USE_CH14        ((BSW_NM_CFG_REQ_BUS_SYNC_CH14 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH15)
#define BSW_NM_REQ_BUS_SYNC_USE_CH15        ((BSW_NM_CFG_REQ_BUS_SYNC_CH15 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH16)
#define BSW_NM_REQ_BUS_SYNC_USE_CH16        ((BSW_NM_CFG_REQ_BUS_SYNC_CH16 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH17)
#define BSW_NM_REQ_BUS_SYNC_USE_CH17        ((BSW_NM_CFG_REQ_BUS_SYNC_CH17 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH18)
#define BSW_NM_REQ_BUS_SYNC_USE_CH18        ((BSW_NM_CFG_REQ_BUS_SYNC_CH18 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH19)
#define BSW_NM_REQ_BUS_SYNC_USE_CH19        ((BSW_NM_CFG_REQ_BUS_SYNC_CH19 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH20)
#define BSW_NM_REQ_BUS_SYNC_USE_CH20        ((BSW_NM_CFG_REQ_BUS_SYNC_CH20 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH21)
#define BSW_NM_REQ_BUS_SYNC_USE_CH21        ((BSW_NM_CFG_REQ_BUS_SYNC_CH21 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH22)
#define BSW_NM_REQ_BUS_SYNC_USE_CH22        ((BSW_NM_CFG_REQ_BUS_SYNC_CH22 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH23)
#define BSW_NM_REQ_BUS_SYNC_USE_CH23        ((BSW_NM_CFG_REQ_BUS_SYNC_CH23 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH24)
#define BSW_NM_REQ_BUS_SYNC_USE_CH24        ((BSW_NM_CFG_REQ_BUS_SYNC_CH24 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH25)
#define BSW_NM_REQ_BUS_SYNC_USE_CH25        ((BSW_NM_CFG_REQ_BUS_SYNC_CH25 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH26)
#define BSW_NM_REQ_BUS_SYNC_USE_CH26        ((BSW_NM_CFG_REQ_BUS_SYNC_CH26 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH27)
#define BSW_NM_REQ_BUS_SYNC_USE_CH27        ((BSW_NM_CFG_REQ_BUS_SYNC_CH27 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH28)
#define BSW_NM_REQ_BUS_SYNC_USE_CH28        ((BSW_NM_CFG_REQ_BUS_SYNC_CH28 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH29)
#define BSW_NM_REQ_BUS_SYNC_USE_CH29        ((BSW_NM_CFG_REQ_BUS_SYNC_CH29 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH30)
#define BSW_NM_REQ_BUS_SYNC_USE_CH30        ((BSW_NM_CFG_REQ_BUS_SYNC_CH30 == BSW_USE) ? BSW_USE : BSW_NM_REQ_BUS_SYNC_USE_CH31)
#define BSW_NM_REQ_BUS_SYNC_USE_CH31        ((BSW_NM_CFG_REQ_BUS_SYNC_CH31 == BSW_USE) ? BSW_USE : BSW_NOUSE)

#define BSW_NM_REQBUSSYNC_CAN_CH(ch)        ( (BSW_NM_TYPE(ch) == BSW_COMM_BUS_TYPE_CAN) ? BSW_NM_CFG_REQ_BUS_SYNC_CH##ch : BSW_NOUSE )

#define BSW_NM_REQ_BUS_SYNC_USE_CAN         BSW_NM_REQBUSSYNC_CAN_USE_CH0
#define BSW_NM_REQBUSSYNC_CAN_USE_CH0       ((BSW_NM_REQBUSSYNC_CAN_CH(0) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH1)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH1       ((BSW_NM_REQBUSSYNC_CAN_CH(1) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH2)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH2       ((BSW_NM_REQBUSSYNC_CAN_CH(2) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH3)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH3       ((BSW_NM_REQBUSSYNC_CAN_CH(3) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH4)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH4       ((BSW_NM_REQBUSSYNC_CAN_CH(4) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH5)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH5       ((BSW_NM_REQBUSSYNC_CAN_CH(5) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH6)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH6       ((BSW_NM_REQBUSSYNC_CAN_CH(6) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH7)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH7       ((BSW_NM_REQBUSSYNC_CAN_CH(7) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH8)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH8       ((BSW_NM_REQBUSSYNC_CAN_CH(8) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH9)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH9       ((BSW_NM_REQBUSSYNC_CAN_CH(9) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH10)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH10      ((BSW_NM_REQBUSSYNC_CAN_CH(10) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH11)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH11      ((BSW_NM_REQBUSSYNC_CAN_CH(11) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH12)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH12      ((BSW_NM_REQBUSSYNC_CAN_CH(12) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH13)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH13      ((BSW_NM_REQBUSSYNC_CAN_CH(13) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH14)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH14      ((BSW_NM_REQBUSSYNC_CAN_CH(14) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH15)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH15      ((BSW_NM_REQBUSSYNC_CAN_CH(15) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH16)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH16      ((BSW_NM_REQBUSSYNC_CAN_CH(16) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH17)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH17      ((BSW_NM_REQBUSSYNC_CAN_CH(17) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH18)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH18      ((BSW_NM_REQBUSSYNC_CAN_CH(18) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH19)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH19      ((BSW_NM_REQBUSSYNC_CAN_CH(19) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH20)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH20      ((BSW_NM_REQBUSSYNC_CAN_CH(20) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH21)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH21      ((BSW_NM_REQBUSSYNC_CAN_CH(21) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH22)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH22      ((BSW_NM_REQBUSSYNC_CAN_CH(22) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH23)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH23      ((BSW_NM_REQBUSSYNC_CAN_CH(23) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH24)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH24      ((BSW_NM_REQBUSSYNC_CAN_CH(24) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH25)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH25      ((BSW_NM_REQBUSSYNC_CAN_CH(25) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH26)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH26      ((BSW_NM_REQBUSSYNC_CAN_CH(26) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH27)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH27      ((BSW_NM_REQBUSSYNC_CAN_CH(27) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH28)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH28      ((BSW_NM_REQBUSSYNC_CAN_CH(28) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH29)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH29      ((BSW_NM_REQBUSSYNC_CAN_CH(29) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH30)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH30      ((BSW_NM_REQBUSSYNC_CAN_CH(30) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_CAN_USE_CH31)
#define BSW_NM_REQBUSSYNC_CAN_USE_CH31      ((BSW_NM_REQBUSSYNC_CAN_CH(31) == BSW_USE) ? BSW_USE : BSW_NOUSE)

#define BSW_NM_REQBUSSYNC_ETH_CH(ch)        ( (BSW_NM_TYPE(ch) == BSW_COMM_BUS_TYPE_ETH) ? BSW_NM_CFG_REQ_BUS_SYNC_CH##ch : BSW_NOUSE )

#define BSW_NM_REQ_BUS_SYNC_USE_ETH         BSW_NM_REQBUSSYNC_ETH_USE_CH0
#define BSW_NM_REQBUSSYNC_ETH_USE_CH0       ((BSW_NM_REQBUSSYNC_ETH_CH(0) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH1)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH1       ((BSW_NM_REQBUSSYNC_ETH_CH(1) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH2)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH2       ((BSW_NM_REQBUSSYNC_ETH_CH(2) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH3)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH3       ((BSW_NM_REQBUSSYNC_ETH_CH(3) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH4)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH4       ((BSW_NM_REQBUSSYNC_ETH_CH(4) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH5)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH5       ((BSW_NM_REQBUSSYNC_ETH_CH(5) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH6)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH6       ((BSW_NM_REQBUSSYNC_ETH_CH(6) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH7)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH7       ((BSW_NM_REQBUSSYNC_ETH_CH(7) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH8)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH8       ((BSW_NM_REQBUSSYNC_ETH_CH(8) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH9)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH9       ((BSW_NM_REQBUSSYNC_ETH_CH(9) == BSW_USE)  ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH10)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH10      ((BSW_NM_REQBUSSYNC_ETH_CH(10) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH11)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH11      ((BSW_NM_REQBUSSYNC_ETH_CH(11) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH12)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH12      ((BSW_NM_REQBUSSYNC_ETH_CH(12) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH13)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH13      ((BSW_NM_REQBUSSYNC_ETH_CH(13) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH14)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH14      ((BSW_NM_REQBUSSYNC_ETH_CH(14) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH15)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH15      ((BSW_NM_REQBUSSYNC_ETH_CH(15) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH16)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH16      ((BSW_NM_REQBUSSYNC_ETH_CH(16) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH17)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH17      ((BSW_NM_REQBUSSYNC_ETH_CH(17) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH18)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH18      ((BSW_NM_REQBUSSYNC_ETH_CH(18) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH19)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH19      ((BSW_NM_REQBUSSYNC_ETH_CH(19) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH20)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH20      ((BSW_NM_REQBUSSYNC_ETH_CH(20) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH21)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH21      ((BSW_NM_REQBUSSYNC_ETH_CH(21) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH22)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH22      ((BSW_NM_REQBUSSYNC_ETH_CH(22) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH23)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH23      ((BSW_NM_REQBUSSYNC_ETH_CH(23) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH24)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH24      ((BSW_NM_REQBUSSYNC_ETH_CH(24) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH25)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH25      ((BSW_NM_REQBUSSYNC_ETH_CH(25) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH26)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH26      ((BSW_NM_REQBUSSYNC_ETH_CH(26) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH27)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH27      ((BSW_NM_REQBUSSYNC_ETH_CH(27) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH28)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH28      ((BSW_NM_REQBUSSYNC_ETH_CH(28) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH29)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH29      ((BSW_NM_REQBUSSYNC_ETH_CH(29) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH30)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH30      ((BSW_NM_REQBUSSYNC_ETH_CH(30) == BSW_USE) ? BSW_USE : BSW_NM_REQBUSSYNC_ETH_USE_CH31)
#define BSW_NM_REQBUSSYNC_ETH_USE_CH31      ((BSW_NM_REQBUSSYNC_ETH_CH(31) == BSW_USE) ? BSW_USE : BSW_NOUSE)

/*--------------------------------------------------------------------------*/
/* Types                                                                    */
/*--------------------------------------------------------------------------*/


/*--------------------------------------------------------------------------*/
/* Function Prototypes                                                      */
/*--------------------------------------------------------------------------*/


/*--------------------------------------------------------------------------*/
/* Data                                                                     */
/*--------------------------------------------------------------------------*/


/*--------------------------------------------------------------------------*/
/* Constants                                                                */
/*--------------------------------------------------------------------------*/

#endif /* BSW_NM_CONFIG_H */

/****************************************************************************/
/* History                                                                  */
/*  Version         :Date                                                   */
/*  v1-0-0          :2017/04/25                                             */
/*  v2-0-0          :2022/01/06                                             */
/****************************************************************************/

/**** End of File ***********************************************************/
