/* Port-r04-303 */
/************************************************************************************************/
/*																								*/
/*		Port Handler/Driver																		*/
/*																								*/
/*		Copyright : DENSO CORPORATION															*/
/*																								*/
/************************************************************************************************/

#ifndef PORT_TYPE_H
#define PORT_TYPE_H

#include "Std_Types.h"

#include "Port_Cfg.h"
#include "Port_Ucfg.h"

/*==============================================================================================*/
/* defines / data types / structs / unions / macros												*/
/*==============================================================================================*/
/* Port type */
typedef enum {
#if MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2A
	PORT_PORT_TYPE_NORMAL = 0,	/* Normal Port */
	PORT_PORT_TYPE_ANALOG = 1,	/* Analog Port */
	PORT_PORT_TYPE_JTAG   = 2,	/* Jtag Port */
#elif MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2B
	PORT_PORT_TYPE_NORMAL = 0,	/* Normal Port */
	PORT_PORT_TYPE_JTAG   = 1,	/* Jtag Port */
#endif
} Port_PortType;

/* Functions subject to Noise Filter */
typedef enum
{
#if MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2A
	/* RLIN */
	PORT_NOISE_FILTER_FUNC_RLIN30RX = 0,
	PORT_NOISE_FILTER_FUNC_RLIN31RX,
	/* SRCAN */
	PORT_NOISE_FILTER_FUNC_CAN0RX,
	PORT_NOISE_FILTER_FUNC_CAN1RX,
	/* FLX */
	PORT_NOISE_FILTER_FUNC_FLX0RXDA,
	PORT_NOISE_FILTER_FUNC_FLX1RXDA,
	/* SENT */
	PORT_NOISE_FILTER_FUNC_SENT0RX,
	PORT_NOISE_FILTER_FUNC_SENT1RX,
	PORT_NOISE_FILTER_FUNC_SENT2RX,
	PORT_NOISE_FILTER_FUNC_SENT3RX,
	PORT_NOISE_FILTER_FUNC_SENT4RX,
	PORT_NOISE_FILTER_FUNC_SENT5RX,
	PORT_NOISE_FILTER_FUNC_SENT6RX,
	PORT_NOISE_FILTER_FUNC_SENT7RX,
	/* PSI5 */
	PORT_NOISE_FILTER_FUNC_PSI50RX,
	PORT_NOISE_FILTER_FUNC_PSI51RX,
	PORT_NOISE_FILTER_FUNC_PSI52RX,
	PORT_NOISE_FILTER_FUNC_PSI53RX,
	/* PIC */
	PORT_NOISE_FILTER_FUNC_TAPA0ESO,
	PORT_NOISE_FILTER_FUNC_TAPA1ESO,
	/* ADCJ */
	PORT_NOISE_FILTER_FUNC_ADCJ0TRG0,
	PORT_NOISE_FILTER_FUNC_ADCJ0TRG1,
	PORT_NOISE_FILTER_FUNC_ADCJ0TRG2,
	PORT_NOISE_FILTER_FUNC_ADCJ0TRG3,
	PORT_NOISE_FILTER_FUNC_ADCJ0TRG4,
	PORT_NOISE_FILTER_FUNC_ADCJ1TRG0,
	PORT_NOISE_FILTER_FUNC_ADCJ1TRG1,
	PORT_NOISE_FILTER_FUNC_ADCJ1TRG2,
	PORT_NOISE_FILTER_FUNC_ADCJ1TRG3,
	PORT_NOISE_FILTER_FUNC_ADCJ1TRG4,
	PORT_NOISE_FILTER_FUNC_ADCJ2TRG0,
	PORT_NOISE_FILTER_FUNC_ADCJ2TRG1,
	PORT_NOISE_FILTER_FUNC_ADCJ2TRG2,
	PORT_NOISE_FILTER_FUNC_ADCJ2TRG3,
	PORT_NOISE_FILTER_FUNC_ADCJ2TRG4,
	/* ENCA */
	PORT_NOISE_FILTER_FUNC_ENCA0TIN0,
	PORT_NOISE_FILTER_FUNC_ENCA0TIN1,
	PORT_NOISE_FILTER_FUNC_ENCA1TIN0,
	PORT_NOISE_FILTER_FUNC_ENCA1TIN1,
	/* TAUD */
	PORT_NOISE_FILTER_FUNC_TAUD0I0,
	PORT_NOISE_FILTER_FUNC_TAUD0I1,
	PORT_NOISE_FILTER_FUNC_TAUD0I2,
	PORT_NOISE_FILTER_FUNC_TAUD0I3,
	PORT_NOISE_FILTER_FUNC_TAUD0I4,
	PORT_NOISE_FILTER_FUNC_TAUD0I5,
	PORT_NOISE_FILTER_FUNC_TAUD0I6,
	PORT_NOISE_FILTER_FUNC_TAUD0I7,
	PORT_NOISE_FILTER_FUNC_TAUD0I8,
	PORT_NOISE_FILTER_FUNC_TAUD0I9,
	PORT_NOISE_FILTER_FUNC_TAUD0I10,
	PORT_NOISE_FILTER_FUNC_TAUD0I11,
	PORT_NOISE_FILTER_FUNC_TAUD0I12,
	PORT_NOISE_FILTER_FUNC_TAUD0I13,
	PORT_NOISE_FILTER_FUNC_TAUD0I14,
	PORT_NOISE_FILTER_FUNC_TAUD0I15,
	PORT_NOISE_FILTER_FUNC_TAUD1I0,
	PORT_NOISE_FILTER_FUNC_TAUD1I1,
	PORT_NOISE_FILTER_FUNC_TAUD1I2,
	PORT_NOISE_FILTER_FUNC_TAUD1I3,
	PORT_NOISE_FILTER_FUNC_TAUD1I4,
	PORT_NOISE_FILTER_FUNC_TAUD1I5,
	PORT_NOISE_FILTER_FUNC_TAUD1I6,
	PORT_NOISE_FILTER_FUNC_TAUD1I7,
	PORT_NOISE_FILTER_FUNC_TAUD1I8,
	PORT_NOISE_FILTER_FUNC_TAUD1I9,
	PORT_NOISE_FILTER_FUNC_TAUD1I10,
	PORT_NOISE_FILTER_FUNC_TAUD1I11,
	PORT_NOISE_FILTER_FUNC_TAUD1I12,
	PORT_NOISE_FILTER_FUNC_TAUD1I13,
	PORT_NOISE_FILTER_FUNC_TAUD1I14,
	PORT_NOISE_FILTER_FUNC_TAUD1I15,
	PORT_NOISE_FILTER_FUNC_TAUD2I0,
	PORT_NOISE_FILTER_FUNC_TAUD2I1,
	PORT_NOISE_FILTER_FUNC_TAUD2I2,
	PORT_NOISE_FILTER_FUNC_TAUD2I3,
	PORT_NOISE_FILTER_FUNC_TAUD2I4,
	PORT_NOISE_FILTER_FUNC_TAUD2I5,
	PORT_NOISE_FILTER_FUNC_TAUD2I6,
	PORT_NOISE_FILTER_FUNC_TAUD2I7,
	PORT_NOISE_FILTER_FUNC_TAUD2I8,
	PORT_NOISE_FILTER_FUNC_TAUD2I9,
	PORT_NOISE_FILTER_FUNC_TAUD2I10,
	PORT_NOISE_FILTER_FUNC_TAUD2I11,
	PORT_NOISE_FILTER_FUNC_TAUD2I12,
	PORT_NOISE_FILTER_FUNC_TAUD2I13,
	PORT_NOISE_FILTER_FUNC_TAUD2I14,
	PORT_NOISE_FILTER_FUNC_TAUD2I15,
	/* TSG3 */
	PORT_NOISE_FILTER_FUNC_TSG30PTSI0_ENCA0E0,
	PORT_NOISE_FILTER_FUNC_TSG30PTSI1_ENCA0E1,
	PORT_NOISE_FILTER_FUNC_TSG30PTSI2_ENCA0EC,
	PORT_NOISE_FILTER_FUNC_TSG30CLKI,
	PORT_NOISE_FILTER_FUNC_TSG31PTSI0_ENCA1E0,
	PORT_NOISE_FILTER_FUNC_TSG31PTSI1_ENCA1E1,
	PORT_NOISE_FILTER_FUNC_TSG31PTSI2_ENCA1EC,
	PORT_NOISE_FILTER_FUNC_TSG31CLKI,
	/* NMI */
	PORT_NOISE_FILTER_FUNC_NMI,
	/* INTP */
	PORT_NOISE_FILTER_FUNC_INTP0,
	PORT_NOISE_FILTER_FUNC_INTP1,
	PORT_NOISE_FILTER_FUNC_INTP2,
	PORT_NOISE_FILTER_FUNC_INTP3,
	PORT_NOISE_FILTER_FUNC_INTP4,
	PORT_NOISE_FILTER_FUNC_INTP5,
	PORT_NOISE_FILTER_FUNC_INTP6,
	PORT_NOISE_FILTER_FUNC_INTP7,
	PORT_NOISE_FILTER_FUNC_INTP8,
	PORT_NOISE_FILTER_FUNC_INTP9,
	PORT_NOISE_FILTER_FUNC_INTP10,
	PORT_NOISE_FILTER_FUNC_INTP11,
	PORT_NOISE_FILTER_FUNC_INTP12,
	PORT_NOISE_FILTER_FUNC_INTP13,
	PORT_NOISE_FILTER_FUNC_INTP14,
	PORT_NOISE_FILTER_FUNC_INTP15,
	PORT_NOISE_FILTER_FUNC_INTP16,
	PORT_NOISE_FILTER_FUNC_INTP17,
	PORT_NOISE_FILTER_FUNC_INTP18,
	PORT_NOISE_FILTER_FUNC_INTP19,
	PORT_NOISE_FILTER_FUNC_INTP20,
	PORT_NOISE_FILTER_FUNC_INTP21,
	PORT_NOISE_FILTER_FUNC_INTP22,
	PORT_NOISE_FILTER_FUNC_INTP23,
	PORT_NOISE_FILTER_FUNC_INTP24,
	PORT_NOISE_FILTER_FUNC_INTP25,
	PORT_NOISE_FILTER_FUNC_INTP26,
	PORT_NOISE_FILTER_FUNC_INTP27,
	PORT_NOISE_FILTER_FUNC_INTP28,
	PORT_NOISE_FILTER_FUNC_INTP29,
	PORT_NOISE_FILTER_FUNC_INTP30,
	PORT_NOISE_FILTER_FUNC_INTP31,
	PORT_NOISE_FILTER_FUNC_INTP32,
	PORT_NOISE_FILTER_FUNC_INTP33,
	PORT_NOISE_FILTER_FUNC_INTP34,
	PORT_NOISE_FILTER_FUNC_INTP35,
	PORT_NOISE_FILTER_FUNC_INTP36,
	PORT_NOISE_FILTER_FUNC_INTP37,
	PORT_NOISE_FILTER_FUNC_INTP38,
	PORT_NOISE_FILTER_FUNC_INTP39,
	/* TAUJ */
	PORT_NOISE_FILTER_FUNC_TAUJ0I0,
	PORT_NOISE_FILTER_FUNC_TAUJ0I1,
	PORT_NOISE_FILTER_FUNC_TAUJ0I2,
	PORT_NOISE_FILTER_FUNC_TAUJ0I3,
	PORT_NOISE_FILTER_FUNC_TAUJ1I0,
	PORT_NOISE_FILTER_FUNC_TAUJ1I1,
	PORT_NOISE_FILTER_FUNC_TAUJ1I2,
	PORT_NOISE_FILTER_FUNC_TAUJ1I3,
	PORT_NOISE_FILTER_FUNC_TAUJ2I0,
	PORT_NOISE_FILTER_FUNC_TAUJ2I1,
	PORT_NOISE_FILTER_FUNC_TAUJ2I2,
	PORT_NOISE_FILTER_FUNC_TAUJ2I3,
	PORT_NOISE_FILTER_FUNC_TAUJ3I0,
	PORT_NOISE_FILTER_FUNC_TAUJ3I1,
	PORT_NOISE_FILTER_FUNC_TAUJ3I2,
	PORT_NOISE_FILTER_FUNC_TAUJ3I3,
	/* ECM */
	PORT_NOISE_FILTER_FUNC_ERRORIN0,
	PORT_NOISE_FILTER_FUNC_ERRORIN1,
	PORT_NOISE_FILTER_FUNC_ERRORIN2,
	PORT_NOISE_FILTER_FUNC_ERRORIN3,
#elif MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2B
	/* RLIN */
	PORT_NOISE_FILTER_FUNC_RLIN30RX = 0,
	PORT_NOISE_FILTER_FUNC_RLIN31RX,
	/* SRCAN */
	PORT_NOISE_FILTER_FUNC_CAN0RX,
	PORT_NOISE_FILTER_FUNC_CAN1RX,
	/* FLX */
	PORT_NOISE_FILTER_FUNC_FLX0RXDA,
	/* SENT */
	PORT_NOISE_FILTER_FUNC_SENT0RX,
	PORT_NOISE_FILTER_FUNC_SENT1RX,
	PORT_NOISE_FILTER_FUNC_SENT2RX,
	PORT_NOISE_FILTER_FUNC_SENT3RX,
	PORT_NOISE_FILTER_FUNC_SENT4RX,
	PORT_NOISE_FILTER_FUNC_SENT5RX,
	PORT_NOISE_FILTER_FUNC_SENT6RX,
	PORT_NOISE_FILTER_FUNC_SENT7RX,
	PORT_NOISE_FILTER_FUNC_SENT8RX,
	PORT_NOISE_FILTER_FUNC_SENT9RX,
	PORT_NOISE_FILTER_FUNC_SENT10RX,
	PORT_NOISE_FILTER_FUNC_SENT11RX,
	PORT_NOISE_FILTER_FUNC_SENT12RX,
	PORT_NOISE_FILTER_FUNC_SENT13RX,
	PORT_NOISE_FILTER_FUNC_SENT14RX,
	PORT_NOISE_FILTER_FUNC_SENT15RX,
	PORT_NOISE_FILTER_FUNC_SENT16RX,
	PORT_NOISE_FILTER_FUNC_SENT17RX,
	PORT_NOISE_FILTER_FUNC_SENT18RX,
	PORT_NOISE_FILTER_FUNC_SENT19RX,
	PORT_NOISE_FILTER_FUNC_SENT20RX,
	PORT_NOISE_FILTER_FUNC_SENT21RX,
	PORT_NOISE_FILTER_FUNC_SENT22RX,
	PORT_NOISE_FILTER_FUNC_SENT23RX,
	PORT_NOISE_FILTER_FUNC_SENT24RX,
	PORT_NOISE_FILTER_FUNC_SENT25RX,
	PORT_NOISE_FILTER_FUNC_SENT26RX,
	PORT_NOISE_FILTER_FUNC_SENT27RX,
	PORT_NOISE_FILTER_FUNC_SENT28RX,
	PORT_NOISE_FILTER_FUNC_SENT29RX,
	/* PSI5 */
	PORT_NOISE_FILTER_FUNC_PSI50RX,
	PORT_NOISE_FILTER_FUNC_PSI51RX,
	PORT_NOISE_FILTER_FUNC_PSI52RX,
	PORT_NOISE_FILTER_FUNC_PSI53RX,
	/* PIC */
	PORT_NOISE_FILTER_FUNC_INTTAPA0ESO_TAPA0ESO,
	PORT_NOISE_FILTER_FUNC_INTTAPA1ESO_TAPA1ESO,
	PORT_NOISE_FILTER_FUNC_INTTAPA2ESO_TAPA2ESO,
	PORT_NOISE_FILTER_FUNC_INTTAPA3ESO_TAPA3ESO,
	PORT_NOISE_FILTER_FUNC_INTTAPA4ESO_TAPA4ESO,
	PORT_NOISE_FILTER_FUNC_INTTAPA5ESO_TAPA5ESO,
	/* ADCK */
	PORT_NOISE_FILTER_FUNC_ADCK0TRG0,
	PORT_NOISE_FILTER_FUNC_ADCK0TRG1,
	PORT_NOISE_FILTER_FUNC_ADCK0TRG2,
	PORT_NOISE_FILTER_FUNC_ADCK0TRG3,
	PORT_NOISE_FILTER_FUNC_ADCK0TRG4,
	PORT_NOISE_FILTER_FUNC_ADCK1TRG0,
	PORT_NOISE_FILTER_FUNC_ADCK1TRG1,
	PORT_NOISE_FILTER_FUNC_ADCK1TRG2,
	PORT_NOISE_FILTER_FUNC_ADCK1TRG3,
	PORT_NOISE_FILTER_FUNC_ADCK1TRG4,
	PORT_NOISE_FILTER_FUNC_ADCK2TRG0,
	PORT_NOISE_FILTER_FUNC_ADCK2TRG1,
	PORT_NOISE_FILTER_FUNC_ADCK2TRG2,
	PORT_NOISE_FILTER_FUNC_ADCK2TRG3,
	PORT_NOISE_FILTER_FUNC_ADCK2TRG4,
	PORT_NOISE_FILTER_FUNC_ADCK3TRG0,
	PORT_NOISE_FILTER_FUNC_ADCK3TRG1,
	PORT_NOISE_FILTER_FUNC_ADCK3TRG2,
	PORT_NOISE_FILTER_FUNC_ADCK3TRG3,
	PORT_NOISE_FILTER_FUNC_ADCK3TRG4,
	PORT_NOISE_FILTER_FUNC_ADCKATRG0,
	PORT_NOISE_FILTER_FUNC_ADCKATRG1,
	PORT_NOISE_FILTER_FUNC_ADCKATRG2,
	PORT_NOISE_FILTER_FUNC_ADCKATRG3,
	PORT_NOISE_FILTER_FUNC_ADCKATRG4,
	/* RHSB */
	PORT_NOISE_FILTER_FUNC_RHSB0EMRG,
	PORT_NOISE_FILTER_FUNC_RHSB1EMRG,
	PORT_NOISE_FILTER_FUNC_RHSB2EMRG,
	PORT_NOISE_FILTER_FUNC_RHSB3EMRG,
	/* ENCA */
	PORT_NOISE_FILTER_FUNC_ENCA0TIN0,
	PORT_NOISE_FILTER_FUNC_ENCA0TIN1,
	PORT_NOISE_FILTER_FUNC_ENCA1TIN0,
	PORT_NOISE_FILTER_FUNC_ENCA1TIN1,
	/* TAUD */
	PORT_NOISE_FILTER_FUNC_TAUD0I0,
	PORT_NOISE_FILTER_FUNC_TAUD0I1,
	PORT_NOISE_FILTER_FUNC_TAUD0I2,
	PORT_NOISE_FILTER_FUNC_TAUD0I3,
	PORT_NOISE_FILTER_FUNC_TAUD0I4,
	PORT_NOISE_FILTER_FUNC_TAUD0I5,
	PORT_NOISE_FILTER_FUNC_TAUD0I6,
	PORT_NOISE_FILTER_FUNC_TAUD0I7,
	PORT_NOISE_FILTER_FUNC_TAUD0I8,
	PORT_NOISE_FILTER_FUNC_TAUD0I9,
	PORT_NOISE_FILTER_FUNC_TAUD0I10,
	PORT_NOISE_FILTER_FUNC_TAUD0I11,
	PORT_NOISE_FILTER_FUNC_TAUD0I12,
	PORT_NOISE_FILTER_FUNC_TAUD0I13,
	PORT_NOISE_FILTER_FUNC_TAUD0I14,
	PORT_NOISE_FILTER_FUNC_TAUD0I15,
	PORT_NOISE_FILTER_FUNC_TAUD1I0,
	PORT_NOISE_FILTER_FUNC_TAUD1I1,
	PORT_NOISE_FILTER_FUNC_TAUD1I2,
	PORT_NOISE_FILTER_FUNC_TAUD1I3,
	PORT_NOISE_FILTER_FUNC_TAUD1I4,
	PORT_NOISE_FILTER_FUNC_TAUD1I5,
	PORT_NOISE_FILTER_FUNC_TAUD1I6,
	PORT_NOISE_FILTER_FUNC_TAUD1I7,
	PORT_NOISE_FILTER_FUNC_TAUD1I8,
	PORT_NOISE_FILTER_FUNC_TAUD1I9,
	PORT_NOISE_FILTER_FUNC_TAUD1I10,
	PORT_NOISE_FILTER_FUNC_TAUD1I11,
	PORT_NOISE_FILTER_FUNC_TAUD1I12,
	PORT_NOISE_FILTER_FUNC_TAUD1I13,
	PORT_NOISE_FILTER_FUNC_TAUD1I14,
	PORT_NOISE_FILTER_FUNC_TAUD1I15,
	PORT_NOISE_FILTER_FUNC_TAUD2I0,
	PORT_NOISE_FILTER_FUNC_TAUD2I1,
	PORT_NOISE_FILTER_FUNC_TAUD2I2,
	PORT_NOISE_FILTER_FUNC_TAUD2I3,
	PORT_NOISE_FILTER_FUNC_TAUD2I4,
	PORT_NOISE_FILTER_FUNC_TAUD2I5,
	PORT_NOISE_FILTER_FUNC_TAUD2I6,
	PORT_NOISE_FILTER_FUNC_TAUD2I7,
	PORT_NOISE_FILTER_FUNC_TAUD2I8,
	PORT_NOISE_FILTER_FUNC_TAUD2I9,
	PORT_NOISE_FILTER_FUNC_TAUD2I10,
	PORT_NOISE_FILTER_FUNC_TAUD2I11,
	PORT_NOISE_FILTER_FUNC_TAUD2I12,
	PORT_NOISE_FILTER_FUNC_TAUD2I13,
	PORT_NOISE_FILTER_FUNC_TAUD2I14,
	PORT_NOISE_FILTER_FUNC_TAUD2I15,
	PORT_NOISE_FILTER_FUNC_TAUD3I0,
	PORT_NOISE_FILTER_FUNC_TAUD3I1,
	PORT_NOISE_FILTER_FUNC_TAUD3I2,
	PORT_NOISE_FILTER_FUNC_TAUD3I3,
	PORT_NOISE_FILTER_FUNC_TAUD3I4,
	PORT_NOISE_FILTER_FUNC_TAUD3I5,
	PORT_NOISE_FILTER_FUNC_TAUD3I6,
	PORT_NOISE_FILTER_FUNC_TAUD3I7,
	PORT_NOISE_FILTER_FUNC_TAUD3I8,
	PORT_NOISE_FILTER_FUNC_TAUD3I9,
	PORT_NOISE_FILTER_FUNC_TAUD3I10,
	PORT_NOISE_FILTER_FUNC_TAUD3I11,
	PORT_NOISE_FILTER_FUNC_TAUD3I12,
	PORT_NOISE_FILTER_FUNC_TAUD3I13,
	PORT_NOISE_FILTER_FUNC_TAUD3I14,
	PORT_NOISE_FILTER_FUNC_TAUD3I15,
	/* TSG3 */
	PORT_NOISE_FILTER_FUNC_TSG30PTSI0_ENCA0E0,
	PORT_NOISE_FILTER_FUNC_TSG30PTSI1_ENCA0E1,
	PORT_NOISE_FILTER_FUNC_TSG30PTSI2_ENCA0EC,
	PORT_NOISE_FILTER_FUNC_TSG30CLKI,
	PORT_NOISE_FILTER_FUNC_TSG31PTSI0_ENCA1E0,
	PORT_NOISE_FILTER_FUNC_TSG31PTSI1_ENCA1E1,
	PORT_NOISE_FILTER_FUNC_TSG31PTSI2_ENCA1EC,
	PORT_NOISE_FILTER_FUNC_TSG31CLKI,
	PORT_NOISE_FILTER_FUNC_TSG32CLKI,
	/* Interrupt */
	PORT_NOISE_FILTER_FUNC_IRQ0,
	PORT_NOISE_FILTER_FUNC_IRQ1,
	PORT_NOISE_FILTER_FUNC_IRQ2,
	PORT_NOISE_FILTER_FUNC_IRQ3,
	PORT_NOISE_FILTER_FUNC_IRQ4,
	PORT_NOISE_FILTER_FUNC_IRQ5,
	PORT_NOISE_FILTER_FUNC_IRQ6,
	PORT_NOISE_FILTER_FUNC_IRQ7,
	PORT_NOISE_FILTER_FUNC_IRQ8,
	PORT_NOISE_FILTER_FUNC_IRQ9,
	PORT_NOISE_FILTER_FUNC_IRQ10,
	PORT_NOISE_FILTER_FUNC_IRQ11,
	PORT_NOISE_FILTER_FUNC_IRQ12,
	PORT_NOISE_FILTER_FUNC_IRQ13,
	PORT_NOISE_FILTER_FUNC_IRQ14,
	PORT_NOISE_FILTER_FUNC_IRQ15,
	PORT_NOISE_FILTER_FUNC_IRQ16,
	PORT_NOISE_FILTER_FUNC_IRQ17,
	PORT_NOISE_FILTER_FUNC_IRQ18,
	PORT_NOISE_FILTER_FUNC_IRQ19,
	PORT_NOISE_FILTER_FUNC_IRQ20,
	PORT_NOISE_FILTER_FUNC_IRQ21,
	PORT_NOISE_FILTER_FUNC_IRQ22,
	PORT_NOISE_FILTER_FUNC_IRQ23,
	PORT_NOISE_FILTER_FUNC_IRQ24,
	PORT_NOISE_FILTER_FUNC_IRQ25,
	PORT_NOISE_FILTER_FUNC_IRQ26,
	PORT_NOISE_FILTER_FUNC_IRQ27,
	PORT_NOISE_FILTER_FUNC_IRQ28,
	PORT_NOISE_FILTER_FUNC_IRQ29,
	PORT_NOISE_FILTER_FUNC_IRQ30,
	PORT_NOISE_FILTER_FUNC_IRQ31,
	PORT_NOISE_FILTER_FUNC_IRQ32,
	PORT_NOISE_FILTER_FUNC_IRQ33,
	PORT_NOISE_FILTER_FUNC_IRQ34,
	PORT_NOISE_FILTER_FUNC_IRQ35,
	PORT_NOISE_FILTER_FUNC_IRQ36,
	PORT_NOISE_FILTER_FUNC_IRQ37,
	PORT_NOISE_FILTER_FUNC_IRQ38,
	PORT_NOISE_FILTER_FUNC_IRQ39,
	PORT_NOISE_FILTER_FUNC_NMI,
	PORT_NOISE_FILTER_FUNC_IRQ40,
	PORT_NOISE_FILTER_FUNC_IRQ41,
	PORT_NOISE_FILTER_FUNC_IRQ42,
	PORT_NOISE_FILTER_FUNC_IRQ43,
	/* ECM */
	PORT_NOISE_FILTER_FUNC_ERRORIN0,
	PORT_NOISE_FILTER_FUNC_ERRORIN1,
	PORT_NOISE_FILTER_FUNC_ERRORIN2,
	PORT_NOISE_FILTER_FUNC_ERRORIN3,
	PORT_NOISE_FILTER_FUNC_ERRORIN4,
	PORT_NOISE_FILTER_FUNC_ERRORIN5,
	PORT_NOISE_FILTER_FUNC_ERRORIN6,
	PORT_NOISE_FILTER_FUNC_ERRORIN7,
	/* TAUJ */
	PORT_NOISE_FILTER_FUNC_TAUJ2I0,
	PORT_NOISE_FILTER_FUNC_TAUJ2I1,
	PORT_NOISE_FILTER_FUNC_TAUJ2I2,
	PORT_NOISE_FILTER_FUNC_TAUJ2I3,
	PORT_NOISE_FILTER_FUNC_TAUJ3I0,
	PORT_NOISE_FILTER_FUNC_TAUJ3I1,
	PORT_NOISE_FILTER_FUNC_TAUJ3I2,
	PORT_NOISE_FILTER_FUNC_TAUJ3I3,
	/* TSGTRG */
	PORT_NOISE_FILTER_FUNC_TSGTRG,
	/* EMU */
	PORT_NOISE_FILTER_FUNC_EM00_IN_A,
	PORT_NOISE_FILTER_FUNC_EM00_IN_B,
	PORT_NOISE_FILTER_FUNC_EM00_IN_Z,
	PORT_NOISE_FILTER_FUNC_EM10_IN_A,
	PORT_NOISE_FILTER_FUNC_EM10_IN_B,
	PORT_NOISE_FILTER_FUNC_EM10_IN_Z,
#endif
	/* Max */
	PORT_NOISE_FILTER_FUNC_FILTERNUMMAX
} Port_NoiseFilterFunc;	

/* Noise Filter Enabl Contro Bit */
#if MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2A
#define		PORT_NOISE_FILTER_RLIN30RX_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_RLIN31RX_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_CAN0RX_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_CAN1RX_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_FLX0RXDA_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_FLX1RXDA_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_SENT0RX_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_SENT1RX_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_SENT2RX_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_SENT3RX_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_SENT4RX_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_SENT5RX_ENABLE_CTRL_BIT					(5U)
#define		PORT_NOISE_FILTER_SENT6RX_ENABLE_CTRL_BIT					(6U)
#define		PORT_NOISE_FILTER_SENT7RX_ENABLE_CTRL_BIT					(7U)
#define		PORT_NOISE_FILTER_PSI50RX_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_PSI51RX_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_PSI52RX_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_PSI53RX_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAPA0ESO_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAPA1ESO_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_ADCJ0TRG0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_ADCJ0TRG1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_ADCJ0TRG2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_ADCJ0TRG3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_ADCJ0TRG4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_ADCJ1TRG0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_ADCJ1TRG1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_ADCJ1TRG2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_ADCJ1TRG3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_ADCJ1TRG4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_ADCJ2TRG0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_ADCJ2TRG1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_ADCJ2TRG2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_ADCJ2TRG3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_ADCJ2TRG4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_ENCA0TIN0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_ENCA0TIN1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_ENCA1TIN0_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_ENCA1TIN1_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAUD0I0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUD0I1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAUD0I2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAUD0I3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAUD0I4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_TAUD0I5_ENABLE_CTRL_BIT					(5U)
#define		PORT_NOISE_FILTER_TAUD0I6_ENABLE_CTRL_BIT					(6U)
#define		PORT_NOISE_FILTER_TAUD0I7_ENABLE_CTRL_BIT					(7U)
#define		PORT_NOISE_FILTER_TAUD0I8_ENABLE_CTRL_BIT					(8U)
#define		PORT_NOISE_FILTER_TAUD0I9_ENABLE_CTRL_BIT					(9U)
#define		PORT_NOISE_FILTER_TAUD0I10_ENABLE_CTRL_BIT					(10U)
#define		PORT_NOISE_FILTER_TAUD0I11_ENABLE_CTRL_BIT					(11U)
#define		PORT_NOISE_FILTER_TAUD0I12_ENABLE_CTRL_BIT					(12U)
#define		PORT_NOISE_FILTER_TAUD0I13_ENABLE_CTRL_BIT					(13U)
#define		PORT_NOISE_FILTER_TAUD0I14_ENABLE_CTRL_BIT					(14U)
#define		PORT_NOISE_FILTER_TAUD0I15_ENABLE_CTRL_BIT					(15U)
#define		PORT_NOISE_FILTER_TAUD1I0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUD1I1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAUD1I2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAUD1I3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAUD1I4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_TAUD1I5_ENABLE_CTRL_BIT					(5U)
#define		PORT_NOISE_FILTER_TAUD1I6_ENABLE_CTRL_BIT					(6U)
#define		PORT_NOISE_FILTER_TAUD1I7_ENABLE_CTRL_BIT					(7U)
#define		PORT_NOISE_FILTER_TAUD1I8_ENABLE_CTRL_BIT					(8U)
#define		PORT_NOISE_FILTER_TAUD1I9_ENABLE_CTRL_BIT					(9U)
#define		PORT_NOISE_FILTER_TAUD1I10_ENABLE_CTRL_BIT					(10U)
#define		PORT_NOISE_FILTER_TAUD1I11_ENABLE_CTRL_BIT					(11U)
#define		PORT_NOISE_FILTER_TAUD1I12_ENABLE_CTRL_BIT					(12U)
#define		PORT_NOISE_FILTER_TAUD1I13_ENABLE_CTRL_BIT					(13U)
#define		PORT_NOISE_FILTER_TAUD1I14_ENABLE_CTRL_BIT					(14U)
#define		PORT_NOISE_FILTER_TAUD1I15_ENABLE_CTRL_BIT					(15U)
#define		PORT_NOISE_FILTER_TAUD2I0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUD2I1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAUD2I2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAUD2I3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAUD2I4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_TAUD2I5_ENABLE_CTRL_BIT					(5U)
#define		PORT_NOISE_FILTER_TAUD2I6_ENABLE_CTRL_BIT					(6U)
#define		PORT_NOISE_FILTER_TAUD2I7_ENABLE_CTRL_BIT					(7U)
#define		PORT_NOISE_FILTER_TAUD2I8_ENABLE_CTRL_BIT					(8U)
#define		PORT_NOISE_FILTER_TAUD2I9_ENABLE_CTRL_BIT					(9U)
#define		PORT_NOISE_FILTER_TAUD2I10_ENABLE_CTRL_BIT					(10U)
#define		PORT_NOISE_FILTER_TAUD2I11_ENABLE_CTRL_BIT					(11U)
#define		PORT_NOISE_FILTER_TAUD2I12_ENABLE_CTRL_BIT					(12U)
#define		PORT_NOISE_FILTER_TAUD2I13_ENABLE_CTRL_BIT					(13U)
#define		PORT_NOISE_FILTER_TAUD2I14_ENABLE_CTRL_BIT					(14U)
#define		PORT_NOISE_FILTER_TAUD2I15_ENABLE_CTRL_BIT					(15U)
#define		PORT_NOISE_FILTER_TSG30PTSI0_ENCA0E0_ENABLE_CTRL_BIT		(0U)
#define		PORT_NOISE_FILTER_TSG30PTSI1_ENCA0E1_ENABLE_CTRL_BIT		(1U)
#define		PORT_NOISE_FILTER_TSG30PTSI2_ENCA0EC_ENABLE_CTRL_BIT		(2U)
#define		PORT_NOISE_FILTER_TSG30CLKI_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TSG31PTSI0_ENCA1E0_ENABLE_CTRL_BIT		(4U)
#define		PORT_NOISE_FILTER_TSG31PTSI1_ENCA1E1_ENABLE_CTRL_BIT		(5U)
#define		PORT_NOISE_FILTER_TSG31PTSI2_ENCA1EC_ENABLE_CTRL_BIT		(6U)
#define		PORT_NOISE_FILTER_TSG31CLKI_ENABLE_CTRL_BIT					(7U)
#define		PORT_NOISE_FILTER_NMI_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_INTP0_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_INTP1_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_INTP2_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_INTP3_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_INTP4_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_INTP5_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_INTP6_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_INTP7_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_INTP8_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_INTP9_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_INTP10_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP11_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP12_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP13_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP14_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP15_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP16_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP17_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP18_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP19_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP20_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP21_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP22_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP23_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP24_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP25_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP26_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP27_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP28_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP29_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP30_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP31_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP32_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP33_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP34_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP35_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP36_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP37_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP38_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_INTP39_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUJ0I0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUJ0I1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAUJ0I2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAUJ0I3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAUJ1I0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUJ1I1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAUJ1I2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAUJ1I3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAUJ2I0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUJ2I1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAUJ2I2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAUJ2I3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAUJ3I0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUJ3I1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAUJ3I2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAUJ3I3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_ERRORIN0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_ERRORIN1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_ERRORIN2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_ERRORIN3_ENABLE_CTRL_BIT					(3U)
#elif MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2B
#define		PORT_NOISE_FILTER_RLIN30RX_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_RLIN31RX_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_CAN0RX_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_CAN1RX_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_FLX0RXDA_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_FLX1RXDA_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_SENT0RX_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_SENT1RX_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_SENT2RX_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_SENT3RX_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_SENT4RX_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_SENT5RX_ENABLE_CTRL_BIT					(5U)
#define		PORT_NOISE_FILTER_SENT6RX_ENABLE_CTRL_BIT					(6U)
#define		PORT_NOISE_FILTER_SENT7RX_ENABLE_CTRL_BIT					(7U)
#define		PORT_NOISE_FILTER_SENT8RX_ENABLE_CTRL_BIT					(8U)
#define		PORT_NOISE_FILTER_SENT9RX_ENABLE_CTRL_BIT					(9U)
#define		PORT_NOISE_FILTER_SENT10RX_ENABLE_CTRL_BIT					(10U)
#define		PORT_NOISE_FILTER_SENT11RX_ENABLE_CTRL_BIT					(11U)
#define		PORT_NOISE_FILTER_SENT12RX_ENABLE_CTRL_BIT					(12U)
#define		PORT_NOISE_FILTER_SENT13RX_ENABLE_CTRL_BIT					(13U)
#define		PORT_NOISE_FILTER_SENT14RX_ENABLE_CTRL_BIT					(14U)
#define		PORT_NOISE_FILTER_SENT15RX_ENABLE_CTRL_BIT					(15U)
#define		PORT_NOISE_FILTER_SENT16RX_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_SENT17RX_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_SENT18RX_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_SENT19RX_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_SENT20RX_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_SENT21RX_ENABLE_CTRL_BIT					(5U)
#define		PORT_NOISE_FILTER_SENT22RX_ENABLE_CTRL_BIT					(6U)
#define		PORT_NOISE_FILTER_SENT23RX_ENABLE_CTRL_BIT					(7U)
#define		PORT_NOISE_FILTER_SENT24RX_ENABLE_CTRL_BIT					(8U)
#define		PORT_NOISE_FILTER_SENT25RX_ENABLE_CTRL_BIT					(9U)
#define		PORT_NOISE_FILTER_SENT26RX_ENABLE_CTRL_BIT					(10U)
#define		PORT_NOISE_FILTER_SENT27RX_ENABLE_CTRL_BIT					(11U)
#define		PORT_NOISE_FILTER_SENT28RX_ENABLE_CTRL_BIT					(12U)
#define		PORT_NOISE_FILTER_SENT29RX_ENABLE_CTRL_BIT					(13U)
#define		PORT_NOISE_FILTER_PSI50RX_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_PSI51RX_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_PSI52RX_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_PSI53RX_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAPA0ESO_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAPA1ESO_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAPA2ESO_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAPA3ESO_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAPA4ESO_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_TAPA5ESO_ENABLE_CTRL_BIT					(5U)
#define		PORT_NOISE_FILTER_ADCK0TRG0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_ADCK0TRG1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_ADCK0TRG2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_ADCK0TRG3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_ADCK0TRG4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_ADCK1TRG0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_ADCK1TRG1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_ADCK1TRG2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_ADCK1TRG3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_ADCK1TRG4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_ADCK2TRG0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_ADCK2TRG1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_ADCK2TRG2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_ADCK2TRG3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_ADCK2TRG4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_ADCK3TRG0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_ADCK3TRG1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_ADCK3TRG2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_ADCK3TRG3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_ADCK3TRG4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_ADCKATRG0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_ADCKATRG1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_ADCKATRG2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_ADCKATRG3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_ADCKATRG4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_RHSB0EMRG_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_RHSB1EMRG_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_RHSB2EMRG_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_RHSB3EMRG_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_ENCA0TIN0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_ENCA0TIN1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_ENCA1TIN0_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_ENCA1TIN1_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAUD0I0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUD0I1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAUD0I2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAUD0I3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAUD0I4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_TAUD0I5_ENABLE_CTRL_BIT					(5U)
#define		PORT_NOISE_FILTER_TAUD0I6_ENABLE_CTRL_BIT					(6U)
#define		PORT_NOISE_FILTER_TAUD0I7_ENABLE_CTRL_BIT					(7U)
#define		PORT_NOISE_FILTER_TAUD0I8_ENABLE_CTRL_BIT					(8U)
#define		PORT_NOISE_FILTER_TAUD0I9_ENABLE_CTRL_BIT					(9U)
#define		PORT_NOISE_FILTER_TAUD0I10_ENABLE_CTRL_BIT					(10U)
#define		PORT_NOISE_FILTER_TAUD0I11_ENABLE_CTRL_BIT					(11U)
#define		PORT_NOISE_FILTER_TAUD0I12_ENABLE_CTRL_BIT					(12U)
#define		PORT_NOISE_FILTER_TAUD0I13_ENABLE_CTRL_BIT					(13U)
#define		PORT_NOISE_FILTER_TAUD0I14_ENABLE_CTRL_BIT					(14U)
#define		PORT_NOISE_FILTER_TAUD0I15_ENABLE_CTRL_BIT					(15U)
#define		PORT_NOISE_FILTER_TAUD1I0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUD1I1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAUD1I2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAUD1I3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAUD1I4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_TAUD1I5_ENABLE_CTRL_BIT					(5U)
#define		PORT_NOISE_FILTER_TAUD1I6_ENABLE_CTRL_BIT					(6U)
#define		PORT_NOISE_FILTER_TAUD1I7_ENABLE_CTRL_BIT					(7U)
#define		PORT_NOISE_FILTER_TAUD1I8_ENABLE_CTRL_BIT					(8U)
#define		PORT_NOISE_FILTER_TAUD1I9_ENABLE_CTRL_BIT					(9U)
#define		PORT_NOISE_FILTER_TAUD1I10_ENABLE_CTRL_BIT					(10U)
#define		PORT_NOISE_FILTER_TAUD1I11_ENABLE_CTRL_BIT					(11U)
#define		PORT_NOISE_FILTER_TAUD1I12_ENABLE_CTRL_BIT					(12U)
#define		PORT_NOISE_FILTER_TAUD1I13_ENABLE_CTRL_BIT					(13U)
#define		PORT_NOISE_FILTER_TAUD1I14_ENABLE_CTRL_BIT					(14U)
#define		PORT_NOISE_FILTER_TAUD1I15_ENABLE_CTRL_BIT					(15U)
#define		PORT_NOISE_FILTER_TAUD2I0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUD2I1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAUD2I2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAUD2I3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAUD2I4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_TAUD2I5_ENABLE_CTRL_BIT					(5U)
#define		PORT_NOISE_FILTER_TAUD2I6_ENABLE_CTRL_BIT					(6U)
#define		PORT_NOISE_FILTER_TAUD2I7_ENABLE_CTRL_BIT					(7U)
#define		PORT_NOISE_FILTER_TAUD2I8_ENABLE_CTRL_BIT					(8U)
#define		PORT_NOISE_FILTER_TAUD2I9_ENABLE_CTRL_BIT					(9U)
#define		PORT_NOISE_FILTER_TAUD2I10_ENABLE_CTRL_BIT					(10U)
#define		PORT_NOISE_FILTER_TAUD2I11_ENABLE_CTRL_BIT					(11U)
#define		PORT_NOISE_FILTER_TAUD2I12_ENABLE_CTRL_BIT					(12U)
#define		PORT_NOISE_FILTER_TAUD2I13_ENABLE_CTRL_BIT					(13U)
#define		PORT_NOISE_FILTER_TAUD2I14_ENABLE_CTRL_BIT					(14U)
#define		PORT_NOISE_FILTER_TAUD2I15_ENABLE_CTRL_BIT					(15U)
#define		PORT_NOISE_FILTER_TAUD3I0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUD3I1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAUD3I2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAUD3I3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAUD3I4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_TAUD3I5_ENABLE_CTRL_BIT					(5U)
#define		PORT_NOISE_FILTER_TAUD3I6_ENABLE_CTRL_BIT					(6U)
#define		PORT_NOISE_FILTER_TAUD3I7_ENABLE_CTRL_BIT					(7U)
#define		PORT_NOISE_FILTER_TAUD3I8_ENABLE_CTRL_BIT					(8U)
#define		PORT_NOISE_FILTER_TAUD3I9_ENABLE_CTRL_BIT					(9U)
#define		PORT_NOISE_FILTER_TAUD3I10_ENABLE_CTRL_BIT					(10U)
#define		PORT_NOISE_FILTER_TAUD3I11_ENABLE_CTRL_BIT					(11U)
#define		PORT_NOISE_FILTER_TAUD3I12_ENABLE_CTRL_BIT					(12U)
#define		PORT_NOISE_FILTER_TAUD3I13_ENABLE_CTRL_BIT					(13U)
#define		PORT_NOISE_FILTER_TAUD3I14_ENABLE_CTRL_BIT					(14U)
#define		PORT_NOISE_FILTER_TAUD3I15_ENABLE_CTRL_BIT					(15U)
#define		PORT_NOISE_FILTER_TSG30PTSI0_ENCA0E0_ENABLE_CTRL_BIT		(0U)
#define		PORT_NOISE_FILTER_TSG30PTSI1_ENCA0E1_ENABLE_CTRL_BIT		(1U)
#define		PORT_NOISE_FILTER_TSG30PTSI2_ENCA0EC_ENABLE_CTRL_BIT		(2U)
#define		PORT_NOISE_FILTER_TSG30CLKI_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TSG31PTSI0_ENCA1E0_ENABLE_CTRL_BIT		(4U)
#define		PORT_NOISE_FILTER_TSG31PTSI1_ENCA1E1_ENABLE_CTRL_BIT		(5U)
#define		PORT_NOISE_FILTER_TSG31PTSI2_ENCA1EC_ENABLE_CTRL_BIT		(6U)
#define		PORT_NOISE_FILTER_TSG31CLKI_ENABLE_CTRL_BIT					(7U)
#define		PORT_NOISE_FILTER_TSG32CLKI_ENABLE_CTRL_BIT					(8U)
#define		PORT_NOISE_FILTER_IRQ0_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ1_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ2_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ3_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ4_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ5_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ6_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ7_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ8_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ9_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ10_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ11_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ12_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ13_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ14_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ15_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ16_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ17_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ18_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ19_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ20_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ21_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ22_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ23_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ24_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ25_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ26_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ27_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ28_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ29_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ30_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ31_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ32_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ33_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ34_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ35_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ36_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ37_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ38_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ39_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_NMI_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ40_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ41_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ42_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_IRQ43_ENABLE_CTRL_BIT						(0U)
#define		PORT_NOISE_FILTER_ERRORIN0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_ERRORIN1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_ERRORIN2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_ERRORIN3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_ERRORIN4_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_ERRORIN5_ENABLE_CTRL_BIT					(5U)
#define		PORT_NOISE_FILTER_ERRORIN6_ENABLE_CTRL_BIT					(6U)
#define		PORT_NOISE_FILTER_ERRORIN7_ENABLE_CTRL_BIT					(7U)
#define		PORT_NOISE_FILTER_TAUJ2I0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUJ2I1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAUJ2I2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAUJ2I3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TAUJ3I0_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_TAUJ3I1_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_TAUJ3I2_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_TAUJ3I3_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_TSGTRG_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_EM00_IN_A_ENABLE_CTRL_BIT					(0U)
#define		PORT_NOISE_FILTER_EM00_IN_B_ENABLE_CTRL_BIT					(1U)
#define		PORT_NOISE_FILTER_EM00_IN_Z_ENABLE_CTRL_BIT					(2U)
#define		PORT_NOISE_FILTER_EM10_IN_A_ENABLE_CTRL_BIT					(3U)
#define		PORT_NOISE_FILTER_EM10_IN_B_ENABLE_CTRL_BIT					(4U)
#define		PORT_NOISE_FILTER_EM10_IN_Z_ENABLE_CTRL_BIT					(5U)
#endif

/* Mode Config */
typedef struct {
#if MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2A
	uint32	u4LVDSCtrlA;			/* LVDS(Port2) */
	uint32	u4LVDSCtrlB;			/* LVDS(Port4) */
#elif MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2B
	uint32	u4LVDSCtrlC;			/* LVDS(Port10) */
	uint32	u4LVDSCtrlD;			/* LVDS(Port25) */
#endif
	uint16	u2ModeCtrl;				/* MODE SELECTION */
	uint16	u2Mode;					/* I/O control */
	uint16	u2InBufCtrl;			/* Whether to use input buffer */
	uint16	u2IPCtrl;				/* I/O control mode selection */
	uint16	u2FuncCtrl;				/* Alternative Mode selection */
	uint16	u2FuncCtrlExp;			/* Alternative Mode selection extension */
	uint16	u2FuncCtrlAddExp;		/* Alternative Mode selection additional extension */
#if MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2B
	uint16	u2FuncCtrlExtAddExp;	/* Alternative Mode selection external addition extension */
#endif
	uint16	u2PullUp;				/* Pull-up control */
	uint16	u2PullDown;				/* Pull-down control */
	uint16	u2InBufSel;				/* Input buffer selection */
	uint16	u2InBufSelAdv;			/* Input buffer selection extension */
	uint16	u2OpenDrainCtrl;		/* Open Drain/Push Pull Selection */
	uint16	u2OpenDrainCtrlExp;		/* Open Drain/Push Pull Selection Extension */
	uint16	u2DriveStrCtrl;			/* Drive strength selection */
	uint16	u2UnivCharCtrl;			/* Drive strength selection extension */
	uint16	u2OutValInv;			/* Invert output value */
	uint16	u2BIDirectionCtrl;		/* Bidirectional mode */
	uint16	u2Port;					/* Output level */
	uint16	u2PortNot;				/* Output value inversion */
#if MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2B
	uint16	u2ErrInOpenDrainCtrl;	/* ERRORIN Open-drain control */
#endif
} Port_InitModeType;

/* Noise Filter */
typedef struct {
	Port_NoiseFilterFunc	enFilterType;				/* Feature (s) */	
	uint16					u2IsNoiseFilterEnable;		/* Valid invalid */
	uint8					u1FilterCtrl;				/* Operation */
	uint8					u1DigitalNoiseElimCtrl;		/* Features */
} Port_NoiseFilterType;

/* Address Table for Noise Filter Settings */
typedef struct {
	uint32					u4DNFAENAddr;				/* Address for setting enable/disable of digital filter */
	uint32					u4FCLACTLAddr;				/* Address of register for setting noise control */
	uint32					u4DNFACTLAddr;				/* Address of noise rejection control register */
} Port_NoiseFilterRegType;

/* Safe State */
typedef struct {
	uint16		u2SafeStateCtrl;	/* Valid invalid */
	uint16		u2ErrTrigSel;		/* Error trigger selection */
	uint16		u2ErrTrigSelExp;	/* Error Trigger Selection Extension */
#if MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2B
	uint16		u2SafeStateTrigSelAddExp;	/* Error Trigger Selection Additional Extension */
#endif
} Port_SafeStateType;

/* Port Information */
typedef struct {
	Port_InitModeType		stInitMode;					/* Mode value */
	Port_PortType			enPort_Type;				/* Port type */
	uint16					u2IsDirectionChangeable;	/* Can Dynamic Change Direction */
	uint16					u2IsModeChangeable;			/* Can Dynamic Change Mode */
	uint8					u1PortId;					/* Port number */
} Port_PortInfoType;

/* Pin Information */
typedef struct {
	uint8	u1Pin_pos;		/* Pin number */
	uint8	u1Port_idx;		/* Index of Port Information */
} Port_PinInfoType;

/* Mode value for Port_SetPinMode () */
typedef struct {
	uint8	u1IsAltMode;				/* MODE SELECTION */
	uint8	u1Mode;						/* I/O control */
	uint8	u1InBufCtrl;				/* Whether to use input buffer */
	uint8	u1IPCtrl;					/* I/O control mode selection */
	uint8	u1FuncCtrl;					/* Alternative Mode selection */
	uint8	u1FuncCtrlExp;				/* Alternative Mode selection extension */
	uint8	u1IsAltMode5to8;			/* Alternative Mode selection additional extension */
#if MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2B
	uint8	u1IsAltMode9to16;			/* Alternative Mode selection additional extension */
#endif
	uint8	u1PullUp;					/* Pull-up control */
	uint8	u1PullDown;					/* Pull-down control */
	uint8	u1InBufSel;					/* Input buffer selection */
	uint8	u1InBufSelAdv;				/* Input buffer selection extension */
	uint8	u1OpenDrainCtrl;			/* Open Drain/Push Pull Selection */
	uint8	u1OpenDrainCtrlExp;			/* Open Drain/Push Pull Selection Extension */
	uint8	u1DriveStrCtrl;				/* Drive strength selection */
	uint8	u1UnivCharCtrl;				/* Drive strength selection extension */
	uint8	u1OutValInv;				/* Invert output value */
	uint8	u1BiDirectionCtrl;			/* Bidirectional mode */
	uint8	u1Port;						/* Output level */
	uint8	u1PortNot;					/* Output value inversion */
	uint8	u1PORT_LVDS_voltage;		/* Voltage setting */
	uint8	u1PORT_LVDS_Enable;			/* LVDS input enabled/disabled */
#if MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2B
	uint8	u1PORT_LVDS_OutputType;		/* LVDS input enabled/disabled */
	uint8	u1ErrInOpenDrainCtrl;		/* ERRORIN Open-drain control */
#endif
} Port_ModeParamType;


/* Pin ID */
typedef uint16 Port_PinType;
/* Pin Mode */
typedef uint32 Port_PinModeType;

#if (PORT_CFG_REG_CHK == STD_ON)

typedef struct{
	uint16		u2ErrTrigSel				:1;
	uint16		u2ErrTrigSelExp				:1;
#if MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2B
	uint16		u2SafeStateTrigSelAddExp	:1;
#endif
	uint16		u2SafeStateCtrl				:1;
#if MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2B
	uint16		u2dummy						:12;
#else /* MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2A */
	uint16		u2dummy						:13;
#endif
} Port_SafeStateDataType;

typedef struct{
	uint32						u4PortControl;				/* PCR */
	Port_SafeStateDataType		stSafeSate;
#if MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2B
	uint8						u1ErrInOpenDrainCtrl;
#endif
	uint8						u1PinChangeable;
} Port_ChkPinModeType;

#endif /* (PORT_CFG_REG_CHK == STD_ON ) */

#if (MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2A)

/* Number of elements */
#define PORT_USED_PIN_MAX					((uint16)301U)		/* Number of Pins */
#define PORT_USED_PORT_MAX					((uint8)27U)		/* Number of Ports */
#define PORT_NOISE_FILTER_MAX				((uint8)156U)		/* Number of functions subject to Noise Filter */

/* Direction */
typedef enum {
	PORT_PIN_OUT = 0,
	PORT_PIN_IN
} Port_PinDirectionType;

/* Port Config */
typedef struct{
	Port_PortInfoType		stPortInfo[PORT_USED_PORT_MAX];			/* Port Information */
	Port_PinInfoType		stPinInfo[PORT_USED_PIN_MAX];			/* Pin Information */
	Port_NoiseFilterType	stNoiseFilter[PORT_NOISE_FILTER_MAX];	/* Noise Filter Information */
	Port_SafeStateType		stSafeState[PORT_USED_PORT_MAX];		/* Safe State Information */
	uint16					u2PortUnconfig[PORT_USED_PORT_MAX];				/* Port Initialization Required */
	uint16					u2SafeStateUnconfig[PORT_USED_PORT_MAX];		/* SafeState Initialization Required */
	uint8					u1NoiseFilterUnconfig[PORT_NOISE_FILTER_MAX];	/* NoiseFilter Initialization Required */
	uint8					u1LVDS_1_Unconfig;								/* LVDS_A Initialization Required */
	uint8					u1LVDS_2_Unconfig;								/* LVDS_B Initialization Required */
#if (PORT_CFG_REG_CHK == STD_ON)
	const Port_ChkPinModeType*	pstPinRegChkInfo;							/* Pin Infomation Pointer */
#endif
} Port_ConfigType;

typedef struct {
	Port_ModeParamType			stMode;				/* Mode value */
	Port_NoiseFilterType		stNoiseFilter;		/* NiseFilter */
	Port_SafeStateType			stSafeState;		/* Safe State */
	uint8						u1IsFilterSet;		/* Has Noise Filter set */
	uint8						u1IsModeSet;		/* Mode set or not */
	uint8						u1IsSafeStateSet;	/* Safe State set or not */
} Port_SetPinModeType;

#elif (MCAL_SPAL_TARGET == MCAL_TARGET_RH850U2B)

/* Number of elements */
#define PORT_USED_PIN_MAX					((uint16)365U)		/* Number of Pins */
#define PORT_USED_PORT_MAX					((uint8)32U)		/* Number of Ports */
#define PORT_NOISE_FILTER_MAX				((uint8)219U)		/* Number of functions subject to Noise Filter */

/* Direction */
typedef enum {
	PORT_PIN_OUT = 0,
	PORT_PIN_IN
} Port_PinDirectionType;

/* Parameters for Port_SetPinMode () */
typedef struct {
	Port_ModeParamType			stMode;				/* Mode value */
	Port_NoiseFilterType		stNoiseFilter;		/* NiseFilter */
	Port_SafeStateType			stSafeState;		/* Safe State */
	uint8						u1IsFilterSet;		/* Has Noise Filter set */
	uint8						u1IsModeSet;		/* Mode set or not */
	uint8						u1IsSafeStateSet;	/* Safe State set or not */
} Port_SetPinModeType;

/* Port Config */
typedef struct{
	Port_PortInfoType		stPortInfo[PORT_USED_PORT_MAX];			/* Port Information */
	Port_PinInfoType		stPinInfo[PORT_USED_PIN_MAX];			/* Pin Information */
	Port_NoiseFilterType	stNoiseFilter[PORT_NOISE_FILTER_MAX];	/* Noise Filter Information */
	Port_SafeStateType		stSafeState[PORT_USED_PORT_MAX];		/* Safe State Information */
	uint16					u2PortUnconfig[PORT_USED_PORT_MAX];				/* Port Initialization Required */
	uint16					u2SafeStateUnconfig[PORT_USED_PORT_MAX];		/* SafeState Initialization Required */
	uint8					u1NoiseFilterUnconfig[PORT_NOISE_FILTER_MAX];	/* NoiseFilter Initialization Required */
	uint8					u1LVDS_1_Unconfig;								/* LVDS_C Initialization Required */
	uint8					u1LVDS_2_Unconfig;								/* LVDS_D Initialization Required */
	uint16					u2Pulvsel5;		/* pull-up/down voltage option setting  */
	uint16					u2Pulvsel5_Unconfig;		/* pull-up/down voltage option can be set  */
#if (PORT_CFG_REG_CHK == STD_ON)
	const Port_ChkPinModeType*	pstPinRegChkInfo;							/* Pin Infomation Pointer */
#endif
} Port_ConfigType;

#endif


#endif /* PORT_TYPE_H */
/*-- End Of File -------------------------------------------------------------------------------*/
