/* Spi-r04-3000-0200-a-v00 */
/************************************************************************************************/
/*																								*/
/*		SPI Driver																				*/
/*																								*/
/*		Copyright : DENSO CORPORATION															*/
/*																								*/
/************************************************************************************************/

#ifndef SPI_UCFG_H
#define SPI_UCFG_H

/*==============================================================================================*/
/*	include files																				*/
/*==============================================================================================*/
#include "bswlib.h"
#include "Os.h"

/*==============================================================================================*/
/*	defines / data types / structs / unions / macros											*/
/*==============================================================================================*/
#define BSW_CFG_GETSPINLOCK_SPI()					SuspendAllInterrupts()
#define BSW_CFG_RELEASESPINLOCK_SPI()	 			ResumeAllInterrupts()

#define BSW_CFG_GETSPINLOCK_PIL_SPI()				SuspendAllInterrupts()
#define BSW_CFG_RELEASESPINLOCK_PIL_SPI()			ResumeAllInterrupts()

#define SPI_CFG_MODEA_USE					(ON)
#define SPI_CFG_MODEB_USE					(OFF)
#define SPI_CFG_MODEC_USE					(ON)

#define SPI_CFG_SYNCSEND_TIMEOUT			(20U)	/* @todo S.Abe : 20251024 to avoid an infinit loop */
#define SPI_CFG_SYNCRECEIVE_TIMEOUT			(20U)	/* @todo S.Abe : 20251024 to avoid an infinit loop */
#define SPI_CFG_SENDDMASTOP_TIMEOUT			(20U)	/* @todo S.Abe : 20251024 to avoid an infinit loop */
#define SPI_CFG_RECEIVEDMASTOP_TIMEOUT		(20U)	/* @todo S.Abe : 20251024 to avoid an infinit loop */
#define SPI_CFG_ASYNCDMASTART_TIMEOUT		(20U)	/* @todo S.Abe : 20251024 to avoid an infinit loop */

#define Bswlib_GetCoreId()					(u4_g_GetCoreId())


/* Spi Communication Mode A Channel ID (SPI_COMA_ID xxx) */
#define SPI_COMA_ID_ETHSW					(0)
#define SPI_COMA_ID_CANTRCV_0				(1)
#define SPI_COMA_ID_CANTRCV_1				(2)

#define SPI_UCFG_MODEA_CHANNEL_NUM			(3)

#define SPI_UCFG_MODEA_CH0_HARDCH			(PIL_SPI_CH0_0)
#define SPI_UCFG_MODEA_CH0_SHIFTCLOCKIDLELEVEL	(PIL_SPI_CKR_LOW)
#define SPI_UCFG_MODEA_CH0_SOUTFUNCTION		(PIL_SPI_SOLS_LOW)
#define SPI_UCFG_MODEA_CH0_CLOCKIDLELEVEL	(LO)
#define SPI_UCFG_MODEA_CH0_STARTEDGE		(PIL_SPI_STARTEDGE_CS)
#define SPI_UCFG_MODEA_CH0_BITRATE_PATTERN	(PIL_SPI_BITRATE_10M)
#define SPI_UCFG_MODEA_CH0_BITDIRECTION		(PIL_SPI_DIRECTION_MSBFIRST)
#define SPI_UCFG_MODEA_CH0_DATASIZE			(PIL_SPI_LENGTH_8BIT)
#define SPI_UCFG_MODEA_CH0_CSACTIVELEVEL	(LO)
#define SPI_UCFG_MODEA_CH0_CSID				(PIL_SPI_CSID_0)
#define SPI_UCFG_MODEA_CH0_CS2CLKDELAY		(PIL_SPI_DELAY_50NS)
#define SPI_UCFG_MODEA_CH0_CLK2CSDELAY		(PIL_SPI_DELAY_50NS)
#define SPI_UCFG_MODEA_CH0_INTERDATATIME	(PIL_SPI_DELAY_800NS)
#define SPI_UCFG_MODEA_CH0_COREID			(BSW_CORE_ID_CORE0)

#define SPI_UCFG_MODEA_CH1_HARDCH			(PIL_SPI_CH6_0)
#define SPI_UCFG_MODEA_CH1_SHIFTCLOCKIDLELEVEL	(PIL_SPI_CKR_LOW)
#define SPI_UCFG_MODEA_CH1_SOUTFUNCTION		(PIL_SPI_SOLS_LOW)
#define SPI_UCFG_MODEA_CH1_CLOCKIDLELEVEL	(LO)
#define SPI_UCFG_MODEA_CH1_STARTEDGE		(PIL_SPI_STARTEDGE_CLK)
#define SPI_UCFG_MODEA_CH1_BITRATE_PATTERN	(PIL_SPI_BITRATE_0_91M)
#define SPI_UCFG_MODEA_CH1_BITDIRECTION		(PIL_SPI_DIRECTION_MSBFIRST)
#define SPI_UCFG_MODEA_CH1_DATASIZE			(PIL_SPI_LENGTH_16BIT)
#define SPI_UCFG_MODEA_CH1_CSACTIVELEVEL	(LO)
#define SPI_UCFG_MODEA_CH1_CSID				(PIL_SPI_CSID_0)
#define SPI_UCFG_MODEA_CH1_CS2CLKDELAY		(PIL_SPI_DELAY_200NS)
#define SPI_UCFG_MODEA_CH1_CLK2CSDELAY		(PIL_SPI_DELAY_200NS)
#define SPI_UCFG_MODEA_CH1_INTERDATATIME	(0)
#define SPI_UCFG_MODEA_CH1_COREID			(BSW_CORE_ID_CORE0)

#define SPI_UCFG_MODEA_CH2_HARDCH			(PIL_SPI_CH7_0)
#define SPI_UCFG_MODEA_CH2_SHIFTCLOCKIDLELEVEL	(PIL_SPI_CKR_LOW)
#define SPI_UCFG_MODEA_CH2_SOUTFUNCTION		(PIL_SPI_SOLS_LOW)
#define SPI_UCFG_MODEA_CH2_CLOCKIDLELEVEL	(LO)
#define SPI_UCFG_MODEA_CH2_STARTEDGE		(PIL_SPI_STARTEDGE_CLK)
#define SPI_UCFG_MODEA_CH2_BITRATE_PATTERN	(PIL_SPI_BITRATE_0_91M)
#define SPI_UCFG_MODEA_CH2_BITDIRECTION		(PIL_SPI_DIRECTION_MSBFIRST)
#define SPI_UCFG_MODEA_CH2_DATASIZE			(PIL_SPI_LENGTH_16BIT)
#define SPI_UCFG_MODEA_CH2_CSACTIVELEVEL	(LO)
#define SPI_UCFG_MODEA_CH2_CSID				(PIL_SPI_CSID_0)
#define SPI_UCFG_MODEA_CH2_CS2CLKDELAY		(PIL_SPI_DELAY_200NS)
#define SPI_UCFG_MODEA_CH2_CLK2CSDELAY		(PIL_SPI_DELAY_200NS)
#define SPI_UCFG_MODEA_CH2_INTERDATATIME	(0)
#define SPI_UCFG_MODEA_CH2_COREID			(BSW_CORE_ID_CORE0)

#define SPI_COMA_SEQID_ETHSW				(0)
#define SPI_COMA_SEQID_CANTRCV_0			(1)
#define SPI_COMA_SEQID_CANTRCV_1			(2)

#define SPI_UCFG_MODEA_SEQUENCE_NUM			(3)

#define SPI_UCFG_SEQ0_CHID					(SPI_COMA_ID_ETHSW)
#define SPI_UCFG_SEQ1_CHID					(SPI_COMA_ID_CANTRCV_0)
#define SPI_UCFG_SEQ2_CHID					(SPI_COMA_ID_CANTRCV_1)

/* Spi Communication ModeC ID (SPI_COMC_ID xxx) */
#define SPI_COMC_ID_SOC_MCU1				(0)
#define SPI_COMC_ID_SOC_MCU2				(1)
#define SPI_COMC_ID_SOC_MCU3				(2)

#define SPI_UCFG_MODEC_CHANNEL_NUM			(3)

#define SPI_UCFG_MODEC_CH0_HARDCH			(PIL_SPI_CH2_0)
#define SPI_UCFG_MODEC_CH0_SHIFTCLOCKIDLELEVEL	(PIL_SPI_CKR_HIGH)
#define SPI_UCFG_MODEC_CH0_SOUTFUNCTION		(PIL_SPI_SOLS_LOW)
#define SPI_UCFG_MODEC_CH0_CLOCKIDLELEVEL	(LO)
#define SPI_UCFG_MODEC_CH0_STARTEDGE		(PIL_SPI_STARTEDGE_CLK)
#define SPI_UCFG_MODEC_CH0_BITRATE_PATTERN	(PIL_SPI_BITRATE_10M)
#define SPI_UCFG_MODEC_CH0_BITDIRECTION		(PIL_SPI_DIRECTION_MSBFIRST)
#define SPI_UCFG_MODEC_CH0_DATASIZE			(PIL_SPI_LENGTH_32BIT)
#define SPI_UCFG_MODEC_CH0_CSINENABLE 		(PIL_SPI_CS_IGNORE)
#define SPI_UCFG_MODEC_CH0_CSACTIVELEVEL	(LO)
#define SPI_UCFG_MODEC_CH0_CSID				(PIL_SPI_CSID_0)
#define SPI_UCFG_MODEC_CH0_MASTERSLAVEMODE	(PIL_SPI_MASTERSLAVE_SLAVE)
#define SPI_UCFG_MODEC_CH0_CS2CLKDELAY		(PIL_SPI_DELAY_50NS)
#define SPI_UCFG_MODEC_CH0_CLK2CSDELAY		(PIL_SPI_DELAY_50NS)
#define SPI_UCFG_MODEC_CH0_NEXTACCESSDELAY	(PIL_SPI_DELAY_50NS)
#define SPI_UCFG_MODEC_CH0_COREID			(BSW_CORE_ID_CORE0)
#define SPI_UCFG_MODEC_CH0_TRGSELDMADTS		(PIL_SPI_TGCTL_TRGSEL_DMA)
#define SPI_UCFG_MODEC_CH0_DMATXCH			(DMA_CH_DATA_ID_0)
#define SPI_UCFG_MODEC_CH0_DMARXCH			(DMA_CH_DATA_ID_1)
#define SPI_UCFG_MODEC_CH0_DMASIZE			(u1DMA_TRANSSIZE_4)
#define SPI_UCFG_MODEC_CH0_NOTIF_ID			(0) //@todo
#define SPI_UCFG_MODEC_CH0_NOTIF_ARG		(0)
#define SPI_UCFG_MODEC_CH0_NOTIF_ENABLE		(OFF)

#define SPI_UCFG_MODEC_CH1_HARDCH			(PIL_SPI_CH3_0)
#define SPI_UCFG_MODEC_CH1_SHIFTCLOCKIDLELEVEL	(PIL_SPI_CKR_HIGH)
#define SPI_UCFG_MODEC_CH1_SOUTFUNCTION		(PIL_SPI_SOLS_LOW)
#define SPI_UCFG_MODEC_CH1_CLOCKIDLELEVEL	(LO)
#define SPI_UCFG_MODEC_CH1_STARTEDGE		(PIL_SPI_STARTEDGE_CLK)
#define SPI_UCFG_MODEC_CH1_BITRATE_PATTERN	(PIL_SPI_BITRATE_10M)
#define SPI_UCFG_MODEC_CH1_BITDIRECTION		(PIL_SPI_DIRECTION_MSBFIRST)
#define SPI_UCFG_MODEC_CH1_DATASIZE			(PIL_SPI_LENGTH_32BIT)
#define SPI_UCFG_MODEC_CH1_CSINENABLE 		(PIL_SPI_CS_IGNORE)
#define SPI_UCFG_MODEC_CH1_CSACTIVELEVEL	(LO)
#define SPI_UCFG_MODEC_CH1_CSID				(PIL_SPI_CSID_0)
#define SPI_UCFG_MODEC_CH1_MASTERSLAVEMODE	(PIL_SPI_MASTERSLAVE_SLAVE)
#define SPI_UCFG_MODEC_CH1_CS2CLKDELAY		(PIL_SPI_DELAY_50NS)
#define SPI_UCFG_MODEC_CH1_CLK2CSDELAY		(PIL_SPI_DELAY_50NS)
#define SPI_UCFG_MODEC_CH1_NEXTACCESSDELAY	(PIL_SPI_DELAY_50NS)
#define SPI_UCFG_MODEC_CH1_COREID			(BSW_CORE_ID_CORE0)
#define SPI_UCFG_MODEC_CH1_TRGSELDMADTS		(PIL_SPI_TGCTL_TRGSEL_DMA)
#define SPI_UCFG_MODEC_CH1_DMATXCH			(DMA_CH_DATA_ID_2)
#define SPI_UCFG_MODEC_CH1_DMARXCH			(DMA_CH_DATA_ID_3)
#define SPI_UCFG_MODEC_CH1_DMASIZE			(u1DMA_TRANSSIZE_4)
#define SPI_UCFG_MODEC_CH1_NOTIF_ID			(0) //@todo
#define SPI_UCFG_MODEC_CH1_NOTIF_ARG		(0)
#define SPI_UCFG_MODEC_CH1_NOTIF_ENABLE		(OFF)

#define SPI_UCFG_MODEC_CH2_HARDCH			(PIL_SPI_CH4_0)
#define SPI_UCFG_MODEC_CH2_SHIFTCLOCKIDLELEVEL	(PIL_SPI_CKR_HIGH)
#define SPI_UCFG_MODEC_CH2_SOUTFUNCTION		(PIL_SPI_SOLS_LOW)
#define SPI_UCFG_MODEC_CH2_CLOCKIDLELEVEL	(LO)
#define SPI_UCFG_MODEC_CH2_STARTEDGE		(PIL_SPI_STARTEDGE_CLK)
#define SPI_UCFG_MODEC_CH2_BITRATE_PATTERN	(PIL_SPI_BITRATE_10M)
#define SPI_UCFG_MODEC_CH2_BITDIRECTION		(PIL_SPI_DIRECTION_MSBFIRST)
#define SPI_UCFG_MODEC_CH2_DATASIZE			(PIL_SPI_LENGTH_32BIT)
#define SPI_UCFG_MODEC_CH2_CSINENABLE 		(PIL_SPI_CS_IGNORE)
#define SPI_UCFG_MODEC_CH2_CSACTIVELEVEL	(LO)
#define SPI_UCFG_MODEC_CH2_CSID				(PIL_SPI_CSID_0)
#define SPI_UCFG_MODEC_CH2_MASTERSLAVEMODE	(PIL_SPI_MASTERSLAVE_SLAVE)
#define SPI_UCFG_MODEC_CH2_CS2CLKDELAY		(PIL_SPI_DELAY_50NS)
#define SPI_UCFG_MODEC_CH2_CLK2CSDELAY		(PIL_SPI_DELAY_50NS)
#define SPI_UCFG_MODEC_CH2_NEXTACCESSDELAY	(PIL_SPI_DELAY_50NS)
#define SPI_UCFG_MODEC_CH2_COREID			(BSW_CORE_ID_CORE0)
#define SPI_UCFG_MODEC_CH2_TRGSELDMADTS		(PIL_SPI_TGCTL_TRGSEL_DMA)
#define SPI_UCFG_MODEC_CH2_DMATXCH			(DMA_CH_DATA_ID_4)
#define SPI_UCFG_MODEC_CH2_DMARXCH			(DMA_CH_DATA_ID_5)
#define SPI_UCFG_MODEC_CH2_DMASIZE			(u1DMA_TRANSSIZE_4)
#define SPI_UCFG_MODEC_CH2_NOTIF_ID			(0) //@todo
#define SPI_UCFG_MODEC_CH2_NOTIF_ARG		(0)
#define SPI_UCFG_MODEC_CH2_NOTIF_ENABLE		(OFF)


#define IOC_SPINLOCK_ID_PIL_SPI				(0)
#define IOC_SPINLOCK_ID_SPI					(0)

#endif /* SPI_UCFG_H */
/*-- End Of File -------------------------------------------------------------------------------*/
