# coding: utf-8

################################################################################
# [IN_FILE]                                                                    #
#------------------------------------------------------------------------------#
#   [IN]  SrecFile | Motorola S-record(S3) ファイル                            #
################################################################################
[IN_FILE]
SrecFile  = W:\src\DevRRPG\ReprogProject\env\out\Reprog_SBL.run
StartFile = False
EndFile   = True


################################################################################
# [PLAINTEXT]                                                                  #
#------------------------------------------------------------------------------#
#   [OUT] PlainRunFile        | Motorola S-record(S3) 結合ファイル             #
################################################################################
[PLAINTEXT]
PlainRunFile        = W:\src\DevRRPG\Tool\TS-WriterData\TSW-SendData.x

