# coding: utf-8

################################################################################
# [IN_FILE]                                                                    #
#------------------------------------------------------------------------------#
#   [IN]  SrecFile | Motorola S-record(S3) ファイル                            #
################################################################################
[IN_FILE]
SrecFile = W:\src\DevRRPG\ReprogProject\env\out\Reprog_SBL.run


################################################################################
# [CRC]                                                                        #
#------------------------------------------------------------------------------#
#   [IN]  Calc        | CRC 算出                                               #
#                     |  True  : する                                          #
#                     |  False : しない                                        #
#   [OUT] CrcBinFile  | CRC 出力ファイル(Binary)                               #
################################################################################
[CRC]
Calc        = True
CrcBinFile  = W:\src\DevRRPG\Tool\Phase6CANoe\DLfile\Reprog_SBL.crc


################################################################################
# [CMAC]                                                                       #
#------------------------------------------------------------------------------#
#   [IN]  Calc         | CMAC 算出                                             #
#                      |  True  : する                                         #
#                      |  False : しない                                       #
#   [IN]  KEY          | 鍵(16byte)                                            #
#   [OUT] CmacBinFile  | CMAC 出力ファイル(Binary)                             #
################################################################################
[CMAC]
Calc         = False
KEY          = 0123456789ABCDEFFEDCBA9876543210
CmacBinFile  = C:\Users\$USERNAME$\Documents\TMS\SQT_Project\$CFGPTN$\CANoe\DLfile\Reprog_SBL.cmac


################################################################################
# [SIGNATURE]                                                                  #
#------------------------------------------------------------------------------#
#   [IN]  Calc        | 署名算出                                               #
#                     |  True  : する                                          #
#                     |  False : しない                                        #
#   [IN]  Algorithm   | RSA アルゴリズム                                       #
#                     |  PKCS1_v1_5                                            #
#                     |  PSS                                                   #
#   [IN]  PrivateKey  | 秘密鍵(署名生成キー)                                   #
#   [IN]  PublicKey   | 公開鍵(署名検証キー)                                   #
#   [OUT] SigBinFile  | 署名ファイル(Binary)                                   #
################################################################################
[SIGNATURE]
Calc        = False
Algorithm   = PSS
PrivateKey  = C:\Users\$USERNAME$\Documents\TMS\SQT_Project\Tool\Converter\SigKey\private-key_3072.pem
PublicKey   = C:\Users\$USERNAME$\Documents\TMS\SQT_Project\Tool\Converter\SigKey\public-key_3072.pem
SigBinFile  = C:\Users\$USERNAME$\Documents\TMS\SQT_Project\$CFGPTN$\CANoe\DLfile\Reprog_SBL.sig


################################################################################
# [PLAINTEXT]                                                                  #
#------------------------------------------------------------------------------#
#   [OUT] PlainTextFile       | 平文 Text (改行あり)                           #
#   [OUT] PlainBinFile        | 平文 Binary                                    #
################################################################################
[PLAINTEXT]
PlainTextFile       = W:\src\DevRRPG\Tool\Phase6CANoe\DLfile\Plain\Reprog_SBL.txt
PlainBinFile        = W:\src\DevRRPG\Tool\Phase6CANoe\DLfile\Plain\Reprog_SBL.bin


################################################################################
# [ENCRYPT]                                                                    #
#------------------------------------------------------------------------------#
#   [IN]  CBC                  | CBC 暗号化                                    #
#                              |  True  : する                                 #
#                              |  False : しない                               #
#   [IN]  PKCS7PAD             | PKCS #7 padding                               #
#                              |  True  : する                                 #
#                              |  False : しない                               #
#   [IN]  KEY                  | 鍵(16byte)                                    #
#   [IN]  IV                   | IV(16byte)                                    #
#   [OUT] CipherTextFile       | 暗号文 Text (改行あり)                        #
#   [OUT] CipherBinFile        | 暗号文 Binary                                 #
################################################################################
[ENCRYPT]
CBC                  = False
PKCS7PAD             = False
KEY                  = 0123456789ABCDEFFEDCBA9876543210
IV                   = F9E8D7C6B5A4938228394A5B6C7D8E9F
CipherTextFile       = C:\Users\$USERNAME$\Documents\TMS\SQT_Project\$CFGPTN$\CANoe\DLfile\Cipher\Reprog_SBL.txt
CipherBinFile        = C:\Users\$USERNAME$\Documents\TMS\SQT_Project\$CFGPTN$\CANoe\DLfile\Cipher\Reprog_SBL.bin


##################################################################################################
# [COMPRESS]                                                                                     #
#------------------------------------------------------------------------------------------------#
#   [IN]  emCompress                   | emCompress 圧縮                                         #
#                                      |  True  : する                                           #
#                                      |  False : しない                                         #
#   [IN]  emCompressOpt_ws             | emCompress 圧縮オプション(-ws)                          #
#   [IN]  emCompressOpt_lc             | emCompress 圧縮オプション(-lc)                          #
#   [IN]  emCompressOpt_lp             | emCompress 圧縮オプション(-lp)                          #
#   [IN]  emCompressOpt_pb             | emCompress 圧縮オプション(-pb)                          #
#   [IN]  emCompressUtilExe            | COMPRESS_LZMA_Util.exe                                  #
#   [OUT] CompBinFile                  | 圧縮テンポラリファイル(サイズ埋め込み無)                #
#   [OUT] CompSizePlainTextFile        | 圧縮ファイル(サイズ埋め込み有) (平文) Text (改行あり)   #
#   [OUT] CompSizePlainBinFile         | 圧縮ファイル(サイズ埋め込み有) (平文) Binary            #
#   [OUT] CompSizeCipherTextFile       | 圧縮ファイル(サイズ埋め込み有) (暗号文) Text (改行あり) #
#   [OUT] CompSizeCipherBinFile        | 圧縮ファイル(サイズ埋め込み有) (暗号文) Binary          #
##################################################################################################
[COMPRESS]
emCompress                   = False
emCompressOpt_ws             = 1024
emCompressOpt_lc             = 0
emCompressOpt_lp             = 0
emCompressOpt_pb             = 0
emCompressUtilExe            = C:\Users\$USERNAME$\Documents\TMS\SQT_Project\Tool\Converter\emCompress\COMPRESS_LZMA_Util.exe
CompBinFile                  = C:\Users\$USERNAME$\Documents\TMS\SQT_Project\$CFGPTN$\CANoe\DLfile\PlainCompress\_Tmp_CompRawFile_Reprog_SBL.bin
CompSizePlainTextFile        = C:\Users\$USERNAME$\Documents\TMS\SQT_Project\$CFGPTN$\CANoe\DLfile\PlainCompress\Reprog_SBL.txt
CompSizePlainBinFile         = C:\Users\$USERNAME$\Documents\TMS\SQT_Project\$CFGPTN$\CANoe\DLfile\PlainCompress\Reprog_SBL.bin
CompSizeCipherTextFile       = C:\Users\$USERNAME$\Documents\TMS\SQT_Project\$CFGPTN$\CANoe\DLfile\CipherCompress\Reprog_SBL.txt
CompSizeCipherBinFile        = C:\Users\$USERNAME$\Documents\TMS\SQT_Project\$CFGPTN$\CANoe\DLfile\CipherCompress\Reprog_SBL.bin

